;Item version setting file
;by Cooler liuyujun@263.net 2004.02.25

;Format:
;Version=xxx
;Example:
;xxx=0, means only have one version item, 
        item info store in the directory item\000
;xxx=1, means have two version item, 
        each item info store in the directory item\000 and item\001

[ItemVersion]
Version=1
[FunctionOpen]
InstrumentFunction=1
