[List]
;ÊÀ½çµØÍ¼µÄÍ¼ÎÄ¼şÃû£¨jpg¸ñÊ½£©
WorldMapImage=\Spr\Ui4\Ğ¡µØÍ¼\800²é¿´´óµØÍ¼.spr
WorldMapImage1024=\Spr\Ui4\Ğ¡µØÍ¼\1024²é¿´´óµØÍ¼.spr
1=·âÉñÌ¨
1_StallType=2
1_name=$Phong ThÇn ®µi
2=³ç³Ç´óÓª
2_StallType=1
2_name=$Sïng Thµnh doanh
3=ÓñĞé¹¬
3_StallType=1
3_name=$Ngäc H­ cung
4=ò¿ÓÈÄ¹
4_StallType=1
4_name=$Xi V­u Mé
5=³ç³ÇÒ°Íâ
5_name=$Sïng thµnh
6=±±º£
6_name=$B¾c H¶i
7=ÑàÉ½
7_name=$YÕn S¬n
8=À¥ÂØÉ½Â´
8_name=$Ch©n nói C«n L«n
9=Î÷À¥ÂØ
9_name=$T©y C«n L«n
10=Ê×ÑôÉ½
10_name=$Thñ D­¬ng s¬n
11=ÓÎ»ê¹Ø
11_name=$Du Hån
12=Ãç½®
12_name=$Miªu C­¬ng
13=¾ŞÂ¹
13_name=$Cù Léc
14=äü¹Ø
14_name=$§ång Quan
15=ÃÏ½ò
15_name=$M¹nh T©n
16=ÈıÉ½¹Ø
16_name=$Tam S¬n
17=áªÉ½
17_name=$Kú S¬n
18=ÄÁÒ°
18_name=$Môc D·
19=¾øÁúÁë
19_name=$TuyÖt Long lÜnh
20=Î÷áª
20_StallType=2
20_name=$T©y Kú
21=³¯¸è
21_StallType=2
21_name=$TriÒu Ca
22=»ÄÄ®
22_name=$Hoang m¹c
23=É³Ä®ÍÁ³Ç
23_name=$Thæ Thµnh
24=É³Ä®·çÌ²
24_name=$Phong Than
25=É³Ä®ÂÌÖŞ
25_name=$Lôc Ch©u
26=ËÀÍöÉ³Ä®
26_name=$Sa M¹c chÕt
27=ĞùÔ¯¶´Ò»²ã
27_name=$Hiªn Viªn tÇng 1
28=ĞùÔ¯¶´¶ş²ã
28_name=$Hiªn Viªn tÇng 2
29=ĞùÔ¯¶´Èı²ã
29_name=$Hiªn Viªn tÇng 3
30=ĞùÔ¯¶´ËÄ²ã
30_name=$Hiªn Viªn tÇng 4
31=ĞùÔ¯¶´Îå²ã
31_name=$Hiªn Viªn tÇng 5
32=ÓñÈª±ù´¨
32_name=$Ngäc TuyÒn
33=±ù´¨Ñ©¹È
33_name=$TuyÕt Cèc
34=´ó·ç±ù´¨
34_name=$§¹i Phong
35=´óÔó±ù´¨
35_name=$§¹i Th¹ch
36=±ù´¨Ö®¼«
36_name=$B¨ng Xuyªn Cùc
37=¶«º£Ë®Óò
37_name=$Thñy Vùc
38=¶«º£º£µ×
38_name=$Long Cung
39=¶«º£º£¹µ
39_name=$H¶i C©u
40=¶«º£ÁúÓò
40_name=$Long Vùc
41=¶«º£ÁúÔ¨
41_name=$Long Uyªn
42=±ÌÓÎ¹¬Ò»²ã
42_name=$Bİch Du tÇng 1
43=±ÌÓÎ¹¬¶ş²ã
43_name=$Bİch Du tÇng 2
44=±ÌÓÎ¹¬Èı²ã
44_name=$Bİch Du tÇng 3
45=±ÌÓÎ¹¬ËÄ²ã
45_name=$Bİch Du tÇng 4
46=±ÌÓÎ¹¬Îå²ã
46_name=$Bİch Du tÇng 5
47=À¦ÏÉ¹¬Ò»²ã
47_name=$Khæn Tiªn tÇng 1
48=À¦ÏÉ¹¬¶ş²ã
48_name=$Khæn Tiªn tÇng 2
49=À¦ÏÉ¹¬Èı²ã
49_name=$Khæn Tiªn tÇng 3
50=À¦ÏÉ¹¬ËÄ²ã
50_name=$Khæn Tiªn tÇng 4
51=À¦ÏÉ¹¬Îå²ã
51_name=$Khæn Tiªn tÇng 5
52=Ñş³Ø
52_StallType=2
52_name=$Diªu Tr×
53=´óº£
53_name=$§¹i H¶i
54=ÅîÀ³
54_name=$Bång Lai
55=¶«å­
55_name=$§«ng Doanh
56=·½ÕÉ
56_name=$Ph­¬ng Tr­îng
57=¿ó³¡
57_name=$Kho¸ng tr­êng
58=Ò©Íõ¹È
58_name=$D­îc V­¬ng cèc
59=³ç³Ç¿ó³¡
59_name=$S.Thµnh kho¸ng tr­êng
60=ÌìÀÎ
60_name=$Thiªn Lao
61=10ÄêÇ°ÓñĞé¹¬
61_name=$Ngäc H­ 10 n¨m tr­íc
62=10ÄêºóÓñĞé¹¬
62_name=$Ngäc H­ 10 n¨m sau
63=10Äêºó³¯¸è
63_name=$TriÒu Ca 10 n¨m sau
64=2000ÄêÇ°¹ÅÕ½³¡
64_name=$ViÔn Cæ
65=³ÂÌÁ¹Ø
65_name=$TrÇn §­êng
66=ÖíÁı³ÇÕ¯
66_name=$Tr­ Lung tr¹i
67=ÍòÏÉÕó£¨ÍÁ£©
67_StallType=2
67_name=$V¹n Tiªn (Thæ)
68=ÍòÏÉÕó£¨Ë®£©
68_StallType=2
68_name=$V¹n Tiªn (Thñy)
69=ÍòÏÉÕó£¨»ğ£©
69_StallType=2
69_name=$V¹n Tiªn (Háa)
70=ÍòÏÉÕó£¨·ç£©
70_StallType=2
70_name=$V¹n Tiªn (Phong)
71=ÉÌÖÜÕ½³¡
71_name=$ChiÕn tr­êng
72=¿ªÃ÷µº
72_name=$Khai Minh ®¶o
73=¼ÑÃÎ¹Ø
73_name=$BÊt Chu Thiªn quan
73_type=32
74=Óü·¨É½
74_name=$BÊt Chu S¬n
74_type=32
75=ÒÄ·½²¿Âä
75_name=$Ngôc Ph¸p s¬n
75_type=32
76=ÚæÈªÊ¥µØ
76_name=$Th¸nh §Şa
76_type=32
77=Á÷²¨É½
77_name=$L­u Ba s¬n
77_type=32
78=¿ÕÉ£ÁéÉ½
78_name=$Kh«ng Tang Linh
79=ÍòÏÉÕó-»Ã£¨ÍÁ£©
79_StallType=2
79_name=$V¹n Tiªn TrËn (HuyÔn)
80=ÍòÏÉÕó-»Ã£¨Ë®£©
80_StallType=2
80_name=$V¹n Tiªn TrËn (HuyÔn)
81=ÍòÏÉÕó-»Ã£¨»ğ£©
81_StallType=2
81_name=$V¹n Tiªn TrËn (HuyÔn)
82=ÍòÏÉÕó-»Ã£¨·ç£©
82_StallType=2
82_name=$V¹n Tiªn TrËn (HuyÔn)
83=¼ÀÔ¨¹È
83_name=$TÕ Uyªn Cèc
86=xuan_wu_shen_yu
86_name=$HuyÒn Vò ThÇn Vùc
92=Ô¶¹ÅÁÑÏ¶
92_name=$Manh mèi
93=×ÏĞş¶´Ìì
93_name=$Tö HuyÒn §éng Thiªn
94=Óñ·å¶´Ìì
94_name=$Ngäc Phong §éng Thiªn
95=»ÔÃ÷¶´Ìì
95_name=$Huy Minh §éng Thiªn
96=ÌìÀÎ
96_name=$B¸ch Linh C¸t
97=ÑÖÂŞµî
97_name=$Diªm La ®iÖn
98=»ÆÈª¸®
98_name=$Hoµng TuyÒn phñ
99=ÄÏ¿Â¿¤
99_name=$Nam Kha quËn
60000_name=$ Khu LuyÖn TËp Bİ MËt I
60000=expmap_i
60001_name=$ Khu LuyÖn TËp Bİ MËt II
60001=expmap_ii
60002_name=$ Khu LuyÖn TËp Bİ MËt III
60002=expmap_iii
60003_name=$ Khu LuyÖn TËp Bİ MËt IV
60003=expmap_iv
60004_name=$ Khu LuyÖn TËp Bİ MËt V
60004=expmap_v
60005_name=$ Khu LuyÖn TËp Bİ MËt VI
60005=expmap_vi
60006_name=$ Khu LuyÖn TËp Bİ MËt VII
60006=expmap_vii
60007_name=$ Khu LuyÖn TËp Bİ MËt VIII
60007=expmap_viii
60008_name=$ Khu LuyÖn TËp Bİ MËt IX
60008=expmap_ix
60009_name=$ Khu LuyÖn TËp Bİ MËt X
60009=expmap_x
60010_name=$ Tr­êng §iÕu DiÔn Vâ Tr­êng
60010=drillground_zhaoge
60011_name=$ T©y Kú DiÔn Vâ Tr­êng
60011=drillground_xiqi
60012_name=$ Sïng Thµnh §¹i Doanh DiÔn Vâ Tr­êng
60012=drillground_chongcheng_camp
60013_name=$ Ngäc H­ Cung DiÔn Vâ Tr­êng
60013=drillground_yuxu_temple
60014_name=$ Xi V­u Mé DiÔn Vâ Tr­êng
60014=drillground_chiyou_mausoleum
60015=ÉÌÖÜÕ½³¡
60015_name=$Th­¬ng Chu Tiªn Ma
60015_type=32
60020_name=$§Êu Tr­êng
60020=¾º¼¼³¡
60021_name=$§Êu Tr­êng
60021=¾º¼¼³¡
60022_name=$§Êu Tr­êng
60022=¾º¼¼³¡
60023_name=$§Êu Tr­êng
60023=¾º¼¼³¡
60024_name=$§Êu Tr­êng
60024=¾º¼¼³¡
60025_name=$§Êu Tr­êng
60025=¾º¼¼³¡
60026_name=$§Êu Tr­êng
60026=¾º¼¼³¡
60027_name=$§Êu Tr­êng
60027=¾º¼¼³¡
60028_name=$§Êu Tr­êng
60028=¾º¼¼³¡
60029_name=$§Êu Tr­êng
60029=¾º¼¼³¡
