-- Phong Than npc_fix 2026-09-29: Bao Thuong (trade run), rebuilt. ASCII file, Vietnamese as TCVN3 escapes;
-- generated by scratchpad\baothuong\gen.py. VNG only kept the dialogue (StringResource 10710-10775) and the
-- support items; the merchant scripts are lost, so trade rules here are new (documented in
-- docs\features\bao-thuong-chay-buon-phong-than-20260929.md).
-- Flow: level 20+ -> rent a camel (small 10 / large 25 loads) -> buy the local speciality -> carry it to a
-- merchant in another city -> sell. Profit and experience grow with the price of the goods bought and
-- with the distance between the two cities.
-- Tasks (unused by VNG scripts): 1900 camel 0/1/2, 1901 goods id, 1902 loads, 1903 origin map,
-- 1904 unit price paid, 1905 finished runs.
Include("\\script\\phongthan\\lib\\vng_tasknote.lua")

BT_T_CAMEL = 1900
BT_T_GOOD = 1901
BT_T_QTY = 1902
BT_T_FROM = 1903
BT_T_PRICE = 1904
BT_T_RUNS = 1905

-- city: map -> order (distance), local goods id, name
BT_CITY = {
	[1002] = { 1, 3, "S\239ng Th\181nh" },
	[1003] = { 2, 4, "Ng\228c H\173" },
	[1004] = { 3, 5, "Xi V\173u" },
	[1020] = { 4, 1, "T\169y K\250" },
	[1021] = { 5, 2, "Tri\210u Ca" },
}
-- goods: name, unit price (luong)
BT_GOODS = {
	[1] = { "Tr\181 T\169y K\250", 2000 },
	[2] = { "L\244a Tri\210u Ca", 3000 },
	[3] = { "Da th\243 S\239ng Th\181nh", 1500 },
	[4] = { "Linh d\173\238c Ng\228c H\173", 2500 },
	[5] = { "Kho\184ng th\185ch Xi V\173u", 1800 },
}
-- camel: rent fee, capacity
BT_CAMEL = { [1] = { 1000, 10 }, [2] = { 5000, 25 } }
BT_EXP_PER_LUONG = 2        -- experience = loads * unit price * 2
BT_STAR = { 3, 5482 }       -- Ngoi Sao May Man (VNG: reward of Bao Thuong), 1 per run of 10+ loads

function BT_City()
	local w = GetWorldPos()
	return BT_CITY[w], w
end

function BT_Clear()
	SetTask(BT_T_GOOD, 0)
	SetTask(BT_T_QTY, 0)
	SetTask(BT_T_FROM, 0)
	SetTask(BT_T_PRICE, 0)
end

function BT_SellPrice(from, to, price)
	local a = BT_CITY[from]
	local b = BT_CITY[to]
	if a == nil or b == nil then return price end
	local d = a[1] - b[1]
	if d < 0 then d = -d end
	-- 1.3x for the next city, +0.1x per extra step (max 1.7x)
	return floor(price * (12 + d) / 10)
end

function main()
	if GetLevel() < 20 then
		Talk(1, "no", 10712)
		return
	end
	local mt = GetMorphType() if mt ~= -1 and mt ~= 0 then
		Talk(1, "no", 10710)
		return
	end
	local city, w = BT_City()
	if city == nil then
		Talk(1, "no", 10715)
		return
	end
	local camel = GetTask(BT_T_CAMEL)
	local qty = GetTask(BT_T_QTY)
	local from = GetTask(BT_T_FROM)
	local tasks = {}
	if qty > 0 and from ~= w then
		tinsert(tasks, { "Giao h\181ng", "bt_deliver"; show = 1 })
	end
	if camel == 0 then
		tinsert(tasks, { "Thu\170 l\185c \174\181", "bt_rent"; show = 1 })
	elseif qty == 0 then
		tinsert(tasks, { "Mua h\181ng: " .. BT_GOODS[city[2]][1], "bt_buy"; show = 1 })
		tinsert(tasks, { "Tr\182 l\185c \174\181", "bt_return"; show = 1 })
	else
		tinsert(tasks, { "Xem h\181ng tr\170n l\185c \174\181", "bt_cargo"; show = 1 })
		tinsert(tasks, { "Tr\182 l\185c \174\181", "bt_return"; show = 1 })
	end
	tinsert(tasks, { "T\215m hi\211u B\181o Th\173\172ng", "bt_intro"; show = 1 })
	tinsert(tasks, { "K\213t th\243c \174\232i tho\185i", "no"; show = 1 })
	SayTask(10711, tasks)
end

function bt_intro()
	Talk(1, "main", 10716)
end

function bt_cargo()
	local g = BT_GOODS[GetTask(BT_T_GOOD)]
	local name = "?"
	if g then name = g[1] end
	Talk(1, "no", "L\185c \174\181 c\241a ng\173\172i \174ang ch\235 " .. GetTask(BT_T_QTY) .. " ki\214n " .. name .. ". H\183y mang \174\213n th\173\172ng nh\169n \235 th\181nh kh\184c \174\211 b\184n, c\181ng xa c\181ng l\234i.")
end

function bt_rent()
	local tasks = {
		{ "L\185c \174\181 nh\225 (1000 l\173\238ng, ch\235 10 ki\214n)", "bt_rent1"; show = 1 },
		{ "L\185c \174\181 l\237n (5000 l\173\238ng, ch\235 25 ki\214n)", "bt_rent2"; show = 1 },
		{ "K\213t th\243c \174\232i tho\185i", "no"; show = 1 },
	}
	SayTask(10717, tasks)
end

function bt_rent_n(t)
	if GetTask(BT_T_CAMEL) ~= 0 then return end
	local fee = BT_CAMEL[t][1]
	if GetCash() < fee then
		Talk(1, "no", 10719)
		return
	end
	Pay(fee)
	SetTask(BT_T_CAMEL, t)
	Talk(1, "no", 10718)
end
function bt_rent1() bt_rent_n(1) end
function bt_rent2() bt_rent_n(2) end

function bt_buy()
	local city, w = BT_City()
	local camel = GetTask(BT_T_CAMEL)
	if city == nil or camel == 0 then return end
	local g = BT_GOODS[city[2]]
	local cap = BT_CAMEL[camel][2]
	local tasks = {
		{ "5 " .. g[1] .. " (" .. (5 * g[2]) .. " l\173\238ng" .. ")", "bt_buy5"; show = 1 },
		{ "10 " .. g[1] .. " (" .. (10 * g[2]) .. " l\173\238ng" .. ")", "bt_buy10"; show = 1 },
		{ cap .. " " .. g[1] .. " (" .. (cap * g[2]) .. " l\173\238ng" .. ")", "bt_buyfull"; show = (cap > 10) and 1 or 0 },
		{ "K\213t th\243c \174\232i tho\185i", "no"; show = 1 },
	}
	SayTask(10715, tasks)
end

function bt_buy_n(n)
	local city, w = BT_City()
	local camel = GetTask(BT_T_CAMEL)
	if city == nil or camel == 0 or GetTask(BT_T_QTY) > 0 then return end
	local cap = BT_CAMEL[camel][2]
	if n > cap then n = cap end
	local g = BT_GOODS[city[2]]
	local cost = n * g[2]
	if GetCash() < cost then
		Talk(1, "no", "Ng\173\172i kh\171ng \174\241 ti\210n mua s\232 h\181ng n\181y.")
		return
	end
	Pay(cost)
	SetTask(BT_T_GOOD, city[2])
	SetTask(BT_T_QTY, n)
	SetTask(BT_T_FROM, w)
	SetTask(BT_T_PRICE, g[2])
	Msg2Player("\167\183 mua " .. n .. " " .. g[1] .. ", h\183y ch\235 \174\213n th\173\172ng nh\169n \235 th\181nh kh\184c \174\211 b\184n.")
	Talk(1, "no", "H\181ng \174\183 ch\202t l\170n l\185c \174\181. Th\173\172ng nh\169n \235 S\239ng Th\181nh, Ng\228c H\173, Xi V\173u, T\169y K\250, Tri\210u Ca \174\210u thu mua h\181ng t\245 n\172i kh\184c.")
end
function bt_buy5() bt_buy_n(5) end
function bt_buy10() bt_buy_n(10) end
function bt_buyfull()
	local camel = GetTask(BT_T_CAMEL)
	if camel > 0 then bt_buy_n(BT_CAMEL[camel][2]) end
end

function bt_deliver()
	local tasks = {
		{ "Giao h\181ng", "bt_deliver_ok"; show = 1 },
		{ "K\213t th\243c \174\232i tho\185i", "no"; show = 1 },
	}
	SayTask(10713, tasks)
end

function bt_deliver_ok()
	local city, w = BT_City()
	local qty = GetTask(BT_T_QTY)
	local from = GetTask(BT_T_FROM)
	local price = GetTask(BT_T_PRICE)
	if city == nil or qty <= 0 or from == w or price <= 0 then
		Talk(1, "no", 10714)
		return
	end
	local unit = BT_SellPrice(from, w, price)
	local money = unit * qty
	local exp = qty * price * BT_EXP_PER_LUONG
	BT_Clear()
	SetTask(BT_T_RUNS, GetTask(BT_T_RUNS) + 1)
	Earn(money)
	AddOwnExp(exp)
	if qty >= 10 then
		AddNormalItem(BT_STAR[1], BT_STAR[2], 0, 1, 0, 0)
	end
	Msg2Player("B\184n " .. qty .. " ki\214n h\181ng, thu \174\173\238c " .. money .. " l\173\238ng (l\234i " .. (money - qty * price) .. " l\173\238ng), nh\203n " .. exp .. " kinh nghi\214m.")
end

function bt_return()
	if GetTask(BT_T_QTY) > 0 then
		local tasks = {
			{ "Tr\182 l\185c \174\181, b\225 h\181ng", "bt_return_ok"; show = 1 },
			{ "K\213t th\243c \174\232i tho\185i", "no"; show = 1 },
		}
		SayTask(10722, tasks)
	else
		bt_return_ok()
	end
end

function bt_return_ok()
	BT_Clear()
	SetTask(BT_T_CAMEL, 0)
	Talk(1, "no", 10723)
end

function no()
	CloseDialog()
end
