-- Generated by scratchpad\npcnames\gen_npcnames.py (coordinator 2026-10-03).
-- Renames PTADM_NPC_FIX NPCs that still carry GBK names (unreadable in the TCVN3 client) and binds
-- their script, since PTAdm_FixNpcScripts no longer matches them by name afterwards.
PTNN_ROWS = {
	{ 1002, "\178\214\191\226\185\220\192\237\212\177", "Th\241 Kh\232", "\\script\\phongthan\\npc_fix\\1002_thu_kho.lua" },
	{ 1002, "\203\213\187\164", "T\171 H\233", "\\script\\phongthan\\npc_fix\\1002_to_ho.lua" },
	{ 1002, "\194\179\208\219", "L\231 H\239ng", "\\script\\phongthan\\npc_fix\\1002_lo_hung.lua" },
	{ 1002, "\218\249\206\196\187\175", "\162u Thi\170n H\227a", "\\script\\phongthan\\npc_fix\\1002_au_thien_hoa.lua" },
	{ 1002, "\179\231\211\166\177\235", "S\239ng \248ng B\173u", "\\script\\phongthan\\npc_fix\\1002_sung_ung_buu.lua" },
	{ 1002, "\179\231\211\166\240\189", "S\239ng \248ng Loan", "\\script\\phongthan\\npc_fix\\1002_sung_ung_loan.lua" },
	{ 1002, "\234\203\204\239", "Tri\214u \167i\210n", "\\script\\phongthan\\npc_fix\\1002_trieu_dien.lua" },
	{ 1002, "\234\203\192\215", "Tri\214u L\171i", "\\script\\phongthan\\npc_fix\\1002_trieu_loi.lua" },
	{ 1002, "\179\231\186\238\187\162", "S\239ng H\199u H\230", "\\script\\phongthan\\npc_fix\\1002_sung_hau_ho.lua" },
	{ 1002, "\179\231\186\218\187\162", "S\239ng H\190c H\230", "\\script\\phongthan\\npc_fix\\1002_sung_hac_ho.lua" },
	{ 1002, "\214\163\194\215", "Tr\222nh Lu\169n", "\\script\\phongthan\\npc_fix\\1002_trinh_luan.lua" },
	{ 1003, "\180\200\186\189\181\192\200\203", "T\245 H\181ng \167\185o Nh\169n", "\\script\\phongthan\\npc_fix\\1003_tu_hang.lua" },
	{ 1003, "\193\233\177\166\180\243\183\168\202\166", "Linh B\182o \167\185i Ph\184p S\173", "\\script\\phongthan\\npc_fix\\1003_linh_bao.lua" },
	{ 1003, "\196\207\188\171\207\201\206\204", "Nam C\249c Ti\170n \164ng", "\\script\\phongthan\\npc_fix\\1003_nam_cuc.lua" },
	{ 1003, "\187\198\193\250\213\230\200\203", "Ho\181ng Long Ch\169n Nh\169n", "\\script\\phongthan\\npc_fix\\1003_hoang_long.lua" },
	{ 1003, "\200\188\181\198\181\192\200\203", "Nhi\170n \167\168ng \167\185o Nh\169n", "\\script\\phongthan\\npc_fix\\1003_nhien_dang.lua" },
	{ 1003, "\212\198\214\208\215\211", "V\169n Trung T\246", "\\script\\phongthan\\npc_fix\\1003_van_trung_tu.lua" },
	{ 1004, "\201\217\234\187\205\188\204\218", "Thi\213u H\185o (\167\229 \167\187ng)", "\\script\\phongthan\\npc_fix\\1004_thieu_hao.lua" },
	{ 1004, "\186\243\205\193\205\188\204\218", "H\203u Th\230 (\167\229 \167\187ng)", "\\script\\phongthan\\npc_fix\\1004_hau_tho.lua" },
	{ 1004, "\183\231\178\174\205\188\204\218", "Phong B\184 (\167\229 \167\187ng)", "\\script\\phongthan\\npc_fix\\1004_phong_ba.lua" },
	{ 1004, "\215\163\200\218\205\188\204\218", "Ch\243c Dung (\167\229 \167\187ng)", "\\script\\phongthan\\npc_fix\\1004_chuc_dung.lua" },
	{ 1004, "\185\178\185\164\205\188\204\218", "C\233ng C\171ng (\167\229 \167\187ng)", "\\script\\phongthan\\npc_fix\\1004_cong_cong.lua" },
	{ 1004, "\208\204\204\236", "H\215nh Thi\170n", "\\script\\phongthan\\npc_fix\\1004_hinh_thien.lua" },
	{ 1004, "\184\223\195\247", "Cao Minh", "\\script\\phongthan\\npc_fix\\1004_cao_minh.lua" },
	{ 1004, "\191\228\184\184\205\188\204\218", "Khoa Ph\244 (\167\229 \167\187ng)", "\\script\\phongthan\\npc_fix\\1004_khoa_phu.lua" },
	{ 1021, "\187\198\183\201\187\162", "Ho\181ng Phi H\230", "\\script\\phongthan\\npc_fix\\1021_hoang_phi_ho.lua" },
	{ 1021, "\186\250\207\178\195\196", "H\229 H\251 M\222", "\\script\\phongthan\\npc_fix\\1021_ho_hy_mi.lua" },
	{ 1021, "\187\198\204\236\187\175", "Ho\181ng Thi\170n H\227a", "\\script\\phongthan\\npc_fix\\1021_hoang_thien_hoa.lua" },
	{ 1021, "\205\193\208\208\203\239", "Th\230 H\181nh T\171n", "\\script\\phongthan\\npc_fix\\1021_tho_hanh_ton.lua" },
	{ 1021, "\190\198\181\234\192\207\176\229", "Ch\241 T\246u \167i\213m", "\\script\\phongthan\\npc_fix\\1021_chu_tuu_diem.lua" },
	{ 1020, "\206\228\205\245", "V\226 V\173\172ng", "\\script\\phongthan\\npc_fix\\1020_vo_vuong.lua" },
	{ 1020, "\209\238\234\175", "D\173\172ng Ti\212n", "\\script\\phongthan\\npc_fix\\1020_duong_tien.lua" },
	{ 1021, "\230\167\188\186", "\167\190c K\251", "\\script\\phongthan\\npc_fix\\1021_dac_ky.lua" },
	{ 1020, "\189\170\215\211\209\192", "Kh\173\172ng T\246 Nha", "\\script\\phongthan\\npc_fix\\1020_khuong_tu_nha.lua" },
	{ 1020, "\192\215\213\240\215\211", "L\171i Ch\202n T\246", "\\script\\phongthan\\npc_fix\\1020_loi_chan_tu.lua" },
	{ 1065, "\192\238\190\184", "L\253 T\220nh", "\\script\\phongthan\\npc_fix\\1065_ly_tinh.lua" },
	{ 1015, "\183\231\193\214", "Phong L\169m", "\\script\\phongthan\\npc_fix\\1015_phong_lam.lua" },
	{ 1015, "\206\226\193\250", "Ng\171 Long", "\\script\\phongthan\\npc_fix\\1015_ngo_long.lua" },
	{ 1015, "\179\163\234\187", "Th\173\172ng H\185o", "\\script\\phongthan\\npc_fix\\1015_thuong_hao.lua" },
	{ 1016, "\181\203\190\197\185\171", "\167\198ng C\246u C\171ng", "\\script\\phongthan\\npc_fix\\1016_dang_cuu_cong.lua" },
	{ 1014, "\206\197\204\171\202\166", "V\168n Th\184i S\173", "\\script\\phongthan\\npc_fix\\1014_van_thai_su.lua" },
	{ 1052, "\206\247\205\245\196\184", "T\169y V\173\172ng M\201u", "\\script\\phongthan\\npc_fix\\1052_tay_vuong_mau.lua" },
	{ 1044, "\182\224\177\166\181\192\200\203", "\167a B\182o \167\185o Nh\169n", "\\script\\phongthan\\npc_fix\\1044_da_bao.lua" },
	{ 1064, "\201\241\197\169", "Th\199n N\171ng (\167\229 \167\187ng)", "\\script\\phongthan\\npc_fix\\1064_than_nong.lua" },
	{ 1062, "\212\170\202\188\204\236\215\240", "Nguy\170n Th\241y Thi\170n T\171n", "\\script\\phongthan\\npc_fix\\1062_nguyen_thuy.lua" },
	{ 1061, "\196\234\201\217\230\167\188\186", "\167\190c K\251 l\243c nh\225", "\\script\\phongthan\\npc_fix\\1061_dac_ky_luc_nho.lua" },
	{ 1003, "\212\211\187\245\201\204", "T\185p H\227a", "\\script\\phongthan\\npc_fix\\1003_tap_hoa.lua" },
	{ 1004, "\212\211\187\245\201\204", "T\185p H\227a", "\\script\\phongthan\\npc_fix\\1004_tap_hoa.lua" },
	{ 1002, "\197\220\201\204", "B\181o Th\173\172ng", "\\script\\phongthan\\npc_fix\\bao_thuong.lua" },
	{ 1003, "\197\220\201\204", "B\181o Th\173\172ng", "\\script\\phongthan\\npc_fix\\bao_thuong.lua" },
	{ 1004, "\197\220\201\204", "B\181o Th\173\172ng", "\\script\\phongthan\\npc_fix\\bao_thuong.lua" },
	{ 1020, "\197\220\201\204", "B\181o Th\173\172ng", "\\script\\phongthan\\npc_fix\\bao_thuong.lua" },
	{ 1021, "\197\220\201\204", "B\181o Th\173\172ng", "\\script\\phongthan\\npc_fix\\bao_thuong.lua" },
	{ 1020, "\212\211\187\245\201\204", "T\185p H\227a", "\\script\\phongthan\\npc_fix\\1020_tap_hoa.lua" },
	{ 1020, "\204\171\203\234\202\166", "Th\184i Tu\213 S\173", "\\script\\phongthan\\npc_fix\\1020_thai_tue.lua" },
	{ 1021, "\212\211\187\245\201\204", "T\185p H\227a", "\\script\\phongthan\\npc_fix\\1021_tap_hoa.lua" },
	{ 1020, "\203\227\195\252\207\200\201\250", "Th\199y T\173\237ng S\232", "\\script\\\206\247\225\170\\\203\227\195\252\207\200\201\250.lua" },
	{ 1021, "\203\227\195\252\207\200\201\250", "Th\199y T\173\237ng S\232", "\\script\\\179\175\184\232\\\203\227\195\252\207\200\201\250.lua" },
	{ 1020, "\178\201\210\169\192\207\200\203", "Ng\173\234i H\184i Thu\232c", "\\script\\\206\247\225\170\\\178\201\210\169\192\207\200\203.lua" },
	{ 1020, "\216\212\202\166", "Th\199y B\227i", "\\script\\\178\202\198\177\\\216\212.lua" },
	{ 1020, "\208\193\195\226", "T\169n Mi\212n", "\\script\\\206\247\225\170\\\208\193\195\226.lua" },
	{ 1021, "\197\253\197\195", "T\215 B\181", "\\script\\\179\175\184\232\\\197\253\197\195.lua" },
	{ 1001, "\176\216\188\248", "B\184 Gi\184m", "\\script\\\183\226\201\241\204\168\\\176\216\188\248.lua" },
	{ 1001, "\205\188\202\233\185\221", "\167\229 Th\173 Qu\184n", "\\script\\\183\226\201\241\204\168\\\205\188\202\233\185\221.lua" },
	{ 1003, "\190\229\193\244\203\239", "C\239 L\173u T\171n", "\\script\\\211\241\208\233\185\172\\\190\229\193\244\203\239.lua" },
	{ 1006, "\183\226\211\161\214\174\203\254", "Phong \202n Th\184p", "\\script\\item\\\204\236\238\184\208\199\\\183\226\211\161\214\174\203\2541.lua" },
	{ 1007, "\183\226\211\161\214\174\203\254", "Phong \202n Th\184p", "\\script\\item\\\204\236\238\184\208\199\\\183\226\211\161\214\174\203\2542.lua" },
	{ 1012, "\183\226\211\161\214\174\203\254", "Phong \202n Th\184p", "\\script\\item\\\204\236\238\184\208\199\\\183\226\211\161\214\174\203\2543.lua" },
	{ 1013, "\183\226\211\161\214\174\203\254", "Phong \202n Th\184p", "\\script\\item\\\204\236\238\184\208\199\\\183\226\211\161\214\174\203\2544.lua" },
	{ 1010, "\183\226\211\161\214\174\203\254", "Phong \202n Th\184p", "\\script\\item\\\204\236\238\184\208\199\\\183\226\211\161\214\174\203\2545.lua" },
	{ 1009, "\183\226\211\161\214\174\203\254", "Phong \202n Th\184p", "\\script\\item\\\204\236\238\184\208\199\\\183\226\211\161\214\174\203\2546.lua" },
	{ 1002, "\212\211\187\245\201\204", "T\185p H\227a" },
	{ 1002, "\201\250\187\238\188\188\196\220\192\207\202\166\163\168\180\243\211\170\163\169", "Sinh Ho\185t S\173 (\167\185i Doanh)", "\\script\\phongthan\\sinhhoat\\sh_master.lua" },
	{ 1052, "\182\254\192\201\201\241", "Nh\222 Lang Th\199n", "\\script\\phongthan\\npc_fix\\1052_nhi_lang_than.lua" },
}

function PTEXT_npcnames_Tick()
	local maxn = PTADM_MAX_NPC or 48000
	local i = 1
	while i < maxn do
		local nm = GetNpcName(i)
		if nm and nm ~= "" then
			local k = 1
			while PTNN_ROWS[k] do
				local r = PTNN_ROWS[k]
				if nm == r[2] then
					local w = GetNpcPos(i)
					if w == r[1] then
						if r[4] then SetNpcScript(i, r[4]) end
						SetNpcName(i, r[3])
					end
				end
				k = k + 1
			end
		end
		i = i + 1
	end
end
