-- sudo_dongdi_lib.lua (2026-10-03, agent sudo_dongdi). Lua 4.0, ASCII (TCVN3 as byte escapes).
-- Generated by scratchpad\sudo_dongdi\gen_lua.py. Doc: docs\features\su-do-dong-di-phong-than-20261003.md
-- Included by: the 3 newbie Vo su, Na Tra Tay Ky, 17 field doctors (PAK copies patched by ptfix
-- extra_sudo_dongdi.py), the trial NPCs npc_fix 1021_tho_hanh_ton / 1021_hoang_thien_hoa / 1020_duong_tien,
-- the Tru Yeu death scripts \script\npcdeath\<template>.lua (ptfix) and sudo_dongdi_drop.lua.
--  * Solo path of the master-apprentice quests: a player who is NOT in a team counts as a valid pair.
--    A team of exactly 2 with the master-apprentice relation keeps the VNG path; any other team is refused.
--  * Tru Yeu (task 42): kill credit for the 8 target templates (the VNG death scripts of 7 of them are
--    missing, so nothing counted even for a real pair). Solo kill count = half of the VNG pair count.
--  * Dong Di (task 597): drops of the quest materials that have no source on this server.

-- the master part of the trial rewards is skipped when solo; keep the call harmless if unregistered
if AddMasterPRValue == nil then
	function AddMasterPRValue(n) end
end

function PTSD_IsPair()
	if GetTeamSize() ~= 2 then return 0 end
	local n = 0
	if IsCaptain() == 0 then n = GetTeamMember(1) else n = GetTeamMember(2) end
	if n and n > 0 and IsMasterPRRelation(n) == 1 then return 1 end
	return 0
end

-- 1 = may take / continue the master-apprentice quest (VNG pair, or solo outside any team)
function PTSD_JudgeRelation()
	if PTSD_IsPair() == 1 then return 1 end
	if GetTeamSize() <= 1 then return 1 end
	return 0
end

PTSD_PR_NAMES = {
	[13] = "Ng\173u S\184t",
	[16] = "D\185 Xoa",
	[17] = "Thi\170n H\185o",
	[18] = "Sa H\229n",
	[20] = "L\244c Quy",
	[23] = "L\183o H\229 l\171",
	[28] = "B\168ng Linh",
	[30] = "Anh Chi\170u Th\199n",
}

-- solo kill count: half of the VNG pair formula 100+(floor(levels/10)-5)*40 with levels = 2 x own level
function PTSD_PR_SoloCount(lv)
	local c = floor((100 + (floor(2 * lv / 10) - 5) * 40) / 2)
	if c < 30 then c = 30 end
	return c
end

-- solo variant of mission_PR_confirm of the newbie Vo su (obj = the teacher's object table)
function PTSD_PR_ConfirmSolo(obj)
	local lv = GetLevel()
	local i = 8
	if lv < 25 then i = random(1, 2)
	elseif lv < 30 then i = 3
	elseif lv < 35 then i = 4
	elseif lv < 40 then i = 5
	elseif lv < 45 then i = 6
	elseif lv < 50 then i = 7
	end
	RemoveIBBuff(215)
	if AddIBBuff(215) ~= 1 then
		Talk(1, "no", "Tr\185ng th\184i c\241a ng\173\172i kh\171ng ph\239 h\238p, kh\171ng th\211 ti\213p nh\203n nhi\214m v\244 s\173 \174\229, khi kh\184c h\183y quay l\185i!")
		return
	end
	SetTask(895, GetTask(895) + 1)
	SetTask(896, SystemTime())
	SetTask(906, GetWeekDay())
	SetTask(897, obj[i].id)
	local count = PTSD_PR_SoloCount(lv)
	SetTask(898, count)
	TaskNote(42, i - 1)
	Talk(1, "no", "D\173\237i s\249 b\182o h\233 c\241a v\223ng s\184ng <color=yellow>Nh\169n gi\182<color>, gi\213t qu\184i nh\203n \174\173\238c nh\169n \174\171i kinh nghi\214m. Ng\173\172i l\181m <color=green>m\233t m\215nh<color> n\170n ch\216 c\199n h\181ng ph\244c " .. count .. ". " .. obj[i].name .. ". Ch\243c ng\173\172i may m\190n!")
end

function PTSD_PR_Credit(tpl)
	if GetTask(897) ~= tpl + 1 then return end
	local count = GetTask(898)
	if count <= 0 then return end
	if PTSD_JudgeRelation() ~= 1 then return end
	local nm = PTSD_PR_NAMES[tpl + 1] or ""
	if HaveIBBuff(215) == 0 then
		Msg2Player("Tr\245 Y\170u: V\223ng s\184ng \174\183 bi\213n m\202t, nhi\214m v\244 truy s\184t th\202t b\185i. H\183y h\241y r\229i nh\203n l\185i \235 V\226 s\173.")
		return
	end
	if count > 1 then
		SetTask(898, count - 1)
		Msg2Player("Tr\245 Y\170u: B\185n c\223n ph\182i gi\213t " .. (count - 1) .. " " .. nm .. "!")
	else
		SetTask(898, 0)
		TaskNote(42, 8)
		Msg2Player("Tr\245 Y\170u: B\185n \174\183 h\181ng ph\244c \174\241 " .. nm .. ", h\183y v\210 g\198p V\226 s\173 nh\203n th\173\235ng.")
	end
end

-- OnDeath body of the Tru Yeu target death scripts: killer + team members on the same map
function PTSD_PR_OnDeath(npcindex)
	local killer = PlayerIndex
	if not killer or killer <= 0 then return end
	local tpl = GetNpcTemplateID(npcindex)
	if not tpl then return end
	local w = GetWorldPos()
	local n = GetTeamSize()
	if n and n > 0 then
		local mem = {}
		local i = 1
		while i <= n do
			mem[i] = GetTeamMember(i)
			i = i + 1
		end
		i = 1
		while i <= n do
			if mem[i] and mem[i] > 0 then
				PlayerIndex = mem[i]
				if GetWorldPos() == w then PTSD_PR_Credit(tpl) end
			end
			i = i + 1
		end
		PlayerIndex = killer
	else
		PTSD_PR_Credit(tpl)
	end
end

-- ------------------------------------------------------------ Dong Di quest drops (killer only)
-- rates in percent per kill; the tu linh (3/22..25, x100 each) come one of each missing kind per kill
PTSD_RATE_KEY = 25     -- Ngoc Hu phu (0/4/21) and Hong bao thach (3/79), task 597 = 7, Lam Cot
PTSD_RATE_SAM = 30     -- Qua nhan sam (3/81), task 597 = 300, Phi Tho of Khai Minh dao (1072)
PTSD_RATE_HOA = 30     -- Mai/Lan/Truc/Cuc (3/73..76), Lieu Nhan accepted (task 588 = 2 or 5)
PTSD_RATE_TULINH = 100 -- Dia tam/Phong le/Thuy hon/Hoa linh (3/22..25), task 597 = 17..21
PTSD_FLOWER_NAMES = { [73] = "Mai", [74] = "Lan", [75] = "Tr\243c", [76] = "C\243c" }
PTSD_TULINH_NAMES = { [22] = "\167\222a t\169m", [23] = "Phong l\214", [24] = "Th\241y h\229n", [25] = "H\225a linh" }

function PTSD_Roll(rate)
	if rate >= 100 then return 1 end
	if random(1, 100) <= rate then return 1 end
	return nil
end

function PTSD_DY_OnKill(npc)
	if not PlayerIndex or PlayerIndex <= 0 then return end
	local st = GetTask(597)
	local w = GetWorldPos()
	if st == 7 and (w == 1044 or w == 1045 or w == 1047) then
		if GetItemLevel2(0, 4, 21) < 1 and PTSD_Roll(PTSD_RATE_KEY) then
			AddNormalItem(0, 4, 21, 1, 0, 0)
			Msg2Player("\167\171ng Nguy: nh\203n \174\173\238c Ng\228c H\173 Ph\239 (\174em \174\213n B\184 Gi\184m).")
		elseif HaveNormalItem(3, 79, 0, 0) < 1 and PTSD_Roll(PTSD_RATE_KEY) then
			AddNormalItemPile(3, 79, 0, 0, 0, 0)
			Msg2Player("\167\171ng Nguy: nh\203n \174\173\238c H\229ng b\182o th\185ch (\174em \174\213n B\184 Gi\184m).")
		end
		return
	end
	if st == 300 and w == 1072 then
		if HaveNormalItem(3, 81, 0, 0) < 1 and PTSD_Roll(PTSD_RATE_SAM) then
			AddNormalItem(3, 81, 0, 0, 0, 0)
			Msg2Player("\167\171ng Nguy: nh\203n \174\173\238c Qu\182 nh\169n s\169m, mau \174em v\210 cho thi\213u n\247 Di t\233c.")
		end
		return
	end
	if st >= 17 and st <= 21 and w == 1072 then
		local s = GetTask(588)
		if (s == 2 or s == 5) and HaveEventItem(111) == 0 and PTSD_Roll(PTSD_RATE_HOA) then
			local k = 73
			while k <= 76 do
				if HaveNormalItem(3, k, 0, 0) < 1 then
					AddNormalItemPile(3, k, 0, 0, 0, 0)
					Msg2Player("\167\171ng Nguy: nh\203n \174\173\238c hoa " .. PTSD_FLOWER_NAMES[k])
					k = 99
				end
				k = k + 1
			end
		end
		if s >= 1 and PTSD_Roll(PTSD_RATE_TULINH) then
			local k = 22
			while k <= 25 do
				if HaveNormalItem(3, k, 0, 0) < 100 then
					AddNormalItemPile(3, k, 0, 0, 0, 0)
				end
				k = k + 1
			end
		end
	end
end
