-- Phong Than 2026-10-03 (tienma45): Tien Ma gioi phase 4 (Nguc Phap Son 1075) + phase 5 (Thanh Dia 1076).
-- Generated by scratchpad\tienma45\mk45.py; edit the generator, not this file.
-- Minute tick of tienma45 (servertimer.lua calls PTEXT_tienma45_Tick() protected, once a minute).
-- 1. registers the loose role/monster scripts and the PAK stubs of extra_tienma45.py once per server start;
-- 2. first tick: takes over the region placeholders of maps 1075/1076 (same template, same cell; the
--    npc_restore placeholder scripts stay on disk), spawns the other dialog NPCs;
-- 3. keeps every dialog NPC and the quest monster packs alive (re-spawn when the index lost our name/mark).
-- Dong Di NPCs (map 1073, ext\sudo_dongdi.lua) and the Tien Ma phase 1-3 NPCs (ext\tienma.lua) are not touched.
PT45_EXT_MAX_NPC = 48000
PT45_EXT_K_PACK = 7745
PT45_EXT_MOB = "\\script\\phongthan\\tienma45\\tm45_mob.lua"
PT45_EXT_SCRIPTS = {}
PT45_EXT_SCRIPTS[1] = "\\script\\phongthan\\tienma45\\n45_bachhop_1.lua"
PT45_EXT_SCRIPTS[2] = "\\script\\phongthan\\tienma45\\n45_bachhop_2.lua"
PT45_EXT_SCRIPTS[3] = "\\script\\phongthan\\tienma45\\n45_bachhop_3.lua"
PT45_EXT_SCRIPTS[4] = "\\script\\phongthan\\tienma45\\n45_bachhop_4.lua"
PT45_EXT_SCRIPTS[5] = "\\script\\phongthan\\tienma45\\n45_bachhop_5.lua"
PT45_EXT_SCRIPTS[6] = "\\script\\phongthan\\tienma45\\n45_conggate.lua"
PT45_EXT_SCRIPTS[7] = "\\script\\phongthan\\tienma45\\n45_dongdat.lua"
PT45_EXT_SCRIPTS[8] = "\\script\\phongthan\\tienma45\\n45_duocsu_1.lua"
PT45_EXT_SCRIPTS[9] = "\\script\\phongthan\\tienma45\\n45_duocsu_2.lua"
PT45_EXT_SCRIPTS[10] = "\\script\\phongthan\\tienma45\\n45_herb_1.lua"
PT45_EXT_SCRIPTS[11] = "\\script\\phongthan\\tienma45\\n45_herb_2.lua"
PT45_EXT_SCRIPTS[12] = "\\script\\phongthan\\tienma45\\n45_hondungsi.lua"
PT45_EXT_SCRIPTS[13] = "\\script\\phongthan\\tienma45\\n45_huyenthach.lua"
PT45_EXT_SCRIPTS[14] = "\\script\\phongthan\\tienma45\\n45_khieuloi.lua"
PT45_EXT_SCRIPTS[15] = "\\script\\phongthan\\tienma45\\n45_khuongtunha.lua"
PT45_EXT_SCRIPTS[16] = "\\script\\phongthan\\tienma45\\n45_laban_1.lua"
PT45_EXT_SCRIPTS[17] = "\\script\\phongthan\\tienma45\\n45_laban_2.lua"
PT45_EXT_SCRIPTS[18] = "\\script\\phongthan\\tienma45\\n45_laban_3.lua"
PT45_EXT_SCRIPTS[19] = "\\script\\phongthan\\tienma45\\n45_laban_4.lua"
PT45_EXT_SCRIPTS[20] = "\\script\\phongthan\\tienma45\\n45_leu.lua"
PT45_EXT_SCRIPTS[21] = "\\script\\phongthan\\tienma45\\n45_longnhan_1.lua"
PT45_EXT_SCRIPTS[22] = "\\script\\phongthan\\tienma45\\n45_longnhan_2.lua"
PT45_EXT_SCRIPTS[23] = "\\script\\phongthan\\tienma45\\n45_mattham_1.lua"
PT45_EXT_SCRIPTS[24] = "\\script\\phongthan\\tienma45\\n45_mattham_2.lua"
PT45_EXT_SCRIPTS[25] = "\\script\\phongthan\\tienma45\\n45_mo_1.lua"
PT45_EXT_SCRIPTS[26] = "\\script\\phongthan\\tienma45\\n45_mo_2.lua"
PT45_EXT_SCRIPTS[27] = "\\script\\phongthan\\tienma45\\n45_phagioi.lua"
PT45_EXT_SCRIPTS[28] = "\\script\\phongthan\\tienma45\\n45_phaptru_1.lua"
PT45_EXT_SCRIPTS[29] = "\\script\\phongthan\\tienma45\\n45_phaptru_2.lua"
PT45_EXT_SCRIPTS[30] = "\\script\\phongthan\\tienma45\\n45_phaptru_3.lua"
PT45_EXT_SCRIPTS[31] = "\\script\\phongthan\\tienma45\\n45_phaptru_4.lua"
PT45_EXT_SCRIPTS[32] = "\\script\\phongthan\\tienma45\\n45_saladest_1.lua"
PT45_EXT_SCRIPTS[33] = "\\script\\phongthan\\tienma45\\n45_saladest_2.lua"
PT45_EXT_SCRIPTS[34] = "\\script\\phongthan\\tienma45\\n45_salaguide_1.lua"
PT45_EXT_SCRIPTS[35] = "\\script\\phongthan\\tienma45\\n45_salaguide_2.lua"
PT45_EXT_SCRIPTS[36] = "\\script\\phongthan\\tienma45\\n45_salatd_1.lua"
PT45_EXT_SCRIPTS[37] = "\\script\\phongthan\\tienma45\\n45_salatd_2.lua"
PT45_EXT_SCRIPTS[38] = "\\script\\phongthan\\tienma45\\n45_songthu.lua"
PT45_EXT_SCRIPTS[39] = "\\script\\phongthan\\tienma45\\n45_statue_1.lua"
PT45_EXT_SCRIPTS[40] = "\\script\\phongthan\\tienma45\\n45_statue_10.lua"
PT45_EXT_SCRIPTS[41] = "\\script\\phongthan\\tienma45\\n45_statue_11.lua"
PT45_EXT_SCRIPTS[42] = "\\script\\phongthan\\tienma45\\n45_statue_12.lua"
PT45_EXT_SCRIPTS[43] = "\\script\\phongthan\\tienma45\\n45_statue_2.lua"
PT45_EXT_SCRIPTS[44] = "\\script\\phongthan\\tienma45\\n45_statue_3.lua"
PT45_EXT_SCRIPTS[45] = "\\script\\phongthan\\tienma45\\n45_statue_4.lua"
PT45_EXT_SCRIPTS[46] = "\\script\\phongthan\\tienma45\\n45_statue_5.lua"
PT45_EXT_SCRIPTS[47] = "\\script\\phongthan\\tienma45\\n45_statue_6.lua"
PT45_EXT_SCRIPTS[48] = "\\script\\phongthan\\tienma45\\n45_statue_7.lua"
PT45_EXT_SCRIPTS[49] = "\\script\\phongthan\\tienma45\\n45_statue_8.lua"
PT45_EXT_SCRIPTS[50] = "\\script\\phongthan\\tienma45\\n45_statue_9.lua"
PT45_EXT_SCRIPTS[51] = "\\script\\phongthan\\tienma45\\n45_suoi.lua"
PT45_EXT_SCRIPTS[52] = "\\script\\phongthan\\tienma45\\n45_tamnguyen_1.lua"
PT45_EXT_SCRIPTS[53] = "\\script\\phongthan\\tienma45\\n45_tamnguyen_2.lua"
PT45_EXT_SCRIPTS[54] = "\\script\\phongthan\\tienma45\\n45_tinhquan.lua"
PT45_EXT_SCRIPTS[55] = "\\script\\phongthan\\tienma45\\n45_tocnhan.lua"
PT45_EXT_SCRIPTS[56] = "\\script\\phongthan\\tienma45\\n45_tubattuong.lua"
PT45_EXT_SCRIPTS[57] = "\\script\\phongthan\\tienma45\\n45_tuhanhsu5_1.lua"
PT45_EXT_SCRIPTS[58] = "\\script\\phongthan\\tienma45\\n45_tuhanhsu5_2.lua"
PT45_EXT_SCRIPTS[59] = "\\script\\phongthan\\tienma45\\n45_tuhanhsu_1.lua"
PT45_EXT_SCRIPTS[60] = "\\script\\phongthan\\tienma45\\n45_tuhanhsu_2.lua"
PT45_EXT_SCRIPTS[61] = "\\script\\phongthan\\tienma45\\n45_tuonghon_1.lua"
PT45_EXT_SCRIPTS[62] = "\\script\\phongthan\\tienma45\\n45_tuonghon_2.lua"
PT45_EXT_SCRIPTS[63] = "\\script\\phongthan\\tienma45\\n45_vodanh.lua"
PT45_EXT_SCRIPTS[64] = "\\script\\phongthan\\tienma45\\n45_yenbaich.lua"
PT45_EXT_SCRIPTS[65] = "\\script\\phongthan\\tienma45\\n45_yenphong.lua"
PT45_EXT_SCRIPTS[66] = "\\script\\phongthan\\tienma45\\n45_yenthucdi.lua"
PT45_EXT_SCRIPTS[67] = "\\script\\phongthan\\tienma45\\n45_yentuminh.lua"
PT45_EXT_SCRIPTS[68] = "\\script\\phongthan\\tienma45\\n45_yenvan.lua"
PT45_EXT_SCRIPTS[69] = "\\script\\phongthan\\tienma45\\tm45_mob.lua"
-- PAK paths of extra_tienma45.py (item scripts, death scripts, VNG NPC paths); harmless while ptfix is not deployed
PT45_EXT_PAK = {}
PT45_EXT_PAK[1] = "\\script\\item\\\189\226\214\228\183\251.lua"
PT45_EXT_PAK[2] = "\\script\\item\\hetuluoshu.lua"
PT45_EXT_PAK[3] = "\\script\\item\\\210\253\200\170\213\235.lua"
PT45_EXT_PAK[4] = "\\script\\npcdeath\\\236\229.lua"
PT45_EXT_PAK[5] = "\\script\\npcdeath\\\213\248.lua"
PT45_EXT_PAK[6] = "\\script\\npcdeath\\\207\201\161\164\199\213\212\173.lua"
PT45_EXT_PAK[7] = "\\script\\npcdeath\\\196\167\161\164\199\213\212\173.lua"
PT45_EXT_PAK[8] = "\\script\\\211\252\183\168\201\189\\\208\222\208\208\202\166\207\201.lua"
PT45_EXT_PAK[9] = "\\script\\\211\252\183\168\201\189\\\208\222\208\208\202\166\196\167.lua"
PT45_EXT_PAK[10] = "\\script\\\211\252\183\168\201\189\\\217\200\178\174\210\230.lua"
PT45_EXT_PAK[11] = "\\script\\\211\252\183\168\201\189\\\217\200\202\229\210\196.lua"
PT45_EXT_PAK[12] = "\\script\\\211\252\183\168\201\189\\\217\200\183\231.lua"
PT45_EXT_PAK[13] = "\\script\\\211\252\183\168\201\189\\\217\200\212\198.lua"
PT45_EXT_PAK[14] = "\\script\\\211\252\183\168\201\189\\\217\200\215\211\195\247.lua"
PT45_EXT_PAK[15] = "\\script\\\211\252\183\168\201\189\\\207\201\189\231\195\220\204\189.lua"
PT45_EXT_PAK[16] = "\\script\\\211\252\183\168\201\189\\\196\167\189\231\195\220\204\189.lua"
PT45_EXT_PAK[17] = "\\script\\\211\252\183\168\201\189\\\203\196\178\187\207\2411.lua"
PT45_EXT_PAK[18] = "\\script\\\211\252\183\168\201\189\\\208\165\192\215\182\212\187\176.lua"
PT45_EXT_PAK[19] = "\\script\\\211\252\183\168\201\189\\\242\221\242\246\215\211.lua"
PT45_EXT_PAK[20] = "\\script\\\211\252\183\168\201\189\\\199\224\212\198\191\205.lua"
PT45_EXT_PAK[21] = "\\script\\\211\252\183\168\201\189\\\182\190\192\188\178\221.lua"
PT45_EXT_PAK[22] = "\\script\\\211\252\183\168\201\189\\\193\250\201\224\192\188.lua"
PT45_EXT_PAK[23] = "\\script\\\211\252\183\168\201\189\\\200\170\203\174.lua"
PT45_EXT_PAK[24] = "\\script\\\211\252\183\168\201\189\\\202\167\215\217\181\196\215\229\200\203.lua"
PT45_EXT_PAK[25] = "\\script\\\218\230\200\170\202\165\181\216\\\208\222\208\208\202\166\207\201.lua"
PT45_EXT_PAK[26] = "\\script\\\218\230\200\170\202\165\181\216\\\208\222\208\208\202\166\196\167.lua"
PT45_EXT_PAK[27] = "\\script\\\218\230\200\170\202\165\181\216\\\207\201\190\252\210\189\202\166.lua"
PT45_EXT_PAK[28] = "\\script\\\218\230\200\170\202\165\181\216\\\196\167\190\252\210\189\202\166.lua"
PT45_EXT_PAK[29] = "\\script\\\218\230\200\170\202\165\181\216\\\188\167\208\254\183\226.lua"
PT45_EXT_PAK[30] = "\\script\\\218\230\200\170\202\165\181\216\\\189\170\216\174\206\253.lua"
PT45_EXT_PAK[31] = "\\script\\\218\230\200\170\202\165\181\216\\\188\167\208\254\183\226\196\185.lua"
PT45_EXT_PAK[32] = "\\script\\\218\230\200\170\202\165\181\216\\\189\170\216\174\206\253\196\185.lua"
PT45_EXT_PAK[33] = "\\script\\\218\230\200\170\202\165\181\216\\\202\165\181\216\176\217\186\207.lua"
PT45_EXT_PAK[34] = "\\script\\\218\230\200\170\202\165\181\216\\\242\221\242\246\215\211.lua"
PT45_EXT_PAK[35] = "\\script\\\218\230\200\170\202\165\181\216\\\199\224\212\198\191\205.lua"
PT45_EXT_PAK[36] = "\\script\\\218\230\200\170\202\165\181\216\\\202\165\200\170\201\241\177\248\\\189\170\134\141\195\249\214\174\187\234.lua"
PT45_EXT_PAK[37] = "\\script\\\218\230\200\170\202\165\181\216\\\202\165\200\170\201\241\177\248\\\188\167\178\212\208\254\214\174\187\234.lua"
PT45_EXT_PAK[38] = "\\script\\\218\230\200\170\202\165\181\216\\\218\230\200\170\204\189\195\216\\\206\222\195\251\192\207\200\203.lua"
PT45_EXT_PAK[39] = "\\script\\\218\230\200\170\202\165\181\216\\\218\230\200\170\204\189\195\216\\\206\222\195\251\192\207\200\203\181\196\213\202\197\241.lua"
PT45_EXT_PAK[40] = "\\script\\\218\230\200\170\202\165\181\216\\\218\230\200\170\204\189\195\216\\\205\193\182\209.lua"
-- dialog NPCs: { map, template, x, y, name (TCVN3), script, adopt, spawn x, spawn y }
PT45_EXT_NPCS = {}
local s
s = {} PT45_EXT_NPCS[1] = s -- tuhanhsu_tien
s[1] = 1075 s[2] = 765 s[3] = 1844 s[4] = 3576 s[5] = "Tu H\181nh S\173"
s[6] = "\\script\\phongthan\\tienma45\\n45_tuhanhsu_1.lua" s[7] = 1 s[8] = 1844 s[9] = 3576
s = {} PT45_EXT_NPCS[2] = s -- tuhanhsu_ma
s[1] = 1075 s[2] = 765 s[3] = 1884 s[4] = 3352 s[5] = "Tu H\181nh S\173"
s[6] = "\\script\\phongthan\\tienma45\\n45_tuhanhsu_2.lua" s[7] = 1 s[8] = 1884 s[9] = 3352
s = {} PT45_EXT_NPCS[3] = s -- yenthucdi
s[1] = 1075 s[2] = 1009 s[3] = 1868 s[4] = 3432 s[5] = "Y\211n Th\243c Di"
s[6] = "\\script\\phongthan\\tienma45\\n45_yenthucdi.lua" s[7] = 1 s[8] = 1868 s[9] = 3432
s = {} PT45_EXT_NPCS[4] = s -- yenbaich
s[1] = 1075 s[2] = 1008 s[3] = 1884 s[4] = 3432 s[5] = "Y\211n B\184 \221ch"
s[6] = "\\script\\phongthan\\tienma45\\n45_yenbaich.lua" s[7] = 1 s[8] = 1884 s[9] = 3432
s = {} PT45_EXT_NPCS[5] = s -- mattham_tien
s[1] = 1075 s[2] = 1013 s[3] = 1932 s[4] = 3624 s[5] = "M\203t th\184m Ti\170n gi\237i"
s[6] = "\\script\\phongthan\\tienma45\\n45_mattham_1.lua" s[7] = 1 s[8] = 1932 s[9] = 3624
s = {} PT45_EXT_NPCS[6] = s -- mattham_ma
s[1] = 1075 s[2] = 1014 s[3] = 1796 s[4] = 3352 s[5] = "M\203t th\184m Ma gi\237i"
s[6] = "\\script\\phongthan\\tienma45\\n45_mattham_2.lua" s[7] = 1 s[8] = 1792 s[9] = 3356
s = {} PT45_EXT_NPCS[7] = s -- khieuloi
s[1] = 1075 s[2] = 210 s[3] = 2092 s[4] = 3336 s[5] = "Khi\213u L\171i"
s[6] = "\\script\\phongthan\\tienma45\\n45_khieuloi.lua" s[7] = 1 s[8] = 2092 s[9] = 3336
s = {} PT45_EXT_NPCS[8] = s -- yenphong
s[1] = 1075 s[2] = 1010 s[3] = 1600 s[4] = 3818 s[5] = "Y\211n Phong"
s[6] = "\\script\\phongthan\\tienma45\\n45_yenphong.lua" s[7] = 0 s[8] = 1600 s[9] = 3818
s = {} PT45_EXT_NPCS[9] = s -- yenvan
s[1] = 1075 s[2] = 1011 s[3] = 1898 s[4] = 3442 s[5] = "Y\211n V\169n"
s[6] = "\\script\\phongthan\\tienma45\\n45_yenvan.lua" s[7] = 0 s[8] = 1898 s[9] = 3442
s = {} PT45_EXT_NPCS[10] = s -- yentuminh
s[1] = 1075 s[2] = 1012 s[3] = 1896 s[4] = 3418 s[5] = "Y\211n T\246 Minh"
s[6] = "\\script\\phongthan\\tienma45\\n45_yentuminh.lua" s[7] = 0 s[8] = 1896 s[9] = 3418
s = {} PT45_EXT_NPCS[11] = s -- tubattuong
s[1] = 1075 s[2] = 1023 s[3] = 1722 s[4] = 3644 s[5] = "T\248 B\202t T\173\237ng"
s[6] = "\\script\\phongthan\\tienma45\\n45_tubattuong.lua" s[7] = 0 s[8] = 1722 s[9] = 3644
s = {} PT45_EXT_NPCS[12] = s -- phaptru_1
s[1] = 1075 s[2] = 1016 s[3] = 2023 s[4] = 3196 s[5] = "Ph\184p tr\244 (B\190c)"
s[6] = "\\script\\phongthan\\tienma45\\n45_phaptru_1.lua" s[7] = 0 s[8] = 2023 s[9] = 3196
s = {} PT45_EXT_NPCS[13] = s -- phaptru_2
s[1] = 1075 s[2] = 1017 s[3] = 2105 s[4] = 3813 s[5] = "Ph\184p tr\244 (\167\171ng)"
s[6] = "\\script\\phongthan\\tienma45\\n45_phaptru_2.lua" s[7] = 0 s[8] = 2105 s[9] = 3813
s = {} PT45_EXT_NPCS[14] = s -- phaptru_3
s[1] = 1075 s[2] = 1018 s[3] = 1604 s[4] = 3773 s[5] = "Ph\184p tr\244 (Nam)"
s[6] = "\\script\\phongthan\\tienma45\\n45_phaptru_3.lua" s[7] = 0 s[8] = 1604 s[9] = 3773
s = {} PT45_EXT_NPCS[15] = s -- phaptru_4
s[1] = 1075 s[2] = 1015 s[3] = 1629 s[4] = 3206 s[5] = "Ph\184p tr\244 (T\169y)"
s[6] = "\\script\\phongthan\\tienma45\\n45_phaptru_4.lua" s[7] = 0 s[8] = 1629 s[9] = 3206
s = {} PT45_EXT_NPCS[16] = s -- laban_1
s[1] = 1075 s[2] = 1019 s[3] = 1872 s[4] = 3396 s[5] = "La B\181n (B\190c)"
s[6] = "\\script\\phongthan\\tienma45\\n45_laban_1.lua" s[7] = 0 s[8] = 1872 s[9] = 3396
s = {} PT45_EXT_NPCS[17] = s -- laban_2
s[1] = 1075 s[2] = 1020 s[3] = 1906 s[4] = 3436 s[5] = "La B\181n (\167\171ng)"
s[6] = "\\script\\phongthan\\tienma45\\n45_laban_2.lua" s[7] = 0 s[8] = 1906 s[9] = 3436
s = {} PT45_EXT_NPCS[18] = s -- laban_3
s[1] = 1075 s[2] = 1021 s[3] = 1861 s[4] = 3477 s[5] = "La B\181n (Nam)"
s[6] = "\\script\\phongthan\\tienma45\\n45_laban_3.lua" s[7] = 0 s[8] = 1861 s[9] = 3477
s = {} PT45_EXT_NPCS[19] = s -- laban_4
s[1] = 1075 s[2] = 1022 s[3] = 1836 s[4] = 3440 s[5] = "La B\181n (T\169y)"
s[6] = "\\script\\phongthan\\tienma45\\n45_laban_4.lua" s[7] = 0 s[8] = 1836 s[9] = 3440
s = {} PT45_EXT_NPCS[20] = s -- conggate
s[1] = 1075 s[2] = 876 s[3] = 1848 s[4] = 3464 s[5] = "C\230ng th\234i gian"
s[6] = "\\script\\phongthan\\tienma45\\n45_conggate.lua" s[7] = 0 s[8] = 1848 s[9] = 3464
s = {} PT45_EXT_NPCS[21] = s -- khuongtunha
s[1] = 1075 s[2] = 301 s[3] = 1596 s[4] = 3500 s[5] = "Kh\173\172ng T\246 Nha l\243c nh\225"
s[6] = "\\script\\phongthan\\tienma45\\n45_khuongtunha.lua" s[7] = 0 s[8] = 1596 s[9] = 3500
s = {} PT45_EXT_NPCS[22] = s -- doclan
s[1] = 1075 s[2] = 1246 s[3] = 1656 s[4] = 3280 s[5] = "\167\233c Lan Th\182o"
s[6] = "\\script\\phongthan\\tienma45\\n45_herb_1.lua" s[7] = 0 s[8] = 1656 s[9] = 3280
s = {} PT45_EXT_NPCS[23] = s -- longthiet
s[1] = 1075 s[2] = 1246 s[3] = 1984 s[4] = 3712 s[5] = "Long Thi\214t Lan"
s[6] = "\\script\\phongthan\\tienma45\\n45_herb_2.lua" s[7] = 0 s[8] = 1984 s[9] = 3712
s = {} PT45_EXT_NPCS[24] = s -- suoi
s[1] = 1075 s[2] = 876 s[3] = 1856 s[4] = 3504 s[5] = "N\173\237c su\232i"
s[6] = "\\script\\phongthan\\tienma45\\n45_suoi.lua" s[7] = 0 s[8] = 1856 s[9] = 3504
s = {} PT45_EXT_NPCS[25] = s -- huyenthach
s[1] = 1075 s[2] = 876 s[3] = 2089 s[4] = 3263 s[5] = "Huy\210n Th\185ch"
s[6] = "\\script\\phongthan\\tienma45\\n45_huyenthach.lua" s[7] = 0 s[8] = 2089 s[9] = 3263
s = {} PT45_EXT_NPCS[26] = s -- phagioi
s[1] = 1075 s[2] = 876 s[3] = 2080 s[4] = 3552 s[5] = "Ph\184 Gi\237i Th\185ch \167\181i"
s[6] = "\\script\\phongthan\\tienma45\\n45_phagioi.lua" s[7] = 0 s[8] = 2080 s[9] = 3552
s = {} PT45_EXT_NPCS[27] = s -- tocnhan
s[1] = 1075 s[2] = 165 s[3] = 2110 s[4] = 3700 s[5] = "T\233c nh\169n m\202t t\221ch"
s[6] = "\\script\\phongthan\\tienma45\\n45_tocnhan.lua" s[7] = 0 s[8] = 2110 s[9] = 3700
s = {} PT45_EXT_NPCS[28] = s -- tinhquan
s[1] = 1075 s[2] = 1115 s[3] = 1950 s[4] = 3520 s[5] = "Tinh qu\169n \174i\170u t\173\238ng"
s[6] = "\\script\\phongthan\\tienma45\\n45_tinhquan.lua" s[7] = 0 s[8] = 1950 s[9] = 3520
s = {} PT45_EXT_NPCS[29] = s -- phuduttu
s[1] = 1075 s[2] = 1186 s[3] = 2032 s[4] = 3808 s[5] = "Ph\239 Du T\246"
s[6] = "\\script\\phongthan\\tienma45\\n45_salaguide_1.lua" s[7] = 0 s[8] = 2032 s[9] = 3808
s = {} PT45_EXT_NPCS[30] = s -- thanhvan
s[1] = 1075 s[2] = 1185 s[3] = 1936 s[4] = 3184 s[5] = "Thanh V\169n Kh\184ch"
s[6] = "\\script\\phongthan\\tienma45\\n45_salaguide_2.lua" s[7] = 0 s[8] = 1936 s[9] = 3184
s = {} PT45_EXT_NPCS[31] = s -- phuduttu_d
s[1] = 1075 s[2] = 1186 s[3] = 1912 s[4] = 3648 s[5] = "Ph\239 Du T\246"
s[6] = "\\script\\phongthan\\tienma45\\n45_saladest_1.lua" s[7] = 0 s[8] = 1912 s[9] = 3648
s = {} PT45_EXT_NPCS[32] = s -- thanhvan_d
s[1] = 1075 s[2] = 1185 s[3] = 1792 s[4] = 3376 s[5] = "Thanh V\169n Kh\184ch"
s[6] = "\\script\\phongthan\\tienma45\\n45_saladest_2.lua" s[7] = 0 s[8] = 1792 s[9] = 3376
s = {} PT45_EXT_NPCS[33] = s -- tuhanhsu5_tien
s[1] = 1076 s[2] = 765 s[3] = 1980 s[4] = 3816 s[5] = "Tu H\181nh S\173"
s[6] = "\\script\\phongthan\\tienma45\\n45_tuhanhsu5_1.lua" s[7] = 1 s[8] = 1980 s[9] = 3816
s = {} PT45_EXT_NPCS[34] = s -- tuhanhsu5_ma
s[1] = 1076 s[2] = 765 s[3] = 1644 s[4] = 3240 s[5] = "Tu H\181nh S\173"
s[6] = "\\script\\phongthan\\tienma45\\n45_tuhanhsu5_2.lua" s[7] = 1 s[8] = 1644 s[9] = 3240
s = {} PT45_EXT_NPCS[35] = s -- duocsu_tien
s[1] = 1076 s[2] = 149 s[3] = 1916 s[4] = 3816 s[5] = "D\173\238c S\173 Ti\170n gi\237i"
s[6] = "\\script\\phongthan\\tienma45\\n45_duocsu_1.lua" s[7] = 1 s[8] = 1916 s[9] = 3816
s = {} PT45_EXT_NPCS[36] = s -- duocsu_ma
s[1] = 1076 s[2] = 149 s[3] = 1676 s[4] = 3256 s[5] = "D\173\238c S\173 Ma gi\237i"
s[6] = "\\script\\phongthan\\tienma45\\n45_duocsu_2.lua" s[7] = 1 s[8] = 1676 s[9] = 3256
s = {} PT45_EXT_NPCS[37] = s -- khuongngutich
s[1] = 1076 s[2] = 202 s[3] = 1700 s[4] = 3272 s[5] = "Kh\173\172ng Ngu T\221ch"
s[6] = "\\script\\phongthan\\tienma45\\n45_tamnguyen_2.lua" s[7] = 1 s[8] = 1700 s[9] = 3272
s = {} PT45_EXT_NPCS[38] = s -- cohuyenphong
s[1] = 1076 s[2] = 202 s[3] = 1944 s[4] = 3792 s[5] = "C\172 Huy\210n Phong"
s[6] = "\\script\\phongthan\\tienma45\\n45_tamnguyen_1.lua" s[7] = 0 s[8] = 1944 s[9] = 3792
s = {} PT45_EXT_NPCS[39] = s -- hondungsi
s[1] = 1076 s[2] = 1168 s[3] = 1655 s[4] = 3845 s[5] = "H\229n D\242ng s\220 c\230 \174\185i"
s[6] = "\\script\\phongthan\\tienma45\\n45_hondungsi.lua" s[7] = 0 s[8] = 1655 s[9] = 3845
s = {} PT45_EXT_NPCS[40] = s -- mo_co
s[1] = 1076 s[2] = 1163 s[3] = 1967 s[4] = 3775 s[5] = "M\233 C\172 Huy\210n Phong"
s[6] = "\\script\\phongthan\\tienma45\\n45_mo_1.lua" s[7] = 0 s[8] = 1967 s[9] = 3775
s = {} PT45_EXT_NPCS[41] = s -- mo_khuong
s[1] = 1076 s[2] = 1164 s[3] = 1679 s[4] = 3215 s[5] = "M\233 Kh\173\172ng Ngu T\221ch"
s[6] = "\\script\\phongthan\\tienma45\\n45_mo_2.lua" s[7] = 0 s[8] = 1679 s[9] = 3215
s = {} PT45_EXT_NPCS[42] = s -- banglongnhan
s[1] = 1076 s[2] = 876 s[3] = 1976 s[4] = 3392 s[5] = "B\168ng Long Nh\183n"
s[6] = "\\script\\phongthan\\tienma45\\n45_longnhan_1.lua" s[7] = 0 s[8] = 1976 s[9] = 3392
s = {} PT45_EXT_NPCS[43] = s -- hoalongnhan
s[1] = 1076 s[2] = 876 s[3] = 1992 s[4] = 3360 s[5] = "H\225a Long Nh\183n"
s[6] = "\\script\\phongthan\\tienma45\\n45_longnhan_2.lua" s[7] = 0 s[8] = 1992 s[9] = 3360
s = {} PT45_EXT_NPCS[44] = s -- leu
s[1] = 1076 s[2] = 876 s[3] = 2024 s[4] = 3472 s[5] = "L\210u c\241a V\171 Danh L\183o Nh\169n"
s[6] = "\\script\\phongthan\\tienma45\\n45_leu.lua" s[7] = 0 s[8] = 2024 s[9] = 3472
s = {} PT45_EXT_NPCS[45] = s -- dongdat
s[1] = 1076 s[2] = 876 s[3] = 2020 s[4] = 3560 s[5] = "\167\232ng \174\202t"
s[6] = "\\script\\phongthan\\tienma45\\n45_dongdat.lua" s[7] = 0 s[8] = 2020 s[9] = 3560
s = {} PT45_EXT_NPCS[46] = s -- vodanh
s[1] = 1076 s[2] = 165 s[3] = 1760 s[4] = 3480 s[5] = "V\171 Danh L\183o Nh\169n"
s[6] = "\\script\\phongthan\\tienma45\\n45_vodanh.lua" s[7] = 0 s[8] = 1760 s[9] = 3480
s = {} PT45_EXT_NPCS[47] = s -- tuong_khuong
s[1] = 1076 s[2] = 1169 s[3] = 2004 s[4] = 3448 s[5] = "H\229n Kh\173\172ng Giai Minh"
s[6] = "\\script\\phongthan\\tienma45\\n45_tuonghon_1.lua" s[7] = 0 s[8] = 2004 s[9] = 3448
s = {} PT45_EXT_NPCS[48] = s -- tuong_co
s[1] = 1076 s[2] = 1170 s[3] = 2037 s[4] = 3459 s[5] = "H\229n C\172 Th\173\172ng Huy\210n"
s[6] = "\\script\\phongthan\\tienma45\\n45_tuonghon_2.lua" s[7] = 0 s[8] = 2037 s[9] = 3459
s = {} PT45_EXT_NPCS[49] = s -- phuduttu_td
s[1] = 1076 s[2] = 1186 s[3] = 2008 s[4] = 3760 s[5] = "Ph\239 Du T\246"
s[6] = "\\script\\phongthan\\tienma45\\n45_salatd_1.lua" s[7] = 0 s[8] = 2008 s[9] = 3760
s = {} PT45_EXT_NPCS[50] = s -- thanhvan_td
s[1] = 1076 s[2] = 1185 s[3] = 1624 s[4] = 3296 s[5] = "Thanh V\169n Kh\184ch"
s[6] = "\\script\\phongthan\\tienma45\\n45_salatd_2.lua" s[7] = 0 s[8] = 1624 s[9] = 3296
s = {} PT45_EXT_NPCS[51] = s -- songthu
s[1] = 1076 s[2] = 876 s[3] = 1800 s[4] = 3472 s[5] = "Sa La Song Th\244"
s[6] = "\\script\\phongthan\\tienma45\\n45_songthu.lua" s[7] = 0 s[8] = 1800 s[9] = 3472
s = {} PT45_EXT_NPCS[52] = s -- bachhop_1
s[1] = 1076 s[2] = 1246 s[3] = 1790 s[4] = 3700 s[5] = "Th\184nh \167\222a B\184ch H\238p"
s[6] = "\\script\\phongthan\\tienma45\\n45_bachhop_1.lua" s[7] = 0 s[8] = 1790 s[9] = 3700
s = {} PT45_EXT_NPCS[53] = s -- bachhop_2
s[1] = 1076 s[2] = 1246 s[3] = 1804 s[4] = 3700 s[5] = "Th\184nh \167\222a B\184ch H\238p"
s[6] = "\\script\\phongthan\\tienma45\\n45_bachhop_2.lua" s[7] = 0 s[8] = 1804 s[9] = 3700
s = {} PT45_EXT_NPCS[54] = s -- bachhop_3
s[1] = 1076 s[2] = 1246 s[3] = 1818 s[4] = 3700 s[5] = "Th\184nh \167\222a B\184ch H\238p"
s[6] = "\\script\\phongthan\\tienma45\\n45_bachhop_3.lua" s[7] = 0 s[8] = 1818 s[9] = 3700
s = {} PT45_EXT_NPCS[55] = s -- bachhop_4
s[1] = 1076 s[2] = 1246 s[3] = 1790 s[4] = 3726 s[5] = "Th\184nh \167\222a B\184ch H\238p"
s[6] = "\\script\\phongthan\\tienma45\\n45_bachhop_4.lua" s[7] = 0 s[8] = 1790 s[9] = 3726
s = {} PT45_EXT_NPCS[56] = s -- bachhop_5
s[1] = 1076 s[2] = 1246 s[3] = 1804 s[4] = 3726 s[5] = "Th\184nh \167\222a B\184ch H\238p"
s[6] = "\\script\\phongthan\\tienma45\\n45_bachhop_5.lua" s[7] = 0 s[8] = 1804 s[9] = 3726
s = {} PT45_EXT_NPCS[57] = s -- statue_1
s[1] = 1075 s[2] = 1115 s[3] = 2082 s[4] = 3431 s[5] = "Tinh qu\169n Th\184i D\173\172ng"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_1.lua" s[7] = 0 s[8] = 2082 s[9] = 3431
s = {} PT45_EXT_NPCS[58] = s -- statue_2
s[1] = 1075 s[2] = 1116 s[3] = 2053 s[4] = 3596 s[5] = "Tinh qu\169n Th\184i Tu\213"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_2.lua" s[7] = 0 s[8] = 2053 s[9] = 3596
s = {} PT45_EXT_NPCS[59] = s -- statue_3
s[1] = 1075 s[2] = 1117 s[3] = 1972 s[4] = 3711 s[5] = "Tinh qu\169n Ti\211u Hao"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_3.lua" s[7] = 0 s[8] = 1972 s[9] = 3711
s = {} PT45_EXT_NPCS[60] = s -- statue_4
s[1] = 1075 s[2] = 1118 s[3] = 1871 s[4] = 3760 s[5] = "Tinh qu\169n D\222ch M\183"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_4.lua" s[7] = 0 s[8] = 1871 s[9] = 3760
s = {} PT45_EXT_NPCS[61] = s -- statue_5
s[1] = 1075 s[2] = 1119 s[3] = 1759 s[4] = 3708 s[5] = "Tinh qu\169n Ng\242 Qu\251"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_5.lua" s[7] = 0 s[8] = 1759 s[9] = 3708
s = {} PT45_EXT_NPCS[62] = s -- statue_6
s[1] = 1075 s[2] = 1120 s[3] = 1690 s[4] = 3596 s[5] = "Tinh qu\169n \167\185i Hao"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_6.lua" s[7] = 0 s[8] = 1690 s[9] = 3596
s = {} PT45_EXT_NPCS[63] = s -- statue_7
s[1] = 1075 s[2] = 1121 s[3] = 1657 s[4] = 3423 s[5] = "Tinh qu\169n B\185ch H\230"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_7.lua" s[7] = 0 s[8] = 1657 s[9] = 3423
s = {} PT45_EXT_NPCS[64] = s -- statue_8
s[1] = 1075 s[2] = 1122 s[3] = 1690 s[4] = 3266 s[5] = "Tinh qu\169n Thi\170n C\200u"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_8.lua" s[7] = 0 s[8] = 1690 s[9] = 3266
s = {} PT45_EXT_NPCS[65] = s -- statue_9
s[1] = 1075 s[2] = 1123 s[3] = 1767 s[4] = 3145 s[5] = "Tinh qu\169n B\184ch Vi\214t"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_9.lua" s[7] = 0 s[8] = 1767 s[9] = 3145
s = {} PT45_EXT_NPCS[66] = s -- statue_10
s[1] = 1075 s[2] = 1124 s[3] = 1866 s[4] = 3136 s[5] = "Tinh qu\169n T\246 Vi"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_10.lua" s[7] = 0 s[8] = 1866 s[9] = 3136
s = {} PT45_EXT_NPCS[67] = s -- statue_11
s[1] = 1075 s[2] = 1125 s[3] = 1977 s[4] = 3145 s[5] = "Tinh qu\169n Thi\170n \167\248c"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_11.lua" s[7] = 0 s[8] = 1977 s[9] = 3145
s = {} PT45_EXT_NPCS[68] = s -- statue_12
s[1] = 1075 s[2] = 1126 s[3] = 2053 s[4] = 3266 s[5] = "Tinh qu\169n Th\184i \162m"
s[6] = "\\script\\phongthan\\tienma45\\n45_statue_12.lua" s[7] = 0 s[8] = 2053 s[9] = 3266
-- quest monsters: { map, template, level, x, y, name (TCVN3), species }
PT45_EXT_MOBS = {}
s = {} PT45_EXT_MOBS[1] = s s[1] = 1075 s[2] = 743 s[3] = 58 s[4] = 1679 s[5] = 3345 s[6] = "Thi\213t Tinh" s[7] = 1
s = {} PT45_EXT_MOBS[2] = s s[1] = 1075 s[2] = 743 s[3] = 58 s[4] = 1702 s[5] = 3320 s[6] = "Thi\213t Tinh" s[7] = 1
s = {} PT45_EXT_MOBS[3] = s s[1] = 1075 s[2] = 743 s[3] = 58 s[4] = 1722 s[5] = 3316 s[6] = "Thi\213t Tinh" s[7] = 1
s = {} PT45_EXT_MOBS[4] = s s[1] = 1075 s[2] = 743 s[3] = 58 s[4] = 1689 s[5] = 3342 s[6] = "Thi\213t Tinh" s[7] = 1
s = {} PT45_EXT_MOBS[5] = s s[1] = 1075 s[2] = 743 s[3] = 58 s[4] = 1684 s[5] = 3337 s[6] = "Thi\213t Tinh" s[7] = 1
s = {} PT45_EXT_MOBS[6] = s s[1] = 1075 s[2] = 743 s[3] = 58 s[4] = 1681 s[5] = 3322 s[6] = "Thi\213t Tinh" s[7] = 1
s = {} PT45_EXT_MOBS[7] = s s[1] = 1075 s[2] = 743 s[3] = 58 s[4] = 1713 s[5] = 3348 s[6] = "Thi\213t Tinh" s[7] = 1
s = {} PT45_EXT_MOBS[8] = s s[1] = 1075 s[2] = 743 s[3] = 58 s[4] = 1695 s[5] = 3336 s[6] = "Thi\213t Tinh" s[7] = 1
s = {} PT45_EXT_MOBS[9] = s s[1] = 1075 s[2] = 480 s[3] = 60 s[4] = 1993 s[5] = 3627 s[6] = "L\170 Linh Thi" s[7] = 2
s = {} PT45_EXT_MOBS[10] = s s[1] = 1075 s[2] = 480 s[3] = 60 s[4] = 2002 s[5] = 3638 s[6] = "L\170 Linh Thi" s[7] = 2
s = {} PT45_EXT_MOBS[11] = s s[1] = 1075 s[2] = 480 s[3] = 60 s[4] = 1984 s[5] = 3635 s[6] = "L\170 Linh Thi" s[7] = 2
s = {} PT45_EXT_MOBS[12] = s s[1] = 1075 s[2] = 480 s[3] = 60 s[4] = 1993 s[5] = 3658 s[6] = "L\170 Linh Thi" s[7] = 2
s = {} PT45_EXT_MOBS[13] = s s[1] = 1075 s[2] = 480 s[3] = 60 s[4] = 2000 s[5] = 3658 s[6] = "L\170 Linh Thi" s[7] = 2
s = {} PT45_EXT_MOBS[14] = s s[1] = 1075 s[2] = 480 s[3] = 60 s[4] = 1970 s[5] = 3659 s[6] = "L\170 Linh Thi" s[7] = 2
s = {} PT45_EXT_MOBS[15] = s s[1] = 1075 s[2] = 480 s[3] = 60 s[4] = 1974 s[5] = 3642 s[6] = "L\170 Linh Thi" s[7] = 2
s = {} PT45_EXT_MOBS[16] = s s[1] = 1075 s[2] = 480 s[3] = 60 s[4] = 2006 s[5] = 3659 s[6] = "L\170 Linh Thi" s[7] = 2
s = {} PT45_EXT_MOBS[17] = s s[1] = 1075 s[2] = 654 s[3] = 62 s[4] = 2052 s[5] = 3322 s[6] = "S\172n H\199u" s[7] = 3
s = {} PT45_EXT_MOBS[18] = s s[1] = 1075 s[2] = 654 s[3] = 62 s[4] = 2059 s[5] = 3309 s[6] = "S\172n H\199u" s[7] = 3
s = {} PT45_EXT_MOBS[19] = s s[1] = 1075 s[2] = 654 s[3] = 62 s[4] = 2027 s[5] = 3287 s[6] = "S\172n H\199u" s[7] = 3
s = {} PT45_EXT_MOBS[20] = s s[1] = 1075 s[2] = 654 s[3] = 62 s[4] = 2035 s[5] = 3280 s[6] = "S\172n H\199u" s[7] = 3
s = {} PT45_EXT_MOBS[21] = s s[1] = 1075 s[2] = 654 s[3] = 62 s[4] = 2045 s[5] = 3309 s[6] = "S\172n H\199u" s[7] = 3
s = {} PT45_EXT_MOBS[22] = s s[1] = 1075 s[2] = 654 s[3] = 62 s[4] = 2040 s[5] = 3306 s[6] = "S\172n H\199u" s[7] = 3
s = {} PT45_EXT_MOBS[23] = s s[1] = 1075 s[2] = 654 s[3] = 62 s[4] = 2018 s[5] = 3313 s[6] = "S\172n H\199u" s[7] = 3
s = {} PT45_EXT_MOBS[24] = s s[1] = 1075 s[2] = 654 s[3] = 62 s[4] = 2034 s[5] = 3300 s[6] = "S\172n H\199u" s[7] = 3
s = {} PT45_EXT_MOBS[25] = s s[1] = 1075 s[2] = 1109 s[3] = 60 s[4] = 1765 s[5] = 3678 s[6] = "T\233c nh\169n b\222 m\170 ho\198c" s[7] = 4
s = {} PT45_EXT_MOBS[26] = s s[1] = 1075 s[2] = 1109 s[3] = 60 s[4] = 1779 s[5] = 3693 s[6] = "T\233c nh\169n b\222 m\170 ho\198c" s[7] = 4
s = {} PT45_EXT_MOBS[27] = s s[1] = 1075 s[2] = 1109 s[3] = 60 s[4] = 1741 s[5] = 3681 s[6] = "T\233c nh\169n b\222 m\170 ho\198c" s[7] = 4
s = {} PT45_EXT_MOBS[28] = s s[1] = 1075 s[2] = 1109 s[3] = 60 s[4] = 1738 s[5] = 3695 s[6] = "T\233c nh\169n b\222 m\170 ho\198c" s[7] = 4
s = {} PT45_EXT_MOBS[29] = s s[1] = 1075 s[2] = 1109 s[3] = 60 s[4] = 1739 s[5] = 3718 s[6] = "T\233c nh\169n b\222 m\170 ho\198c" s[7] = 4
s = {} PT45_EXT_MOBS[30] = s s[1] = 1075 s[2] = 1109 s[3] = 60 s[4] = 1750 s[5] = 3688 s[6] = "T\233c nh\169n b\222 m\170 ho\198c" s[7] = 4
s = {} PT45_EXT_MOBS[31] = s s[1] = 1075 s[2] = 1157 s[3] = 66 s[4] = 2048 s[5] = 3700 s[6] = "Ng\244c Ph\184p Th\199n" s[7] = 24
s = {} PT45_EXT_MOBS[32] = s s[1] = 1076 s[2] = 934 s[3] = 72 s[4] = 1814 s[5] = 3578 s[6] = "Ch\243c Th\199n" s[7] = 5
s = {} PT45_EXT_MOBS[33] = s s[1] = 1076 s[2] = 934 s[3] = 72 s[4] = 1778 s[5] = 3574 s[6] = "Ch\243c Th\199n" s[7] = 5
s = {} PT45_EXT_MOBS[34] = s s[1] = 1076 s[2] = 934 s[3] = 72 s[4] = 1797 s[5] = 3556 s[6] = "Ch\243c Th\199n" s[7] = 5
s = {} PT45_EXT_MOBS[35] = s s[1] = 1076 s[2] = 934 s[3] = 72 s[4] = 1795 s[5] = 3546 s[6] = "Ch\243c Th\199n" s[7] = 5
s = {} PT45_EXT_MOBS[36] = s s[1] = 1076 s[2] = 934 s[3] = 72 s[4] = 1785 s[5] = 3548 s[6] = "Ch\243c Th\199n" s[7] = 5
s = {} PT45_EXT_MOBS[37] = s s[1] = 1076 s[2] = 934 s[3] = 72 s[4] = 1780 s[5] = 3578 s[6] = "Ch\243c Th\199n" s[7] = 5
s = {} PT45_EXT_MOBS[38] = s s[1] = 1076 s[2] = 935 s[3] = 72 s[4] = 1761 s[5] = 3428 s[6] = "Chu L\220nh" s[7] = 6
s = {} PT45_EXT_MOBS[39] = s s[1] = 1076 s[2] = 936 s[3] = 72 s[4] = 1750 s[5] = 3422 s[6] = "Chu L\220nh" s[7] = 6
s = {} PT45_EXT_MOBS[40] = s s[1] = 1076 s[2] = 935 s[3] = 72 s[4] = 1754 s[5] = 3449 s[6] = "Chu L\220nh" s[7] = 6
s = {} PT45_EXT_MOBS[41] = s s[1] = 1076 s[2] = 936 s[3] = 72 s[4] = 1771 s[5] = 3433 s[6] = "Chu L\220nh" s[7] = 6
s = {} PT45_EXT_MOBS[42] = s s[1] = 1076 s[2] = 935 s[3] = 72 s[4] = 1754 s[5] = 3441 s[6] = "Chu L\220nh" s[7] = 6
s = {} PT45_EXT_MOBS[43] = s s[1] = 1076 s[2] = 936 s[3] = 72 s[4] = 1765 s[5] = 3430 s[6] = "Chu L\220nh" s[7] = 6
s = {} PT45_EXT_MOBS[44] = s s[1] = 1076 s[2] = 937 s[3] = 73 s[4] = 1889 s[5] = 3529 s[6] = "C\200u Mang" s[7] = 7
s = {} PT45_EXT_MOBS[45] = s s[1] = 1076 s[2] = 937 s[3] = 73 s[4] = 1886 s[5] = 3538 s[6] = "C\200u Mang" s[7] = 7
s = {} PT45_EXT_MOBS[46] = s s[1] = 1076 s[2] = 937 s[3] = 73 s[4] = 1879 s[5] = 3503 s[6] = "C\200u Mang" s[7] = 7
s = {} PT45_EXT_MOBS[47] = s s[1] = 1076 s[2] = 937 s[3] = 73 s[4] = 1879 s[5] = 3518 s[6] = "C\200u Mang" s[7] = 7
s = {} PT45_EXT_MOBS[48] = s s[1] = 1076 s[2] = 937 s[3] = 73 s[4] = 1922 s[5] = 3523 s[6] = "C\200u Mang" s[7] = 7
s = {} PT45_EXT_MOBS[49] = s s[1] = 1076 s[2] = 937 s[3] = 73 s[4] = 1880 s[5] = 3536 s[6] = "C\200u Mang" s[7] = 7
s = {} PT45_EXT_MOBS[50] = s s[1] = 1076 s[2] = 1226 s[3] = 75 s[4] = 1706 s[5] = 3640 s[6] = "Thi\170n Ni\170n Ninh V\173\172ng" s[7] = 8
s = {} PT45_EXT_MOBS[51] = s s[1] = 1076 s[2] = 1227 s[3] = 75 s[4] = 1720 s[5] = 3656 s[6] = "Thi\170n Ni\170n Lang V\173\172ng" s[7] = 9
s = {} PT45_EXT_MOBS[52] = s s[1] = 1076 s[2] = 1173 s[3] = 74 s[4] = 1799 s[5] = 3615 s[6] = "Tri\213t Ph\244c" s[7] = 10

if PT45_EXT_NPC_IDX == nil then PT45_EXT_NPC_IDX = {} end
if PT45_EXT_MOB_IDX == nil then PT45_EXT_MOB_IDX = {} end

function PT45_ExtNop(m)
end

function PT45_ExtRegister()
	if PT45_EXT_REGISTERED then return end
	local i = 1
	while PT45_EXT_SCRIPTS[i] do
		ReLoadScript(PT45_EXT_SCRIPTS[i])
		i = i + 1
	end
	i = 1
	while PT45_EXT_PAK[i] do
		call(ReLoadScript, { PT45_EXT_PAK[i] }, "x", PT45_ExtNop)
		i = i + 1
	end
	PT45_EXT_REGISTERED = 1
end

-- one scan over the NPC table: region placeholders of 1075/1076 with the same template on the same cell
function PT45_ExtAdopt()
	local want = 0
	local k = 1
	while PT45_EXT_NPCS[k] do
		if PT45_EXT_NPCS[k][7] == 1 then want = want + 1 end
		k = k + 1
	end
	local got = 0
	local i = 1
	while i < PT45_EXT_MAX_NPC and got < want do
		local nm = GetNpcName(i)
		if nm and nm ~= "" then
			local w, x, y = GetNpcPos(i)
			if w == 1075 or w == 1076 then
				got = got + PT45_ExtAdoptOne(i, w, x, y)
			end
		end
		i = i + 1
	end
	return got
end

function PT45_ExtAdoptOne(i, w, x, y)
	local tpl = GetNpcTemplateID(i)
	local k = 1
	while PT45_EXT_NPCS[k] do
		local s = PT45_EXT_NPCS[k]
		if s[7] == 1 and not PT45_EXT_NPC_IDX[k] and s[1] == w and tpl == s[2] and abs(x - s[3]) <= 1 and abs(y - s[4]) <= 1 then
			SetNpcName(i, s[5])
			SetNpcScript(i, s[6])
			if (s[8] ~= s[3] or s[9] ~= s[4]) and SetNpcPos then SetNpcPos(i, s[8], s[9]) end
			PT45_EXT_NPC_IDX[k] = i
			return 1
		end
		k = k + 1
	end
	return 0
end

function PT45_ExtSpawn(tpl, lv, m, x, y, removable)
	local sw = SubWorldID2Idx(m)
	if sw == nil or sw < 0 then return 0 end
	local ni = AddNpc(tpl, lv, sw, x * 32, y * 32, removable)
	if ni == nil or ni <= 0 then ni = AddNpc(tpl, lv, sw, (x + 2) * 32, y * 32, removable) end
	if ni == nil or ni <= 0 then ni = AddNpc(tpl, lv, sw, x * 32, (y + 2) * 32, removable) end
	if ni == nil or ni <= 0 then return 0 end
	return ni
end

function PT45_ExtEnsureNpcs()
	local k = 1
	while PT45_EXT_NPCS[k] do
		local s = PT45_EXT_NPCS[k]
		local ni = PT45_EXT_NPC_IDX[k]
		if not (ni and ni > 0 and GetNpcName(ni) == s[5]) then
			ni = PT45_ExtSpawn(s[2], 1, s[1], s[8], s[9], 0)
			if ni > 0 then
				SetNpcName(ni, s[5])
				SetNpcScript(ni, s[6])
				PT45_EXT_NPC_IDX[k] = ni
			end
		end
		k = k + 1
	end
end

function PT45_ExtEnsureMobs()
	local k = 1
	while PT45_EXT_MOBS[k] do
		local s = PT45_EXT_MOBS[k]
		local ni = PT45_EXT_MOB_IDX[k]
		if not (ni and ni > 0 and GetNpcName(ni) == s[6] and GetNpcParam(ni, 1) == PT45_EXT_K_PACK and GetNpcParam(ni, 2) == s[7]) then
			ni = PT45_ExtSpawn(s[2], s[3], s[1], s[4], s[5], 1)
			if ni > 0 then
				SetNpcName(ni, s[6])
				SetNpcScript(ni, PT45_EXT_MOB)
				SetNpcParam(ni, 1, PT45_EXT_K_PACK)
				SetNpcParam(ni, 2, s[7])
				PT45_EXT_MOB_IDX[k] = ni
			end
		end
		k = k + 1
	end
end

function PTEXT_tienma45_Tick()
	PT45_ExtRegister()
	if not PT45_EXT_ADOPTED then
		PT45_EXT_ADOPTED = 1
		PT45_ExtAdopt()
	end
	PT45_ExtEnsureNpcs()
	PT45_ExtEnsureMobs()
end
