-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Minute tick of Tien Ma phase 1-3 (servertimer.lua PTAdm_ExtOne("tienma") calls PTEXT_tienma_Tick(), protected).
-- 1. registers the loose NPC/monster scripts (and the PAK paths of extra_tienma.py) once per server start;
-- 2. first tick: takes over the region placeholders listed with adopt=1 (same template and cell; map 1073:
--    Tu Hanh Su x2, Dac Ky, Lien Dang Ho Su, Cuu Thien Huyen Nu, Tao Bao; map 1074: Tu Hanh Su x2, Son Than
--    Hong Bac), spawns the rest;
-- 3. keeps every dialog NPC/object and the quest monster packs alive (re-spawn when the index lost our name).
-- Data: one call per record (engine Lua stack is 120 slots: no big table constructors).
PTTM_EXT_MAX_NPC = 48000
PTTM_EXT_K_PACK = 7701
PTTM_EXT_SCRIPTS = {}
PTTM_EXT_PAK = {}
PTTM_EXT_NPCS = {}
PTTM_EXT_MOBS = {}
function PTTM_S(p) tinsert(PTTM_EXT_SCRIPTS, p) end
function PTTM_P(p) tinsert(PTTM_EXT_PAK, p) end
-- { map, template, x, y, name (TCVN3), script, adopt }
function PTTM_N(m, t, x, y, n, s, a) local r = {} r[1] = m r[2] = t r[3] = x r[4] = y r[5] = n r[6] = s r[7] = a tinsert(PTTM_EXT_NPCS, r) end
-- { map, template, level, x, y, name (TCVN3) }
function PTTM_M(m, t, l, x, y, n) local r = {} r[1] = m r[2] = t r[3] = l r[4] = x r[5] = y r[6] = n tinsert(PTTM_EXT_MOBS, r) end
PTTM_S("\\script\\phongthan\\tienma\\npc_bachhac.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_bcs1.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_bcs2.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_chucdung.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_cuuthien.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_dacky.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_haithuoc.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_huyendo.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_lamp.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_liendang.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_linhxathu.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_misc.lua")
PTTM_S("\\script\\phongthan\\tienma\\mob_kill.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_moctra.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_nuoa.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_thanthan.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_tiepdan.lua")
PTTM_S("\\script\\phongthan\\tienma\\npc_tuhanhsu.lua")
-- VNG paths (PAK, ptfix plug-in extra_tienma.py); ReLoadScript is protected and harmless while missing
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\189\211\210\253\181\192\200\203.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\208\222\208\208\202\166.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\208\222\208\208\202\166\207\201.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\230\167\188\186.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\193\233\201\223\202\247.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\208\254\182\188\180\243\183\168\202\166.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\176\215\186\215\181\192\179\164.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\193\233\209\192\189\163\207\201.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\196\190\223\184.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\193\171\181\198\202\216\187\164\213\223.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\193\171\181\198\202\216\187\164\213\223\196\167.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\215\163\200\218.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\197\174\230\180\196\239\196\239.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\186\244\207\201\203\254.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\187\189\196\167\203\254.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\190\197\204\236\208\254\197\174.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\207\201\189\217\205\188\204\218.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\196\167\189\217\205\188\204\218.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\178\201\210\169\200\203.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\178\201\210\169\200\203\181\196\208\214\181\220.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\193\233\202\175\189\240.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\193\233\202\175\196\190.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\193\233\202\175\203\174.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\193\233\202\175\187\240.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\193\171\181\198\215\249.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\206\180\191\170\187\168\181\196\194\252\205\211\194\222\187\170.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\206\180\191\170\187\168\181\196\194\252\214\233\201\179\187\170.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\210\189\201\250.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\210\189\201\250\207\201.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\187\164\183\168\207\201.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\187\164\183\168\196\167.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\179\224\190\171\215\211.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\184\223\190\245.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\196\167\192\241\202\217.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\178\220\177\166.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\207\244\201\253.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\199\224\208\233\181\192\179\164.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\206\218\212\198\189\163\207\201.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\242\176\202\215\189\163\207\201.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\189\240\185\226\189\163\207\201.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\205\173\189\179.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\178\214\191\226\185\220\192\237\212\177.lua")
PTTM_P("\\script\\\178\187\214\220\204\236\185\216\\\178\214\191\226\185\220\192\237\212\177\207\201.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\208\222\208\208\202\166\207\201.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\208\222\208\208\202\166\196\167.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\187\240\201\241.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\203\174\201\241.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\199\167\196\234\180\243\202\175.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\206\222\247\177\215\211.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\186\233\194\175\181\164\191\205.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\194\185\201\241.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\196\207\218\164\215\211.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\192\235\185\184\215\240\213\223.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\183\246\229\246\181\192\200\203.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\192\238\208\203\176\212.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\201\189\201\241\186\232\178\171.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\209\238\200\206.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\189\240\223\184.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\209\238\201\173.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\204\250\185\218\181\192\200\203.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\204\176\195\247\215\240\213\223.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\204\236\203\227\215\211.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\199\230\204\236\203\254.lua")
PTTM_P("\\script\\\178\187\214\220\201\189\\\204\236\212\192\211\252\215\228.lua")
PTTM_P("\\script\\npcdeath\\\236\229.lua")
PTTM_P("\\script\\npcdeath\\\211\197\179\230.lua")
PTTM_P("\\script\\npcdeath\\\213\248.lua")
PTTM_P("\\script\\npcdeath\\\196\252.lua")
PTTM_P("\\script\\npcdeath\\\207\201\161\164\192\235\214\236.lua")
PTTM_P("\\script\\npcdeath\\\196\167\161\164\192\235\214\236.lua")
PTTM_P("\\script\\npcdeath\\\202\201\192\199.lua")
PTTM_P("\\script\\npcdeath\\\207\201\161\164\183\231\209\253.lua")
PTTM_P("\\script\\npcdeath\\\196\167\161\164\183\231\209\253.lua")
PTTM_P("\\script\\npcdeath\\\207\201\161\164\199\213\212\173.lua")
PTTM_P("\\script\\npcdeath\\\196\167\161\164\199\213\212\173.lua")
PTTM_P("\\script\\item\\\216\212\190\237\\\199\172.lua")
PTTM_P("\\script\\item\\\216\212\190\237\\\182\210.lua")
PTTM_P("\\script\\item\\\216\212\190\237\\\192\235.lua")
PTTM_P("\\script\\item\\\216\212\190\237\\\213\240.lua")
PTTM_P("\\script\\item\\\216\212\190\237\\\217\227.lua")
PTTM_P("\\script\\item\\\216\212\190\237\\\191\178.lua")
PTTM_P("\\script\\item\\\216\212\190\237\\\244\222.lua")
PTTM_P("\\script\\item\\\216\212\190\237\\\192\164.lua")
PTTM_P("\\script\\item\\\187\195\185\226\190\181.lua")
PTTM_N(1020, 767, 1476, 3060, "Ti\213p D\201n \167\185o Nh\169n", "\\script\\phongthan\\tienma\\npc_tiepdan.lua", 0) -- tiepdan_tk
PTTM_N(1021, 767, 1776, 3047, "Ti\213p D\201n \167\185o Nh\169n", "\\script\\phongthan\\tienma\\npc_tiepdan.lua", 0) -- tiepdan_tc
PTTM_N(1073, 767, 1970, 3830, "Ti\213p D\201n \167\185o Nh\169n", "\\script\\phongthan\\tienma\\npc_tiepdan.lua", 0) -- tiepdan_tien
PTTM_N(1073, 767, 1630, 3214, "Ti\213p D\201n \167\185o Nh\169n", "\\script\\phongthan\\tienma\\npc_tiepdan.lua", 0) -- tiepdan_ma
PTTM_N(1073, 765, 1996, 3784, "Tu H\181nh S\173", "\\script\\phongthan\\tienma\\npc_tuhanhsu.lua", 1) -- tuhanhsu_tien
PTTM_N(1073, 765, 1612, 3208, "Tu H\181nh S\173", "\\script\\phongthan\\tienma\\npc_tuhanhsu.lua", 1) -- tuhanhsu_ma
PTTM_N(1073, 164, 1956, 3304, "\167\190c K\251", "\\script\\phongthan\\tienma\\npc_dacky.lua", 1) -- dacky
PTTM_N(1073, 775, 1776, 3600, "Linh X\181 Th\244", "\\script\\phongthan\\tienma\\npc_linhxathu.lua", 0) -- linhxathu
PTTM_N(1073, 779, 1792, 3612, "Huy\210n \167\171 \167\185i Ph\184p S\173", "\\script\\phongthan\\tienma\\npc_huyendo.lua", 0) -- huyendo
PTTM_N(1073, 761, 1964, 3752, "B\185ch H\185c \167\185o Tr\173\235ng", "\\script\\phongthan\\tienma\\npc_bachhac.lua", 0) -- bachhac
PTTM_N(1073, 771, 1603, 3226, "Linh Nha Ki\213m Ti\170n", "\\script\\phongthan\\tienma\\npc_bachhac.lua", 0) -- linhnha
PTTM_N(1073, 763, 1980, 3820, "M\233c Tra", "\\script\\phongthan\\tienma\\npc_moctra.lua", 0) -- mocTra
PTTM_N(1073, 822, 1932, 3656, "Li\170n \167\168ng H\233 S\248", "\\script\\phongthan\\tienma\\npc_liendang.lua", 1) -- liendang_tien
PTTM_N(1073, 822, 1652, 3262, "Li\170n \167\168ng H\233 S\248", "\\script\\phongthan\\tienma\\npc_liendang.lua", 0) -- liendang_ma
PTTM_N(1073, 874, 1946, 3690, "Li\170n T\228a", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lientoa
PTTM_N(1073, 763, 1918, 3642, "Kim H\181 \167\229ng T\246", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- kimha
PTTM_N(1073, 781, 1668, 3753, "Ch\243c Dung", "\\script\\phongthan\\tienma\\npc_chucdung.lua", 0) -- chucdung
PTTM_N(1073, 780, 1656, 3769, "N\247 Oa N\173\172ng N\173\172ng", "\\script\\phongthan\\tienma\\npc_nuoa.lua", 0) -- nuoa
PTTM_N(1073, 776, 1624, 3686, "Ng\173\234i H\184i Thu\232c", "\\script\\phongthan\\tienma\\npc_haithuoc.lua", 0) -- haithuoc
PTTM_N(1073, 950, 1816, 3456, "Huynh \167\214 Ng\173\234i H\184i Thu\232c", "\\script\\phongthan\\tienma\\npc_haithuoc.lua", 0) -- brother
PTTM_N(1073, 790, 1694, 3722, "H\171 Ti\170n Th\184p", "\\script\\phongthan\\tienma\\npc_nuoa.lua", 0) -- thap_tien
PTTM_N(1073, 791, 1632, 3736, "H\171 Ma Th\184p", "\\script\\phongthan\\tienma\\npc_nuoa.lua", 0) -- thap_ma
PTTM_N(1073, 837, 1996, 3256, "C\246u Thi\170n Huy\210n N\247", "\\script\\phongthan\\tienma\\npc_cuuthien.lua", 1) -- cuuthien
PTTM_N(1073, 838, 2008, 3328, "V\203t T\230 Ti\170n Ki\213p", "\\script\\phongthan\\tienma\\npc_cuuthien.lua", 0) -- totem_tien
PTTM_N(1073, 839, 1936, 3232, "V\203t T\230 Ma Ki\213p", "\\script\\phongthan\\tienma\\npc_cuuthien.lua", 0) -- totem_ma
PTTM_N(1073, 766, 1968, 3792, "\167\185i Phu", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- daiphu_tien
PTTM_N(1073, 766, 1640, 3214, "\167\185i Phu", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- daiphu_ma
PTTM_N(1073, 813, 1720, 3792, "H\233 Ph\184p L\244c Gi\184p Tr\203n", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- hophap_tien
PTTM_N(1073, 814, 1936, 3216, "H\233 Ph\184p Ng\242 H\181nh Tr\203n", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- hophap_ma
PTTM_N(1073, 764, 1990, 3770, "X\221ch Tinh T\246", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- xichtinhtu
PTTM_N(1073, 774, 1616, 3240, "Cao Gi\184c", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- caogiac
PTTM_N(1073, 773, 1603, 3235, "Ma L\212 Th\228", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- molietho
PTTM_N(1073, 759, 1956, 3784, "T\181o B\182o", "\\script\\phongthan\\tienma\\npc_misc.lua", 1) -- taobao
PTTM_N(1073, 768, 1976, 3812, "Th\241 Kh\232", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- thukho_tien
PTTM_N(1073, 768, 1636, 3200, "Th\241 Kh\232", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- thukho_ma
PTTM_N(1073, 760, 1952, 3798, "Ti\170u Th\168ng", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- tieuthang
PTTM_N(1073, 762, 1956, 3767, "Thanh H\173 \167\185o Tr\173\235ng", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- thanhhu
PTTM_N(1073, 769, 1626, 3248, "\164 V\169n Ki\213m Ti\170n", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- ovan
PTTM_N(1073, 770, 1644, 3232, "Di \167\199u Ki\213m Ti\170n", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- cauthu
PTTM_N(1073, 772, 1608, 3256, "Kim Quang Ki\213m Ti\170n", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- kimquang
PTTM_N(1073, 777, 1972, 3760, "Th\238 \167\229ng", "\\script\\phongthan\\tienma\\npc_misc.lua", 0) -- thodong
PTTM_N(1074, 765, 1724, 3560, "Tu H\181nh S\173", "\\script\\phongthan\\tienma\\npc_tuhanhsu.lua", 1) -- tuhanhsu_tien4
PTTM_N(1074, 765, 1652, 3528, "Tu H\181nh S\173", "\\script\\phongthan\\tienma\\npc_tuhanhsu.lua", 1) -- tuhanhsu_ma4
PTTM_N(1074, 860, 1676, 3192, "S\172n Th\199n H\229ng B\184c", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 1) -- sonthan
PTTM_N(1074, 856, 1800, 3560, "H\225a Th\199n", "\\script\\phongthan\\tienma\\npc_thanthan.lua", 0) -- hoathan
PTTM_N(1074, 857, 1830, 3580, "Th\241y Th\199n", "\\script\\phongthan\\tienma\\npc_thanthan.lua", 0) -- thuythan
PTTM_N(1074, 876, 1988, 3612, "Thi\170n Ni\170n \167\185i Th\185ch", "\\script\\phongthan\\tienma\\npc_thanthan.lua", 0) -- daithach
PTTM_N(1074, 842, 1742, 3726, "V\171 \166\172ng T\246", "\\script\\phongthan\\tienma\\npc_bcs1.lua", 0) -- vouong
PTTM_N(1074, 850, 1615, 3650, "H\229ng L\173 \167\172n Kh\184ch", "\\script\\phongthan\\tienma\\npc_bcs1.lua", 0) -- honglu
PTTM_N(1074, 1047, 1927, 3216, "L\233c Th\199n", "\\script\\phongthan\\tienma\\npc_bcs1.lua", 0) -- locthan
PTTM_N(1074, 841, 1744, 3753, "Ph\239 B\203t \167\185o Nh\169n", "\\script\\phongthan\\tienma\\npc_bcs1.lua", 0) -- phubat
PTTM_N(1074, 854, 1636, 3654, "L\253 H\173ng B\184", "\\script\\phongthan\\tienma\\npc_bcs1.lua", 0) -- lyhungba
PTTM_N(1074, 843, 1750, 3584, "Nam Minh T\246", "\\script\\phongthan\\tienma\\npc_bcs1.lua", 0) -- namminh
PTTM_N(1074, 849, 1630, 3540, "Ly C\202u T\171n Gi\182", "\\script\\phongthan\\tienma\\npc_bcs1.lua", 0) -- lycau
PTTM_N(1074, 862, 2086, 3797, "Kim Tra", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 0) -- kimtra
PTTM_N(1074, 861, 2075, 3699, "D\173\172ng S\169m", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 0) -- duongsam
PTTM_N(1074, 840, 1780, 3700, "Thi\213t Qu\184n \167\185o Nh\169n", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 0) -- thietquan
PTTM_N(1074, 848, 1660, 3600, "B\199n Minh T\171n Gi\182", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 0) -- thamminh
PTTM_N(1074, 847, 1760, 3540, "D\173\172ng Nh\203m", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 0) -- duongnham
PTTM_N(1074, 845, 1700, 3600, "Thi\170n To\184n T\246", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 0) -- thientoan
PTTM_N(1074, 928, 1850, 3400, "K\215nh Thi\170n Th\184p", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 0) -- kinhthien1
PTTM_N(1074, 928, 1950, 3500, "K\215nh Thi\170n Th\184p", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 0) -- kinhthien2
PTTM_N(1074, 928, 1760, 3320, "K\215nh Thi\170n Th\184p", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 0) -- kinhthien3
PTTM_N(1074, 1112, 1900, 3260, "Thi\170n Nh\185c H\233 Ph\184p Tr\173\235ng L\183o", "\\script\\phongthan\\tienma\\npc_bcs2.lua", 0) -- thiennhac
PTTM_N(1073, 819, 1902, 3632, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 1
PTTM_N(1073, 819, 1932, 3620, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 2
PTTM_N(1073, 819, 1962, 3632, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 3
PTTM_N(1073, 819, 1962, 3680, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 4
PTTM_N(1073, 819, 1932, 3692, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 5
PTTM_N(1073, 819, 1902, 3680, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 6
PTTM_N(1073, 819, 1624, 3238, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 7
PTTM_N(1073, 819, 1652, 3226, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 8
PTTM_N(1073, 819, 1682, 3238, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 9
PTTM_N(1073, 819, 1682, 3286, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 10
PTTM_N(1073, 819, 1649, 3295, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 11
PTTM_N(1073, 819, 1622, 3286, "Li\170n Hoa Th\199n \167\168ng", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- lamp 12
PTTM_N(1073, 792, 1890, 3729, "M\185n \167\181 La Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_tien
PTTM_N(1073, 792, 1888, 3727, "M\185n \167\181 La Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_tien
PTTM_N(1073, 792, 1803, 3633, "M\185n \167\181 La Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_tien
PTTM_N(1073, 792, 1797, 3643, "M\185n \167\181 La Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_tien
PTTM_N(1073, 792, 1857, 3555, "M\185n \167\181 La Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_tien
PTTM_N(1073, 792, 1864, 3565, "M\185n \167\181 La Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_tien
PTTM_N(1073, 792, 1754, 3714, "M\185n \167\181 La Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_tien
PTTM_N(1073, 792, 1754, 3719, "M\185n \167\181 La Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_tien
PTTM_N(1073, 793, 1706, 3306, "M\185n Ch\169u Sa Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_ma
PTTM_N(1073, 793, 1707, 3291, "M\185n Ch\169u Sa Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_ma
PTTM_N(1073, 793, 1769, 3351, "M\185n Ch\169u Sa Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_ma
PTTM_N(1073, 793, 1752, 3360, "M\185n Ch\169u Sa Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_ma
PTTM_N(1073, 793, 1659, 3419, "M\185n Ch\169u Sa Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_ma
PTTM_N(1073, 793, 1657, 3427, "M\185n Ch\169u Sa Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_ma
PTTM_N(1073, 793, 1805, 3278, "M\185n Ch\169u Sa Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_ma
PTTM_N(1073, 793, 1796, 3275, "M\185n Ch\169u Sa Hoa", "\\script\\phongthan\\tienma\\npc_lamp.lua", 0) -- flower_ma
PTTM_N(1073, 946, 1700, 3560, "Linh Th\185ch 1", "\\script\\phongthan\\tienma\\npc_haithuoc.lua", 0) -- linh thach 1
PTTM_N(1073, 947, 1800, 3500, "Linh Th\185ch 2", "\\script\\phongthan\\tienma\\npc_haithuoc.lua", 0) -- linh thach 2
PTTM_N(1073, 948, 1900, 3420, "Linh Th\185ch 3", "\\script\\phongthan\\tienma\\npc_haithuoc.lua", 0) -- linh thach 3
PTTM_N(1073, 949, 1860, 3320, "Linh Th\185ch 4", "\\script\\phongthan\\tienma\\npc_haithuoc.lua", 0) -- linh thach 4
PTTM_N(1073, 946, 1760, 3360, "Linh Th\185ch 5", "\\script\\phongthan\\tienma\\npc_haithuoc.lua", 0) -- linh thach 5
PTTM_N(1073, 947, 1680, 3420, "Linh Th\185ch 6", "\\script\\phongthan\\tienma\\npc_haithuoc.lua", 0) -- linh thach 6
PTTM_N(1073, 948, 1720, 3660, "Linh Th\185ch 7", "\\script\\phongthan\\tienma\\npc_haithuoc.lua", 0) -- linh thach 7
PTTM_N(1073, 949, 1860, 3740, "Linh Th\185ch 8", "\\script\\phongthan\\tienma\\npc_haithuoc.lua", 0) -- linh thach 8
PTTM_M(1073, 739, 72, 1722, 3762, "Phi Th\232")
PTTM_M(1073, 739, 72, 1725, 3766, "Phi Th\232")
PTTM_M(1073, 739, 72, 1736, 3798, "Phi Th\232")
PTTM_M(1073, 739, 72, 1704, 3792, "Phi Th\232")
PTTM_M(1073, 739, 72, 1728, 3775, "Phi Th\232")
PTTM_M(1073, 739, 72, 1713, 3763, "Phi Th\232")
PTTM_M(1073, 739, 72, 1709, 3781, "Phi Th\232")
PTTM_M(1073, 739, 72, 1711, 3775, "Phi Th\232")
PTTM_M(1073, 808, 70, 1745, 3686, "\166u Tr\239ng")
PTTM_M(1073, 808, 70, 1761, 3695, "\166u Tr\239ng")
PTTM_M(1073, 808, 70, 1765, 3692, "\166u Tr\239ng")
PTTM_M(1073, 808, 70, 1757, 3703, "\166u Tr\239ng")
PTTM_M(1073, 808, 70, 1765, 3697, "\166u Tr\239ng")
PTTM_M(1073, 808, 70, 1743, 3710, "\166u Tr\239ng")
PTTM_M(1073, 808, 70, 1756, 3714, "\166u Tr\239ng")
PTTM_M(1073, 808, 70, 1760, 3689, "\166u Tr\239ng")
PTTM_M(1073, 740, 74, 1853, 3494, "Tr\185nh Nanh")
PTTM_M(1073, 741, 74, 1872, 3516, "Tr\185nh Nanh")
PTTM_M(1073, 740, 74, 1874, 3491, "Tr\185nh Nanh")
PTTM_M(1073, 741, 74, 1878, 3518, "Tr\185nh Nanh")
PTTM_M(1073, 740, 74, 1878, 3494, "Tr\185nh Nanh")
PTTM_M(1073, 741, 74, 1866, 3507, "Tr\185nh Nanh")
PTTM_M(1073, 740, 74, 1851, 3500, "Tr\185nh Nanh")
PTTM_M(1073, 741, 74, 1878, 3503, "Tr\185nh Nanh")
PTTM_M(1073, 745, 74, 1892, 3657, "Ly Ch\169u")
PTTM_M(1073, 744, 74, 1915, 3640, "Ly Ch\169u")
PTTM_M(1073, 745, 74, 1916, 3666, "Ly Ch\169u")
PTTM_M(1073, 744, 74, 1896, 3646, "Ly Ch\169u")
PTTM_M(1073, 745, 74, 1909, 3662, "Ly Ch\169u")
PTTM_M(1073, 744, 74, 1884, 3656, "Ly Ch\169u")
PTTM_M(1073, 745, 74, 1901, 3653, "Ly Ch\169u")
PTTM_M(1073, 744, 74, 1889, 3651, "Ly Ch\169u")
PTTM_M(1073, 783, 74, 1777, 3320, "Ma Kh\169m Nguy\170n")
PTTM_M(1073, 743, 74, 1762, 3311, "Ti\170n Kh\169m Nguy\170n")
PTTM_M(1073, 783, 74, 1801, 3290, "Ma Kh\169m Nguy\170n")
PTTM_M(1073, 743, 74, 1801, 3327, "Ti\170n Kh\169m Nguy\170n")
PTTM_M(1073, 783, 74, 1786, 3324, "Ma Kh\169m Nguy\170n")
PTTM_M(1073, 743, 74, 1815, 3285, "Ti\170n Kh\169m Nguy\170n")
PTTM_M(1074, 746, 78, 1805, 3449, "S\227i")
PTTM_M(1074, 746, 78, 1809, 3441, "S\227i")
PTTM_M(1074, 746, 78, 1776, 3471, "S\227i")
PTTM_M(1074, 746, 78, 1801, 3437, "S\227i")
PTTM_M(1074, 746, 78, 1827, 3431, "S\227i")
PTTM_M(1074, 746, 78, 1798, 3475, "S\227i")
PTTM_M(1074, 746, 78, 1790, 3475, "S\227i")
PTTM_M(1074, 746, 78, 1812, 3449, "S\227i")
PTTM_M(1074, 885, 80, 1887, 3403, "S\227i Ch\243a")
PTTM_M(1074, 885, 80, 1842, 3398, "S\227i Ch\243a")
PTTM_M(1074, 748, 78, 1715, 3439, "Phong Y\170u (Ti\170n)")
PTTM_M(1074, 749, 78, 1716, 3394, "Phong Y\170u (Ma)")
PTTM_M(1074, 748, 78, 1710, 3415, "Phong Y\170u (Ti\170n)")
PTTM_M(1074, 749, 78, 1681, 3412, "Phong Y\170u (Ma)")
PTTM_M(1074, 748, 78, 1721, 3425, "Phong Y\170u (Ti\170n)")
PTTM_M(1074, 749, 78, 1676, 3428, "Phong Y\170u (Ma)")
PTTM_M(1074, 748, 78, 1695, 3448, "Phong Y\170u (Ti\170n)")
PTTM_M(1074, 749, 78, 1680, 3446, "Phong Y\170u (Ma)")
PTTM_M(1074, 747, 78, 1966, 3682, "Huy\213t Y\170u")
PTTM_M(1074, 747, 78, 1934, 3678, "Huy\213t Y\170u")
PTTM_M(1074, 747, 78, 1941, 3672, "Huy\213t Y\170u")
PTTM_M(1074, 747, 78, 1956, 3672, "Huy\213t Y\170u")
PTTM_M(1074, 747, 78, 1963, 3676, "Huy\213t Y\170u")
PTTM_M(1074, 747, 78, 1952, 3673, "Huy\213t Y\170u")
PTTM_M(1074, 750, 78, 1754, 3273, "Phong Th\243 S\172n H\229n (Ti\170n)")
PTTM_M(1074, 751, 78, 1776, 3234, "Phong Th\243 S\172n H\229n (Ma)")
PTTM_M(1074, 750, 78, 1735, 3232, "Phong Th\243 S\172n H\229n (Ti\170n)")
PTTM_M(1074, 751, 78, 1783, 3279, "Phong Th\243 S\172n H\229n (Ma)")
PTTM_M(1074, 750, 78, 1756, 3240, "Phong Th\243 S\172n H\229n (Ti\170n)")
PTTM_M(1074, 751, 78, 1756, 3266, "Phong Th\243 S\172n H\229n (Ma)")
PTTM_M(1074, 750, 78, 1778, 3248, "Phong Th\243 S\172n H\229n (Ti\170n)")
PTTM_M(1074, 751, 78, 1751, 3252, "Phong Th\243 S\172n H\229n (Ma)")
PTTM_M(1074, 927, 85, 1639, 3319, "La H\199u")
if PTTM_EXT_NPC_IDX == nil then PTTM_EXT_NPC_IDX = {} end
if PTTM_EXT_MOB_IDX == nil then PTTM_EXT_MOB_IDX = {} end

function PTTM_ExtRegister()
	if PTTM_EXT_REGISTERED then return end
	local i = 1
	while PTTM_EXT_SCRIPTS[i] do
		ReLoadScript(PTTM_EXT_SCRIPTS[i])
		i = i + 1
	end
	i = 1
	while PTTM_EXT_PAK[i] do
		call(ReLoadScript, { PTTM_EXT_PAK[i] }, "x", PTTM_ExtNop)
		i = i + 1
	end
	PTTM_EXT_REGISTERED = 1
end

function PTTM_ExtNop(m)
end

-- one scan over the NPC table: region placeholders with the same template on the same cell (maps 1073/1074)
function PTTM_ExtAdopt()
	local i = 1
	local want = 0
	local k = 1
	while PTTM_EXT_NPCS[k] do
		if PTTM_EXT_NPCS[k][7] == 1 then want = want + 1 end
		k = k + 1
	end
	if want == 0 then return 0 end
	local got = 0
	while i < PTTM_EXT_MAX_NPC and got < want do
		local nm = GetNpcName(i)
		if nm and nm ~= "" then
			local w, x, y = GetNpcPos(i)
			if w == 1073 or w == 1074 then
				local tpl = GetNpcTemplateID(i)
				k = 1
				while PTTM_EXT_NPCS[k] do
					local s = PTTM_EXT_NPCS[k]
					if s[7] == 1 and not PTTM_EXT_NPC_IDX[k] and w == s[1] and tpl == s[2] and abs(x - s[3]) <= 1 and abs(y - s[4]) <= 1 then
						SetNpcName(i, s[5])
						SetNpcScript(i, s[6])
						PTTM_EXT_NPC_IDX[k] = i
						got = got + 1
					end
					k = k + 1
				end
			end
		end
		i = i + 1
	end
	return got
end

function PTTM_ExtSpawn(tpl, lv, m, x, y, removable)
	local sw = SubWorldID2Idx(m)
	if sw == nil or sw < 0 then return 0 end
	local ni = AddNpc(tpl, lv, sw, x * 32, y * 32, removable)
	if ni == nil or ni <= 0 then ni = AddNpc(tpl, lv, sw, (x + 2) * 32, y * 32, removable) end
	if ni == nil or ni <= 0 then ni = AddNpc(tpl, lv, sw, x * 32, (y + 2) * 32, removable) end
	if ni == nil or ni <= 0 then return 0 end
	return ni
end

function PTTM_ExtEnsureNpcs()
	local k = 1
	while PTTM_EXT_NPCS[k] do
		local s = PTTM_EXT_NPCS[k]
		local ni = PTTM_EXT_NPC_IDX[k]
		if not (ni and ni > 0 and GetNpcName(ni) == s[5]) then
			ni = PTTM_ExtSpawn(s[2], 1, s[1], s[3], s[4], 0)
			if ni > 0 then
				SetNpcName(ni, s[5])
				SetNpcScript(ni, s[6])
				PTTM_EXT_NPC_IDX[k] = ni
			end
		end
		k = k + 1
	end
end

function PTTM_ExtEnsureMobs()
	local k = 1
	while PTTM_EXT_MOBS[k] do
		local s = PTTM_EXT_MOBS[k]
		local ni = PTTM_EXT_MOB_IDX[k]
		if not (ni and ni > 0 and GetNpcName(ni) == s[6] and GetNpcParam(ni, 1) == PTTM_EXT_K_PACK) then
			ni = PTTM_ExtSpawn(s[2], s[3], s[1], s[4], s[5], 1)
			if ni > 0 then
				SetNpcName(ni, s[6])
				SetNpcScript(ni, "\\script\\phongthan\\tienma\\mob_kill.lua")
				SetNpcParam(ni, 1, PTTM_EXT_K_PACK)
				PTTM_EXT_MOB_IDX[k] = ni
			end
		end
		k = k + 1
	end
end

function PTEXT_tienma_Tick()
	PTTM_ExtRegister()
	if not PTTM_EXT_ADOPTED then
		PTTM_EXT_ADOPTED = 1
		PTTM_ExtAdopt()
	end
	PTTM_ExtEnsureNpcs()
	PTTM_ExtEnsureMobs()
end
