-- Phong Than 2026-10-03 (agent vantieu/vanluong): extension tick of Van Luong + Van Tieu 2004.
-- ASCII file generated by scratchpad\vantieu\gen.py; loaded by servertimer.lua (PTAdm_ExtTick), which calls
-- PTEXT_vanluong_Tick() once per minute, protected. Everything here is idempotent.
--  1. first tick: register the PAK / loose scripts (ReLoadScript) and rebind the VNG Tieu Su of Dong Quan
--     (map 1014, placement "\script\yun_biao\tong_guan_biao_shi.lua") to \script\phongthan\vanluong\vl_core.lua;
--  2. every tick: keep the fixed NPCs alive (Luong Thao Quan 1014, Tong Tieu Dau 1019, Tieu Su 1004);
--  3. Van Tieu schedule (VNG systemtimetask: open 19:00, close 19:10; here 3 windows of 30 minutes): spawn the
--     Tieu Dau Than Bi on Tuyet Long linh like \script\yun_biao\kai_qi.lua (with the 6th AddNpc argument) and
--     close like guan_bi.lua. Global values 422-426 as in VNG.

PTEXTVL_CORE = "\\script\\phongthan\\vanluong\\vl_core.lua"
PTEXTVL_SCRIPTS = {
	PTEXTVL_CORE,
	"\\script\\\212\203\239\218\\\228\252\185\216\239\218\202\166.lua",
	"\\script\\\212\203\239\218\\\201\241\195\216\239\218\205\183.lua",
	"\\script\\\212\203\239\218\\\239\218\179\181.lua",
	"\\script\\\212\203\239\218\\\177\166\207\228.lua",
	"\\script\\\212\203\239\218\\\215\220\239\218\205\183.lua",
	"\\script\\\212\203\239\218\\\239\218\202\166.lua",
}
PTEXTVL_GIVER_GBK = "\239\218\202\166"
PTEXTVL_GIVER_NAME = "Ti\170u S\173 \167\229ng Quan"
PTEXTVL_GIVER_MAP = 1014
PTEXTVL_MAX_NPC = 48000
-- { map, template, mpsX, mpsY, name, script, param0 }
PTEXTVL_NPCS = {
	{ 1014, 1520, 47936, 112000, "L\173\172ng Th\182o Quan", PTEXTVL_CORE, 21401 },
	{ 1019, 152, 51488, 94528, "T\230ng Ti\170u \167\199u", "\\script\\\212\203\239\218\\\215\220\239\218\205\183.lua", 0 },
	{ 1004, 152, 52448, 103360, "Ti\170u S\173", "\\script\\\212\203\239\218\\\239\218\202\166.lua", 0 },
}
-- Van Tieu: { hour, minute, minutes open }
PTEXTVL_WINDOWS = { { 12, 0, 30 }, { 19, 0, 30 }, { 21, 0, 30 } }
PTEXTVL_TIEU_MAP = 1019
PTEXTVL_TIEU_TPL = 152
PTEXTVL_TIEU_NAME = "Ti\170u \167\199u Th\199n B\221"
PTEXTVL_TIEU_SCRIPT = "\\script\\\212\203\239\218\\\201\241\195\216\239\218\205\183.lua"
PTEXTVL_TIEU_POS = { { 1464, 3239 }, { 1462, 3330 }, { 1434, 3210 }, { 1500, 3356 }, { 1495, 3416 } }
PTEXTVL_CHEST_NAME = "B\182o R\173\172ng Ti\170u Xa"

PTEXTVL_SPAWNED = {}
PTEXTVL_TICKS = 0

function PTEXTVL_Init()
	local k = 1
	while PTEXTVL_SCRIPTS[k] do
		ReLoadScript(PTEXTVL_SCRIPTS[k])
		k = k + 1
	end
	PTEXTVL_INIT = 1
	PTEXTVL_BindGiver()
end

function PTEXTVL_BindGiver()
	local g = PTEXTVL_GIVER
	if g and g > 0 and GetNpcName(g) == PTEXTVL_GIVER_NAME and GetNpcPos(g) == PTEXTVL_GIVER_MAP then
		SetNpcScript(g, PTEXTVL_CORE)
		return g
	end
	local i = 1
	while i < PTEXTVL_MAX_NPC do
		local nm = GetNpcName(i)
		if nm == PTEXTVL_GIVER_GBK or nm == PTEXTVL_GIVER_NAME then
			if GetNpcPos(i) == PTEXTVL_GIVER_MAP then
				SetNpcScript(i, PTEXTVL_CORE)
				SetNpcName(i, PTEXTVL_GIVER_NAME)
				PTEXTVL_GIVER = i
				return i
			end
		end
		i = i + 1
	end
	return 0
end

function PTEXTVL_EnsureNpcs()
	local k = 1
	while PTEXTVL_NPCS[k] do
		local s = PTEXTVL_NPCS[k]
		local ni = PTEXTVL_SPAWNED[k]
		if not (ni and ni > 0 and GetNpcName(ni) == s[5] and GetNpcPos(ni) == s[1]) then
			local sw = SubWorldID2Idx(s[1])
			if sw and sw >= 0 then
				ni = AddNpc(s[2], 1, sw, s[3], s[4], 0)
				if ni and ni > 0 then
					SetNpcName(ni, s[5])
					SetNpcScript(ni, s[6])
					if s[7] > 0 then SetNpcParam(ni, 0, s[7]) end
					PTEXTVL_SPAWNED[k] = ni
				end
			end
		end
		k = k + 1
	end
end

-- returns window number (1..n) when the Van Tieu window is open now
function PTEXTVL_Window()
	local h = tonumber(date("%H"))
	local m = tonumber(date("%M"))
	if not h or not m then return 0 end
	local now = h * 60 + m
	local k = 1
	while PTEXTVL_WINDOWS[k] do
		local w = PTEXTVL_WINDOWS[k]
		local s = w[1] * 60 + w[2]
		if now >= s and now < s + w[3] then return k end
		k = k + 1
	end
	return 0
end

function PTEXTVL_DelNamed(gv, name)
	local d = GetGlobalValue(gv)
	if d and d > 0 and GetNpcName(d) == name then DelNpc(d) end
	SetGlobalValue(gv, 0)
end

function PTEXTVL_Open()
	local sw = SubWorldID2Idx(PTEXTVL_TIEU_MAP)
	if not sw or sw < 0 then return 0 end
	PTEXTVL_DelNamed(425, PTEXTVL_CHEST_NAME)
	PTEXTVL_DelNamed(426, PTEXTVL_TIEU_NAME)
	local p = PTEXTVL_TIEU_POS[random(1, 5)]
	local npc = AddNpc(PTEXTVL_TIEU_TPL, 1, sw, p[1] * 32, p[2] * 32, 0)
	if not npc or npc <= 0 then return 0 end
	SetNpcName(npc, PTEXTVL_TIEU_NAME)
	SetNpcScript(npc, PTEXTVL_TIEU_SCRIPT)
	SetGlobalValue(426, npc)
	SetGlobalValue(422, 1)
	SetGlobalValue(423, 0)
	SetGlobalValue(424, 0)
	AddGlobalCountNews("Ti\170u \167\199u Th\199n B\221 \174\183 xu\202t hi\214n \235 Tuy\214t Long L\220nh (" .. p[1] .. "/" .. p[2] .. "), t\215m d\242ng s\220 \184p ti\170u \174\213n T\230ng Ti\170u \167\199u!", 2)
	return npc
end

function PTEXTVL_Close()
	SetGlobalValue(422, 0)
	PTEXTVL_DelNamed(426, PTEXTVL_TIEU_NAME)
end

function PTEXTVL_Schedule()
	local k = PTEXTVL_Window()
	if k > 0 then
		local key = tonumber(date("%Y%m%d")) * 10 + k
		if PTEXTVL_OPENKEY ~= key then
			PTEXTVL_OPENKEY = key
			PTEXTVL_Open()
		end
	elseif PTEXTVL_FORCE and PTEXTVL_TICKS < PTEXTVL_FORCE then
		return
	elseif GetGlobalValue(422) == 1 then
		PTEXTVL_Close()
	end
end

-- admin / test helper (bridge): open a Van Tieu window now for 30 minutes
function PTEXTVL_ForceOpen()
	PTEXTVL_FORCE = PTEXTVL_TICKS + 30
	return PTEXTVL_Open()
end

function PTEXT_vanluong_Tick()
	if not PTEXTVL_INIT then PTEXTVL_Init() end
	PTEXTVL_TICKS = PTEXTVL_TICKS + 1
	PTEXTVL_EnsureNpcs()
	if mod(PTEXTVL_TICKS, 30) == 0 then PTEXTVL_BindGiver() end
	PTEXTVL_Schedule()
end
