-- Phong Than "Lenh Bai Dao Si" (magicscript 61480, 2026-10-04, agent lbdaosi). Permanent, never consumed
-- (KItemList::ExecuteScript only calls main; this script never removes the item). Generated by
-- scratchpad\lbdaosi\gen.py - edit the generator, not this file. Doc: docs\features\lenh-bai-dao-si-phong-than-20261004.md
-- Right click (Dao Si only): skill set of the client auto fight (PhongThanAutoFight.inl, Alt+A/S/D) by element:
-- Tho + Hoa + Bang (default), Hoa + Bang + Loi, all, one element, or skill by skill per element (also the 3 buffs);
-- r2: rows Bat dau / Dung tu dong danh, and choosing a set starts the auto fight (task 2617 command, option 2618),
-- by the auto). Stored in task 2613 (0 = skills on the keys; else 2^30 + sum 2^(id - 3)), sent to the client with
-- SyncTaskValue (VNG s2c_synctaskvalue). Menus <= 7 rows; only learnt skills are listed.
-- Lua 4 / engine: no top-level dofile, one small statement per record (stack 120 slots).

PTLB_T_DS = 2613      -- Dao Si set: 0 = keys, else 2^30 + sum 2^(id - 3), ids 3..26
PTLB_T_DN = 2614      -- Di Nhan set: 0 = off, else 2^30 + sum 2^(id - 43), ids 43..51
PTLB_T_GDS = 2615     -- 1 = Lenh Bai Dao Si given (auto gift)
PTLB_T_GDN = 2616     -- 1 = Lenh Bai Di Nhan given (auto gift)
PTLB_ITEM_DS = 61480
PTLB_ITEM_DN = 61481
PTLB_T_GS = 2619      -- Giap Si set: 0 = keys, else 2^30 + sum 2^(id - 27), ids 27..42
PTLB_T_GGS = 2620     -- 1 = Lenh Bai Giap Si given (auto gift)
PTLB_ITEM_GS = 61482
PTLB_FLAG = 1073741824
PTLB_T_CMD = 2617     -- start / stop request for the client auto fight: sequence x 4 + 1 (start) / 2 (stop)
PTLB_T_PREF = 2618    -- 0 = start the auto fight when a set is chosen (default), 1 = do not

function PTLB_No()
end

function PTLB_Say(title, o)
	local n = getn(o)
	local t = { title, n }
	local k = 1
	while k <= n do t[k + 2] = o[k] k = k + 1 end
	call(Say, t)
end

function PTLB_Pow(k)
	local v = 1
	local i = 0
	while i < k do v = v * 2 i = i + 1 end
	return v
end

-- 1 when bit k of v is set (Lua 4: no bit operators)
function PTLB_Bit(v, k)
	local q = floor(v / PTLB_Pow(k))
	if q - floor(q / 2) * 2 == 1 then return 1 end
	return nil
end

function PTLB_Learnt(id)
	local l = HaveMagic(id)
	if l and l > 0 then return 1 end
	return nil
end

function PTLB_AddSk(t, id, el, kind, nm, grp)
	local s = {}
	s.grp = grp
	s.id = id
	s.el = el
	s.kind = kind
	s.nm = nm
	t.n = t.n + 1
	t[t.n] = s
end

function PTLB_AddPS(prof, id, mx, tier, nm)
	local s = {}
	s.id = id
	s.mx = mx
	s.tier = tier
	s.nm = nm
	tinsert(PTLB_PS[prof], s)
end

-- skills of the profession the character may raise now (rebirth skills once their level is reached)
function PTLB_ProfList(prof)
	PTLB_Load()
	local r = {}
	local t = PTLB_PS[prof]
	if not t then return r end
	local lv = GetLevel()
	local i = 1
	while t[i] do
		if t[i].tier <= lv then tinsert(r, t[i]) end
		i = i + 1
	end
	return r
end

function PTLB_FindPS(prof, id)
	local l = PTLB_ProfList(prof)
	local i = 1
	while l[i] do
		if l[i].id == id then return l[i], i end
		i = i + 1
	end
	return nil, 0
end

function PTLB_Lv(id)
	local l = HaveMagic(id)
	if l and l > 0 then return l end
	return 0
end

-- learn (if needed) and set skill s to its max level, as the web admin does (SetSkillLevel + AddMagic, which
-- syncs the client skill bar). Skill points are neither spent nor refunded. 1 when the level is reached.
function PTLB_MaxOne(s)
	if PTLB_Lv(s.id) >= s.mx then return 1 end
	SetSkillLevel(s.id, s.mx)
	AddMagic(s.id, s.mx)
	if PTLB_Lv(s.id) >= s.mx then return 1 end
	return 0
end

function PTLB_MaxAll(prof)
	local l = PTLB_ProfList(prof)
	local ok = 0
	local i = 1
	while l[i] do
		ok = ok + PTLB_MaxOne(l[i])
		i = i + 1
	end
	return ok, getn(l)
end

-- skill tables: { id, element (1 Bang 2 Hoa 3 Loi 4 Tho), kind (1 attack 2 buff 3 aura 4 heal 5 curse), name }
function PTLB_Load()
	if PTLB_DS then return end
	PTLB_EL = { "B\168ng", "H\225a", "L\171i", "Th\230" }
	PTLB_KIND = { "", "buff", "h\181o quang", "h\229i m\184u", "ch\243 nguy\210n" }
	PTLB_DS = { n = 0, base = 3, task = PTLB_T_DS }
	PTLB_AddSk(PTLB_DS, 4, 4, 1, "L\173u Tinh Th\185ch", 1)
	PTLB_AddSk(PTLB_DS, 8, 4, 1, "Thi\170n Phong \167\222a Nh\203n", 1)
	PTLB_AddSk(PTLB_DS, 16, 4, 1, "Ng\242 Nh\185c Tri\210u T\171ng", 1)
	PTLB_AddSk(PTLB_DS, 20, 4, 1, "Thi\170n B\168ng \167\222a Li\214t", 1)
	PTLB_AddSk(PTLB_DS, 24, 4, 1, "Huy\210n N\247 B\230 Thi\170n", 1)
	PTLB_AddSk(PTLB_DS, 6, 2, 1, "T\221ch L\222ch H\225a", 2)
	PTLB_AddSk(PTLB_DS, 10, 2, 1, "Phong L\169m H\225a S\172n", 2)
	PTLB_AddSk(PTLB_DS, 18, 2, 1, "Th\203p Ph\173\172ng Li\214t H\225a", 2)
	PTLB_AddSk(PTLB_DS, 26, 2, 1, "Tam Mu\233i Ch\169n H\225a", 2)
	PTLB_AddSk(PTLB_DS, 5, 1, 1, "B\168ng Tuy\213t \167\185n", 3)
	PTLB_AddSk(PTLB_DS, 13, 1, 1, "Thi\213t M\183 B\168ng Qua", 3)
	PTLB_AddSk(PTLB_DS, 21, 1, 1, "B\168ng Phong B\185o", 3)
	PTLB_AddSk(PTLB_DS, 25, 1, 1, "B\168ng Phong V\185n L\253", 3)
	PTLB_AddSk(PTLB_DS, 3, 3, 1, "Ch\173\235ng T\169m L\171i", 4)
	PTLB_AddSk(PTLB_DS, 11, 3, 1, "H\185n \167\222a L\171i", 4)
	PTLB_AddSk(PTLB_DS, 15, 3, 1, "Phong V\169n L\171i \167\233ng", 4)
	PTLB_AddSk(PTLB_DS, 23, 3, 1, "L\171i \167\233ng C\246u Thi\170n", 4)
	PTLB_AddSk(PTLB_DS, 9, 1, 2, "B\168ng C\172 Tuy\213t C\232t", 5)
	PTLB_AddSk(PTLB_DS, 22, 2, 2, "Ch\243c Dung Ch\169n Kh\221", 5)
	PTLB_AddSk(PTLB_DS, 19, 3, 2, "L\171i Phong Gi\184p", 5)
	PTLB_DN = { n = 0, base = 43, task = PTLB_T_DN }
	PTLB_AddSk(PTLB_DN, 43, 0, 3, "Kim Cang Ch\243", 1)
	PTLB_AddSk(PTLB_DN, 46, 0, 3, "C\173\234ng C\171ng Ch\243", 1)
	PTLB_AddSk(PTLB_DN, 48, 0, 3, "B\229 \167\210 Ch\243", 1)
	PTLB_AddSk(PTLB_DN, 50, 0, 3, "T\203t Phong Ch\243", 1)
	PTLB_AddSk(PTLB_DN, 45, 0, 4, "B\230 T\169m Ch\243", 2)
	PTLB_AddSk(PTLB_DN, 47, 0, 5, "Ph\184 Gi\184p Ch\243", 2)
	PTLB_AddSk(PTLB_DN, 49, 0, 5, "Tr\182m T\169m Ch\243", 2)
	PTLB_GS = { n = 0, base = 27, task = PTLB_T_GS }
	PTLB_AddSk(PTLB_GS, 27, 1, 1, "T\213 Huy\213t Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 30, 1, 1, "H\229i Phong Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 32, 1, 1, "Ho\181nh Kh\171ng Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 36, 1, 1, "Huy\210n B\168ng Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 38, 1, 1, "Li\170n Ho\181n Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 41, 1, 1, "Thi\170n Qu\169n Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 29, 2, 1, "Khai S\172n Tr\182m", 2)
	PTLB_AddSk(PTLB_GS, 31, 2, 1, "\167i\214n Quang Tr\182m", 2)
	PTLB_AddSk(PTLB_GS, 35, 2, 1, "Tam \167\199u L\244c Th\241", 2)
	PTLB_AddSk(PTLB_GS, 37, 2, 1, "H\225a Quang Tr\182m", 2)
	PTLB_AddSk(PTLB_GS, 39, 2, 1, "L\185c \167\222a Tr\182m", 2)
	PTLB_AddSk(PTLB_GS, 42, 2, 1, "Khuynh Th\181nh Nh\202t K\221ch", 2)
	PTLB_AddSk(PTLB_GS, 28, 0, 3, "L\168ng Ba Vi B\233", 3)
	PTLB_AddSk(PTLB_GS, 40, 0, 3, "Thu\199n D\173\172ng H\233 Th\211", 3)
	PTLB_BL = { "\167o\182n \174ao", "Tr\173\234ng \174ao" }
	-- skills of each profession for "Nang cap ky nang": { id, max level (skills.txt MaxLevel), player level needed, name }
	PTLB_PS = {}
	PTLB_PS[0] = {}
	PTLB_PS[1] = {}
	PTLB_PS[2] = {}
	PTLB_AddPS(0, 27, 10, 0, "T\213 Huy\213t Tr\182m")
	PTLB_AddPS(0, 28, 10, 0, "L\168ng Ba Vi B\233")
	PTLB_AddPS(0, 29, 10, 0, "Khai S\172n Tr\182m")
	PTLB_AddPS(0, 30, 10, 0, "H\229i Phong Tr\182m")
	PTLB_AddPS(0, 31, 10, 0, "\167i\214n Quang Tr\182m")
	PTLB_AddPS(0, 32, 10, 0, "Ho\181nh Kh\171ng Tr\182m")
	PTLB_AddPS(0, 33, 10, 0, "Tinh Th\171ng \167o\182n \167ao")
	PTLB_AddPS(0, 34, 10, 0, "Tinh Th\171ng Tr\173\234ng \167ao")
	PTLB_AddPS(0, 35, 10, 0, "Tam \167\199u L\244c Th\241")
	PTLB_AddPS(0, 36, 10, 0, "Huy\210n B\168ng Tr\182m")
	PTLB_AddPS(0, 37, 10, 0, "H\225a Quang Tr\182m")
	PTLB_AddPS(0, 38, 10, 0, "Li\170n Ho\181n Tr\182m")
	PTLB_AddPS(0, 39, 10, 0, "L\185c \167\222a Tr\182m")
	PTLB_AddPS(0, 40, 10, 0, "Thu\199n D\173\172ng H\233 Th\211")
	PTLB_AddPS(0, 41, 10, 0, "Thi\170n Qu\169n Tr\182m")
	PTLB_AddPS(0, 42, 10, 0, "Khuynh Th\181nh Nh\202t K\221ch")
	PTLB_AddPS(0, 1481, 10, 60, "Huy\213t Chi\213n Sa Tr\173\234ng")
	PTLB_AddPS(0, 1482, 10, 120, "D\220 Chi\213n D\173\236ng Chi\213n")
	PTLB_AddPS(0, 1483, 10, 180, "B\184ch Chi\213n D\173 Sinh")
	PTLB_AddPS(1, 3, 10, 0, "Ch\173\235ng T\169m L\171i")
	PTLB_AddPS(1, 4, 10, 0, "L\173u Tinh Th\185ch")
	PTLB_AddPS(1, 5, 10, 0, "B\168ng Tuy\213t \167\185n")
	PTLB_AddPS(1, 6, 10, 0, "T\221ch L\222ch H\225a")
	PTLB_AddPS(1, 7, 10, 0, "Tinh Th\171ng L\171i H\214")
	PTLB_AddPS(1, 8, 10, 0, "Thi\170n Phong \167\222a Nh\203n")
	PTLB_AddPS(1, 9, 10, 0, "B\168ng C\172 Tuy\213t C\232t")
	PTLB_AddPS(1, 10, 10, 0, "Phong L\169m H\225a S\172n")
	PTLB_AddPS(1, 11, 10, 0, "H\185n \167\222a L\171i")
	PTLB_AddPS(1, 12, 10, 0, "Tinh Th\171ng Th\230 H\214")
	PTLB_AddPS(1, 13, 10, 0, "Thi\213t M\183 B\168ng Qua")
	PTLB_AddPS(1, 14, 10, 0, "Tinh Th\171ng H\225a H\214")
	PTLB_AddPS(1, 15, 10, 0, "Phong V\169n L\171i \167\233ng")
	PTLB_AddPS(1, 16, 10, 0, "Ng\242 Nh\185c Tri\210u T\171ng")
	PTLB_AddPS(1, 17, 10, 0, "Tinh Th\171ng B\168ng H\214")
	PTLB_AddPS(1, 18, 10, 0, "Th\203p Ph\173\172ng Li\214t H\225a")
	PTLB_AddPS(1, 19, 10, 0, "L\171i Phong Gi\184p")
	PTLB_AddPS(1, 20, 10, 0, "Thi\170n B\168ng \167\222a Li\214t")
	PTLB_AddPS(1, 21, 10, 0, "B\168ng Phong B\185o")
	PTLB_AddPS(1, 22, 10, 0, "Ch\243c Dung Ch\169n Kh\221")
	PTLB_AddPS(1, 23, 10, 0, "L\171i \167\233ng C\246u Thi\170n")
	PTLB_AddPS(1, 24, 10, 0, "Huy\210n N\247 B\230 Thi\170n")
	PTLB_AddPS(1, 25, 10, 0, "B\168ng Phong V\185n L\253")
	PTLB_AddPS(1, 26, 10, 0, "Tam Mu\233i Ch\169n H\225a")
	PTLB_AddPS(1, 1484, 10, 60, "Nghi\214p H\225a Ph\199n T\169m")
	PTLB_AddPS(1, 1485, 10, 120, "H\185o Nhi\170n Ch\221nh Kh\221")
	PTLB_AddPS(1, 1486, 10, 180, "D\201n H\225a Thi\170u Th\169n")
	PTLB_AddPS(2, 43, 10, 0, "Kim Cang Ch\243")
	PTLB_AddPS(2, 44, 10, 0, "Th\171i Th\169n Ch\243")
	PTLB_AddPS(2, 45, 10, 0, "B\230 T\169m Ch\243")
	PTLB_AddPS(2, 46, 10, 0, "C\173\234ng C\171ng Ch\243")
	PTLB_AddPS(2, 47, 10, 0, "Ph\184 Gi\184p Ch\243")
	PTLB_AddPS(2, 48, 10, 0, "B\229 \167\210 Ch\243")
	PTLB_AddPS(2, 49, 10, 0, "Tr\182m T\169m Ch\243")
	PTLB_AddPS(2, 50, 10, 0, "T\203t Phong Ch\243")
	PTLB_AddPS(2, 51, 10, 0, "V\185n C\232t To\181n Kh\171")
	PTLB_AddPS(2, 1487, 10, 60, "\167\233c H\181nh Thi\170n H\185")
	PTLB_AddPS(2, 1488, 10, 120, "C\230 Ho\198c Ch\243ng Sinh")
	PTLB_AddPS(2, 1489, 10, 180, "V\185n \167\233c H\233 Th\169n")
end

-- set value: 0 or 2^30 + bits
function PTLB_Has(t, v, id)
	if v < PTLB_FLAG then return nil end
	return PTLB_Bit(v, id - t.base)
end

function PTLB_With(t, v, id)
	if v < PTLB_FLAG then v = PTLB_FLAG end
	if PTLB_Has(t, v, id) then return v end
	return v + PTLB_Pow(id - t.base)
end

function PTLB_Without(t, v, id)
	if not PTLB_Has(t, v, id) then return v end
	v = v - PTLB_Pow(id - t.base)
	if v <= PTLB_FLAG then return 0 end
	return v
end

-- current PlayerIndex: store and send to the client (VNG s2c_synctaskvalue, read by PhongThanAutoFight.inl)
function PTLB_Apply(task, v)
	SetTask(task, v)
	SyncTaskValue(task)
end

-- the current task 2617 is sent first, so the client has a baseline when a command follows
function PTLB_Baseline()
	PTLB_Apply(PTLB_T_CMD, GetTask(PTLB_T_CMD))
end

function PTLB_Cmd(c)
	local s = floor(GetTask(PTLB_T_CMD) / 4) + 1
	if s > 99999 then s = 1 end
	PTLB_Apply(PTLB_T_CMD, s * 4 + c)
end

-- ask the client to start the auto fight (as Alt+A); not in a safe zone
function PTLB_StartAuto(token)
	if GetFightState() == 0 then
		Msg2Player(token .. ": \174ang \235 khu v\249c an to\181n, ch\173a th\211 t\249 \174\233ng \174\184nh. Ra ngo\181i b\183i luy\214n r\229i ch\228n B\190t \174\199u t\249 \174\233ng \174\184nh trong l\214nh b\181i ho\198c b\202m Alt+A.")
		return
	end
	PTLB_Cmd(1)
	Msg2Player(token .. ": b\190t \174\199u t\249 \174\233ng \174\184nh (nh\173 Alt+A). D\245ng: ch\228n D\245ng t\249 \174\233ng \174\184nh trong l\214nh b\181i ho\198c b\202m l\185i Alt+A.")
end

function PTLB_StopAuto(token)
	PTLB_Cmd(2)
	Msg2Player(token .. ": \174\183 g\246i l\214nh d\245ng t\249 \174\233ng \174\184nh.")
end

function PTLB_PrefText()
	if GetTask(PTLB_T_PREF) == 0 then return "T\249 b\203t t\249 \174\184nh khi ch\228n b\233: \167ANG B\203T" end
	return "T\249 b\203t t\249 \174\184nh khi ch\228n b\233: \167ANG T\190T"
end

function PTLB_TogglePref()
	if GetTask(PTLB_T_PREF) == 0 then SetTask(PTLB_T_PREF, 1) else SetTask(PTLB_T_PREF, 0) end
end

-- learnt skills of group g of table t, in table order: { index in the table, ... }
function PTLB_GroupList(t, g)
	local r = {}
	local i = 1
	while i <= t.n do
		if t[i].grp == g and PTLB_Learnt(t[i].id) then tinsert(r, i) end
		i = i + 1
	end
	return r
end

-- "a trong b": skills of group g switched on / learnt
function PTLB_GroupCount(t, v, g)
	local l = PTLB_GroupList(t, g)
	local on = 0
	local i = 1
	while l[i] do
		if PTLB_Has(t, v, t[l[i]].id) then on = on + 1 end
		i = i + 1
	end
	return on .. " trong " .. getn(l)
end

-- number of learnt skills of the set, and of them the attack skills
function PTLB_Count(t, v)
	local n = 0
	local a = 0
	local i = 1
	while i <= t.n do
		local s = t[i]
		if PTLB_Has(t, v, s.id) and PTLB_Learnt(s.id) then
			n = n + 1
			if s.kind == 1 then a = a + 1 end
		end
		i = i + 1
	end
	return n, a
end

-- short text of the learnt skills of a Dao Si set: "Tho 3, Hoa 2, Bang 4 + buff 1"
function PTLB_DescDS(v)
	if v < PTLB_FLAG then return "theo ph\221m \174ang g\184n" end
	local c = { 0, 0, 0, 0 }
	local b = 0
	local i = 1
	while i <= PTLB_DS.n do
		local s = PTLB_DS[i]
		if PTLB_Has(PTLB_DS, v, s.id) and PTLB_Learnt(s.id) then
			if s.kind == 1 then c[s.el] = c[s.el] + 1 else b = b + 1 end
		end
		i = i + 1
	end
	local r = ""
	local k = { 4, 2, 1, 3 }
	i = 1
	while i <= 4 do
		if c[k[i]] > 0 then
			if r ~= "" then r = r .. ", " end
			r = r .. PTLB_EL[k[i]] .. " " .. c[k[i]]
		end
		i = i + 1
	end
	if r == "" then r = "ch\173a c\227 chi\170u \174\184nh \174\183 h\228c (d\239ng ph\221m)" end
	if b > 0 then r = r .. " + buff " .. b end
	return r
end

function PTLB_DescGS(v)
	if v < PTLB_FLAG then return "theo ph\221m \174ang g\184n" end
	local c = { 0, 0 }
	local b = 0
	local i = 1
	while i <= PTLB_GS.n do
		local s = PTLB_GS[i]
		if PTLB_Has(PTLB_GS, v, s.id) and PTLB_Learnt(s.id) then
			if s.kind == 1 then c[s.el] = c[s.el] + 1 else b = b + 1 end
		end
		i = i + 1
	end
	local r = ""
	if c[1] > 0 then r = PTLB_BL[1] .. " " .. c[1] end
	if c[2] > 0 then
		if r ~= "" then r = r .. ", " end
		r = r .. PTLB_BL[2] .. " " .. c[2]
	end
	if r == "" then r = "ch\173a c\227 chi\170u \174\184nh \174\183 h\228c (d\239ng ph\221m)" end
	if b > 0 then r = r .. " + h\181o quang " .. b end
	return r
end

function PTLB_DescDN(v)
	if v < PTLB_FLAG then return "t\190t" end
	local r = ""
	local i = 1
	while i <= PTLB_DN.n do
		local s = PTLB_DN[i]
		if PTLB_Has(PTLB_DN, v, s.id) and PTLB_Learnt(s.id) then
			if r ~= "" then r = r .. ", " end
			r = r .. s.nm
		end
		i = i + 1
	end
	if r == "" then r = "ch\173a h\228c chi\170u n\181o trong b\233" end
	return r
end

function PTLBDS_Title()
	PTLB_Load()
	return "<color=yellow>L\214nh B\181i \167\185o S\220<color>: b\233 chi\170u t\249 \174\184nh lu\169n phi\170n. Hi\214n t\185i: <color=green>" .. PTLB_DescDS(GetTask(PTLB_T_DS)) .. "<color>. Ch\228n b\233 l\181 t\249 b\203t t\249 \174\184nh; Alt+A c\242ng b\203t ho\198c t\190t."
end

-- attack skills of the given elements replace the attack part; the chosen buffs stay
function PTLBDS_SetEls(e1, e2, e3, e4)
	PTLB_Load()
	local v = GetTask(PTLB_T_DS)
	local i = 1
	while i <= PTLB_DS.n do
		local s = PTLB_DS[i]
		if s.kind == 1 then
			if s.el == e1 or s.el == e2 or s.el == e3 or s.el == e4 then v = PTLB_With(PTLB_DS, v, s.id) else v = PTLB_Without(PTLB_DS, v, s.id) end
		end
		i = i + 1
	end
	PTLB_Apply(PTLB_T_DS, v)
	local n, a = PTLB_Count(PTLB_DS, v)
	Msg2Player("L\214nh B\181i \167\185o S\220: b\233 chi\170u " .. PTLB_DescDS(v) .. " - t\249 \174\184nh lu\169n phi\170n " .. a .. " chi\170u \174\184nh \174\183 h\228c.")
	if a == 0 then Msg2Player("B\185n ch\173a h\228c chi\170u \174\184nh n\181o c\241a h\214 \174\183 ch\228n: t\249 \174\184nh t\185m d\239ng chi\170u \174ang g\184n \235 ph\221m.") end
	PTLBDS_After()
end

function PTLBDS_Pre1() PTLBDS_SetEls(4, 2, 1, 0) end
function PTLBDS_Pre2() PTLBDS_SetEls(2, 1, 3, 0) end
function PTLBDS_Pre3() PTLBDS_SetEls(4, 2, 1, 3) end
function PTLBDS_E4() PTLBDS_SetEls(4, 0, 0, 0) end
function PTLBDS_E2() PTLBDS_SetEls(2, 0, 0, 0) end
function PTLBDS_E1() PTLBDS_SetEls(1, 0, 0, 0) end
function PTLBDS_E3() PTLBDS_SetEls(3, 0, 0, 0) end

function PTLBDS_Elem()
	local o = {}
	o[1] = "Ch\216 h\214 Th\230/PTLBDS_E4"
	o[2] = "Ch\216 h\214 H\225a/PTLBDS_E2"
	o[3] = "Ch\216 h\214 B\168ng/PTLBDS_E1"
	o[4] = "Ch\216 h\214 L\171i/PTLBDS_E3"
	o[5] = "Quay l\185i/PTLBDS_More"
	o[6] = "\167\227ng/PTLB_No"
	PTLB_Say(PTLBDS_Title(), o)
end

function PTLBDS_Off()
	PTLB_Apply(PTLB_T_DS, 0)
	Msg2Player("L\214nh B\181i \167\185o S\220: t\249 \174\184nh d\239ng chi\170u \174ang g\184n \235 tay tr\184i, tay ph\182i v\181 ph\221m Q W E / A S D / Z X C.")
	PTLBDS_After()
end

function PTLBDS_Start()
	PTLB_StartAuto("L\214nh B\181i \167\185o S\220")
end

function PTLBDS_Stop()
	PTLB_StopAuto("L\214nh B\181i \167\185o S\220")
end

-- after a set was chosen: start the auto fight (menu closed), or show the menu again (option off)
function PTLBDS_After()
	if GetTask(PTLB_T_PREF) == 0 then
		PTLB_StartAuto("L\214nh B\181i \167\185o S\220")
	else
		PTLBDS_Main()
	end
end

function PTLBDS_Main()
	PTLB_Load()
	local o = {}
	o[1] = "B\190t \174\199u t\249 \174\233ng \174\184nh/PTLBDS_Start"
	o[2] = "D\245ng t\249 \174\233ng \174\184nh/PTLBDS_Stop"
	o[3] = "B\233 Th\230 + H\225a + B\168ng (m\198c \174\222nh)/PTLBDS_Pre1"
	o[4] = "B\233 H\225a + B\168ng + L\171i/PTLBDS_Pre2"
	o[5] = "Ch\228n t\245ng chi\170u (b\203t, t\190t).../PTLBDS_Groups"
	o[6] = "B\233 kh\184c, t\239y ch\228n, n\169ng c\202p k\252 n\168ng.../PTLBDS_More"
	o[7] = "\167\227ng/PTLB_No"
	PTLB_Say(PTLBDS_Title(), o)
end

function PTLBDS_Groups()
	PTLB_Load()
	local v = GetTask(PTLB_T_DS)
	local o = {}
	o[1] = "H\214 Th\230" .. " (" .. PTLB_GroupCount(PTLB_DS, v, 1) .. " \174ang b\203t)" .. "/PTLBDS_G1"
	o[2] = "H\214 H\225a" .. " (" .. PTLB_GroupCount(PTLB_DS, v, 2) .. " \174ang b\203t)" .. "/PTLBDS_G2"
	o[3] = "H\214 B\168ng" .. " (" .. PTLB_GroupCount(PTLB_DS, v, 3) .. " \174ang b\203t)" .. "/PTLBDS_G3"
	o[4] = "H\214 L\171i" .. " (" .. PTLB_GroupCount(PTLB_DS, v, 4) .. " \174ang b\203t)" .. "/PTLBDS_G4"
	o[5] = "Buff h\214" .. " (" .. PTLB_GroupCount(PTLB_DS, v, 5) .. " \174ang b\203t)" .. "/PTLBDS_G5"
	o[6] = "Quay l\185i/PTLBDS_Main"
	o[7] = "\167\227ng/PTLB_No"
	PTLB_Say("<color=yellow>L\214nh B\181i \167\185o S\220<color>: ch\228n nh\227m chi\170u, r\229i b\202m t\245ng chi\170u \174\211 b\203t ho\198c t\190t. [B\203T] = t\249 \174\184nh d\239ng chi\170u \174\227. Ch\216 hi\214n chi\170u \174\183 h\228c.", o)
end

function PTLBDS_Group(g)
	PTLB_Load()
	local l = PTLB_GroupList(PTLB_DS, g)
	local v = GetTask(PTLB_T_DS)
	local names = { "H\214 Th\230", "H\214 H\225a", "H\214 B\168ng", "H\214 L\171i", "Buff h\214" }
	if getn(l) == 0 then
		Say("<color=yellow>L\214nh B\181i \167\185o S\220<color>: b\185n ch\173a h\228c chi\170u n\181o c\241a nh\227m " .. names[g] .. ".", 2, "Quay l\185i/PTLBDS_Groups", "\167\227ng/PTLB_No")
		return
	end
	local o = {}
	local n = 0
	local i = 1
	while l[i] do
		local s = PTLB_DS[l[i]]
		local m = "[t\190t] "
		if PTLB_Has(PTLB_DS, v, s.id) then m = "[B\203T] " end
		n = n + 1
		o[n] = m .. s.nm .. "/PTLBDS_T" .. l[i]
		i = i + 1
	end
	if n <= 5 then n = n + 1 o[n] = "Xong, b\190t \174\199u t\249 \174\233ng \174\184nh/PTLBDS_Start" end
	n = n + 1 o[n] = "Quay l\185i/PTLBDS_Groups"
	if n < 7 then n = n + 1 o[n] = "\167\227ng/PTLB_No" end
	PTLB_Say("<color=yellow>L\214nh B\181i \167\185o S\220<color>: nh\227m " .. names[g] .. " - b\202m m\233t chi\170u \174\211 b\203t ho\198c t\190t (\174ang b\203t " .. PTLB_GroupCount(PTLB_DS, v, g) .. ").", o)
end

function PTLBDS_G1() PTLBDS_Group(1) end
function PTLBDS_G2() PTLBDS_Group(2) end
function PTLBDS_G3() PTLBDS_Group(3) end
function PTLBDS_G4() PTLBDS_Group(4) end
function PTLBDS_G5() PTLBDS_Group(5) end

-- toggle skill k of the table, then show its group page again
function PTLBDS_Toggle(k)
	PTLB_Load()
	local s = PTLB_DS[k]
	if not s or not PTLB_Learnt(s.id) then return end
	local v = GetTask(PTLB_T_DS)
	local on = nil
	if PTLB_Has(PTLB_DS, v, s.id) then v = PTLB_Without(PTLB_DS, v, s.id) else v = PTLB_With(PTLB_DS, v, s.id) on = 1 end
	local n, a = PTLB_Count(PTLB_DS, v)
	if n == 0 then v = 0 end
	PTLB_Apply(PTLB_T_DS, v)
	if on then Msg2Player("L\214nh B\181i \167\185o S\220: b\203t " .. s.nm) else Msg2Player("L\214nh B\181i \167\185o S\220: t\190t " .. s.nm) end
	PTLBDS_Group(s.grp)
end

function PTLBDS_TogglePref()
	PTLB_TogglePref()
	PTLBDS_More()
end

function PTLBDS_More()
	local o = {}
	o[1] = "B\233 t\202t c\182 c\184c h\214/PTLBDS_Pre3"
	o[2] = "Ch\216 m\233t h\214.../PTLBDS_Elem"
	o[3] = "Theo ph\221m \174ang g\184n (b\225 b\233 chi\170u)/PTLBDS_Off"
	o[4] = "N\169ng c\202p k\252 n\168ng (t\232i \174a).../PTLBDS_Up"
	o[5] = PTLB_PrefText() .. "/PTLBDS_TogglePref"
	o[6] = "Quay l\185i/PTLBDS_Main"
	o[7] = "\167\227ng/PTLB_No"
	PTLB_Say(PTLBDS_Title(), o)
end

function PTLBDS_T1() PTLBDS_Toggle(1) end
function PTLBDS_T2() PTLBDS_Toggle(2) end
function PTLBDS_T3() PTLBDS_Toggle(3) end
function PTLBDS_T4() PTLBDS_Toggle(4) end
function PTLBDS_T5() PTLBDS_Toggle(5) end
function PTLBDS_T6() PTLBDS_Toggle(6) end
function PTLBDS_T7() PTLBDS_Toggle(7) end
function PTLBDS_T8() PTLBDS_Toggle(8) end
function PTLBDS_T9() PTLBDS_Toggle(9) end
function PTLBDS_T10() PTLBDS_Toggle(10) end
function PTLBDS_T11() PTLBDS_Toggle(11) end
function PTLBDS_T12() PTLBDS_Toggle(12) end
function PTLBDS_T13() PTLBDS_Toggle(13) end
function PTLBDS_T14() PTLBDS_Toggle(14) end
function PTLBDS_T15() PTLBDS_Toggle(15) end
function PTLBDS_T16() PTLBDS_Toggle(16) end
function PTLBDS_T17() PTLBDS_Toggle(17) end
function PTLBDS_T18() PTLBDS_Toggle(18) end
function PTLBDS_T19() PTLBDS_Toggle(19) end
function PTLBDS_T20() PTLBDS_Toggle(20) end
function PTLBDS_Up()
	local n = getn(PTLB_ProfList(1))
	local o = {}
	o[1] = "N\169ng t\232i \174a to\181n b\233 k\252 n\168ng ph\184i (" .. n .. " chi\170u)" .. "/PTLBDS_UpAll"
	o[2] = "N\169ng t\232i \174a m\233t k\252 n\168ng.../PTLBDS_UP1"
	o[3] = "Quay l\185i/PTLBDS_More"
	o[4] = "\167\227ng/PTLB_No"
	PTLB_Say("<color=yellow>L\214nh B\181i \167\185o S\220<color>: n\169ng k\252 n\168ng c\241a ph\184i l\170n c\202p t\232i \174a (h\228c lu\171n chi\170u ch\173a c\227). Kh\171ng t\232n v\181 kh\171ng ho\181n \174i\211m k\252 n\168ng. Chi\170u chuy\211n sinh 60, 120, 180 ch\216 c\227 khi \174\241 c\202p nh\169n v\203t.", o)
end

function PTLBDS_UpAll()
	Say("<color=yellow>L\214nh B\181i \167\185o S\220<color>: n\169ng TO\181N B\233 k\252 n\168ng c\241a ph\184i l\170n c\202p t\232i \174a?", 2, "\167\229ng \253, n\169ng t\232i \174a to\181n b\233/PTLBDS_UpAllOk", "Kh\171ng/PTLBDS_Up")
end

function PTLBDS_UpAllOk()
	local ok, n = PTLB_MaxAll(1)
	Msg2Player("L\214nh B\181i \167\185o S\220: \174\183 n\169ng t\232i \174a " .. ok .. " trong " .. n .. " k\252 n\168ng c\241a ph\184i.")
	PTLBDS_Up()
end

function PTLBDS_UpPage(pg)
	local l = PTLB_ProfList(1)
	local last = floor((getn(l) + 4) / 5)
	if last < 1 then last = 1 end
	if pg > last then pg = last end
	local o = {}
	local n = 0
	local i = (pg - 1) * 5 + 1
	while i <= pg * 5 and l[i] do
		local s = l[i]
		local lv = PTLB_Lv(s.id)
		local d = " (c\202p " .. lv .. " trong " .. s.mx .. ")"
		if lv <= 0 then d = " (ch\173a h\228c, t\232i \174a " .. s.mx .. ")" end
		if lv >= s.mx then d = " (\174\183 t\232i \174a " .. s.mx .. ")" end
		n = n + 1
		o[n] = s.nm .. d .. "/PTLBDS_U" .. s.id
		i = i + 1
	end
	if pg < last then n = n + 1 o[n] = "Trang sau " .. (pg + 1) .. "/PTLBDS_UP" .. (pg + 1) end
	n = n + 1 o[n] = "Quay l\185i/PTLBDS_Up"
	if n < 7 then n = n + 1 o[n] = "\167\227ng/PTLB_No" end
	PTLB_Say("<color=yellow>L\214nh B\181i \167\185o S\220<color>: ch\228n k\252 n\168ng \174\211 n\169ng l\170n c\202p t\232i \174a (trang " .. pg .. " " .. "trong " .. last .. ").", o)
end

function PTLBDS_UP1() PTLBDS_UpPage(1) end
function PTLBDS_UP2() PTLBDS_UpPage(2) end
function PTLBDS_UP3() PTLBDS_UpPage(3) end
function PTLBDS_UP4() PTLBDS_UpPage(4) end
function PTLBDS_UP5() PTLBDS_UpPage(5) end
function PTLBDS_UP6() PTLBDS_UpPage(6) end

function PTLBDS_UpOne(id)
	local s = PTLB_FindPS(1, id)
	if not s then return end
	if PTLB_Lv(id) >= s.mx then
		Msg2Player("L\214nh B\181i \167\185o S\220: " .. s.nm .. " \174\183 \235 c\202p t\232i \174a " .. s.mx .. ".")
		PTLBDS_UpShow(id)
		return
	end
	Say("<color=yellow>L\214nh B\181i \167\185o S\220<color>: n\169ng " .. s.nm .. " l\170n c\202p t\232i \174a " .. s.mx .. "?", 2, "\167\229ng \253/PTLBDS_Y" .. id, "Kh\171ng/PTLBDS_Up")
end

function PTLBDS_UpOk(id)
	local s = PTLB_FindPS(1, id)
	if not s then return end
	if PTLB_MaxOne(s) > 0 then
		Msg2Player("L\214nh B\181i \167\185o S\220: \174\183 n\169ng " .. s.nm .. " l\170n c\202p " .. s.mx .. ".")
	else
		Msg2Player("L\214nh B\181i \167\185o S\220: kh\171ng n\169ng \174\173\238c " .. s.nm .. ".")
	end
	PTLBDS_UpShow(id)
end

-- show the upgrade page holding skill id
function PTLBDS_UpShow(id)
	local s, pos = PTLB_FindPS(1, id)
	if pos < 1 then pos = 1 end
	PTLBDS_UpPage(floor((pos - 1) / 5) + 1)
end

function PTLBDS_U3() PTLBDS_UpOne(3) end
function PTLBDS_Y3() PTLBDS_UpOk(3) end
function PTLBDS_U4() PTLBDS_UpOne(4) end
function PTLBDS_Y4() PTLBDS_UpOk(4) end
function PTLBDS_U5() PTLBDS_UpOne(5) end
function PTLBDS_Y5() PTLBDS_UpOk(5) end
function PTLBDS_U6() PTLBDS_UpOne(6) end
function PTLBDS_Y6() PTLBDS_UpOk(6) end
function PTLBDS_U7() PTLBDS_UpOne(7) end
function PTLBDS_Y7() PTLBDS_UpOk(7) end
function PTLBDS_U8() PTLBDS_UpOne(8) end
function PTLBDS_Y8() PTLBDS_UpOk(8) end
function PTLBDS_U9() PTLBDS_UpOne(9) end
function PTLBDS_Y9() PTLBDS_UpOk(9) end
function PTLBDS_U10() PTLBDS_UpOne(10) end
function PTLBDS_Y10() PTLBDS_UpOk(10) end
function PTLBDS_U11() PTLBDS_UpOne(11) end
function PTLBDS_Y11() PTLBDS_UpOk(11) end
function PTLBDS_U12() PTLBDS_UpOne(12) end
function PTLBDS_Y12() PTLBDS_UpOk(12) end
function PTLBDS_U13() PTLBDS_UpOne(13) end
function PTLBDS_Y13() PTLBDS_UpOk(13) end
function PTLBDS_U14() PTLBDS_UpOne(14) end
function PTLBDS_Y14() PTLBDS_UpOk(14) end
function PTLBDS_U15() PTLBDS_UpOne(15) end
function PTLBDS_Y15() PTLBDS_UpOk(15) end
function PTLBDS_U16() PTLBDS_UpOne(16) end
function PTLBDS_Y16() PTLBDS_UpOk(16) end
function PTLBDS_U17() PTLBDS_UpOne(17) end
function PTLBDS_Y17() PTLBDS_UpOk(17) end
function PTLBDS_U18() PTLBDS_UpOne(18) end
function PTLBDS_Y18() PTLBDS_UpOk(18) end
function PTLBDS_U19() PTLBDS_UpOne(19) end
function PTLBDS_Y19() PTLBDS_UpOk(19) end
function PTLBDS_U20() PTLBDS_UpOne(20) end
function PTLBDS_Y20() PTLBDS_UpOk(20) end
function PTLBDS_U21() PTLBDS_UpOne(21) end
function PTLBDS_Y21() PTLBDS_UpOk(21) end
function PTLBDS_U22() PTLBDS_UpOne(22) end
function PTLBDS_Y22() PTLBDS_UpOk(22) end
function PTLBDS_U23() PTLBDS_UpOne(23) end
function PTLBDS_Y23() PTLBDS_UpOk(23) end
function PTLBDS_U24() PTLBDS_UpOne(24) end
function PTLBDS_Y24() PTLBDS_UpOk(24) end
function PTLBDS_U25() PTLBDS_UpOne(25) end
function PTLBDS_Y25() PTLBDS_UpOk(25) end
function PTLBDS_U26() PTLBDS_UpOne(26) end
function PTLBDS_Y26() PTLBDS_UpOk(26) end
function PTLBDS_U1484() PTLBDS_UpOne(1484) end
function PTLBDS_Y1484() PTLBDS_UpOk(1484) end
function PTLBDS_U1485() PTLBDS_UpOne(1485) end
function PTLBDS_Y1485() PTLBDS_UpOk(1485) end
function PTLBDS_U1486() PTLBDS_UpOne(1486) end
function PTLBDS_Y1486() PTLBDS_UpOk(1486) end

function main(nItemIdx)
	if GetProfession() ~= 1 then
		Say("<color=yellow>L\214nh B\181i \167\185o S\220<color>: ch\216 d\181nh cho ph\184i \167\185o S\220.", 1, "\167\227ng/PTLB_No")
		return 0
	end
	PTLB_Baseline()
	PTLBDS_Main()
	return 0
end
