-- Phong Than 2026-10-04 (agent lbdaosi): Lenh Bai Dao Si / Lenh Bai Di Nhan, servertimer side.
-- No main() here: dofile'd into the servertimer state by script\phongthan\ext\lbdaosi.lua (minute tick, needs
-- "lbdaosi" in PTADM_EXT_NAMES) and by the web admin bridge commands. Generated by scratchpad\lbdaosi\gen.py.
--  * every minute: tasks 2613 / 2614 are sent again to every online player (KPlayer::SyncCurPlayer clears the
--    client copy at each world entry);
--  * admin sets for offline characters wait in admin_bridge\lbdaosi_pending.txt and are applied at login;
--  * Dao Si / Di Nhan characters get their token once (tasks 2615 / 2616 = 1 when given or already owned).

PTLB_T_DS = 2613      -- Dao Si set: 0 = keys, else 2^30 + sum 2^(id - 3), ids 3..26
PTLB_T_DN = 2614      -- Di Nhan set: 0 = off, else 2^30 + sum 2^(id - 43), ids 43..51
PTLB_T_GDS = 2615     -- 1 = Lenh Bai Dao Si given (auto gift)
PTLB_T_GDN = 2616     -- 1 = Lenh Bai Di Nhan given (auto gift)
PTLB_ITEM_DS = 61480
PTLB_ITEM_DN = 61481
PTLB_T_GS = 2619      -- Giap Si set: 0 = keys, else 2^30 + sum 2^(id - 27), ids 27..42
PTLB_T_GGS = 2620     -- 1 = Lenh Bai Giap Si given (auto gift)
PTLB_ITEM_GS = 61482
PTLB_FLAG = 1073741824
PTLB_T_CMD = 2617     -- start / stop request for the client auto fight: sequence x 4 + 1 (start) / 2 (stop)
PTLB_T_PREF = 2618    -- 0 = start the auto fight when a set is chosen (default), 1 = do not

function PTLB_No()
end

function PTLB_Say(title, o)
	local n = getn(o)
	local t = { title, n }
	local k = 1
	while k <= n do t[k + 2] = o[k] k = k + 1 end
	call(Say, t)
end

function PTLB_Pow(k)
	local v = 1
	local i = 0
	while i < k do v = v * 2 i = i + 1 end
	return v
end

-- 1 when bit k of v is set (Lua 4: no bit operators)
function PTLB_Bit(v, k)
	local q = floor(v / PTLB_Pow(k))
	if q - floor(q / 2) * 2 == 1 then return 1 end
	return nil
end

function PTLB_Learnt(id)
	local l = HaveMagic(id)
	if l and l > 0 then return 1 end
	return nil
end

function PTLB_AddSk(t, id, el, kind, nm, grp)
	local s = {}
	s.grp = grp
	s.id = id
	s.el = el
	s.kind = kind
	s.nm = nm
	t.n = t.n + 1
	t[t.n] = s
end

function PTLB_AddPS(prof, id, mx, tier, nm)
	local s = {}
	s.id = id
	s.mx = mx
	s.tier = tier
	s.nm = nm
	tinsert(PTLB_PS[prof], s)
end

-- skills of the profession the character may raise now (rebirth skills once their level is reached)
function PTLB_ProfList(prof)
	PTLB_Load()
	local r = {}
	local t = PTLB_PS[prof]
	if not t then return r end
	local lv = GetLevel()
	local i = 1
	while t[i] do
		if t[i].tier <= lv then tinsert(r, t[i]) end
		i = i + 1
	end
	return r
end

function PTLB_FindPS(prof, id)
	local l = PTLB_ProfList(prof)
	local i = 1
	while l[i] do
		if l[i].id == id then return l[i], i end
		i = i + 1
	end
	return nil, 0
end

function PTLB_Lv(id)
	local l = HaveMagic(id)
	if l and l > 0 then return l end
	return 0
end

-- learn (if needed) and set skill s to its max level, as the web admin does (SetSkillLevel + AddMagic, which
-- syncs the client skill bar). Skill points are neither spent nor refunded. 1 when the level is reached.
function PTLB_MaxOne(s)
	if PTLB_Lv(s.id) >= s.mx then return 1 end
	SetSkillLevel(s.id, s.mx)
	AddMagic(s.id, s.mx)
	if PTLB_Lv(s.id) >= s.mx then return 1 end
	return 0
end

function PTLB_MaxAll(prof)
	local l = PTLB_ProfList(prof)
	local ok = 0
	local i = 1
	while l[i] do
		ok = ok + PTLB_MaxOne(l[i])
		i = i + 1
	end
	return ok, getn(l)
end

-- skill tables: { id, element (1 Bang 2 Hoa 3 Loi 4 Tho), kind (1 attack 2 buff 3 aura 4 heal 5 curse), name }
function PTLB_Load()
	if PTLB_DS then return end
	PTLB_EL = { "B\168ng", "H\225a", "L\171i", "Th\230" }
	PTLB_KIND = { "", "buff", "h\181o quang", "h\229i m\184u", "ch\243 nguy\210n" }
	PTLB_DS = { n = 0, base = 3, task = PTLB_T_DS }
	PTLB_AddSk(PTLB_DS, 4, 4, 1, "L\173u Tinh Th\185ch", 1)
	PTLB_AddSk(PTLB_DS, 8, 4, 1, "Thi\170n Phong \167\222a Nh\203n", 1)
	PTLB_AddSk(PTLB_DS, 16, 4, 1, "Ng\242 Nh\185c Tri\210u T\171ng", 1)
	PTLB_AddSk(PTLB_DS, 20, 4, 1, "Thi\170n B\168ng \167\222a Li\214t", 1)
	PTLB_AddSk(PTLB_DS, 24, 4, 1, "Huy\210n N\247 B\230 Thi\170n", 1)
	PTLB_AddSk(PTLB_DS, 6, 2, 1, "T\221ch L\222ch H\225a", 2)
	PTLB_AddSk(PTLB_DS, 10, 2, 1, "Phong L\169m H\225a S\172n", 2)
	PTLB_AddSk(PTLB_DS, 18, 2, 1, "Th\203p Ph\173\172ng Li\214t H\225a", 2)
	PTLB_AddSk(PTLB_DS, 26, 2, 1, "Tam Mu\233i Ch\169n H\225a", 2)
	PTLB_AddSk(PTLB_DS, 5, 1, 1, "B\168ng Tuy\213t \167\185n", 3)
	PTLB_AddSk(PTLB_DS, 13, 1, 1, "Thi\213t M\183 B\168ng Qua", 3)
	PTLB_AddSk(PTLB_DS, 21, 1, 1, "B\168ng Phong B\185o", 3)
	PTLB_AddSk(PTLB_DS, 25, 1, 1, "B\168ng Phong V\185n L\253", 3)
	PTLB_AddSk(PTLB_DS, 3, 3, 1, "Ch\173\235ng T\169m L\171i", 4)
	PTLB_AddSk(PTLB_DS, 11, 3, 1, "H\185n \167\222a L\171i", 4)
	PTLB_AddSk(PTLB_DS, 15, 3, 1, "Phong V\169n L\171i \167\233ng", 4)
	PTLB_AddSk(PTLB_DS, 23, 3, 1, "L\171i \167\233ng C\246u Thi\170n", 4)
	PTLB_AddSk(PTLB_DS, 9, 1, 2, "B\168ng C\172 Tuy\213t C\232t", 5)
	PTLB_AddSk(PTLB_DS, 22, 2, 2, "Ch\243c Dung Ch\169n Kh\221", 5)
	PTLB_AddSk(PTLB_DS, 19, 3, 2, "L\171i Phong Gi\184p", 5)
	PTLB_DN = { n = 0, base = 43, task = PTLB_T_DN }
	PTLB_AddSk(PTLB_DN, 43, 0, 3, "Kim Cang Ch\243", 1)
	PTLB_AddSk(PTLB_DN, 46, 0, 3, "C\173\234ng C\171ng Ch\243", 1)
	PTLB_AddSk(PTLB_DN, 48, 0, 3, "B\229 \167\210 Ch\243", 1)
	PTLB_AddSk(PTLB_DN, 50, 0, 3, "T\203t Phong Ch\243", 1)
	PTLB_AddSk(PTLB_DN, 45, 0, 4, "B\230 T\169m Ch\243", 2)
	PTLB_AddSk(PTLB_DN, 47, 0, 5, "Ph\184 Gi\184p Ch\243", 2)
	PTLB_AddSk(PTLB_DN, 49, 0, 5, "Tr\182m T\169m Ch\243", 2)
	PTLB_GS = { n = 0, base = 27, task = PTLB_T_GS }
	PTLB_AddSk(PTLB_GS, 27, 1, 1, "T\213 Huy\213t Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 30, 1, 1, "H\229i Phong Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 32, 1, 1, "Ho\181nh Kh\171ng Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 36, 1, 1, "Huy\210n B\168ng Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 38, 1, 1, "Li\170n Ho\181n Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 41, 1, 1, "Thi\170n Qu\169n Tr\182m", 1)
	PTLB_AddSk(PTLB_GS, 29, 2, 1, "Khai S\172n Tr\182m", 2)
	PTLB_AddSk(PTLB_GS, 31, 2, 1, "\167i\214n Quang Tr\182m", 2)
	PTLB_AddSk(PTLB_GS, 35, 2, 1, "Tam \167\199u L\244c Th\241", 2)
	PTLB_AddSk(PTLB_GS, 37, 2, 1, "H\225a Quang Tr\182m", 2)
	PTLB_AddSk(PTLB_GS, 39, 2, 1, "L\185c \167\222a Tr\182m", 2)
	PTLB_AddSk(PTLB_GS, 42, 2, 1, "Khuynh Th\181nh Nh\202t K\221ch", 2)
	PTLB_AddSk(PTLB_GS, 28, 0, 3, "L\168ng Ba Vi B\233", 3)
	PTLB_AddSk(PTLB_GS, 40, 0, 3, "Thu\199n D\173\172ng H\233 Th\211", 3)
	PTLB_BL = { "\167o\182n \174ao", "Tr\173\234ng \174ao" }
	-- skills of each profession for "Nang cap ky nang": { id, max level (skills.txt MaxLevel), player level needed, name }
	PTLB_PS = {}
	PTLB_PS[0] = {}
	PTLB_PS[1] = {}
	PTLB_PS[2] = {}
	PTLB_AddPS(0, 27, 10, 0, "T\213 Huy\213t Tr\182m")
	PTLB_AddPS(0, 28, 10, 0, "L\168ng Ba Vi B\233")
	PTLB_AddPS(0, 29, 10, 0, "Khai S\172n Tr\182m")
	PTLB_AddPS(0, 30, 10, 0, "H\229i Phong Tr\182m")
	PTLB_AddPS(0, 31, 10, 0, "\167i\214n Quang Tr\182m")
	PTLB_AddPS(0, 32, 10, 0, "Ho\181nh Kh\171ng Tr\182m")
	PTLB_AddPS(0, 33, 10, 0, "Tinh Th\171ng \167o\182n \167ao")
	PTLB_AddPS(0, 34, 10, 0, "Tinh Th\171ng Tr\173\234ng \167ao")
	PTLB_AddPS(0, 35, 10, 0, "Tam \167\199u L\244c Th\241")
	PTLB_AddPS(0, 36, 10, 0, "Huy\210n B\168ng Tr\182m")
	PTLB_AddPS(0, 37, 10, 0, "H\225a Quang Tr\182m")
	PTLB_AddPS(0, 38, 10, 0, "Li\170n Ho\181n Tr\182m")
	PTLB_AddPS(0, 39, 10, 0, "L\185c \167\222a Tr\182m")
	PTLB_AddPS(0, 40, 10, 0, "Thu\199n D\173\172ng H\233 Th\211")
	PTLB_AddPS(0, 41, 10, 0, "Thi\170n Qu\169n Tr\182m")
	PTLB_AddPS(0, 42, 10, 0, "Khuynh Th\181nh Nh\202t K\221ch")
	PTLB_AddPS(0, 1481, 10, 60, "Huy\213t Chi\213n Sa Tr\173\234ng")
	PTLB_AddPS(0, 1482, 10, 120, "D\220 Chi\213n D\173\236ng Chi\213n")
	PTLB_AddPS(0, 1483, 10, 180, "B\184ch Chi\213n D\173 Sinh")
	PTLB_AddPS(1, 3, 10, 0, "Ch\173\235ng T\169m L\171i")
	PTLB_AddPS(1, 4, 10, 0, "L\173u Tinh Th\185ch")
	PTLB_AddPS(1, 5, 10, 0, "B\168ng Tuy\213t \167\185n")
	PTLB_AddPS(1, 6, 10, 0, "T\221ch L\222ch H\225a")
	PTLB_AddPS(1, 7, 10, 0, "Tinh Th\171ng L\171i H\214")
	PTLB_AddPS(1, 8, 10, 0, "Thi\170n Phong \167\222a Nh\203n")
	PTLB_AddPS(1, 9, 10, 0, "B\168ng C\172 Tuy\213t C\232t")
	PTLB_AddPS(1, 10, 10, 0, "Phong L\169m H\225a S\172n")
	PTLB_AddPS(1, 11, 10, 0, "H\185n \167\222a L\171i")
	PTLB_AddPS(1, 12, 10, 0, "Tinh Th\171ng Th\230 H\214")
	PTLB_AddPS(1, 13, 10, 0, "Thi\213t M\183 B\168ng Qua")
	PTLB_AddPS(1, 14, 10, 0, "Tinh Th\171ng H\225a H\214")
	PTLB_AddPS(1, 15, 10, 0, "Phong V\169n L\171i \167\233ng")
	PTLB_AddPS(1, 16, 10, 0, "Ng\242 Nh\185c Tri\210u T\171ng")
	PTLB_AddPS(1, 17, 10, 0, "Tinh Th\171ng B\168ng H\214")
	PTLB_AddPS(1, 18, 10, 0, "Th\203p Ph\173\172ng Li\214t H\225a")
	PTLB_AddPS(1, 19, 10, 0, "L\171i Phong Gi\184p")
	PTLB_AddPS(1, 20, 10, 0, "Thi\170n B\168ng \167\222a Li\214t")
	PTLB_AddPS(1, 21, 10, 0, "B\168ng Phong B\185o")
	PTLB_AddPS(1, 22, 10, 0, "Ch\243c Dung Ch\169n Kh\221")
	PTLB_AddPS(1, 23, 10, 0, "L\171i \167\233ng C\246u Thi\170n")
	PTLB_AddPS(1, 24, 10, 0, "Huy\210n N\247 B\230 Thi\170n")
	PTLB_AddPS(1, 25, 10, 0, "B\168ng Phong V\185n L\253")
	PTLB_AddPS(1, 26, 10, 0, "Tam Mu\233i Ch\169n H\225a")
	PTLB_AddPS(1, 1484, 10, 60, "Nghi\214p H\225a Ph\199n T\169m")
	PTLB_AddPS(1, 1485, 10, 120, "H\185o Nhi\170n Ch\221nh Kh\221")
	PTLB_AddPS(1, 1486, 10, 180, "D\201n H\225a Thi\170u Th\169n")
	PTLB_AddPS(2, 43, 10, 0, "Kim Cang Ch\243")
	PTLB_AddPS(2, 44, 10, 0, "Th\171i Th\169n Ch\243")
	PTLB_AddPS(2, 45, 10, 0, "B\230 T\169m Ch\243")
	PTLB_AddPS(2, 46, 10, 0, "C\173\234ng C\171ng Ch\243")
	PTLB_AddPS(2, 47, 10, 0, "Ph\184 Gi\184p Ch\243")
	PTLB_AddPS(2, 48, 10, 0, "B\229 \167\210 Ch\243")
	PTLB_AddPS(2, 49, 10, 0, "Tr\182m T\169m Ch\243")
	PTLB_AddPS(2, 50, 10, 0, "T\203t Phong Ch\243")
	PTLB_AddPS(2, 51, 10, 0, "V\185n C\232t To\181n Kh\171")
	PTLB_AddPS(2, 1487, 10, 60, "\167\233c H\181nh Thi\170n H\185")
	PTLB_AddPS(2, 1488, 10, 120, "C\230 Ho\198c Ch\243ng Sinh")
	PTLB_AddPS(2, 1489, 10, 180, "V\185n \167\233c H\233 Th\169n")
end

-- set value: 0 or 2^30 + bits
function PTLB_Has(t, v, id)
	if v < PTLB_FLAG then return nil end
	return PTLB_Bit(v, id - t.base)
end

function PTLB_With(t, v, id)
	if v < PTLB_FLAG then v = PTLB_FLAG end
	if PTLB_Has(t, v, id) then return v end
	return v + PTLB_Pow(id - t.base)
end

function PTLB_Without(t, v, id)
	if not PTLB_Has(t, v, id) then return v end
	v = v - PTLB_Pow(id - t.base)
	if v <= PTLB_FLAG then return 0 end
	return v
end

-- current PlayerIndex: store and send to the client (VNG s2c_synctaskvalue, read by PhongThanAutoFight.inl)
function PTLB_Apply(task, v)
	SetTask(task, v)
	SyncTaskValue(task)
end

-- the current task 2617 is sent first, so the client has a baseline when a command follows
function PTLB_Baseline()
	PTLB_Apply(PTLB_T_CMD, GetTask(PTLB_T_CMD))
end

function PTLB_Cmd(c)
	local s = floor(GetTask(PTLB_T_CMD) / 4) + 1
	if s > 99999 then s = 1 end
	PTLB_Apply(PTLB_T_CMD, s * 4 + c)
end

-- ask the client to start the auto fight (as Alt+A); not in a safe zone
function PTLB_StartAuto(token)
	if GetFightState() == 0 then
		Msg2Player(token .. ": \174ang \235 khu v\249c an to\181n, ch\173a th\211 t\249 \174\233ng \174\184nh. Ra ngo\181i b\183i luy\214n r\229i ch\228n B\190t \174\199u t\249 \174\233ng \174\184nh trong l\214nh b\181i ho\198c b\202m Alt+A.")
		return
	end
	PTLB_Cmd(1)
	Msg2Player(token .. ": b\190t \174\199u t\249 \174\233ng \174\184nh (nh\173 Alt+A). D\245ng: ch\228n D\245ng t\249 \174\233ng \174\184nh trong l\214nh b\181i ho\198c b\202m l\185i Alt+A.")
end

function PTLB_StopAuto(token)
	PTLB_Cmd(2)
	Msg2Player(token .. ": \174\183 g\246i l\214nh d\245ng t\249 \174\233ng \174\184nh.")
end

function PTLB_PrefText()
	if GetTask(PTLB_T_PREF) == 0 then return "T\249 b\203t t\249 \174\184nh khi ch\228n b\233: \167ANG B\203T" end
	return "T\249 b\203t t\249 \174\184nh khi ch\228n b\233: \167ANG T\190T"
end

function PTLB_TogglePref()
	if GetTask(PTLB_T_PREF) == 0 then SetTask(PTLB_T_PREF, 1) else SetTask(PTLB_T_PREF, 0) end
end

-- learnt skills of group g of table t, in table order: { index in the table, ... }
function PTLB_GroupList(t, g)
	local r = {}
	local i = 1
	while i <= t.n do
		if t[i].grp == g and PTLB_Learnt(t[i].id) then tinsert(r, i) end
		i = i + 1
	end
	return r
end

-- "a trong b": skills of group g switched on / learnt
function PTLB_GroupCount(t, v, g)
	local l = PTLB_GroupList(t, g)
	local on = 0
	local i = 1
	while l[i] do
		if PTLB_Has(t, v, t[l[i]].id) then on = on + 1 end
		i = i + 1
	end
	return on .. " trong " .. getn(l)
end

-- number of learnt skills of the set, and of them the attack skills
function PTLB_Count(t, v)
	local n = 0
	local a = 0
	local i = 1
	while i <= t.n do
		local s = t[i]
		if PTLB_Has(t, v, s.id) and PTLB_Learnt(s.id) then
			n = n + 1
			if s.kind == 1 then a = a + 1 end
		end
		i = i + 1
	end
	return n, a
end

-- short text of the learnt skills of a Dao Si set: "Tho 3, Hoa 2, Bang 4 + buff 1"
function PTLB_DescDS(v)
	if v < PTLB_FLAG then return "theo ph\221m \174ang g\184n" end
	local c = { 0, 0, 0, 0 }
	local b = 0
	local i = 1
	while i <= PTLB_DS.n do
		local s = PTLB_DS[i]
		if PTLB_Has(PTLB_DS, v, s.id) and PTLB_Learnt(s.id) then
			if s.kind == 1 then c[s.el] = c[s.el] + 1 else b = b + 1 end
		end
		i = i + 1
	end
	local r = ""
	local k = { 4, 2, 1, 3 }
	i = 1
	while i <= 4 do
		if c[k[i]] > 0 then
			if r ~= "" then r = r .. ", " end
			r = r .. PTLB_EL[k[i]] .. " " .. c[k[i]]
		end
		i = i + 1
	end
	if r == "" then r = "ch\173a c\227 chi\170u \174\184nh \174\183 h\228c (d\239ng ph\221m)" end
	if b > 0 then r = r .. " + buff " .. b end
	return r
end

function PTLB_DescGS(v)
	if v < PTLB_FLAG then return "theo ph\221m \174ang g\184n" end
	local c = { 0, 0 }
	local b = 0
	local i = 1
	while i <= PTLB_GS.n do
		local s = PTLB_GS[i]
		if PTLB_Has(PTLB_GS, v, s.id) and PTLB_Learnt(s.id) then
			if s.kind == 1 then c[s.el] = c[s.el] + 1 else b = b + 1 end
		end
		i = i + 1
	end
	local r = ""
	if c[1] > 0 then r = PTLB_BL[1] .. " " .. c[1] end
	if c[2] > 0 then
		if r ~= "" then r = r .. ", " end
		r = r .. PTLB_BL[2] .. " " .. c[2]
	end
	if r == "" then r = "ch\173a c\227 chi\170u \174\184nh \174\183 h\228c (d\239ng ph\221m)" end
	if b > 0 then r = r .. " + h\181o quang " .. b end
	return r
end

function PTLB_DescDN(v)
	if v < PTLB_FLAG then return "t\190t" end
	local r = ""
	local i = 1
	while i <= PTLB_DN.n do
		local s = PTLB_DN[i]
		if PTLB_Has(PTLB_DN, v, s.id) and PTLB_Learnt(s.id) then
			if r ~= "" then r = r .. ", " end
			r = r .. s.nm
		end
		i = i + 1
	end
	if r == "" then r = "ch\173a h\228c chi\170u n\181o trong b\233" end
	return r
end

PTLB_PEND_FILE = "lbdaosi_pending.txt"

function PTLB_PendPath()
	return (PTADM_DIR or "admin_bridge\\") .. PTLB_PEND_FILE
end

-- PTLB_PEND[name] = { [1] = Dao Si value or -1, [2] = Di Nhan value or -1 }
function PTLB_LoadPend()
	if PTLB_PEND then return end
	PTLB_PEND = {}
	local h = openfile(PTLB_PendPath(), "r")
	if not h then return end
	local l = read(h, "*l")
	while l do
		local a = strfind(l, "\t", 1, 1)
		local b = nil
		if a then b = strfind(l, "\t", a + 1, 1) end
		if a and b then
			local k = tonumber(strsub(l, 1, a - 1))
			local v = tonumber(strsub(l, a + 1, b - 1))
			local nm = strsub(l, b + 1)
			if k and v and k >= 1 and k <= 4 and nm ~= "" then
				if not PTLB_PEND[nm] then PTLB_PEND[nm] = { -1, -1, -1, -1 } end
				PTLB_PEND[nm][k] = v
			end
		end
		l = read(h, "*l")
	end
	closefile(h)
end

function PTLB_SavePend()
	local h = openfile(PTLB_PendPath(), "w")
	if not h then return end
	local nm, p = next(PTLB_PEND, nil)
	while nm do
		if p[1] >= 0 then write(h, "1\t" .. p[1] .. "\t" .. nm .. "\n") end
		local k = 2
		while k <= 4 do
			if (p[k] or -1) >= 0 then write(h, k .. "\t" .. p[k] .. "\t" .. nm .. "\n") end
			k = k + 1
		end
		nm, p = next(PTLB_PEND, nm)
	end
	closefile(h)
end

-- web admin (bridge): which 1 = Dao Si, 2 = Di Nhan, 3 = Giap Si; mask = sum 2^(id - base) (0 = keys / off).
-- Online: applied and sent now. Offline: kept for the next login (file survives a server restart).
function PTLB_AdminSet(id, name, which, mask)
	PTLB_Load()
	PTLB_LoadPend()
	local v = 0
	if mask and mask > 0 then v = PTLB_FLAG + mask end
	local task = PTLB_T_DS
	if which == 2 then task = PTLB_T_DN end
	if which == 3 then task = PTLB_T_GS end
	local pi = nil
	if PTAdm_FindPlayer then pi = PTAdm_FindPlayer(name) end
	if pi then
		PTLB_Apply(task, v)
		local d = nil
		if which == 2 then
			d = PTLB_DescDN(v)
			Msg2Player("Admin \174\198t L\214nh B\181i D\222 Nh\169n: t\249 duy tr\215 " .. d .. ".")
		elseif which == 3 then
			d = PTLB_DescGS(v)
			Msg2Player("Admin \174\198t L\214nh B\181i Gi\184p S\220: t\249 \174\184nh lu\169n phi\170n " .. d .. ".")
		else
			d = PTLB_DescDS(v)
			Msg2Player("Admin \174\198t L\214nh B\181i \167\185o S\220: t\249 \174\184nh lu\169n phi\170n " .. d .. ".")
		end
		if PTLB_PEND[name] then
			PTLB_PEND[name][which] = -1
			PTLB_SavePend()
		end
		if PTAdm_Log then PTAdm_Log(id, "OK", name .. " online: task " .. task .. " = " .. v .. " (prof " .. GetProfession() .. ")") end
		PlayerIndex = nil
		return 1
	end
	if not PTLB_PEND[name] then PTLB_PEND[name] = { -1, -1, -1, -1 } end
	PTLB_PEND[name][which] = v
	PTLB_SavePend()
	if PTAdm_Log then PTAdm_Log(id, "OK", "offline " .. name .. ": task " .. task .. " = " .. v .. " ap khi dang nhap") end
	return 0
end

-- current PlayerIndex: max skill sk of profession prof (0 = every skill of the profession). Returns ok, count, text.
function PTLB_DoMax(prof, sk)
	if GetProfession() ~= prof then return 0, 0, "profession " .. GetProfession() .. " ~= " .. prof end
	if sk == 0 then
		local ok, n = PTLB_MaxAll(prof)
		Msg2Player("Admin n\169ng t\232i \174a " .. ok .. " trong " .. n .. " k\252 n\168ng c\241a ph\184i.")
		return ok, n, "all " .. ok .. "/" .. n
	end
	local s = PTLB_FindPS(prof, sk)
	if not s then return 0, 1, "skill " .. sk .. " not of this profession / level" end
	local ok = PTLB_MaxOne(s)
	if ok > 0 then Msg2Player("Admin n\169ng " .. s.nm .. " l\170n c\202p " .. s.mx .. ".") end
	return ok, 1, "skill " .. sk .. " level " .. PTLB_Lv(sk)
end

-- web admin (bridge): max skills; online now, offline at the next login (kind 4: prof x 10000 + skill)
function PTLB_AdminMax(id, name, prof, sk)
	PTLB_Load()
	PTLB_LoadPend()
	local pi = nil
	if PTAdm_FindPlayer then pi = PTAdm_FindPlayer(name) end
	if pi then
		local ok, n, txt = PTLB_DoMax(prof, sk)
		local st = "FAIL"
		if n > 0 and ok == n then st = "OK" end
		if PTAdm_Log then PTAdm_Log(id, st, name .. " online: max " .. txt) end
		PlayerIndex = nil
		return 1
	end
	if not PTLB_PEND[name] then PTLB_PEND[name] = { -1, -1, -1, -1 } end
	PTLB_PEND[name][4] = prof * 10000 + sk
	PTLB_SavePend()
	if PTAdm_Log then PTAdm_Log(id, "OK", "offline " .. name .. ": max skill " .. sk .. " ap khi dang nhap") end
	return 0
end

-- current PlayerIndex: give the profession token once (1 when given now)
function PTLB_GiveOne(task, item, prof)
	if GetProfession() ~= prof or GetTask(task) ~= 0 then return 0 end
	local have = HaveNormalItem(6, 1, item, -1)
	if have and have > 0 then
		SetTask(task, 1)
		return 0
	end
	local r = AddNormalItem(6, 1, item, 1, 0, 0)
	if r and r > 0 then
		SetTask(task, 1)
		return 1
	end
	return 0
end

-- current PlayerIndex, name nm: pending admin set, gift, resend both tasks
function PTLB_TickOne(nm)
	local p = PTLB_PEND[nm]
	if p then
		if p[1] >= 0 then SetTask(PTLB_T_DS, p[1]) end
		if p[2] >= 0 then SetTask(PTLB_T_DN, p[2]) end
		if (p[3] or -1) >= 0 then SetTask(PTLB_T_GS, p[3]) end
		if (p[4] or -1) >= 0 then
			local ok, n, txt = PTLB_DoMax(floor(p[4] / 10000), mod(p[4], 10000))
			if PTAdm_Log then PTAdm_Log("lbdaosi", "OK", nm .. " pending max: " .. txt) end
		end
		PTLB_PEND[nm] = nil
		PTLB_SavePend()
		Msg2Player("Admin \174\183 \174\198t b\233 chi\170u L\214nh B\181i cho b\185n khi b\185n v\190ng m\198t: b\203t t\249 \174\184nh \174\211 d\239ng.")
		if PTAdm_Log then PTAdm_Log("lbdaosi", "OK", nm .. " pending set applied") end
	end
	if PTLB_GiveOne(PTLB_T_GDS, PTLB_ITEM_DS, 1) > 0 then
		Msg2Player("B\185n nh\203n \174\173\238c L\214nh B\181i \167\185o S\220: nh\202p ph\182i \174\211 ch\228n b\233 chi\170u Th\230 / H\225a / B\168ng / L\171i cho t\249 \174\184nh lu\169n phi\170n. D\239ng v\220nh vi\212n, kh\171ng m\202t.")
		if PTAdm_Log then PTAdm_Log("lbdaosi", "OK", nm .. " +Lenh Bai Dao Si") end
	end
	if PTLB_GiveOne(PTLB_T_GGS, PTLB_ITEM_GS, 0) > 0 then
		Msg2Player("B\185n nh\203n \174\173\238c L\214nh B\181i Gi\184p S\220: nh\202p ph\182i \174\211 ch\228n b\233 chi\170u \174o\182n \174ao, tr\173\234ng \174ao, h\181o quang cho t\249 \174\184nh lu\169n phi\170n, b\190t \174\199u, d\245ng t\249 \174\184nh v\181 n\169ng c\202p k\252 n\168ng. D\239ng v\220nh vi\212n, kh\171ng m\202t.")
		if PTAdm_Log then PTAdm_Log("lbdaosi", "OK", nm .. " +Lenh Bai Giap Si") end
	end
	if PTLB_GiveOne(PTLB_T_GDN, PTLB_ITEM_DN, 2) > 0 then
		Msg2Player("B\185n nh\203n \174\173\238c L\214nh B\181i D\222 Nh\169n: nh\202p ph\182i \174\211 ch\228n chi\170u h\231 tr\238 (h\181o quang, B\230 T\169m Ch\243, ch\243 nguy\210n) t\249 duy tr\215 khi t\249 \174\184nh. D\239ng v\220nh vi\212n, kh\171ng m\202t.")
		if PTAdm_Log then PTAdm_Log("lbdaosi", "OK", nm .. " +Lenh Bai Di Nhan") end
	end
	-- SetTask(t, GetTask(t)) turns an unset task into "0": the client then knows it is really 0
	PTLB_Apply(PTLB_T_DS, GetTask(PTLB_T_DS))
	PTLB_Apply(PTLB_T_DN, GetTask(PTLB_T_DN))
	PTLB_Apply(PTLB_T_GS, GetTask(PTLB_T_GS))
	PTLB_Apply(PTLB_T_CMD, GetTask(PTLB_T_CMD))
end

function PTLB_Tick()
	PTLB_Load()
	PTLB_LoadPend()
	local i = 1
	local max = PTADM_MAX_PLAYER or 0
	while i <= max do
		PlayerIndex = i
		local nm = GetName()
		if nm and nm ~= "" then PTLB_TickOne(nm) end
		i = i + 1
	end
	PlayerIndex = nil
end
