-- Phong Than "Lenh Bai Luyen Cong" (magicscript 61420, 2026-10-03, agent luyencong). Permanent, never consumed
-- (KItemList::ExecuteScript only calls main; this script never removes the item). Generated by
-- scratchpad\luyencong\gen.py - edit the generator, not this file. Doc: docs\features\lenh-bai-luyen-cong-phong-than-20261003.md
-- Right click: 20 leveling spots by level band (1-150), 4 pages of 5. Choosing one = NewWorld to a cell next to the
-- densest monster cluster of that band, then SetFightState(1). Row 1 "Bai hop cap nhat" = band of the current level;
-- "Ve thanh gan nhat" = nearest of 5 cities by WorldSet MapPos, at the VNG Chi Nam Phu arrival points.
-- Spot cells: monsters of spawn_<map>.lua (1014: original VNG Region_S records), cell walkable with its 8 neighbours
-- on the client grid and the server Region_S grid, no trap, >= 3 cells from a monster (scratchpad\luyencong\pick.py).
-- Only usable from field maps / cities (1001-1057, 1065, 1074-1078): never out of events, instances, Thien Lao.
-- Lua 4 / engine: one small statement per record (stack 120 slots), no top-level dofile, menus <= 7 rows.

PTLC_ITEM = 61420

function PTLC_Add(lo, hi, m, x, y, mlo, mhi, nm)
	local s = {}
	s.lo = lo
	s.hi = hi
	s.map = m
	s.x = x
	s.y = y
	s.mlo = mlo
	s.mhi = mhi
	s.nm = nm
	PTLC_N = PTLC_N + 1
	PTLC_S[PTLC_N] = s
end

function PTLC_City(k, m, x, y, nm)
	local c = {}
	c.map = m
	c.x = x
	c.y = y
	c.nm = nm
	PTLC_C[k] = c
end

-- { player level lo, hi, map, cell x, cell y (NewWorld units = mps / 32), monster level lo, hi, name }
function PTLC_Load()
	if PTLC_LOADED then return end
	PTLC_S = {}
	PTLC_N = 0
	PTLC_Add(1, 5, 1005, 1665, 3060, 3, 3, "S\239ng th\181nh")   -- [208,191] Sung thanh
	PTLC_Add(6, 9, 1006, 1725, 2862, 7, 7, "B\190c H\182i")   -- [215,178] Bac Hai
	PTLC_Add(10, 14, 1009, 1688, 3344, 12, 12, "T\169y C\171n L\171n")   -- [211,209] Tay Con Lon
	PTLC_Add(15, 19, 1014, 1337, 3250, 15, 15, "\167\229ng Quan")   -- [167,203] ong Quan
	PTLC_Add(20, 24, 1015, 1634, 3233, 20, 20, "M\185nh T\169n")   -- [204,202] Manh Tan
	PTLC_Add(25, 29, 1017, 1655, 3411, 25, 25, "K\250 S\172n")   -- [206,213] Ky Son
	PTLC_Add(30, 34, 1022, 1520, 3524, 30, 30, "Hoang m\185c")   -- [190,220] Hoang mac
	PTLC_Add(35, 39, 1024, 1748, 3344, 36, 38, "Phong Than sa m\185c")   -- [218,209] Phong Than sa mac
	PTLC_Add(40, 44, 1025, 1753, 3115, 43, 43, "L\244c Ch\169u")   -- [219,194] Luc Chau
	PTLC_Add(45, 49, 1026, 1507, 3119, 45, 45, "Sa M\185c ch\213t")   -- [188,194] Sa Mac chet
	PTLC_Add(50, 54, 1034, 1476, 2974, 54, 54, "\167\185i Phong")   -- [184,185] ai Phong
	PTLC_Add(55, 59, 1035, 1782, 3559, 56, 56, "\167\185i Th\185ch")   -- [222,222] ai Thach
	PTLC_Add(60, 64, 1043, 1450, 3427, 61, 61, "B\221ch Du t\199ng 2")   -- [181,214] Bich Du tang 2
	PTLC_Add(65, 69, 1047, 1467, 3123, 66, 68, "Kh\232n Ti\170n t\199ng 1")   -- [183,195] Khon Tien tang 1
	PTLC_Add(70, 74, 1048, 1524, 3052, 70, 70, "Kh\232n Ti\170n t\199ng 2")   -- [190,190] Khon Tien tang 2
	PTLC_Add(75, 79, 1050, 1594, 3090, 75, 77, "Kh\232n Ti\170n t\199ng 4")   -- [199,193] Khon Tien tang 4
	PTLC_Add(80, 84, 1053, 1612, 3607, 80, 80, "\167\185i H\182i")   -- [201,225] ai Hai
	PTLC_Add(85, 89, 1077, 1584, 3853, 85, 85, "L\173u Ba s\172n")   -- [198,240] Luu Ba son
	PTLC_Add(90, 94, 1056, 1771, 2955, 90, 92, "Ph\173\172ng Tr\173\238ng")   -- [221,184] Phuong Truong
	PTLC_Add(95, 150, 1078, 1756, 3166, 95, 95, "Kh\171ng Tang L\220nh")   -- [219,197] Khong Tang Linh
	PTLC_C = {}
	PTLC_City(1, 1002, 1608, 3196, "S\239ng Th\181nh doanh")
	PTLC_City(2, 1003, 1692, 3138, "Ng\228c H\173 cung")
	PTLC_City(3, 1020, 1452, 3086, "T\169y K\250")
	PTLC_City(4, 1021, 1723, 3075, "Tri\210u Ca")
	PTLC_City(5, 1052, 1541, 3190, "Di\170u Tr\215")
	-- nearest city per map (default 1 = Sung Thanh doanh)
	PTLC_T = {}
	PTLC_T[1003] = 2
	PTLC_T[1005] = 4
	PTLC_T[1006] = 4
	PTLC_T[1007] = 2
	PTLC_T[1008] = 2
	PTLC_T[1009] = 2
	PTLC_T[1010] = 3
	PTLC_T[1011] = 2
	PTLC_T[1013] = 4
	PTLC_T[1014] = 3
	PTLC_T[1017] = 2
	PTLC_T[1020] = 3
	PTLC_T[1021] = 4
	PTLC_T[1026] = 2
	PTLC_T[1027] = 4
	PTLC_T[1028] = 4
	PTLC_T[1029] = 5
	PTLC_T[1030] = 5
	PTLC_T[1031] = 4
	PTLC_T[1032] = 4
	PTLC_T[1033] = 4
	PTLC_T[1034] = 3
	PTLC_T[1035] = 2
	PTLC_T[1036] = 3
	PTLC_T[1037] = 4
	PTLC_T[1038] = 4
	PTLC_T[1039] = 4
	PTLC_T[1040] = 4
	PTLC_T[1041] = 2
	PTLC_T[1042] = 4
	PTLC_T[1043] = 3
	PTLC_T[1044] = 4
	PTLC_T[1045] = 3
	PTLC_T[1046] = 5
	PTLC_T[1052] = 5
	PTLC_T[1053] = 2
	PTLC_T[1054] = 4
	PTLC_T[1055] = 4
	PTLC_T[1056] = 4
	PTLC_T[1058] = 4
	PTLC_T[1059] = 4
	PTLC_T[1063] = 3
	PTLC_T[1065] = 5
	PTLC_T[1067] = 3
	PTLC_T[1071] = 2
	PTLC_T[1072] = 5
	PTLC_T[1073] = 2
	PTLC_T[1074] = 2
	PTLC_T[1075] = 2
	PTLC_T[1076] = 2
	PTLC_T[1077] = 2
	PTLC_T[1078] = 4
	PTLC_LOADED = 1
end

function PTLC_No()
end

function PTLC_Say(title, o)
	local n = getn(o)
	local t = { title, n }
	local k = 1
	while k <= n do t[k + 2] = o[k] k = k + 1 end
	call(Say, t)
end

-- map id of the player if the token may be used here, else nil
function PTLC_SrcOk()
	local m = GetWorldPos()
	if not m then return nil end
	if m >= 1001 and m <= 1057 then return m end
	if m == 1065 or (m >= 1074 and m <= 1078) then return m end
	return nil
end

function PTLC_Blocked()
	Say("<color=yellow>L\214nh B\181i Luy\214n C\171ng<color>: kh\171ng d\239ng \174\173\238c \235 b\182n \174\229 n\181y (s\249 ki\214n, ph\227 b\182n, chi\213n tr\173\234ng, Thi\170n Lao). H\183y ra b\182n \174\229 ngo\181i ho\198c v\210 th\181nh tr\173\237c.", 1, "\167\227ng/PTLC_No")
end

function PTLC_LvText(s)
	if s.mlo == s.mhi then return s.mlo .. "" end
	return s.mlo .. "-" .. s.mhi
end

-- index of the spot whose level band holds lv (bands are contiguous from 1)
function PTLC_Best(lv)
	local k = 1
	local i = 1
	while i <= PTLC_N do
		if PTLC_S[i].lo <= lv then k = i end
		i = i + 1
	end
	return k
end

function PTLC_Title(lv)
	return "<color=yellow>L\214nh B\181i Luy\214n C\171ng<color>: c\202p hi\214n t\185i " .. lv .. ". Ch\228n b\183i \174\211 d\222ch chuy\211n t\237i ngay ch\231 c\227 qu\184i (d\202u * = h\238p c\202p). \167\214 t\246 \174i theo s\207 r\234i \174i khi \174\230i b\182n \174\229, d\239ng l\214nh b\181i tri\214u h\229i g\228i l\185i."
end

function PTLC_Main()
	PTLC_Load()
	local lv = GetLevel()
	local s = PTLC_S[PTLC_Best(lv)]
	local o = {}
	o[1] = "B\183i h\238p c\202p nh\202t: " .. s.nm .. " (qu\184i " .. PTLC_LvText(s) .. ")/PTLC_GoBest"
	o[2] = "B\183i c\202p 1-24/PTLC_P1"
	o[3] = "B\183i c\202p 25-49/PTLC_P2"
	o[4] = "B\183i c\202p 50-74/PTLC_P3"
	o[5] = "B\183i c\202p 75-150/PTLC_P4"
	o[6] = "V\210 th\181nh g\199n nh\202t/PTLC_Town"
	o[7] = "\167\227ng/PTLC_No"
	PTLC_Say(PTLC_Title(lv), o)
end

function PTLC_Page(first, last)
	PTLC_Load()
	local lv = GetLevel()
	local b = PTLC_Best(lv)
	local o = {}
	local n = 0
	local i = first
	while i <= last and PTLC_S[i] do
		local s = PTLC_S[i]
		local t = "C\202p " .. s.lo .. "-" .. s.hi .. ": " .. s.nm .. " (qu\184i " .. PTLC_LvText(s) .. ")"
		if i == b then t = t .. " *" end
		n = n + 1
		o[n] = t .. "/PTLC_G" .. i
		i = i + 1
	end
	n = n + 1 o[n] = "Quay l\185i/PTLC_Main"
	n = n + 1 o[n] = "\167\227ng/PTLC_No"
	PTLC_Say(PTLC_Title(lv), o)
end

function PTLC_P1() PTLC_Page(1, 5) end
function PTLC_P2() PTLC_Page(6, 10) end
function PTLC_P3() PTLC_Page(11, 15) end
function PTLC_P4() PTLC_Page(16, 20) end

function PTLC_Go(k)
	PTLC_Load()
	local s = PTLC_S[k]
	if not s then return end
	if not PTLC_SrcOk() then PTLC_Blocked() return end
	local sw = SubWorldID2Idx(s.map)
	if not sw or sw < 0 then
		Msg2Player("B\182n \174\229 " .. s.nm .. " ch\173a \174\173\238c m\235 tr\170n m\184y ch\241.")
		return
	end
	local r = NewWorld(s.map, s.x, s.y)
	if r == 0 then
		Msg2Player("Kh\171ng d\222ch chuy\211n \174\173\238c t\237i " .. s.nm .. ".")
		return
	end
	SetFightState(1)
	Msg2Player("\167\183 t\237i b\183i luy\214n c\171ng " .. s.nm .. " [" .. floor(s.x / 8) .. "," .. floor(s.y / 16) .. "], qu\184i c\202p " .. PTLC_LvText(s) .. ".")
end

function PTLC_GoBest() PTLC_Load() PTLC_Go(PTLC_Best(GetLevel())) end
function PTLC_G1() PTLC_Go(1) end
function PTLC_G2() PTLC_Go(2) end
function PTLC_G3() PTLC_Go(3) end
function PTLC_G4() PTLC_Go(4) end
function PTLC_G5() PTLC_Go(5) end
function PTLC_G6() PTLC_Go(6) end
function PTLC_G7() PTLC_Go(7) end
function PTLC_G8() PTLC_Go(8) end
function PTLC_G9() PTLC_Go(9) end
function PTLC_G10() PTLC_Go(10) end
function PTLC_G11() PTLC_Go(11) end
function PTLC_G12() PTLC_Go(12) end
function PTLC_G13() PTLC_Go(13) end
function PTLC_G14() PTLC_Go(14) end
function PTLC_G15() PTLC_Go(15) end
function PTLC_G16() PTLC_Go(16) end
function PTLC_G17() PTLC_Go(17) end
function PTLC_G18() PTLC_Go(18) end
function PTLC_G19() PTLC_Go(19) end
function PTLC_G20() PTLC_Go(20) end

function PTLC_Town()
	PTLC_Load()
	local m = PTLC_SrcOk()
	if not m then PTLC_Blocked() return end
	local c = PTLC_C[PTLC_T[m] or 1]
	local r = NewWorld(c.map, c.x, c.y)
	if r == 0 then
		Msg2Player("Kh\171ng d\222ch chuy\211n \174\173\238c t\237i " .. c.nm .. ".")
		return
	end
	SetFightState(0)
	Msg2Player("\167\183 v\210 " .. c.nm .. ".")
end

function main(nItemIdx)
	PTLC_Main()
	return 0
end
