-- Phong Than 2026-10-04 (agent lenhbainv): give every character one "Lenh Bai Nhiem Vu" (magicscript 61430, task 2611)
-- and one "Lenh Bai Tiep Te Nhiem Vu" (magicscript 61431, task 2612). Called once a minute from
-- script\phongthan\newbie\starter_gear.lua (PTNB_NvTick, protected by PTAdm_Safe). No main(): dofile'd into the
-- servertimer state. Generated by scratchpad\lenhbainv\gen.py. The task is set only once the token exists (given
-- here, or already in bag / box, e.g. from the web admin), so the gift waits for the ptfix row and a free bag cell.
PTNV_GIVE = { { 61430, 2611 }, { 61431, 2612 } }
PTNV_GIVE_MSG = { "B\185n nh\203n \174\173\238c L\214nh B\181i Nhi\214m V\244: nh\202p ph\182i \174\211 ch\228n nhi\214m v\244 v\181 d\222ch chuy\211n t\237i ngay c\185nh NPC nh\203n/tr\182 nhi\214m v\244. D\239ng v\220nh vi\212n, kh\171ng m\202t.", "B\185n nh\203n \174\173\238c L\214nh B\181i Ti\213p T\213 Nhi\214m V\244: nh\202p ph\182i \174\211 nh\203n \174\241 v\203t ph\200m nhi\214m v\244 c\223n thi\213u c\241a b\173\237c \174ang l\181m. D\239ng v\220nh vi\212n, kh\171ng m\202t." }

-- current PlayerIndex: number of tokens given now
function PTNV_GiveOneToken(k)
	local it = PTNV_GIVE[k][1]
	local tk = PTNV_GIVE[k][2]
	if GetTask(tk) ~= 0 then return 0 end
	local have = HaveNormalItem(6, 1, it, -1)
	if have and have > 0 then
		SetTask(tk, 1)
		return 0
	end
	local r = AddNormalItem(6, 1, it, 1, 0, 0)
	if r and r > 0 then
		SetTask(tk, 1)
		Msg2Player(PTNV_GIVE_MSG[k])
		return 1
	end
	return 0
end

function PTNV_GiveTick()
	local i = 1
	local max = PTADM_MAX_PLAYER or 0
	while i <= max do
		PlayerIndex = i
		local nm = GetName()
		if nm and nm ~= "" then
			local n = PTNV_GiveOneToken(1) + PTNV_GiveOneToken(2)
			if n > 0 and PTAdm_Log then PTAdm_Log("lenhbainv", "OK", nm .. " +" .. n .. " Lenh Bai Nhiem Vu/Tiep Te") end
		end
		i = i + 1
	end
	PlayerIndex = nil
end

