-- Phong Than "Lenh Bai Nhiem Vu" (magicscript 61430, 2026-10-04, agent lenhbainv). Permanent, never consumed.
-- GENERATED by scratchpad\lenhbainv\gen.py - edit the generator. Doc: docs\features\lenh-bai-nhiem-vu-phong-than-20261004.md
-- Right click: "Nhiem vu dang lam" (chains whose task variables show a step in progress, with the NPC of that step)
-- and 5 groups of quest NPCs (newbie, main story, world, daily, events); choosing one = NewWorld next to the NPC.
-- Data + logic: nhiemvu_data.lua (dofile at call time, cwd = Server; no top-level dofile). Menus <= 7 rows.

PTNV_NOFN = "PTNV_No"
-- lenhbainv2: a ReLoadScript of this file also reloads the shared data on the next use
PTNV_LOADED = nil

function PTNV_Load()
	if PTNV_LOADED then return end
	dofile("script\\phongthan\\item\\nhiemvu_data.lua")
	if PTNV_Data then
		PTNV_Data()
		PTNV_LOADED = 1
	end
end

function PTNV_No()
end

PTNV_TM_TITLE = "<color=yellow>L\214nh B\181i Nhi\214m V\244<color>: ch\228n nh\227m nhi\214m v\244 r\229i ch\228n NPC, l\214nh b\181i \174\173a b\185n t\237i ngay c\185nh NPC \174\227. C\202p hi\214n t\185i "
PTNV_TM_CUR = "Nhi\214m v\244 \174ang l\181m"
PTNV_TM_NONE = "<color=yellow>L\214nh B\181i Nhi\214m V\244<color>: ch\173a th\202y nhi\214m v\244 n\181o \174ang l\181m (ho\198c \174\183 xong h\213t c\184c b\173\237c c\227 th\211 nh\203n bi\213t). H\183y nh\203n nhi\214m v\244 \235 c\184c NPC trong menu nh\227m."
PTNV_TM_CURTITLE = "<color=yellow>Nhi\214m v\244 \174ang l\181m<color>: ch\228n \174\211 xem b\173\237c hi\214n t\185i v\181 d\222ch chuy\211n t\237i NPC c\199n g\198p."
PTNV_TM_GOTO = "D\222ch chuy\211n t\237i "
PTNV_TM_NONPC = "B\173\237c n\181y kh\171ng c\227 NPC c\232 \174\222nh \174\211 d\222ch chuy\211n."
PTNV_TM_GOFARM = "T\237i b\183i qu\184i: "
PTNV_TM_GONPC = "T\237i NPC: "

function PTNV_Main()
	PTNV_Load()
	local a = PTNV_Active()
	local o = {}
	o[1] = PTNV_TM_CUR .. " (" .. a.n .. ")/PTNV_AP1"
	o[2] = PTNV_GR[2].title .. "/PTNV_GQ2"
	o[3] = PTNV_GR[3].title .. "/PTNV_GQ3"
	o[4] = PTNV_GR[4].title .. "/PTNV_GQ4"
	o[5] = PTNV_GR[5].title .. "/PTNV_GQ5"
	o[6] = PTNV_GR[6].title .. "/PTNV_GQ6"
	o[7] = PTNV_T_CLOSE .. "/PTNV_No"
	PTNV_Say(PTNV_TM_TITLE .. GetLevel() .. ".", o)
end

function PTNV_ActPage(p)
	PTNV_Load()
	local a = PTNV_Active()
	if a.n == 0 then
		Say(PTNV_TM_NONE, 2, PTNV_T_BACK .. "/main", PTNV_T_CLOSE .. "/PTNV_No")
		return
	end
	local first, last, more = PTNV_Span(a.n, p)
	local o = {}
	local n = 0
	local i = first
	while i <= last do
		local e = a[i]
		local s = PTNV_CH[e.c].title .. ": "
		local tg = PTNV_Target(e.r)
		if tg > 0 then s = s .. PTNV_DS[tg].nm else s = s .. e.r.txt end
		n = n + 1
		o[n] = PTNV_Clip(s, 58) .. "/PTNV_A" .. i
		i = i + 1
	end
	if more then n = n + 1 o[n] = PTNV_T_NEXT .. "/PTNV_AP" .. (p + 1) end
	if p > 1 then n = n + 1 o[n] = PTNV_T_BACK .. "/PTNV_AP" .. (p - 1)
	else n = n + 1 o[n] = PTNV_T_BACK .. "/main" end
	n = n + 1 o[n] = PTNV_T_CLOSE .. "/PTNV_No"
	PTNV_Say(PTNV_TM_CURTITLE, o)
end

function PTNV_Act(i)
	PTNV_Load()
	local a = PTNV_Active()
	local e = a[i]
	if not e then PTNV_ActPage(1) return end
	local o = {}
	local n = 0
	local s = PTNV_StepText(e)
	local tg = PTNV_Target(e.r)
	if tg > 0 then
		n = n + 1
		o[n] = PTNV_Clip(PTNV_TM_GOTO .. PTNV_DS[tg].nm, 58) .. "/PTNV_AG" .. i
		if e.r.farm and e.r.farm > 0 and e.r.farm ~= tg then
			n = n + 1
			o[n] = PTNV_Clip(PTNV_TM_GOFARM .. PTNV_DS[e.r.farm].nm, 58) .. "/PTNV_AF" .. i
		end
		if e.r.dest and e.r.dest > 0 and e.r.dest ~= tg then
			n = n + 1
			o[n] = PTNV_Clip(PTNV_TM_GONPC .. PTNV_DS[e.r.dest].nm, 58) .. "/PTNV_AN" .. i
		end
	else
		s = s .. " " .. PTNV_TM_NONPC
	end
	n = n + 1 o[n] = PTNV_TQ_DETAIL .. "/PTNV_AD" .. i
	n = n + 1 o[n] = PTNV_T_BACK .. "/PTNV_AP" .. (floor((i - 1) / 4) + 1)
	n = n + 1 o[n] = PTNV_T_CLOSE .. "/PTNV_No"
	PTNV_Say(PTNV_Clip(s, 500), o)
end

-- which: 1 = where the step sends the player now (PTNV_Target), 2 = bai quai, 3 = NPC
function PTNV_ActGo(i, which)
	PTNV_Load()
	local a = PTNV_Active()
	local e = a[i]
	if not e then return end
	local d = PTNV_Target(e.r)
	if which == 2 then d = e.r.farm end
	if which == 3 then d = e.r.dest end
	if d and d > 0 then PTNV_Go(d) end
end

PTNV_TQ_NPCS = "Danh s\184ch NPC theo m\232c c\202p"
PTNV_TQ_GTITLE = "<color=yellow>%s<color>: ch\228n nhi\214m v\244 \174\211 xem t\245ng b\173\237c ([>] \174ang l\181m)."
PTNV_TQ_QHINT = "<color>: [>] b\173\237c \174ang l\181m, [x] \174\183 xong. Ch\228n b\173\237c \174\211 xem chi ti\213t v\181 d\222ch chuy\211n."
PTNV_TQ_STEP = "B\173\237c "
PTNV_TQ_CUR = " (\174ang l\181m)"
PTNV_TQ_DONE = " (\174\183 xong)"
PTNV_TQ_TODO = " (ch\173a t\237i)"
PTNV_TQ_JOB = "Vi\214c c\199n l\181m: "
PTNV_TQ_F11 = "F11: "
PTNV_TQ_NPC = "NPC: "
PTNV_TQ_MOB = "Qu\184i: "
PTNV_TQ_LVQ = " c\202p "
PTNV_TQ_NEED = "C\199n: "
PTNV_TQ_HAVE = " c\227 "
PTNV_TQ_NEEDN = ", c\199n "
PTNV_TQ_FIGHT = "Ph\182i t\249 \174\184nh ho\198c t\249 l\181m (l\214nh b\181i kh\171ng thay \174\173\238c)."
PTNV_TQ_COND = "\167i\210u ki\214n: c\202p "
PTNV_TQ_CAMP = ", ph\184i "
PTNV_TQ_RW = "Th\173\235ng (theo F11): "
PTNV_TQ_MORE = "Ti\213p (trang "
PTNV_TQ_OF = " c\241a "
PTNV_TQ_GO = "D\222ch chuy\211n t\237i "
PTNV_TQ_LOCK = "Kh\227a: "
PTNV_TQ_OTHER = "(Chu\231i c\241a ph\184i kh\184c, ch\216 \174\211 xem.)"
PTNV_TQ_DETAIL = "Chi ti\213t t\245ng b\173\237c"
PTNV_TQ_NODYN = "\167i\211m c\244 th\211 do NPC giao khi nh\203n b\173\237c n\181y."
PTNV_TQ_CAMP0 = "Gi\184p S\220"
PTNV_TQ_CAMP1 = "\167\185o S\220"
PTNV_TQ_CAMP2 = "D\222 Nh\169n"

function PTNV_Ctx()
	if not PTNV_CX then PTNV_CX = {} end
	local n = GetName() or "?"
	local c = PTNV_CX[n]
	if not c then
		c = {}
		PTNV_CX[n] = c
	end
	return c
end

function PTNV_LoadDetail()
	if PTNV_F11 then return end
	dofile("script\\phongthan\\item\\nhiemvu_detail.lua")
	if PTNV_DetailData then PTNV_DetailData() end
	if not PTNV_F11 then PTNV_F11 = {} PTNV_RW = {} PTNV_MN = {} end
end

-- entries of group g for this player: quests of the group (own camp; main story: all camps, own first) + NPC list
function PTNV_GList(g)
	local camp = PTNV_Camp()
	local o = {}
	local n = 0
	local pass = 1
	while pass <= 2 do
		local q = 1
		while q <= PTNV_NQ do
			local Q = PTNV_Q[q]
			if Q.g == g then
				local mine = Q.cp < 0 or Q.cp == camp
				if (pass == 1 and mine) or (pass == 2 and not mine and Q.c == 20) then
					n = n + 1
					o[n] = q
				end
			end
			q = q + 1
		end
		pass = pass + 1
	end
	n = n + 1
	o[n] = 0
	o.n = n
	return o
end

function PTNV_GOpen(g)
	PTNV_Load()
	local c = PTNV_Ctx()
	c.g = g
	c.gp = 1
	PTNV_GPage()
end

function PTNV_GPage()
	PTNV_Load()
	local c = PTNV_Ctx()
	local t = PTNV_GList(c.g)
	local first, last, more = PTNV_Span(t.n, c.gp)
	local o = {}
	local n = 0
	local i = first
	while i <= last do
		local s = PTNV_TQ_NPCS
		if t[i] > 0 then
			local Q = PTNV_Q[t[i]]
			s = Q.title
			if PTNV_QCur(t[i]) > 0 then s = "[>] " .. s end
		end
		n = n + 1
		o[n] = PTNV_Clip(s, 60) .. "/PTNV_GE" .. (i - first + 1)
		i = i + 1
	end
	if more then n = n + 1 o[n] = PTNV_T_NEXT .. "/PTNV_GNX" end
	n = n + 1 o[n] = PTNV_T_BACK .. "/PTNV_GBK"
	n = n + 1 o[n] = PTNV_T_CLOSE .. "/PTNV_No"
	PTNV_Say("<color=yellow>" .. PTNV_GR[c.g].title .. PTNV_TQ_QHINT, o)
end

function PTNV_GE(i)
	PTNV_Load()
	local c = PTNV_Ctx()
	if not c.g then return end
	local t = PTNV_GList(c.g)
	local first = PTNV_Span(t.n, c.gp)
	local q = t[first + i - 1]
	if not q then return end
	if q == 0 then PTNV_Page(c.g, 1) return end
	c.from = "g"
	PTNV_QOpen(q)
end

function PTNV_GNX() local c = PTNV_Ctx() c.gp = (c.gp or 1) + 1 PTNV_GPage() end
function PTNV_GBK()
	local c = PTNV_Ctx()
	if c.gp and c.gp > 1 then c.gp = c.gp - 1 PTNV_GPage() else PTNV_Main() end
end

-- does step s (rows: real rows of the chain or pseudo rows) match the player's task variables now
function PTNV_SMatch(s, camp, lv)
	local j = 1
	while j <= s.rows.n do
		if PTNV_Match(s.rows[j], camp, lv) then return 1 end
		j = j + 1
	end
	return nil
end

-- current step index of quest q (0 = none / other camp); second result 1 = every step done
function PTNV_QCur(q)
	local Q = PTNV_Q[q]
	local camp = PTNV_Camp()
	if Q.cp >= 0 and Q.cp ~= camp then return 0, nil end
	local lv = GetLevel()
	local k = 1
	while k <= Q.n do
		if PTNV_SMatch(Q.s[k], camp, lv) then return k, nil end
		k = k + 1
	end
	if Q.var and Q.var > 0 and GetTask(Q.var) > Q.maxhi then return 0, 1 end
	return 0, nil
end

function PTNV_QOpen(q)
	PTNV_Load()
	local c = PTNV_Ctx()
	c.q = q
	local Q = PTNV_Q[q]
	local cur = PTNV_QCur(q)
	local p = 1
	if cur > 0 then
		while 1 do
			local first, last, more = PTNV_Span(Q.n, p)
			if cur <= last or not more then break end
			p = p + 1
		end
	end
	c.qp = p
	PTNV_QPage()
end

function PTNV_QPage()
	PTNV_Load()
	local c = PTNV_Ctx()
	local Q = PTNV_Q[c.q]
	local cur, all = PTNV_QCur(c.q)
	local first, last, more = PTNV_Span(Q.n, c.qp)
	local o = {}
	local n = 0
	local k = first
	while k <= last do
		local s = Q.s[k]
		local mk = "[ ] "
		if k == cur then mk = "[>] " elseif all or (cur > 0 and k < cur) then mk = "[x] " end
		local tail = ""
		if s.lv > 0 then tail = " (" .. s.lv .. ")" end
		n = n + 1
		o[n] = PTNV_Clip(mk .. k .. ". " .. s.txt, 62 - strlen(tail)) .. tail .. "/PTNV_QE" .. (k - first + 1)
		k = k + 1
	end
	if more then n = n + 1 o[n] = PTNV_T_NEXT .. "/PTNV_QN" end
	n = n + 1 o[n] = PTNV_T_BACK .. "/PTNV_QB"
	n = n + 1 o[n] = PTNV_T_CLOSE .. "/PTNV_No"
	PTNV_Say("<color=yellow>" .. Q.title .. PTNV_TQ_QHINT, o)
end

function PTNV_QE(i)
	local c = PTNV_Ctx()
	if not c.q then return end
	PTNV_Load()
	local Q = PTNV_Q[c.q]
	local first = PTNV_Span(Q.n, c.qp)
	local k = first + i - 1
	if k > Q.n then return end
	PTNV_SDOpen(c.q, k)
end

function PTNV_QN() local c = PTNV_Ctx() c.qp = (c.qp or 1) + 1 PTNV_QPage() end
function PTNV_QB()
	local c = PTNV_Ctx()
	if c.qp and c.qp > 1 then c.qp = c.qp - 1 PTNV_QPage() return end
	if c.from == "g" and c.g then PTNV_GPage() else PTNV_Main() end
end

-- destinations offered for step k of quest q: static targets + the target of the matching row / custom row
function PTNV_STargets(q, k)
	local Q = PTNV_Q[q]
	local s = Q.s[k]
	local o = {}
	local n = 0
	local camp = PTNV_Camp()
	local lv = GetLevel()
	local dy = 0
	if s.dyn == "row" then
		local j = 1
		while j <= s.rows.n and dy == 0 do
			if PTNV_Match(s.rows[j], camp, lv) then dy = PTNV_Target(s.rows[j]) end
			j = j + 1
		end
	elseif s.dyn then
		local f = getglobal(s.dyn)
		local r = f and f(camp, lv)
		if r and PTNV_SMatch(s, camp, lv) then dy = PTNV_Target(r) end
	end
	if dy and dy > 0 then n = n + 1 o[n] = dy end
	local j = 1
	while j <= s.t.n and n < 4 do
		if s.t[j] ~= dy then n = n + 1 o[n] = s.t[j] end
		j = j + 1
	end
	o.n = n
	return o
end

-- append text s to line list L, wrapped at spaces into lines of at most 100 bytes
function PTNV_Wrap(L, s)
	while strlen(s) > 100 do
		local cut = 100
		while cut > 40 and strsub(s, cut, cut) ~= " " do cut = cut - 1 end
		L.n = L.n + 1
		L[L.n] = strsub(s, 1, cut)
		s = strsub(s, cut + 1)
	end
	L.n = L.n + 1
	L[L.n] = s
end

function PTNV_Pos(d)
	local mn = PTNV_MN[d.map] or ("" .. d.map)
	return " - " .. mn .. " " .. floor(d.nx / 8) .. "." .. floor(d.ny / 16)
end

function PTNV_DLines(q, k)
	PTNV_LoadDetail()
	local Q = PTNV_Q[q]
	local s = Q.s[k]
	local L = {}
	L.n = 0
	local cur, all = PTNV_QCur(q)
	local st = PTNV_TQ_TODO
	if k == cur then st = PTNV_TQ_CUR elseif all or (cur > 0 and k < cur) then st = PTNV_TQ_DONE end
	if Q.cp >= 0 and Q.cp ~= PTNV_Camp() then st = " " .. PTNV_TQ_OTHER end
	PTNV_Wrap(L, Q.title .. " - " .. PTNV_TQ_STEP .. k .. "/" .. Q.n .. st)
	PTNV_Wrap(L, PTNV_TQ_JOB .. s.txt)
	local f = PTNV_F11[q * 1000 + k]
	if f then PTNV_Wrap(L, PTNV_TQ_F11 .. f) end
	local t = PTNV_STargets(q, k)
	local j = 1
	while j <= t.n do
		local d = PTNV_DS[t[j]]
		if d.kind == 1 then
			local x = PTNV_TQ_MOB .. d.nm
			if d.mlv and d.mlv > 0 then x = x .. PTNV_TQ_LVQ .. d.mlv end
			PTNV_Wrap(L, x .. PTNV_Pos(d))
		else
			PTNV_Wrap(L, PTNV_TQ_NPC .. d.nm .. PTNV_Pos(d))
		end
		if d.gate > 0 and not PTNV_Gate(d.gate) then PTNV_Wrap(L, PTNV_TQ_LOCK .. (PTNV_GATEMSG[d.gate] or "")) end
		j = j + 1
	end
	if t.n == 0 and s.dyn then PTNV_Wrap(L, PTNV_TQ_NODYN) end
	local IS = PTNV_IS[s.set]
	if s.set > 0 and IS then
		local r = {}
		r.set = s.set
		local nd = PTNV_Need(r)
		local i = 1
		while i <= nd.n do
			PTNV_Wrap(L, PTNV_TQ_NEED .. nd[i].it.nm .. PTNV_TQ_HAVE .. nd[i].have .. PTNV_TQ_NEEDN .. nd[i].it.n)
			i = i + 1
		end
	end
	if s.kill == 1 then PTNV_Wrap(L, PTNV_TQ_FIGHT) end
	local cd = PTNV_TQ_COND .. s.lv
	if Q.cp >= 0 then cd = cd .. PTNV_TQ_CAMP .. getglobal("PTNV_TQ_CAMP" .. Q.cp) end
	PTNV_Wrap(L, cd)
	if PTNV_RW[q] then PTNV_Wrap(L, PTNV_TQ_RW .. PTNV_RW[q]) end
	return L
end

-- detail pages: lines up to 420 bytes per page
function PTNV_DSplit(L)
	local P = {}
	P.n = 1
	P[1] = ""
	local i = 1
	while i <= L.n do
		local cur = P[P.n]
		if cur ~= "" and strlen(cur) + strlen(L[i]) + 7 > 420 then
			P.n = P.n + 1
			P[P.n] = L[i]
		elseif cur == "" then P[P.n] = L[i]
		else P[P.n] = cur .. "<enter>" .. L[i] end
		i = i + 1
	end
	return P
end

function PTNV_SDOpen(q, k)
	local c = PTNV_Ctx()
	c.q = q
	c.k = k
	c.dp = 1
	PTNV_DPage()
end

function PTNV_DPage()
	PTNV_Load()
	local c = PTNV_Ctx()
	local P = PTNV_DSplit(PTNV_DLines(c.q, c.k))
	if c.dp > P.n then c.dp = P.n end
	local o = {}
	local n = 0
	if c.dp < P.n then n = n + 1 o[n] = PTNV_TQ_MORE .. (c.dp + 1) .. PTNV_TQ_OF .. P.n .. ")/PTNV_DN" end
	local t = PTNV_STargets(c.q, c.k)
	local j = 1
	while j <= t.n do
		n = n + 1
		o[n] = PTNV_Clip(PTNV_TQ_GO .. PTNV_DS[t[j]].nm, 60) .. "/PTNV_DG" .. j
		j = j + 1
	end
	n = n + 1 o[n] = PTNV_T_BACK .. "/PTNV_DB"
	n = n + 1 o[n] = PTNV_T_CLOSE .. "/PTNV_No"
	PTNV_Say(P[c.dp], o)
end

function PTNV_DN() local c = PTNV_Ctx() c.dp = (c.dp or 1) + 1 PTNV_DPage() end
function PTNV_DB()
	local c = PTNV_Ctx()
	if c.q then
		local Q = PTNV_Q[c.q]
		local p = 1
		while 1 do
			local first, last, more = PTNV_Span(Q.n, p)
			if c.k <= last or not more then break end
			p = p + 1
		end
		c.qp = p
		PTNV_QPage()
	else PTNV_Main() end
end

function PTNV_DG(j)
	PTNV_Load()
	local c = PTNV_Ctx()
	if not c.q then return end
	local t = PTNV_STargets(c.q, c.k)
	if t[j] then PTNV_Go(t[j]) end
end

-- from Nhiem vu dang lam: the step of the active entry i
function PTNV_AD(i)
	PTNV_Load()
	local a = PTNV_Active()
	local e = a[i]
	if not e then return end
	local camp = PTNV_Camp()
	local lv = GetLevel()
	local q = 1
	while q <= PTNV_NQ do
		local Q = PTNV_Q[q]
		if Q.c == e.c and (Q.cp < 0 or Q.cp == camp) then
			local k = 1
			while k <= Q.n do
				local s = Q.s[k]
				local j = 1
				while j <= s.rows.n do
					if s.rows[j] == e.r then PTNV_Ctx().from = "a" PTNV_Ctx().q = q PTNV_SDOpen(q, k) return end
					j = j + 1
				end
				k = k + 1
			end
			k = PTNV_QCur(q)
			if k > 0 then PTNV_Ctx().from = "a" PTNV_SDOpen(q, k) return end
		end
		q = q + 1
	end
end

function PTNV_GQ2() PTNV_GOpen(2) end
function PTNV_GQ3() PTNV_GOpen(3) end
function PTNV_GQ4() PTNV_GOpen(4) end
function PTNV_GQ5() PTNV_GOpen(5) end
function PTNV_GQ6() PTNV_GOpen(6) end
function PTNV_GE1() PTNV_GE(1) end
function PTNV_QE1() PTNV_QE(1) end
function PTNV_GE2() PTNV_GE(2) end
function PTNV_QE2() PTNV_QE(2) end
function PTNV_GE3() PTNV_GE(3) end
function PTNV_QE3() PTNV_QE(3) end
function PTNV_GE4() PTNV_GE(4) end
function PTNV_QE4() PTNV_QE(4) end
function PTNV_GE5() PTNV_GE(5) end
function PTNV_QE5() PTNV_QE(5) end
function PTNV_DG1() PTNV_DG(1) end
function PTNV_DG2() PTNV_DG(2) end
function PTNV_DG3() PTNV_DG(3) end
function PTNV_DG4() PTNV_DG(4) end
function PTNV_AD1() PTNV_AD(1) end
function PTNV_AD2() PTNV_AD(2) end
function PTNV_AD3() PTNV_AD(3) end
function PTNV_AD4() PTNV_AD(4) end
function PTNV_AD5() PTNV_AD(5) end
function PTNV_AD6() PTNV_AD(6) end
function PTNV_AD7() PTNV_AD(7) end
function PTNV_AD8() PTNV_AD(8) end
function PTNV_AD9() PTNV_AD(9) end
function PTNV_AD10() PTNV_AD(10) end
function PTNV_AD11() PTNV_AD(11) end
function PTNV_AD12() PTNV_AD(12) end
function PTNV_AD13() PTNV_AD(13) end
function PTNV_AD14() PTNV_AD(14) end
function PTNV_AD15() PTNV_AD(15) end
function PTNV_AD16() PTNV_AD(16) end
function PTNV_AD17() PTNV_AD(17) end
function PTNV_AD18() PTNV_AD(18) end
function PTNV_AD19() PTNV_AD(19) end
function PTNV_AD20() PTNV_AD(20) end
function PTNV_AD21() PTNV_AD(21) end
function PTNV_AD22() PTNV_AD(22) end
function PTNV_AD23() PTNV_AD(23) end
function PTNV_AD24() PTNV_AD(24) end
function PTNV_AD25() PTNV_AD(25) end
function PTNV_AD26() PTNV_AD(26) end
function PTNV_AD27() PTNV_AD(27) end
function PTNV_AD28() PTNV_AD(28) end
function PTNV_AD29() PTNV_AD(29) end
function PTNV_AD30() PTNV_AD(30) end
function PTNV_AD31() PTNV_AD(31) end
function PTNV_AD32() PTNV_AD(32) end
function PTNV_AD33() PTNV_AD(33) end
function PTNV_AD34() PTNV_AD(34) end
function PTNV_AD35() PTNV_AD(35) end
function PTNV_AD36() PTNV_AD(36) end
function PTNV_AD37() PTNV_AD(37) end
function PTNV_AD38() PTNV_AD(38) end
function PTNV_AD39() PTNV_AD(39) end
function PTNV_AD40() PTNV_AD(40) end

function PTNV_P2_1() PTNV_Load() PTNV_Page(2, 1) end
function PTNV_P2_2() PTNV_Load() PTNV_Page(2, 2) end
function PTNV_P2_3() PTNV_Load() PTNV_Page(2, 3) end
function PTNV_P2_4() PTNV_Load() PTNV_Page(2, 4) end
function PTNV_P2_5() PTNV_Load() PTNV_Page(2, 5) end
function PTNV_P2_6() PTNV_Load() PTNV_Page(2, 6) end
function PTNV_P2_7() PTNV_Load() PTNV_Page(2, 7) end
function PTNV_P2_8() PTNV_Load() PTNV_Page(2, 8) end
function PTNV_P2_9() PTNV_Load() PTNV_Page(2, 9) end
function PTNV_P2_10() PTNV_Load() PTNV_Page(2, 10) end
function PTNV_P3_1() PTNV_Load() PTNV_Page(3, 1) end
function PTNV_P3_2() PTNV_Load() PTNV_Page(3, 2) end
function PTNV_P3_3() PTNV_Load() PTNV_Page(3, 3) end
function PTNV_P3_4() PTNV_Load() PTNV_Page(3, 4) end
function PTNV_P3_5() PTNV_Load() PTNV_Page(3, 5) end
function PTNV_P3_6() PTNV_Load() PTNV_Page(3, 6) end
function PTNV_P4_1() PTNV_Load() PTNV_Page(4, 1) end
function PTNV_P4_2() PTNV_Load() PTNV_Page(4, 2) end
function PTNV_P4_3() PTNV_Load() PTNV_Page(4, 3) end
function PTNV_P4_4() PTNV_Load() PTNV_Page(4, 4) end
function PTNV_P4_5() PTNV_Load() PTNV_Page(4, 5) end
function PTNV_P4_6() PTNV_Load() PTNV_Page(4, 6) end
function PTNV_P5_1() PTNV_Load() PTNV_Page(5, 1) end
function PTNV_P5_2() PTNV_Load() PTNV_Page(5, 2) end
function PTNV_P5_3() PTNV_Load() PTNV_Page(5, 3) end
function PTNV_P5_4() PTNV_Load() PTNV_Page(5, 4) end
function PTNV_P5_5() PTNV_Load() PTNV_Page(5, 5) end
function PTNV_P5_6() PTNV_Load() PTNV_Page(5, 6) end
function PTNV_P6_1() PTNV_Load() PTNV_Page(6, 1) end
function PTNV_P6_2() PTNV_Load() PTNV_Page(6, 2) end
function PTNV_AP1() PTNV_ActPage(1) end
function PTNV_AP2() PTNV_ActPage(2) end
function PTNV_AP3() PTNV_ActPage(3) end
function PTNV_AP4() PTNV_ActPage(4) end
function PTNV_AP5() PTNV_ActPage(5) end
function PTNV_AP6() PTNV_ActPage(6) end
function PTNV_AP7() PTNV_ActPage(7) end
function PTNV_AP8() PTNV_ActPage(8) end
function PTNV_AP9() PTNV_ActPage(9) end
function PTNV_AP10() PTNV_ActPage(10) end
function PTNV_AP11() PTNV_ActPage(11) end
function PTNV_A1() PTNV_Act(1) end
function PTNV_AG1() PTNV_ActGo(1, 1) end
function PTNV_AF1() PTNV_ActGo(1, 2) end
function PTNV_AN1() PTNV_ActGo(1, 3) end
function PTNV_A2() PTNV_Act(2) end
function PTNV_AG2() PTNV_ActGo(2, 1) end
function PTNV_AF2() PTNV_ActGo(2, 2) end
function PTNV_AN2() PTNV_ActGo(2, 3) end
function PTNV_A3() PTNV_Act(3) end
function PTNV_AG3() PTNV_ActGo(3, 1) end
function PTNV_AF3() PTNV_ActGo(3, 2) end
function PTNV_AN3() PTNV_ActGo(3, 3) end
function PTNV_A4() PTNV_Act(4) end
function PTNV_AG4() PTNV_ActGo(4, 1) end
function PTNV_AF4() PTNV_ActGo(4, 2) end
function PTNV_AN4() PTNV_ActGo(4, 3) end
function PTNV_A5() PTNV_Act(5) end
function PTNV_AG5() PTNV_ActGo(5, 1) end
function PTNV_AF5() PTNV_ActGo(5, 2) end
function PTNV_AN5() PTNV_ActGo(5, 3) end
function PTNV_A6() PTNV_Act(6) end
function PTNV_AG6() PTNV_ActGo(6, 1) end
function PTNV_AF6() PTNV_ActGo(6, 2) end
function PTNV_AN6() PTNV_ActGo(6, 3) end
function PTNV_A7() PTNV_Act(7) end
function PTNV_AG7() PTNV_ActGo(7, 1) end
function PTNV_AF7() PTNV_ActGo(7, 2) end
function PTNV_AN7() PTNV_ActGo(7, 3) end
function PTNV_A8() PTNV_Act(8) end
function PTNV_AG8() PTNV_ActGo(8, 1) end
function PTNV_AF8() PTNV_ActGo(8, 2) end
function PTNV_AN8() PTNV_ActGo(8, 3) end
function PTNV_A9() PTNV_Act(9) end
function PTNV_AG9() PTNV_ActGo(9, 1) end
function PTNV_AF9() PTNV_ActGo(9, 2) end
function PTNV_AN9() PTNV_ActGo(9, 3) end
function PTNV_A10() PTNV_Act(10) end
function PTNV_AG10() PTNV_ActGo(10, 1) end
function PTNV_AF10() PTNV_ActGo(10, 2) end
function PTNV_AN10() PTNV_ActGo(10, 3) end
function PTNV_A11() PTNV_Act(11) end
function PTNV_AG11() PTNV_ActGo(11, 1) end
function PTNV_AF11() PTNV_ActGo(11, 2) end
function PTNV_AN11() PTNV_ActGo(11, 3) end
function PTNV_A12() PTNV_Act(12) end
function PTNV_AG12() PTNV_ActGo(12, 1) end
function PTNV_AF12() PTNV_ActGo(12, 2) end
function PTNV_AN12() PTNV_ActGo(12, 3) end
function PTNV_A13() PTNV_Act(13) end
function PTNV_AG13() PTNV_ActGo(13, 1) end
function PTNV_AF13() PTNV_ActGo(13, 2) end
function PTNV_AN13() PTNV_ActGo(13, 3) end
function PTNV_A14() PTNV_Act(14) end
function PTNV_AG14() PTNV_ActGo(14, 1) end
function PTNV_AF14() PTNV_ActGo(14, 2) end
function PTNV_AN14() PTNV_ActGo(14, 3) end
function PTNV_A15() PTNV_Act(15) end
function PTNV_AG15() PTNV_ActGo(15, 1) end
function PTNV_AF15() PTNV_ActGo(15, 2) end
function PTNV_AN15() PTNV_ActGo(15, 3) end
function PTNV_A16() PTNV_Act(16) end
function PTNV_AG16() PTNV_ActGo(16, 1) end
function PTNV_AF16() PTNV_ActGo(16, 2) end
function PTNV_AN16() PTNV_ActGo(16, 3) end
function PTNV_A17() PTNV_Act(17) end
function PTNV_AG17() PTNV_ActGo(17, 1) end
function PTNV_AF17() PTNV_ActGo(17, 2) end
function PTNV_AN17() PTNV_ActGo(17, 3) end
function PTNV_A18() PTNV_Act(18) end
function PTNV_AG18() PTNV_ActGo(18, 1) end
function PTNV_AF18() PTNV_ActGo(18, 2) end
function PTNV_AN18() PTNV_ActGo(18, 3) end
function PTNV_A19() PTNV_Act(19) end
function PTNV_AG19() PTNV_ActGo(19, 1) end
function PTNV_AF19() PTNV_ActGo(19, 2) end
function PTNV_AN19() PTNV_ActGo(19, 3) end
function PTNV_A20() PTNV_Act(20) end
function PTNV_AG20() PTNV_ActGo(20, 1) end
function PTNV_AF20() PTNV_ActGo(20, 2) end
function PTNV_AN20() PTNV_ActGo(20, 3) end
function PTNV_A21() PTNV_Act(21) end
function PTNV_AG21() PTNV_ActGo(21, 1) end
function PTNV_AF21() PTNV_ActGo(21, 2) end
function PTNV_AN21() PTNV_ActGo(21, 3) end
function PTNV_A22() PTNV_Act(22) end
function PTNV_AG22() PTNV_ActGo(22, 1) end
function PTNV_AF22() PTNV_ActGo(22, 2) end
function PTNV_AN22() PTNV_ActGo(22, 3) end
function PTNV_A23() PTNV_Act(23) end
function PTNV_AG23() PTNV_ActGo(23, 1) end
function PTNV_AF23() PTNV_ActGo(23, 2) end
function PTNV_AN23() PTNV_ActGo(23, 3) end
function PTNV_A24() PTNV_Act(24) end
function PTNV_AG24() PTNV_ActGo(24, 1) end
function PTNV_AF24() PTNV_ActGo(24, 2) end
function PTNV_AN24() PTNV_ActGo(24, 3) end
function PTNV_A25() PTNV_Act(25) end
function PTNV_AG25() PTNV_ActGo(25, 1) end
function PTNV_AF25() PTNV_ActGo(25, 2) end
function PTNV_AN25() PTNV_ActGo(25, 3) end
function PTNV_A26() PTNV_Act(26) end
function PTNV_AG26() PTNV_ActGo(26, 1) end
function PTNV_AF26() PTNV_ActGo(26, 2) end
function PTNV_AN26() PTNV_ActGo(26, 3) end
function PTNV_A27() PTNV_Act(27) end
function PTNV_AG27() PTNV_ActGo(27, 1) end
function PTNV_AF27() PTNV_ActGo(27, 2) end
function PTNV_AN27() PTNV_ActGo(27, 3) end
function PTNV_A28() PTNV_Act(28) end
function PTNV_AG28() PTNV_ActGo(28, 1) end
function PTNV_AF28() PTNV_ActGo(28, 2) end
function PTNV_AN28() PTNV_ActGo(28, 3) end
function PTNV_A29() PTNV_Act(29) end
function PTNV_AG29() PTNV_ActGo(29, 1) end
function PTNV_AF29() PTNV_ActGo(29, 2) end
function PTNV_AN29() PTNV_ActGo(29, 3) end
function PTNV_A30() PTNV_Act(30) end
function PTNV_AG30() PTNV_ActGo(30, 1) end
function PTNV_AF30() PTNV_ActGo(30, 2) end
function PTNV_AN30() PTNV_ActGo(30, 3) end
function PTNV_A31() PTNV_Act(31) end
function PTNV_AG31() PTNV_ActGo(31, 1) end
function PTNV_AF31() PTNV_ActGo(31, 2) end
function PTNV_AN31() PTNV_ActGo(31, 3) end
function PTNV_A32() PTNV_Act(32) end
function PTNV_AG32() PTNV_ActGo(32, 1) end
function PTNV_AF32() PTNV_ActGo(32, 2) end
function PTNV_AN32() PTNV_ActGo(32, 3) end
function PTNV_A33() PTNV_Act(33) end
function PTNV_AG33() PTNV_ActGo(33, 1) end
function PTNV_AF33() PTNV_ActGo(33, 2) end
function PTNV_AN33() PTNV_ActGo(33, 3) end
function PTNV_A34() PTNV_Act(34) end
function PTNV_AG34() PTNV_ActGo(34, 1) end
function PTNV_AF34() PTNV_ActGo(34, 2) end
function PTNV_AN34() PTNV_ActGo(34, 3) end
function PTNV_A35() PTNV_Act(35) end
function PTNV_AG35() PTNV_ActGo(35, 1) end
function PTNV_AF35() PTNV_ActGo(35, 2) end
function PTNV_AN35() PTNV_ActGo(35, 3) end
function PTNV_A36() PTNV_Act(36) end
function PTNV_AG36() PTNV_ActGo(36, 1) end
function PTNV_AF36() PTNV_ActGo(36, 2) end
function PTNV_AN36() PTNV_ActGo(36, 3) end
function PTNV_A37() PTNV_Act(37) end
function PTNV_AG37() PTNV_ActGo(37, 1) end
function PTNV_AF37() PTNV_ActGo(37, 2) end
function PTNV_AN37() PTNV_ActGo(37, 3) end
function PTNV_A38() PTNV_Act(38) end
function PTNV_AG38() PTNV_ActGo(38, 1) end
function PTNV_AF38() PTNV_ActGo(38, 2) end
function PTNV_AN38() PTNV_ActGo(38, 3) end
function PTNV_A39() PTNV_Act(39) end
function PTNV_AG39() PTNV_ActGo(39, 1) end
function PTNV_AF39() PTNV_ActGo(39, 2) end
function PTNV_AN39() PTNV_ActGo(39, 3) end
function PTNV_A40() PTNV_Act(40) end
function PTNV_AG40() PTNV_ActGo(40, 1) end
function PTNV_AF40() PTNV_ActGo(40, 2) end
function PTNV_AN40() PTNV_ActGo(40, 3) end
function PTNV_G1() PTNV_Load() PTNV_Go(1) end
function PTNV_G2() PTNV_Load() PTNV_Go(2) end
function PTNV_G3() PTNV_Load() PTNV_Go(3) end
function PTNV_G4() PTNV_Load() PTNV_Go(4) end
function PTNV_G5() PTNV_Load() PTNV_Go(5) end
function PTNV_G6() PTNV_Load() PTNV_Go(6) end
function PTNV_G7() PTNV_Load() PTNV_Go(7) end
function PTNV_G8() PTNV_Load() PTNV_Go(8) end
function PTNV_G9() PTNV_Load() PTNV_Go(9) end
function PTNV_G10() PTNV_Load() PTNV_Go(10) end
function PTNV_G11() PTNV_Load() PTNV_Go(11) end
function PTNV_G12() PTNV_Load() PTNV_Go(12) end
function PTNV_G13() PTNV_Load() PTNV_Go(13) end
function PTNV_G14() PTNV_Load() PTNV_Go(14) end
function PTNV_G15() PTNV_Load() PTNV_Go(15) end
function PTNV_G16() PTNV_Load() PTNV_Go(16) end
function PTNV_G17() PTNV_Load() PTNV_Go(17) end
function PTNV_G18() PTNV_Load() PTNV_Go(18) end
function PTNV_G19() PTNV_Load() PTNV_Go(19) end
function PTNV_G20() PTNV_Load() PTNV_Go(20) end
function PTNV_G21() PTNV_Load() PTNV_Go(21) end
function PTNV_G22() PTNV_Load() PTNV_Go(22) end
function PTNV_G23() PTNV_Load() PTNV_Go(23) end
function PTNV_G24() PTNV_Load() PTNV_Go(24) end
function PTNV_G25() PTNV_Load() PTNV_Go(25) end
function PTNV_G26() PTNV_Load() PTNV_Go(26) end
function PTNV_G27() PTNV_Load() PTNV_Go(27) end
function PTNV_G28() PTNV_Load() PTNV_Go(28) end
function PTNV_G29() PTNV_Load() PTNV_Go(29) end
function PTNV_G30() PTNV_Load() PTNV_Go(30) end
function PTNV_G31() PTNV_Load() PTNV_Go(31) end
function PTNV_G32() PTNV_Load() PTNV_Go(32) end
function PTNV_G33() PTNV_Load() PTNV_Go(33) end
function PTNV_G34() PTNV_Load() PTNV_Go(34) end
function PTNV_G35() PTNV_Load() PTNV_Go(35) end
function PTNV_G36() PTNV_Load() PTNV_Go(36) end
function PTNV_G37() PTNV_Load() PTNV_Go(37) end
function PTNV_G38() PTNV_Load() PTNV_Go(38) end
function PTNV_G39() PTNV_Load() PTNV_Go(39) end
function PTNV_G40() PTNV_Load() PTNV_Go(40) end
function PTNV_G41() PTNV_Load() PTNV_Go(41) end
function PTNV_G42() PTNV_Load() PTNV_Go(42) end
function PTNV_G43() PTNV_Load() PTNV_Go(43) end
function PTNV_G44() PTNV_Load() PTNV_Go(44) end
function PTNV_G45() PTNV_Load() PTNV_Go(45) end
function PTNV_G46() PTNV_Load() PTNV_Go(46) end
function PTNV_G47() PTNV_Load() PTNV_Go(47) end
function PTNV_G48() PTNV_Load() PTNV_Go(48) end
function PTNV_G49() PTNV_Load() PTNV_Go(49) end
function PTNV_G50() PTNV_Load() PTNV_Go(50) end
function PTNV_G51() PTNV_Load() PTNV_Go(51) end
function PTNV_G52() PTNV_Load() PTNV_Go(52) end
function PTNV_G53() PTNV_Load() PTNV_Go(53) end
function PTNV_G54() PTNV_Load() PTNV_Go(54) end
function PTNV_G55() PTNV_Load() PTNV_Go(55) end
function PTNV_G56() PTNV_Load() PTNV_Go(56) end
function PTNV_G57() PTNV_Load() PTNV_Go(57) end
function PTNV_G58() PTNV_Load() PTNV_Go(58) end
function PTNV_G59() PTNV_Load() PTNV_Go(59) end
function PTNV_G60() PTNV_Load() PTNV_Go(60) end
function PTNV_G61() PTNV_Load() PTNV_Go(61) end
function PTNV_G62() PTNV_Load() PTNV_Go(62) end
function PTNV_G63() PTNV_Load() PTNV_Go(63) end
function PTNV_G64() PTNV_Load() PTNV_Go(64) end
function PTNV_G65() PTNV_Load() PTNV_Go(65) end
function PTNV_G66() PTNV_Load() PTNV_Go(66) end
function PTNV_G67() PTNV_Load() PTNV_Go(67) end
function PTNV_G68() PTNV_Load() PTNV_Go(68) end
function PTNV_G69() PTNV_Load() PTNV_Go(69) end
function PTNV_G70() PTNV_Load() PTNV_Go(70) end
function PTNV_G71() PTNV_Load() PTNV_Go(71) end
function PTNV_G72() PTNV_Load() PTNV_Go(72) end
function PTNV_G73() PTNV_Load() PTNV_Go(73) end
function PTNV_G74() PTNV_Load() PTNV_Go(74) end
function PTNV_G75() PTNV_Load() PTNV_Go(75) end
function PTNV_G76() PTNV_Load() PTNV_Go(76) end
function PTNV_G77() PTNV_Load() PTNV_Go(77) end
function PTNV_G78() PTNV_Load() PTNV_Go(78) end
function PTNV_G79() PTNV_Load() PTNV_Go(79) end
function PTNV_G80() PTNV_Load() PTNV_Go(80) end
function PTNV_G81() PTNV_Load() PTNV_Go(81) end
function PTNV_G82() PTNV_Load() PTNV_Go(82) end
function PTNV_G83() PTNV_Load() PTNV_Go(83) end
function PTNV_G84() PTNV_Load() PTNV_Go(84) end
function PTNV_G85() PTNV_Load() PTNV_Go(85) end
function PTNV_G86() PTNV_Load() PTNV_Go(86) end
function PTNV_G87() PTNV_Load() PTNV_Go(87) end
function PTNV_G88() PTNV_Load() PTNV_Go(88) end
function PTNV_G89() PTNV_Load() PTNV_Go(89) end
function PTNV_G90() PTNV_Load() PTNV_Go(90) end
function PTNV_G91() PTNV_Load() PTNV_Go(91) end
function PTNV_G92() PTNV_Load() PTNV_Go(92) end
function PTNV_G93() PTNV_Load() PTNV_Go(93) end
function PTNV_G94() PTNV_Load() PTNV_Go(94) end
function PTNV_G95() PTNV_Load() PTNV_Go(95) end
function PTNV_G96() PTNV_Load() PTNV_Go(96) end
function PTNV_G97() PTNV_Load() PTNV_Go(97) end
function PTNV_G98() PTNV_Load() PTNV_Go(98) end
function PTNV_G99() PTNV_Load() PTNV_Go(99) end
function PTNV_G100() PTNV_Load() PTNV_Go(100) end
function PTNV_G101() PTNV_Load() PTNV_Go(101) end
function PTNV_G102() PTNV_Load() PTNV_Go(102) end
function PTNV_G103() PTNV_Load() PTNV_Go(103) end
function PTNV_G104() PTNV_Load() PTNV_Go(104) end
function PTNV_G105() PTNV_Load() PTNV_Go(105) end
function PTNV_G106() PTNV_Load() PTNV_Go(106) end
function PTNV_G107() PTNV_Load() PTNV_Go(107) end
function PTNV_G108() PTNV_Load() PTNV_Go(108) end
function PTNV_G109() PTNV_Load() PTNV_Go(109) end
function PTNV_G110() PTNV_Load() PTNV_Go(110) end
function PTNV_G111() PTNV_Load() PTNV_Go(111) end
function PTNV_G112() PTNV_Load() PTNV_Go(112) end
function PTNV_G113() PTNV_Load() PTNV_Go(113) end
function PTNV_G114() PTNV_Load() PTNV_Go(114) end
function PTNV_G115() PTNV_Load() PTNV_Go(115) end
function PTNV_G116() PTNV_Load() PTNV_Go(116) end
function PTNV_G117() PTNV_Load() PTNV_Go(117) end
function PTNV_G118() PTNV_Load() PTNV_Go(118) end
function PTNV_G119() PTNV_Load() PTNV_Go(119) end
function PTNV_G120() PTNV_Load() PTNV_Go(120) end
function PTNV_G121() PTNV_Load() PTNV_Go(121) end
function PTNV_G122() PTNV_Load() PTNV_Go(122) end
function PTNV_G123() PTNV_Load() PTNV_Go(123) end
function PTNV_G124() PTNV_Load() PTNV_Go(124) end
function PTNV_G125() PTNV_Load() PTNV_Go(125) end
function PTNV_G126() PTNV_Load() PTNV_Go(126) end
function PTNV_G127() PTNV_Load() PTNV_Go(127) end
function PTNV_G128() PTNV_Load() PTNV_Go(128) end
function PTNV_G129() PTNV_Load() PTNV_Go(129) end
function PTNV_G130() PTNV_Load() PTNV_Go(130) end
function PTNV_G131() PTNV_Load() PTNV_Go(131) end
function PTNV_G132() PTNV_Load() PTNV_Go(132) end
function PTNV_G133() PTNV_Load() PTNV_Go(133) end
function PTNV_G134() PTNV_Load() PTNV_Go(134) end
function PTNV_G135() PTNV_Load() PTNV_Go(135) end
function PTNV_G136() PTNV_Load() PTNV_Go(136) end
function PTNV_G137() PTNV_Load() PTNV_Go(137) end
function PTNV_G138() PTNV_Load() PTNV_Go(138) end
function PTNV_G139() PTNV_Load() PTNV_Go(139) end
function PTNV_G140() PTNV_Load() PTNV_Go(140) end
function PTNV_G141() PTNV_Load() PTNV_Go(141) end
function PTNV_G142() PTNV_Load() PTNV_Go(142) end
function PTNV_G143() PTNV_Load() PTNV_Go(143) end
function PTNV_G144() PTNV_Load() PTNV_Go(144) end
function PTNV_G145() PTNV_Load() PTNV_Go(145) end
function PTNV_G146() PTNV_Load() PTNV_Go(146) end
function PTNV_G147() PTNV_Load() PTNV_Go(147) end
function PTNV_G148() PTNV_Load() PTNV_Go(148) end
function PTNV_G149() PTNV_Load() PTNV_Go(149) end
function PTNV_G150() PTNV_Load() PTNV_Go(150) end
function PTNV_G151() PTNV_Load() PTNV_Go(151) end
function PTNV_G152() PTNV_Load() PTNV_Go(152) end
function PTNV_G153() PTNV_Load() PTNV_Go(153) end
function PTNV_G154() PTNV_Load() PTNV_Go(154) end
function PTNV_G155() PTNV_Load() PTNV_Go(155) end
function PTNV_G156() PTNV_Load() PTNV_Go(156) end
function PTNV_G157() PTNV_Load() PTNV_Go(157) end
function PTNV_G158() PTNV_Load() PTNV_Go(158) end
function PTNV_G159() PTNV_Load() PTNV_Go(159) end
function PTNV_G160() PTNV_Load() PTNV_Go(160) end
function PTNV_G161() PTNV_Load() PTNV_Go(161) end
function PTNV_G162() PTNV_Load() PTNV_Go(162) end
function PTNV_G163() PTNV_Load() PTNV_Go(163) end
function PTNV_G164() PTNV_Load() PTNV_Go(164) end
function PTNV_G165() PTNV_Load() PTNV_Go(165) end
function PTNV_G166() PTNV_Load() PTNV_Go(166) end
function PTNV_G167() PTNV_Load() PTNV_Go(167) end
function PTNV_G168() PTNV_Load() PTNV_Go(168) end
function PTNV_G169() PTNV_Load() PTNV_Go(169) end
function PTNV_G170() PTNV_Load() PTNV_Go(170) end
function PTNV_G171() PTNV_Load() PTNV_Go(171) end
function PTNV_G172() PTNV_Load() PTNV_Go(172) end
function PTNV_G173() PTNV_Load() PTNV_Go(173) end
function PTNV_G174() PTNV_Load() PTNV_Go(174) end
function PTNV_G175() PTNV_Load() PTNV_Go(175) end
function PTNV_G176() PTNV_Load() PTNV_Go(176) end
function PTNV_G177() PTNV_Load() PTNV_Go(177) end
function PTNV_G178() PTNV_Load() PTNV_Go(178) end
function PTNV_G179() PTNV_Load() PTNV_Go(179) end
function PTNV_G180() PTNV_Load() PTNV_Go(180) end
function PTNV_G181() PTNV_Load() PTNV_Go(181) end
function PTNV_G182() PTNV_Load() PTNV_Go(182) end
function PTNV_G183() PTNV_Load() PTNV_Go(183) end
function PTNV_G184() PTNV_Load() PTNV_Go(184) end
function PTNV_G185() PTNV_Load() PTNV_Go(185) end
function PTNV_G186() PTNV_Load() PTNV_Go(186) end
function PTNV_G187() PTNV_Load() PTNV_Go(187) end
function PTNV_G188() PTNV_Load() PTNV_Go(188) end
function PTNV_G189() PTNV_Load() PTNV_Go(189) end
function PTNV_G190() PTNV_Load() PTNV_Go(190) end
function PTNV_G191() PTNV_Load() PTNV_Go(191) end
function PTNV_G192() PTNV_Load() PTNV_Go(192) end
function PTNV_G193() PTNV_Load() PTNV_Go(193) end
function PTNV_G194() PTNV_Load() PTNV_Go(194) end
function PTNV_G195() PTNV_Load() PTNV_Go(195) end
function PTNV_G196() PTNV_Load() PTNV_Go(196) end
function PTNV_G197() PTNV_Load() PTNV_Go(197) end
function PTNV_G198() PTNV_Load() PTNV_Go(198) end
function PTNV_G199() PTNV_Load() PTNV_Go(199) end
function PTNV_G200() PTNV_Load() PTNV_Go(200) end
function PTNV_G201() PTNV_Load() PTNV_Go(201) end
function PTNV_G202() PTNV_Load() PTNV_Go(202) end
function PTNV_G203() PTNV_Load() PTNV_Go(203) end
function PTNV_G204() PTNV_Load() PTNV_Go(204) end
function PTNV_G205() PTNV_Load() PTNV_Go(205) end
function PTNV_G206() PTNV_Load() PTNV_Go(206) end
function PTNV_G207() PTNV_Load() PTNV_Go(207) end
function PTNV_G208() PTNV_Load() PTNV_Go(208) end
function PTNV_G209() PTNV_Load() PTNV_Go(209) end
function PTNV_G210() PTNV_Load() PTNV_Go(210) end
function PTNV_G211() PTNV_Load() PTNV_Go(211) end
function PTNV_G212() PTNV_Load() PTNV_Go(212) end
function PTNV_G213() PTNV_Load() PTNV_Go(213) end
function PTNV_G214() PTNV_Load() PTNV_Go(214) end
function PTNV_G215() PTNV_Load() PTNV_Go(215) end
function PTNV_G216() PTNV_Load() PTNV_Go(216) end
function PTNV_G217() PTNV_Load() PTNV_Go(217) end
function PTNV_G218() PTNV_Load() PTNV_Go(218) end
function PTNV_G219() PTNV_Load() PTNV_Go(219) end
function PTNV_G220() PTNV_Load() PTNV_Go(220) end
function PTNV_G221() PTNV_Load() PTNV_Go(221) end
function PTNV_G222() PTNV_Load() PTNV_Go(222) end
function PTNV_G223() PTNV_Load() PTNV_Go(223) end
function PTNV_G224() PTNV_Load() PTNV_Go(224) end
function PTNV_G225() PTNV_Load() PTNV_Go(225) end
function PTNV_G226() PTNV_Load() PTNV_Go(226) end
function PTNV_G227() PTNV_Load() PTNV_Go(227) end
function PTNV_G228() PTNV_Load() PTNV_Go(228) end
function PTNV_G229() PTNV_Load() PTNV_Go(229) end
function PTNV_G230() PTNV_Load() PTNV_Go(230) end
function PTNV_G231() PTNV_Load() PTNV_Go(231) end
function PTNV_G232() PTNV_Load() PTNV_Go(232) end
function PTNV_G233() PTNV_Load() PTNV_Go(233) end
function PTNV_G234() PTNV_Load() PTNV_Go(234) end
function PTNV_G235() PTNV_Load() PTNV_Go(235) end
function PTNV_G236() PTNV_Load() PTNV_Go(236) end
function PTNV_G237() PTNV_Load() PTNV_Go(237) end
function PTNV_G238() PTNV_Load() PTNV_Go(238) end
function PTNV_G239() PTNV_Load() PTNV_Go(239) end
function PTNV_G240() PTNV_Load() PTNV_Go(240) end
function PTNV_G241() PTNV_Load() PTNV_Go(241) end
function PTNV_G242() PTNV_Load() PTNV_Go(242) end
function PTNV_G243() PTNV_Load() PTNV_Go(243) end
function PTNV_G244() PTNV_Load() PTNV_Go(244) end
function PTNV_G245() PTNV_Load() PTNV_Go(245) end
function PTNV_G246() PTNV_Load() PTNV_Go(246) end
function PTNV_G247() PTNV_Load() PTNV_Go(247) end
function PTNV_G248() PTNV_Load() PTNV_Go(248) end
function PTNV_G249() PTNV_Load() PTNV_Go(249) end
function PTNV_G250() PTNV_Load() PTNV_Go(250) end
function PTNV_G251() PTNV_Load() PTNV_Go(251) end
function PTNV_G252() PTNV_Load() PTNV_Go(252) end
function PTNV_G253() PTNV_Load() PTNV_Go(253) end
function PTNV_G254() PTNV_Load() PTNV_Go(254) end
function PTNV_G255() PTNV_Load() PTNV_Go(255) end
function PTNV_G256() PTNV_Load() PTNV_Go(256) end
function PTNV_G257() PTNV_Load() PTNV_Go(257) end
function PTNV_G258() PTNV_Load() PTNV_Go(258) end
function PTNV_G259() PTNV_Load() PTNV_Go(259) end
function PTNV_G260() PTNV_Load() PTNV_Go(260) end
function PTNV_G261() PTNV_Load() PTNV_Go(261) end
function PTNV_G262() PTNV_Load() PTNV_Go(262) end
function PTNV_G263() PTNV_Load() PTNV_Go(263) end
function PTNV_G264() PTNV_Load() PTNV_Go(264) end
function PTNV_G265() PTNV_Load() PTNV_Go(265) end
function PTNV_G266() PTNV_Load() PTNV_Go(266) end
function PTNV_G267() PTNV_Load() PTNV_Go(267) end
function PTNV_G268() PTNV_Load() PTNV_Go(268) end
function PTNV_G269() PTNV_Load() PTNV_Go(269) end
function PTNV_G270() PTNV_Load() PTNV_Go(270) end
function PTNV_G271() PTNV_Load() PTNV_Go(271) end
function PTNV_G272() PTNV_Load() PTNV_Go(272) end
function PTNV_G273() PTNV_Load() PTNV_Go(273) end
function PTNV_G274() PTNV_Load() PTNV_Go(274) end
function PTNV_G275() PTNV_Load() PTNV_Go(275) end
function PTNV_G276() PTNV_Load() PTNV_Go(276) end
function PTNV_G277() PTNV_Load() PTNV_Go(277) end
function PTNV_G278() PTNV_Load() PTNV_Go(278) end
function PTNV_G279() PTNV_Load() PTNV_Go(279) end
function PTNV_G280() PTNV_Load() PTNV_Go(280) end
function PTNV_G281() PTNV_Load() PTNV_Go(281) end
function PTNV_G282() PTNV_Load() PTNV_Go(282) end
function PTNV_G283() PTNV_Load() PTNV_Go(283) end
function PTNV_G284() PTNV_Load() PTNV_Go(284) end
function PTNV_G285() PTNV_Load() PTNV_Go(285) end
function PTNV_G286() PTNV_Load() PTNV_Go(286) end
function PTNV_G287() PTNV_Load() PTNV_Go(287) end
function PTNV_G288() PTNV_Load() PTNV_Go(288) end
function PTNV_G289() PTNV_Load() PTNV_Go(289) end
function PTNV_G290() PTNV_Load() PTNV_Go(290) end
function PTNV_G291() PTNV_Load() PTNV_Go(291) end
function PTNV_G292() PTNV_Load() PTNV_Go(292) end
function PTNV_G293() PTNV_Load() PTNV_Go(293) end
function PTNV_G294() PTNV_Load() PTNV_Go(294) end
function PTNV_G295() PTNV_Load() PTNV_Go(295) end
function PTNV_G296() PTNV_Load() PTNV_Go(296) end
function PTNV_G297() PTNV_Load() PTNV_Go(297) end
function PTNV_G298() PTNV_Load() PTNV_Go(298) end
function PTNV_G299() PTNV_Load() PTNV_Go(299) end
function PTNV_G300() PTNV_Load() PTNV_Go(300) end
function PTNV_G301() PTNV_Load() PTNV_Go(301) end
function PTNV_G302() PTNV_Load() PTNV_Go(302) end
function PTNV_G303() PTNV_Load() PTNV_Go(303) end
function PTNV_G304() PTNV_Load() PTNV_Go(304) end
function PTNV_G305() PTNV_Load() PTNV_Go(305) end
function PTNV_G306() PTNV_Load() PTNV_Go(306) end
function PTNV_G307() PTNV_Load() PTNV_Go(307) end
function PTNV_G308() PTNV_Load() PTNV_Go(308) end
function PTNV_G309() PTNV_Load() PTNV_Go(309) end
function PTNV_G310() PTNV_Load() PTNV_Go(310) end
function PTNV_G311() PTNV_Load() PTNV_Go(311) end
function PTNV_G312() PTNV_Load() PTNV_Go(312) end
function PTNV_G313() PTNV_Load() PTNV_Go(313) end
function PTNV_G314() PTNV_Load() PTNV_Go(314) end
function PTNV_G315() PTNV_Load() PTNV_Go(315) end
function PTNV_G316() PTNV_Load() PTNV_Go(316) end
function PTNV_G317() PTNV_Load() PTNV_Go(317) end
function PTNV_G318() PTNV_Load() PTNV_Go(318) end
function PTNV_G319() PTNV_Load() PTNV_Go(319) end
function PTNV_G320() PTNV_Load() PTNV_Go(320) end
function PTNV_G321() PTNV_Load() PTNV_Go(321) end
function PTNV_G322() PTNV_Load() PTNV_Go(322) end
function PTNV_G323() PTNV_Load() PTNV_Go(323) end
function PTNV_G324() PTNV_Load() PTNV_Go(324) end
function PTNV_G325() PTNV_Load() PTNV_Go(325) end
function PTNV_G326() PTNV_Load() PTNV_Go(326) end
function PTNV_G327() PTNV_Load() PTNV_Go(327) end
function PTNV_G328() PTNV_Load() PTNV_Go(328) end
function PTNV_G329() PTNV_Load() PTNV_Go(329) end
function PTNV_G330() PTNV_Load() PTNV_Go(330) end
function PTNV_G331() PTNV_Load() PTNV_Go(331) end
function PTNV_G332() PTNV_Load() PTNV_Go(332) end
function PTNV_G333() PTNV_Load() PTNV_Go(333) end
function PTNV_G334() PTNV_Load() PTNV_Go(334) end
function PTNV_G335() PTNV_Load() PTNV_Go(335) end
function PTNV_G336() PTNV_Load() PTNV_Go(336) end
function PTNV_G337() PTNV_Load() PTNV_Go(337) end
function PTNV_G338() PTNV_Load() PTNV_Go(338) end
function PTNV_G339() PTNV_Load() PTNV_Go(339) end
function PTNV_G340() PTNV_Load() PTNV_Go(340) end
function PTNV_G341() PTNV_Load() PTNV_Go(341) end
function PTNV_G342() PTNV_Load() PTNV_Go(342) end
function PTNV_G343() PTNV_Load() PTNV_Go(343) end
function PTNV_G344() PTNV_Load() PTNV_Go(344) end
function PTNV_G345() PTNV_Load() PTNV_Go(345) end
function PTNV_G346() PTNV_Load() PTNV_Go(346) end

function main(nItemIdx)
	PTNV_Main()
	return 0
end

