-- Phong Than 2026-10-05 (agent nuoithu): item 6/1/61550 "De Tu Linh Don" (ptfix extra_nuoithu.py). Right click:
-- the Di Nhan pet (petexp_lib.lua, level 1..10) gets 1000 exp; consumed only below level 10. Generated by
-- scratchpad\nuoithu\gen.py. Doc: docs\features\nuoi-thu-phong-than-20261005.md
Include("\\script\\phongthan\\item\\nuoithu_lib.lua")

function main(nItemIdx)
	return PTNT_UseDT(nItemIdx)
end
