-- Phong Than "Binh Noi Luc Vinh Cuu" (magicscript 61521, 2026-10-04, agent kytrancac). Generated by
-- scratchpad\kytrancac\gen_lua.py - edit the generator, not this file. Doc: docs\features\ky-tran-cac-da-quy-phong-than-20261004.md
-- Right click or quick bar key (1-0): Noi luc full (RestoreMana) at once. Permanent: KItemList::ExecuteScript only calls main and this
-- script never removes the item. Cooldown 2 s per character (GetGameTime loops, 18 per second; kept in this
-- script's own Lua state, so it resets when the server restarts). Refused while the character is dead / reviving.
-- Client auto fight (PhongThanAutoFight.inl, kytrancac:AF1) uses it from the quick bar every 2.5 s at most.
-- No top-level dofile (loose scripts are registered with cwd = their own folder).

PTVCMP_KEY = 61521
PTVCMP_CD = 36
if PTVCMP_LAST == nil then PTVCMP_LAST = {} end

function main(nItemIdx)
	local dead = 0
	if IsPlayerInDeath ~= nil then dead = IsPlayerInDeath() or 0 end
	local life = GetLife(0) or 0
	if dead == 1 or life <= 0 then
		Msg2Player("\167ang tr\228ng th\173\172ng, kh\171ng d\239ng \174\173\238c B\215nh N\233i L\249c V\220nh C\246u.")
		return 0
	end
	local nm = GetName() or ""
	local now = -1
	if GetGameTime ~= nil then now = GetGameTime() or -1 end
	local last = PTVCMP_LAST[nm]
	if now >= 0 and last ~= nil and now >= last and now - last < PTVCMP_CD then
		local left = 1
		if PTVCMP_CD - (now - last) > 18 then left = 2 end
		Msg2Player("B\215nh N\233i L\249c V\220nh C\246u \174ang h\229i, ch\234 th\170m " .. left .. " gi\169y.")
		return 0
	end
	RestoreMana()
	if now >= 0 then PTVCMP_LAST[nm] = now end
	return 0
end
