[Main]
Left=35
Top=543
Width=762
Height=55
Moveable=0
Trans=1
Image=\Spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ะยนคพ฿ฟ๒00.spr

Button0=Status
Button1=Items
Button2=Skills
Button3=Friend
Button4=PK
Button5=FSBook
Button6=Team
Button7=Quest
Button8=Faction
Button9=Help
Button10=System
Button11=PKTimer
Button12=LiftSkills
Interval=0
Speed=20
HideLeft=800
HideTop=543
PopupPos=3
DummyWnd=1


;ษ๚ป๎ผผฤÜฐดลฅ-ทโษ๑ึฎส้ฐดลฅฃฌษ๚ป๎ผผฤÜาฦถฏตฝฦไห๛ฮปึร 2024.03
[FSBook]
Left=110
Top=5
Image=\spr\ui4\zhu_jie_mian\gong_ju_lan_an_niu\fsbook00.spr
Width=50
Height=50
Trans=0
Up=0
Down=1
Over=1
OverFrame=2
Tip=$ Sธch Phong Thวn
ClassType=Player_FSBook


[LiftSkills]
Left=613
Top=5
Image=\Spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ษ๚ป๎ผผฤÜ00.spr
Trans=0
Up=0
Down=1
Over=1
OverFrame=2
Tip=ษ๚ป๎ผผฤÜ
ClassType=Player_Lvskill

[Status]
Left=48
Top=5
MaleImage=\Spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ืดฬฌฤะ00.spr
FemaleImage=\Spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ืดฬฌลฎ00.spr
Width=30
Height=50
Trans=0
Up=0
Down=1
Over=1
OverFrame=2
Tip=ืดฬฌ
ClassType=Player_Status

[Items]
Left=78
Top=5
Trans=0
Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ฮ๏ฦท00.spr
Up=0
Down=1
Over=1
OverFrame=2
Tip=ฮ๏ฦท
ClassType=Player_Items

[Skills]
Left=142
Top=5
Trans=0
Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ฮไนฆ00.spr
Up=0
Down=1
Over=1
OverFrame=2
Tip=ผผฤÜ
ClassType=Player_Skills
ฃปบรำัฐดลฅ=

[Friend]
Left=174
Top=5
Trans=0
Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\บรำั00.spr
Up=0
Down=1
Over=1
OverFrame=2
Tip=บรำั
ClassType=Player_Friend

[PK]
Left=206
Top=5
Trans=0
Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\pk00.spr
Up=0
Down=0
Over=1
OverFrame=2
CheckBox=0
Tip=Pk
ClassType=Player_PK
ItemCount=7
Color_0=255,0,0
ImgFile_0=\Spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\บ์00.spr
MenuText_0=ืิำษPKี๓ำช
Color_1=230,222,75
ImgFile_1=\Spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ปฦ00.spr
MenuText_1=น๚ผาPKี๓ำช
Color_2=130,217,255
ImgFile_2=\spr\ui4\zhu_jie_mian\gong_ju_lan_an_niu\lan_00.spr
MenuText_2=น๚ผาPKี๓ำช
Color_3=203,76,255
ImgFile_3=\Spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ืฯ00.spr
MenuText_3=น๚ผาPKี๓ำช
Color_4=209,170,110
ImgFile_4=\Spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ืุ00.spr
MenuText_4=น๚ผาPKี๓ำช
Color_5=76,198,99
ImgFile_5=\Spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ยฬ00.spr
MenuText_5=PKนุ
Color_6=255,128,0
ImgFile_6=\spr\ui4\zhu_jie_mian\gong_ju_lan_an_niu\cheng_00.spr
MenuText_6=น๚ีฝฤฃสฝี๓ำช

; [Ride]
; Left=613
; Top=5
; Trans=0
; Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ฦ๏ณห00.spr
; Up=0
; Down=1
; Over=1
; OverFrame=2
; CheckOver=1
; Tip=ื๘ฦ๏
; ClassType=Player_Ride

[Team]
Left=517
Top=5
Trans=0
Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ถำฮ้00.spr
Up=0
Down=1
Over=1
OverFrame=2
Tip=ถำฮ้
ClassType=Player_Team

[Quest]
Left=549
Top=5
Trans=0
Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ศฮฮ๑00.spr
Up=0
Down=1
Over=1
OverFrame=2
Tip=ศฮฮ๑
ClassType=Player_Quest

[Faction]
Left=581
Top=5
Trans=0
Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ฐ๏ลษ00.spr
Image_Clan=\spr\Ui4\ฟ็ทþน๚ีฝ\ผาืๅสฯืๅ00.spr
Up=0
Down=1
Over=1
OverFrame=2
Tip=น๚ผา
Tip_Clan=ผาืๅ/สฯืๅ
ClassType=Player_Faction

[Help]
Left=645
Top=5
Trans=0
Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ฐ๏ึ๚00.spr
Up=0
Down=1
Over=2
OverFrame=2
Tip=ฐ๏ึ๚
ClassType=Player_Help

[System]
Left=677
Top=5
Trans=0
Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\ฯตอณ00.spr
Up=0
Down=1
Over=2
OverFrame=2
Tip=ฯตอณ
ClassType=Player_System

[PKTimer]
Left=206
Top=5
Width=50
Height=50
ShadowColor=255,253,122
ShadowColorAlpha=80
ClassType=Player_PKTimer
DummyWnd=1
Image=\spr\Ui4\ึ๗ฝ็รๆ\นคพ฿ภธฐดลฅ\pk00.spr
Frame=0
ออออK(.๊ฤ?ออออออออออออหวีส[Main]=
ออออK(.??ออออออออออออ??[Main]=
ออออK(.๊?ออออออออออออฮ—ั[Main]=
ออออK(.๊อ?ออออออออออออิฦÞษ[Main]=
ออออK(.๊๖?ออออออออออออýฦ?[Main]=
ออออK(.??ออออออออออออ&?0?[Main]=
ออออK(.๊H?ออออออออออออO?Y?[Main]=
ออออK(.๊q?ออออออออออออx?ส[Main]=
ออออK(.๊?ออออออออออออกวซส[Main]=
ออออK(.๊ร?ออออออออออออสวิส[Main]=
ออออK(.๊์?ออออออออออออ๓วýส[Main]=
ออออK(.??ออออออออออออ?&?[Main]=
ออออK(.??ออออออออออออE?O?[Main]=
ออออK(.๊g?ออออออออออออn?x?[Main]=
ออออK(.๊?ออออออออออออ—ศกห[Main]=
ออออK(.๊น?ออออออออออออภศสห[Main]=
ออออK(.๊โ?ออออออออออออ้ศ๓ห[Main]=
ออออK(.๊คl%ออออออออออออซl%ตo%[Main]=
ออออK(.๊ l%อออออออออออองl%ฑo%[Main]=
ออออK(.๊ql%ออออออออออออxl%o%[Main]=
ออออK(.๊l%ออออออออออออกl%ซo%[Main]=
ออออK(.๊รl%ออออออออออออสl%ิo%[Main]=
ออออK(.๊แ…๚ออออออออออออ่…?๒?[Main]=
ออออK(.๊ฒ6ออออออออออออ??[Main]=
ออออK(.๊cYออออออออออออjYt\[Main]=
ออออK(.๊Yออออออออออออ“Y\[Main]=
ออออK(.๊ตYออออออออออออผYฦ\[Main]=
ออออK(.๊ÞYออออออออออออๅY๏\[Main]=
ออออK(.?ZออออออออออออZ][Main]=
ออออK(.?Zออออออออออออ7ZA][Main]=
ออออK(.๊YZออออออออออออ`Zj][Main]=
ออออK(.๊ZออออออออออออZ“][Main]=
ออออK(.๊ซZออออออออออออฒZผ][Main]=
ออออK(.๊ิZออออออออออออÛZๅ][Main]=
ออออK(.๊ýZออออออออออออ[^[Main]=
ออออK(.?[ออออออออออออ-[7^[Main]=
ออออK(.๊O[ออออออออออออV[`^[Main]=
ออออK(.๊x[ออออออออออออ[^[Main]=
ออออK(.๊ก[ออออออออออออจ[ฒ^[Main]=
ออออK(.๊ส[ออออออออออออั[Û^[Main]=
ออออK(.๊๓[ออออออออออออ๚[_[Main]=
ออออK(.?\ออออออออออออ#\-_[Main]=
ออออK(.๊E\ออออออออออออL\V_[Main]=
ออออK(.๊n\ออออออออออออu\_[Main]=
ออออK(.๊—\ออออออออออออ\จ_[Main]=
ออออK(.๊ภ\ออออออออออออว\ั_[Main]=
ออออK(.๊้\ออออออออออออ๐\๚_[Main]=
ออออK(.?]ออออออออออออ]#`[Main]=
ออออK(.?]ออออออออออออB]L`[Main]=
ออออK(.๊d]ออออออออออออk]u`[Main]=
ออออK(.๊]ออออออออออออ”]`[Main]=
ออออK(.๊ถ]ออออออออออออฝ]ว`[Main]=
ออออK(.๊฿]ออออออออออออๆ]๐`[Main]=
ออออK(.?^ออออออออออออ^a[Main]=
ออออK(.๊ัHCออออออออออออุHCโKC[Main]=
ออออK(.๊๚HCออออออออออออICLC[Main]=
ออออK(.?ICออออออออออออ*IC4LC[Main]=
ออออK(.๊LICออออออออออออSIC]LC[Main]=
ออออK(.๊uICออออออออออออ|ICLC[Main]=
ออออK(.๊nOออออออออออออuOO[Main]=
ออออK(.๊—Oออออออออออออ?OจO[Main]=
ออออK(.๊ภOออออออออออออ?OัO[Main]=
ออออK(.๊้Oออออออออออออ?O๚O[Main]=
ออออK(.?€Oออออออออออออ€O#O[Main]=

ออออK(.?€OออออออออออออB€OLO[Main]

