;-------------------------------------------
;分组好友窗口定义

;[GroupFriendWnd]
;Left=56
;Top=58
;Width=150
;Height=232
;Value=350
;WndName=好友分组界面
;Tip=$好友分组界面

[FriendTree_Branch]
Left=0
Top=0
Width=138
Height=24
Trans=1
UseParentClipRect=1

[FriendTree_Branch_OpenButton]
Left=0
Top=6
Width=17
Height=17
Up=0
Down=1
Image=\spr\Ui4\主界面\声望面板\类别+-.spr
UseParentClipRect=1

[FriendTree_Branch_NameText]
Left=21
Top=6
Width=76
Height=19
Font=14
HAlign=0
Color=255,255,255
Text=$好友分组
UseParentClipRect=1

[FriendTree_Branch_NameEdit]
Left=20
Top=6
Width=76
Height=14
Font=14
HAlign=0
Type=2
MaxLen=8
Color=216,252,160
BorderColor=0,0,0
UseParentClipRect=1

[FriendTree_Branch_Number]
Left=80
Top=6
Width=65
Height=19
Font=14
HAlign=0
Color=216,252,160
Text=$好友人数
UseParentClipRect=1

[FriendTree_Item]
Left=0
Top=2
Width=222
Height=0
Trans=1
UseParentClipRect=1

[FriendTree_Item_NameText]
Left=10
Top=2
Width=85
Height=14
Font=14
HAlign=0
Color=255,255,255
UseParentClipRect=1

[FriendTree_Item_MemberList]
;好友列表相对整个聊天界面
Left=-10
Top=0
Width=222
Height=0
ColumnCount=2           ;列数
ColumnWidth_0=200       ;列宽
ColumnWidth_1=25
ColumnFormat_0=1        ;没列的格式,0-2,对齐方式 
ColumnFormat_1=1
Font=14
Color=255,255,0
BorderColor=0,0,0
SelColor=255,255,0            ;点中时的颜色
SelBorderColor=0,255,0
SelItemBgColor=0,50,0      ;背景颜色 
HighLight=1             ;鼠标在上面时是否有颜色，0-1
HighLightColor=0,0,0
HighLightBorderColor=0,255,0
OfflineColor=0,135,133
InitLine=2		;刚打开时，的行数
NumLine=35,35		;好友窗口，改变大小时，允许的行数的范围（包括组行和好友行）
UseParentClipRect=1
