[Main]
Left=237
Top=150
Trans=0
Image=\spr\ui4\系统选项\离线修炼界面00.spr
GroupCount=3
CalculateWay=10

;combobox
[Group_0]
Left=51
Top=58
Width=117
Height=14
SelCount=2
SelText_0=$无
SelInfo_0=$    离线期间不会有任何和经验相关的修练。我们推荐你使用<color=green>八景日月丹<color>，这样在离线时，也可以<color=green>安全<color>进行经验修炼来获得<color=green>经验值<color>。
SelText_1=$八景日月丹
SelInfo_1=$    离线期间，每隔<color=green>1小时<color>进行一次经验修炼，在下次上线时获得<color=green>等级*小时*1200<color=green>经验值<color>，每天最多可进行4小时离线经验修炼。获得经验需要<color=green>八景日月丹<color>状态在下次登陆时存在，请注意目前状态剩余时间。

[Group_0_Btn]
Left=0
Top=0
Up=0
Down=1
Over=1
OverFrame=2
Image=\spr\ui4\系统选项\下拉条.spr

[Group_0_Edit]
Left=3
Top=0
Width=102
Height=14
Font=14
HAlign=0
;Color=255,217,78
Disable=1
Color=218,255,165
FocusBKColor=150,142,105
FocusBKColorAlpha=120

[Group_1]
Left=214
Top=58
Width=117
Height=14
SelCount=2
SelText_0=$无
SelInfo_0=$    离线期间不会有任何和采矿相关的修练。我们推荐你使用<color=green>八景蓝阳丹<color>，这样在离线时，也可以<color=green>安全<color>进行采矿来获得<color=green>蓝水晶碎片或蓝水晶<color>。
SelText_1=$八景蓝阳丹
SelInfo_1=$    离线期间，每隔<color=green>1小时<color>进行一次宝石锻造，在下次上线时获得<color=green>蓝水晶碎片或蓝水晶<color>，最多可累计离线4小时进行宝石锻造。使用此功能每小时消耗一次<color=green>八景蓝阳丹（请确认包裹空间足够）<color>。


[Group_1_Btn]
Left=0
Top=0
Up=0
Down=1
Over=1
OverFrame=2
Image=\spr\ui4\系统选项\下拉条.spr

[Group_1_Edit]
Left=3
Top=0
Width=102
Height=14
Font=14
HAlign=0
;Color=255,217,78
Disable=1
Color=218,255,165
FocusBKColor=150,142,105
FocusBKColorAlpha=120



[Group_2]
Left=50
Top=78
Width=117
Height=14
SelCount=2
SelText_0=$无
SelInfo_0=$    离线期间不会有任何和经验相关的修练。我们推荐你使用<color=green>八景太极丹<color>，这样在离线时，也可以<color=green>安全<color>进行技能修炼来获得<color=green>技能经验值<color>。
SelText_1=$八景太极丹
SelInfo_1=$    离线期间，每隔<color=green>1小时<color>进行一次右键技能修炼，在下次上线时获得<color=green>右键技能经验<color>，最多可累计离线4小时进行技能修炼。使用此功能每小时消耗一次<color=green>八景太极丹（请确认右键技能未达到等级上限）<color>。

[Group_2_Btn]
Left=0
Top=0
Up=0
Down=1
Over=1
OverFrame=2
Image=\spr\ui4\系统选项\下拉条.spr

[Group_2_Edit]
Left=3
Top=0
Width=102
Height=14
Font=14
HAlign=0
;Color=255,217,78
Disable=1
Color=218,255,165
FocusBKColor=150,142,105
FocusBKColorAlpha=120






[BtnConfirm]
Left=60
Top=197
Image=\Spr\Ui4\npc对话条\确定00.spr
Up=0
Down=1
Over=1
OverFrame=2


[BtnCancel]
Left=235
Top=197
Image=\Spr\Ui4\npc对话条\取消00.spr
Up=0
Down=1
Over=1
OverFrame=2

[TxtInfo]
Left=27
Top=104
Width=294
Height=75
Font=14
Color=202,230,171
MultiLine=1

[ChkSaveSetting]
Left=200
Top=178
Image=\spr\ui4\系统选项\记录本次退出方式.spr
Up=0
Down=1
CheckBox=1
CheckOver=1
