-- Phong Than 2026-10-04 (content E4): achievements board. Generated by scratchpad\content\gen_e4.py.
-- Loaded into the servertimer state by ext\thanhtich.lua (minute tick) and, at dialog time, into the Le Quan state
-- (sinhhoat\lq_npc.lua row "Bang thanh tich" -> PTAC_Menu). Counters are player tasks (each script has its own
-- Lua state, only tasks are shared); a task is written only once it becomes non-zero (255-value save limit):
--   2544 world bosses killed - polled here from wb_lib's PTWB_KILLER (same servertimer state; credited killer)
--   2545 daily jobs finished - delta of the daily2/daily3 *_DONE counters (2141/2143/2147/2151/2155/2311/2315),
--        last seen sum in 2546 (those counters reset every day: a smaller sum = new day)
--   newbie2 quests finished = task 2180 - 1 (PTNB2_T_Q, quest index), added to the chain category (not stored)
--   2549 highest Di Nhan pet level seen = task 2505 + 1 (petexp_lib)
--   2547 Van Tien entries: task 2003 (PTVT_T_SESSION, written by PTVT_Join) changed -> +1, key in 2551
--   2552 Thuong Chu entries: task 2340 (PTVC_T_ROUND, written by PTVC_Enter) changed -> +1, key in 2553
--   2548 monsters killed: npc_quests\normal.lua OnDeath wrapper (399 templates with the common death script)
--   2550 milestone tiers rewarded, decimal digit k = category k
-- Status admin_bridge\thanhtich.txt (web admin): one line per character seen since the file exists.
-- Lua 4, ASCII, TCVN3 as escapes.

PTAC_T_BOSS = 2544
PTAC_T_DAILY = 2545
PTAC_T_DSEEN = 2546
PTAC_T_VT = 2547
PTAC_T_KILL = 2548
PTAC_T_PETMAX = 2549
PTAC_T_CLAIM = 2550
PTAC_T_VTKEY = 2551
PTAC_T_TC = 2552
PTAC_T_TCKEY = 2553
PTAC_DAILY_TASKS = { 2141, 2143, 2147, 2151, 2155, 2311, 2315 }
PTAC_STATUS = "admin_bridge\\thanhtich.txt"
PTAC_MAX_PLAYER = 1200
PTAC_HEAD = "<color=green>B\182ng th\181nh t\221ch<color>: "
PTAC_CATS = {}
PTAC_CATS[1] = { key = "boss", name = "H\185 boss th\213 gi\237i", tiers = { 1, 5, 20, 50, 100 } }
PTAC_CATS[2] = { key = "chain", name = "Ho\181n th\181nh nhi\214m v\244 (t\169n th\241 + h\187ng ng\181y)", tiers = { 5, 20, 50, 100, 200 } }
PTAC_CATS[3] = { key = "pet", name = "C\202p \174\214 t\246 cao nh\202t", tiers = { 3, 5, 7, 9, 10 } }
PTAC_CATS[4] = { key = "vt", name = "V\181o V\185n Ti\170n tr\203n", tiers = { 1, 5, 20, 50, 100 } }
PTAC_CATS[5] = { key = "tc", name = "V\181o chi\213n tr\173\234ng Th\173\172ng Chu", tiers = { 1, 5, 20, 50, 100 } }
PTAC_CATS[6] = { key = "kill", name = "T\230ng qu\184i \174\183 h\185", tiers = { 500, 5000, 20000, 100000, 500000 } }
PTAC_REW = {}
PTAC_REW[1] = { money = 20000, g = 1, d = 2, p = 0, lv = 1, se = 0, n = 10, name = "\167\185i H\229ng \174\172n" }
PTAC_REW[2] = { money = 50000, g = 1, d = 5, p = 0, lv = 1, se = 0, n = 20, name = "\167\185i Ho\181n \174\172n" }
PTAC_REW[3] = { money = 100000, g = 3, d = 28, p = 0, lv = 0, se = 0, n = 3, name = "H\229ng Th\241y Tinh" }
PTAC_REW[4] = { money = 200000, g = 8, d = 142, p = 2, lv = 0, se = 0, n = 2, name = "Kh\171ng Th\173 (Ho\181ng)" }
PTAC_REW[5] = { money = 500000, g = 3, d = 79, p = 0, lv = 0, se = 0, n = 2, name = "H\229ng B\182o Th\185ch" }
if PTAC_WARN == nil then PTAC_WARN = {} end
if PTAC_TICKS == nil then PTAC_TICKS = 0 end

function PTAC_No() end

function PTAC_Pow10(k)
	local v = 1
	local i = 1
	while i < k do v = v * 10 i = i + 1 end
	return v
end

function PTAC_Add(t, n)
	if n and n > 0 then SetTask(t, GetTask(t) + n) end
end

function PTAC_Value(k)
	if k == 1 then return GetTask(PTAC_T_BOSS) end
	if k == 2 then
		local q = GetTask(2180) - 1
		if q < 0 then q = 0 end
		return GetTask(PTAC_T_DAILY) + q
	end
	if k == 3 then return GetTask(PTAC_T_PETMAX) end
	if k == 4 then return GetTask(PTAC_T_VT) end
	if k == 5 then return GetTask(PTAC_T_TC) end
	if k == 6 then return GetTask(PTAC_T_KILL) end
	return 0
end

-- update the polled counters of the current player
function PTAC_Poll()
	local s = 0
	local k = 1
	while PTAC_DAILY_TASKS[k] do
		s = s + GetTask(PTAC_DAILY_TASKS[k])
		k = k + 1
	end
	local seen = GetTask(PTAC_T_DSEEN)
	if s ~= seen then
		local d = s - seen
		if d < 0 then d = s end
		PTAC_Add(PTAC_T_DAILY, d)
		SetTask(PTAC_T_DSEEN, s)
	end
	if GetTask(2505) > 0 or GetTask(2506) > 0 then
		local lv = GetTask(2505) + 1
		if lv > GetTask(PTAC_T_PETMAX) then SetTask(PTAC_T_PETMAX, lv) end
	end
	local vk = GetTask(2003)
	if vk ~= 0 and vk ~= GetTask(PTAC_T_VTKEY) then
		SetTask(PTAC_T_VTKEY, vk)
		PTAC_Add(PTAC_T_VT, 1)
	end
	local tk = GetTask(2340)
	if tk ~= 0 and tk ~= GetTask(PTAC_T_TCKEY) then
		SetTask(PTAC_T_TCKEY, tk)
		PTAC_Add(PTAC_T_TC, 1)
	end
end

-- world bosses (servertimer state only): PTWB_KILLER[key] = killer name once per kill, nil again while alive
function PTAC_BossTick()
	if not PTWB_LIST or not PTWB_KILLER then return 0 end
	local first = nil
	if PTAC_BSEEN == nil then PTAC_BSEEN = {} first = 1 end
	local n = 0
	local k = 1
	while PTWB_LIST[k] do
		local key = PTWB_LIST[k].key
		local who = PTWB_KILLER[key]
		if not who or who == "" then
			PTAC_BSEEN[key] = nil
		elseif not PTAC_BSEEN[key] then
			PTAC_BSEEN[key] = 1
			if not first then
				local pi = GetPlayerIndexByName(who)
				if pi and pi > 0 then
					local old = PlayerIndex
					PlayerIndex = pi
					if GetName() == who then
						PTAC_Add(PTAC_T_BOSS, 1)
						Msg2Player("Th\181nh t\221ch: \174\183 h\185 boss th\213 gi\237i l\199n th\248 " .. GetTask(PTAC_T_BOSS) .. ".")
						n = n + 1
					end
					PlayerIndex = old
				end
			end
		end
		k = k + 1
	end
	return n
end

function PTAC_Tier(k)
	return mod(floor(GetTask(PTAC_T_CLAIM) / PTAC_Pow10(k)), 10)
end

-- reward every reached milestone of the current player; returns 1 when the bag was too full
function PTAC_Claim()
	local k = 1
	while PTAC_CATS[k] do
		local c = PTAC_CATS[k]
		local done = PTAC_Tier(k)
		while c.tiers[done + 1] and PTAC_Value(k) >= c.tiers[done + 1] do
			local r = PTAC_REW[done + 1]
			if CalcFreeItemCellCount() < 1 then return 1 end
			SetTask(PTAC_T_CLAIM, GetTask(PTAC_T_CLAIM) + PTAC_Pow10(k))
			done = done + 1
			if r.money > 0 then Earn(r.money) end
			local j = 1
			while j <= r.n do
				AddNormalItemPile(r.g, r.d, r.p, r.lv, r.se, 0)
				j = j + 1
			end
			Msg2Player(PTAC_HEAD .. "\167\185t m\232c th\181nh t\221ch " .. c.name .. " " .. c.tiers[done] .. ": nh\203n " .. r.money .. " l\173\238ng" .. ", " .. r.name .. " x" .. r.n .. ".")
		end
		k = k + 1
	end
	return 0
end

function PTAC_Line(nm)
	local s, pd, pb = 0, 0, 0
	local v = GetTask(2542)
	s = mod(v, 10) pd = mod(floor(v / 10), 10) pb = floor(v / 100)
	return nm .. "\t" .. (GetLevel() or 0) .. "\t" .. PTAC_Value(1) .. "\t" .. PTAC_Value(2) .. "\t" .. PTAC_Value(3) .. "\t" .. PTAC_Value(4)
		.. "\t" .. PTAC_Value(5) .. "\t" .. PTAC_Value(6) .. "\t" .. GetTask(PTAC_T_CLAIM) .. "\t" .. s .. "\t" .. GetTask(2543)
		.. "\t" .. GetTask(2541) .. "\t" .. pd .. "\t" .. pb .. "\t" .. date("%Y-%m-%d %H:%M")
end

function PTAC_LoadDb()
	PTAC_DB = {}
	local h = openfile(PTAC_STATUS, "r")
	if not h then return end
	local l = read(h, "*l")
	l = read(h, "*l")
	while l do
		local p = strfind(l, "\t", 1, 1)
		if p and p > 1 then PTAC_DB[strsub(l, 1, p - 1)] = l end
		l = read(h, "*l")
	end
	closefile(h)
end

function PTAC_WriteDb()
	local h = openfile(PTAC_STATUS .. ".tmp", "w")
	if not h then return end
	write(h, date("%Y-%m-%d %H:%M:%S") .. "\n")
	local k, v
	for k, v in PTAC_DB do write(h, v .. "\n") end
	closefile(h)
	remove(PTAC_STATUS)
	rename(PTAC_STATUS .. ".tmp", PTAC_STATUS)
end

function PTAC_Tick()
	PTAC_TICKS = PTAC_TICKS + 1
	if PTAC_DB == nil then PTAC_LoadDb() end
	PTAC_BossTick()
	local old = PlayerIndex
	local i = 1
	while i <= PTAC_MAX_PLAYER do
		PlayerIndex = i
		local nm = GetName()
		if nm and nm ~= "" then
			PTAC_Poll()
			if PTAC_Claim() == 1 then
				local w = PTAC_WARN[nm]
				if not w or PTAC_TICKS - w >= 30 then
					PTAC_WARN[nm] = PTAC_TICKS
					Msg2Player(PTAC_HEAD .. "\167\185t m\232c th\181nh t\221ch m\237i nh\173ng h\181nh trang \174\199y (c\199n 1 \171 tr\232ng). D\228n t\243i \174\211 nh\203n th\173\235ng.")
				end
			end
			PTAC_DB[nm] = PTAC_Line(nm)
		end
		i = i + 1
	end
	PlayerIndex = old
	PTAC_WriteDb()
end

-- Le Quan row "Bang thanh tich" (dialog of the current player)
function PTAC_Menu()
	PTAC_Poll()
	local full = PTAC_Claim()
	local t = PTAC_HEAD
	local k = 1
	while PTAC_CATS[k] do
		local c = PTAC_CATS[k]
		local done = PTAC_Tier(k)
		t = t .. "<enter>" .. c.name .. ": <color=yellow>" .. PTAC_Value(k) .. "<color>"
		if c.tiers[done + 1] then t = t .. " (m\232c k\213: " .. c.tiers[done + 1] .. ")" else t = t .. " (\174\183 \174\185t m\228i m\232c)" end
		k = k + 1
	end
	t = t .. "<enter>" .. "M\232c th\173\235ng: ti\210n v\181 v\203t ph\200m, t\249 nh\203n khi \174\185t (c\199n 1 \171 tr\232ng)."
	if full == 1 then t = t .. "<enter>" .. "\167\185t m\232c th\181nh t\221ch m\237i nh\173ng h\181nh trang \174\199y (c\199n 1 \171 tr\232ng). D\228n t\243i \174\211 nh\203n th\173\235ng." end
	Say(t, 1, "\167\227ng/PTAC_No")
end
