-- Phong Than 2026-10-04 (content E1): automatic event schedule. Generated by scratchpad\content\gen_e1.py.
-- Loaded into the servertimer state by ext\eventsched.lua (PTEXT_eventsched_Tick, protected, once a minute).
-- Rows (web admin tab "Lich su kien", admin_bridge\eventsched_config.lua):
--   { id, on, days = "0123456" (0 = Sunday, date("%w")), hh, mm, kind, arg, key, dur, title }
--   kind "vantien": PTVT_AdminOpen(arg) (tran 1-4, 0 = all four); "thuongchu": PTVC_ForceOpen() unless a round runs;
--   "boss": PTWB_SpawnKey(key); "exp": x2 monster exp for dur minutes (Bach Ho privilege, task 2021, topped up for
--   every online player once per event - task 2540 keeps which event a player already got).
-- News (AddGlobalNews): pre minutes before (default 5) and at the start. Firing window: start .. start+2 min, once a
-- day per row (key yyyymmdd kept in the state file, so a restart in the window never fires twice).
-- VNG schedules stay untouched: Van Tien (PTVT_SCHED) answers 2 = already open -> logged, nothing else; Thuong Chu
-- runs every hour 00-44 (vienco PTVC_HOURS) -> a row inside a running round is skipped ("busy").
-- Lua 4: no true/false, no local function; ASCII only, TCVN3 as escapes.

PTEV_CFG_FILE = "admin_bridge\\eventsched_config.lua"
PTEV_ST_FILE = "admin_bridge\\eventsched_state.lua"
PTEV_STATUS = "admin_bridge\\eventsched.txt"
PTEV_T_GOT = 2540
PTEV_MAX_PLAYER = 1200
PTEV_TAG = "<color=yellow>[L\222ch s\249 ki\214n]<color> "
PTEV_VTNAME = { "Th\230", "Th\241y", "H\225a", "Phong" }

function PTEV_Nop() end
function PTEV_Err(m) if PTAdm_TickErr then PTAdm_TickErr("eventsched: " .. tostring(m)) end end

function PTEV_Exists(p)
	local h = openfile(p, "r")
	if h then closefile(h) return 1 end
	return nil
end

function PTEV_LoadCfg()
	local old = PTEV_CFG
	PTEV_CFG = nil
	if PTEV_Exists(PTEV_CFG_FILE) then call(dofile, { PTEV_CFG_FILE }, "x", PTEV_Nop) end
	if type(PTEV_CFG) ~= "table" then
		if PTEV_Exists(PTEV_CFG_FILE) and old then PTEV_CFG = old else PTEV_CFG = { enabled = 0, rows = {} } end
		PTEV_SRC = "default"
	else
		PTEV_SRC = "file"
	end
	if type(PTEV_CFG.rows) ~= "table" then PTEV_CFG.rows = {} end
end

function PTEV_LoadState()
	PTEV_ST = nil
	if PTEV_Exists(PTEV_ST_FILE) then call(dofile, { PTEV_ST_FILE }, "x", PTEV_Nop) end
	if type(PTEV_ST) ~= "table" then PTEV_ST = {} end
	if type(PTEV_ST.fired) ~= "table" then PTEV_ST.fired = {} end
	if type(PTEV_ST.pre) ~= "table" then PTEV_ST.pre = {} end
	if type(PTEV_ST.res) ~= "table" then PTEV_ST.res = {} end
	if not PTEV_ST.expEnd then PTEV_ST.expEnd = 0 end
end

-- result texts are ASCII written by this file only; keep them free of quotes / backslashes
function PTEV_Clean(s)
	s = tostring(s or "")
	s = gsub(s, "[^%w%s%-%:%.%,%(%)%/%=%+_]", "")
	return s
end

function PTEV_SaveState()
	local h = openfile(PTEV_ST_FILE .. ".tmp", "w")
	if not h then return end
	write(h, "-- written by script\\phongthan\\content\\ev_lib.lua (content E1); do not edit while the server runs\n")
	write(h, "PTEV_ST = { expEnd = " .. (PTEV_ST.expEnd or 0) .. ", fired = {")
	local k, v
	for k, v in PTEV_ST.fired do write(h, " [" .. k .. "] = \"" .. v .. "\",") end
	write(h, " }, pre = {")
	for k, v in PTEV_ST.pre do write(h, " [" .. k .. "] = \"" .. v .. "\",") end
	write(h, " }, res = {")
	for k, v in PTEV_ST.res do write(h, " [" .. k .. "] = \"" .. PTEV_Clean(v) .. "\",") end
	write(h, " } }\n")
	closefile(h)
	remove(PTEV_ST_FILE)
	rename(PTEV_ST_FILE .. ".tmp", PTEV_ST_FILE)
end

function PTEV_DayOk(days, w)
	if type(days) ~= "string" or days == "" then return 1 end
	if strfind(days, tostring(w), 1, 1) then return 1 end
	return nil
end

function PTEV_Title(r)
	if type(r.title) == "string" and r.title ~= "" then return r.title end
	if r.kind == "vantien" then
		local n = tonumber(r.arg) or 0
		if PTEV_VTNAME[n] then return "V\185n Ti\170n tr\203n" .. " (" .. PTEV_VTNAME[n] .. ")" end
		return "V\185n Ti\170n tr\203n"
	elseif r.kind == "thuongchu" then return "Chi\213n tr\173\234ng Th\173\172ng Chu"
	elseif r.kind == "boss" then
		if PTWB_LIST then
			local k = 1
			while PTWB_LIST[k] do
				if PTWB_LIST[k].key == r.key then return "Boss th\213 gi\237i" .. " " .. PTWB_LIST[k].name end
				k = k + 1
			end
		end
		return "Boss th\213 gi\237i"
	elseif r.kind == "exp" then return "Nh\169n \174\171i kinh nghi\214m to\181n server"
	end
	return tostring(r.kind)
end

function PTEV_News(s)
	AddGlobalNews(PTEV_TAG .. s)
end

-- open one Van Tien tran; returns result code (1 opened, 2 already open, 0 failed)
function PTEV_OpenVt(n)
	if not PTVT_AdminOpen then dofile("script\\phongthan\\vantien\\vt_timer.lua") end
	if not PTVT_AdminOpen then return 0 end
	return PTVT_AdminOpen(n) or 0
end

-- returns announced (1 = the feature posted its own news), result text
function PTEV_Fire(r, now)
	local kind = r.kind
	if kind == "vantien" then
		local n = tonumber(r.arg) or 0
		local res = ""
		local opened = 0
		local first = 1
		local last = 4
		if n >= 1 and n <= 4 then first = n last = n end
		local i = first
		while i <= last do
			local c = PTEV_OpenVt(i)
			if c == 1 then opened = opened + 1 end
			res = res .. " tran" .. i .. "=" .. c
			i = i + 1
		end
		if opened > 0 then return 1, "vantien" .. res end
		return 0, "vantien" .. res .. " (da mo san / lich VNG)"
	elseif kind == "thuongchu" then
		if not PTVC_ForceOpen then
			local h = openfile("script\\phongthan\\ext\\vienco.lua", "r")
			if h then closefile(h) dofile("script\\phongthan\\ext\\vienco.lua") end
		end
		if not PTVC_ForceOpen then return 0, "thuongchu FAIL ext vienco chua nap" end
		if PTVC_Open and PTVC_Open() then return 0, "thuongchu busy (tran dang mo, lich VNG moi gio)" end
		local key = PTVC_ForceOpen()
		return 1, "thuongchu round " .. tostring(key)
	elseif kind == "boss" then
		if not PTWB_SpawnKey then dofile("script\\phongthan\\boss\\wb_lib.lua") end
		if not PTWB_SpawnKey then return 0, "boss FAIL wb_lib" end
		local c = PTWB_SpawnKey(tostring(r.key or ""))
		if c and c > 0 then return 1, "boss " .. tostring(r.key) .. " npc=" .. c end
		if c == 0 then return 0, "boss " .. tostring(r.key) .. " dang song" end
		return 0, "boss " .. tostring(r.key) .. " FAIL " .. tostring(c)
	elseif kind == "exp" then
		local dur = tonumber(r.dur) or 60
		if dur < 1 then dur = 1 end
		if dur > 1440 then dur = 1440 end
		local e = now + dur * 60
		if e > (PTEV_ST.expEnd or 0) then PTEV_ST.expEnd = e end
		PTEV_ExpPlayers(now)
		return 2, "exp x2 " .. dur .. " phut den " .. PTEV_ST.expEnd
	end
	return 0, "kind la " .. tostring(kind)
end

-- x2 exp event: every online player gets the Bach Ho privilege (+100% monster exp) for the time left, once per event
function PTEV_ExpPlayers(now)
	local e = PTEV_ST.expEnd or 0
	if e <= now then return 0 end
	if not PTIB_BaihuExtend then dofile("script\\phongthan\\ibitem\\pt_ibitem_lib.lua") end
	if not PTIB_BaihuExtend then return 0 end
	local n = 0
	local old = PlayerIndex
	local i = 1
	while i <= PTEV_MAX_PLAYER do
		PlayerIndex = i
		local nm = GetName()
		if nm and nm ~= "" and GetTask(PTEV_T_GOT) ~= e then
			SetTask(PTEV_T_GOT, e)
			PTIB_BaihuExtend(e - now)
			Msg2Player("S\249 ki\214n nh\169n \174\171i kinh nghi\214m: kinh nghi\214m \174\184nh qu\184i x2 th\170m " .. floor((e - now + 59) / 60) .. " ph\243t (hi\214u \248ng \167\198c quy\210n B\185ch H\230).")
			n = n + 1
		end
		i = i + 1
	end
	PlayerIndex = old
	return n
end

function PTEV_ExpTick(now)
	local e = PTEV_ST.expEnd or 0
	if e <= 0 then return 0 end
	if now >= e then
		PTEV_ST.expEnd = 0
		PTEV_News("S\249 ki\214n nh\169n \174\171i kinh nghi\214m \174\183 k\213t th\243c. H\209n g\198p l\185i!")
		return 1
	end
	PTEV_ExpPlayers(now)
	return 0
end

function PTEV_WriteStatus(now)
	local h = openfile(PTEV_STATUS .. ".tmp", "w")
	if not h then return end
	write(h, date("%Y-%m-%d %H:%M:%S") .. "\n")
	write(h, "cfg\t" .. (PTEV_CFG.enabled or 0) .. "\t" .. getn(PTEV_CFG.rows) .. "\t" .. (PTEV_SRC or "") .. "\t" .. (PTEV_CFG.pre or 5) .. "\n")
	local left = (PTEV_ST.expEnd or 0) - now
	if left < 0 then left = 0 end
	write(h, "exp\t" .. (PTEV_ST.expEnd or 0) .. "\t" .. left .. "\n")
	local k, v
	for k, v in PTEV_ST.fired do write(h, "row\t" .. k .. "\t" .. v .. "\t" .. PTEV_Clean(PTEV_ST.res[k]) .. "\n") end
	closefile(h)
	remove(PTEV_STATUS)
	rename(PTEV_STATUS .. ".tmp", PTEV_STATUS)
end

-- one minute; hm / w / ymd may be passed by the simulator
function PTEV_Tick(ymd, w, hm, now)
	if not PTEV_INIT then
		PTEV_LoadState()
		PTEV_INIT = 1
	end
	PTEV_LoadCfg()
	ymd = tostring(ymd or date("%Y%m%d"))
	w = w or tonumber(date("%w"))
	hm = hm or (tonumber(date("%H")) * 60 + tonumber(date("%M")))
	now = now or SystemTime()
	local dirty = nil
	local pre = tonumber(PTEV_CFG.pre) or 5
	if pre < 1 then pre = 1 end
	if pre > 30 then pre = 30 end
	if PTEV_CFG.enabled == 1 then
		local k = 1
		while PTEV_CFG.rows[k] do
			local r = PTEV_CFG.rows[k]
			local id = tonumber(r.id) or k
			if r.on == 1 and PTEV_DayOk(r.days, w) then
				local st = (tonumber(r.hh) or 0) * 60 + (tonumber(r.mm) or 0)
				local d = st - hm
				if d >= 1 and d <= pre and PTEV_ST.pre[id] ~= ymd then
					PTEV_ST.pre[id] = ymd
					PTEV_News(PTEV_Title(r) .. " s\207 b\190t \174\199u sau " .. d .. " ph\243t.")
					dirty = 1
				end
				if hm >= st and hm < st + 3 and PTEV_ST.fired[id] ~= ymd then
					PTEV_ST.fired[id] = ymd
					PTEV_ST.pre[id] = ymd
					PTEV_ST.res[id] = "running"
					PTEV_SaveState()
					local a, txt = call(PTEV_Fire, { r, now }, "x", PTEV_Err)
					if a == nil then a = 0 txt = "FAIL loi script" end
					if a == 2 then
						PTEV_News(PTEV_Title(r) .. " b\190t \174\199u! Kinh nghi\214m \174\184nh qu\184i x2 trong " .. (tonumber(r.dur) or 60) .. " ph\243t (m\228i nh\169n v\203t \174ang online v\181 v\181o game trong th\234i gian n\181y).")
					elseif a ~= 1 and strfind(tostring(txt), "busy", 1, 1) == nil and strfind(tostring(txt), "dang song", 1, 1) == nil and strfind(tostring(txt), "FAIL", 1, 1) == nil then
						PTEV_News(PTEV_Title(r) .. " b\190t \174\199u!")
					end
					PTEV_ST.res[id] = date("%H:%M") .. " " .. tostring(txt)
					if PTAdm_Log then PTAdm_Log("eventsched", "OK", "row " .. id .. " " .. PTEV_Clean(txt)) end
					dirty = 1
				end
			end
			k = k + 1
		end
	end
	if PTEV_ExpTick(now) == 1 then dirty = 1 end
	if dirty then PTEV_SaveState() end
	PTEV_WriteStatus(now)
end

-- web admin "Chay ngay": fire row id now (ignores day / time, does not touch the daily key)
function PTEV_AdminRun(logid, id)
	if not PTEV_INIT then PTEV_LoadState() PTEV_INIT = 1 end
	PTEV_LoadCfg()
	local k = 1
	while PTEV_CFG.rows[k] do
		local r = PTEV_CFG.rows[k]
		if (tonumber(r.id) or k) == id then
			local now = SystemTime()
			local a, txt = PTEV_Fire(r, now)
			if a == 2 then
				PTEV_News(PTEV_Title(r) .. " b\190t \174\199u! Kinh nghi\214m \174\184nh qu\184i x2 trong " .. (tonumber(r.dur) or 60) .. " ph\243t (m\228i nh\169n v\203t \174ang online v\181 v\181o game trong th\234i gian n\181y).")
			elseif a ~= 1 and strfind(tostring(txt), "busy", 1, 1) == nil and strfind(tostring(txt), "dang song", 1, 1) == nil and strfind(tostring(txt), "FAIL", 1, 1) == nil then
				PTEV_News(PTEV_Title(r) .. " b\190t \174\199u!")
			end
			PTEV_ST.res[id] = date("%H:%M") .. " (admin) " .. tostring(txt)
			if not PTEV_ST.fired[id] then PTEV_ST.fired[id] = "" end
			PTEV_SaveState()
			PTEV_WriteStatus(now)
			PTAdm_Log(logid, "OK", "row " .. id .. " " .. PTEV_Clean(txt))
			return 1
		end
		k = k + 1
	end
	PTAdm_Log(logid, "FAIL", "khong co dong " .. tostring(id) .. " trong eventsched_config.lua")
	return 0
end

-- web admin "Tat x2 ngay": end the exp event now (players keep the Bach Ho time already granted)
function PTEV_AdminStopExp(logid)
	if not PTEV_INIT then PTEV_LoadState() PTEV_INIT = 1 end
	PTEV_ST.expEnd = 0
	PTEV_SaveState()
	PTEV_WriteStatus(SystemTime())
	PTAdm_Log(logid, "OK", "exp event stopped")
end
