-- Phong Than 2026-10-03 (tienma45): Tien Ma gioi phase 4 (Nguc Phap Son 1075) + phase 5 (Thanh Dia 1076).
-- Generated by scratchpad\tienma45\mk45.py; edit the generator, not this file.
-- role script (khuongngutich): dialog lives in n45_p5.lua
PT45_ROLE = "tamnguyen"
PT45_IDX = 2
Include("\\script\\phongthan\\tienma45\\n45_p5.lua")
