[MiniMap]
Left=442
Top=0
Width=350
Height=300
Image=
Moveable=1


[BtnUp]
Left=166
Top=20
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\µØÍ¼ÉÏ.spr
Tip=$Lªn
SendHoldMsg=1

[BtnDown]
Left=166
Top=283
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\µØÍ¼ÏÂ.spr
Tip=$Xuèng
SendHoldMsg=1

[BtnLeft]
Left=1
Top=147
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\µØÍ¼×ó.spr
Tip=$Tr¸i
SendHoldMsg=1

[BtnRight]
Left=333
Top=147
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\µØÍ¼ÓÒ.spr
Tip=$Ph¶i
SendHoldMsg=1





;ÉÏ
[TitleImage]
Left=198
Top=0
Image=\spr\ui4\Ğ¡µØÍ¼\¶¥²¿.spr
Moveable=1
;ÓÒÉÏ
[BorderConner1]
Left=336
Top=16
Width=20
Height=22
Image=\spr\UI4\Ğ¡µØÍ¼\ÓÒÉÏ.spr
DummyWnd=1
;×óÏÂ
[BorderConner2]
Left=-2
Top=279
Width=20
Height=22
Image=\spr\UI4\Ğ¡µØÍ¼\×óÏÂ.spr
DummyWnd=1

;µØÍ¼Ãû
[SceneName]
Left=198
Top=3
Width=129
Height=14
Font=14
HAlign=1
TextShadow=1
Color=0,255,0
OverColor=0,255,255
SelColor=0,255,255
DummyWnd=1
;µØÍ¼×ø±ê
[ScenePos]
Left=200
Top=19
Width=130
Height=14
Font=14
HAlign=1
Color=0,255,0
DummyWnd=1

;»­µØÍ¼µÄ·¶Î§
[MapRect]
Left=1
Top=20
Width=350
Height=281

;×îĞ¡»¯°´Å¥
[MinSizeBtn]
Left=327
Top=3
Width=22
Height=14
Up=0
Down=1
CheckBox=1
;Over=2
;OverFrame=2
Trans=0
Image=\Spr\UI4\Ğ¡µØÍ¼\¹Ø±Õ¼ü.spr
Tip=$Èn / HiÖn
DisableFrame=1

;ÇĞ»»¸÷ÖÖµØÍ¼µÄ°´Å¥
[SwitchBtn]
Left=334
Top=284
Width=12
Height=12
Up=0
Down=0
;Over=2
;OverFrame=2
Trans=0
Image=\Spr\UI4\Ğ¡µØÍ¼\Ëõ·Å.spr
Tip=$Thu nhá

;ÇĞ»»ÊÀ½çµØÍ¼µÄ°´Å¥
[WorldMapBtn]
Left=317
Top=286
Width=14
Height=10
Up=0
Down=1
Over=1
OverFrame=1
Trans=0
Image=\Spr\UI4\Ğ¡µØÍ¼\ÊÀ½çµØÍ¼¼ü.spr
Tip=$ThÕ giíi

[BtnFlag]
Left=303
Top=284
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\Ğ¡Æì×Ó°´Å¥.spr
Tip=$Hång kú
FlagImage=\Spr\Ui4\Ğ¡µØÍ¼\Ğ¡Æì×Ó.spr

[BtnQuery]
Left=288
Top=284
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\ÎÊºÅ.spr
Tip=$T×m






