[MiniMap]
Left=640
Top=0
Width=161
Height=142
Image=
Moveable=1
;ÉÏ
[TitleImage]
Left=0
Top=0
Image=\spr\UI4\Ğ¡µØÍ¼\¶¥²¿.spr
Moveable=1

[BtnUp]
Left=66
Top=20
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\µØÍ¼ÉÏ.spr
Tip=$Lªn
SendHoldMsg=1

[BtnDown]
Left=66
Top=123
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\µØÍ¼ÏÂ.spr
Tip=$Xuèng
SendHoldMsg=1

[BtnLeft]
Left=3
Top=63
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\µØÍ¼×ó.spr
Tip=$Tr¸i
SendHoldMsg=1

[BtnRight]
Left=135
Top=63
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\µØÍ¼ÓÒ.spr
Tip=$Ph¶i
SendHoldMsg=1




;ÓÒÉÏ
[BorderConner1]
Left=138
Top=16
;Width=20
;Height=22
Image=\spr\UI4\Ğ¡µØÍ¼\ÓÒÉÏ.spr
DummyWnd=1

;×óÏÂ
[BorderConner2]
Left=0
Top=120
;Width=20
;Height=22
Image=\spr\UI4\Ğ¡µØÍ¼\×óÏÂ.spr
DummyWnd=1

;µØÍ¼Ãû
[SceneName]
Left=0
Top=3
Width=129
Height=14
Font=14
HAlign=1
TextShadow=1
Color=0,255,0
OverColor=0,255,255
SelColor=0,255,255
DummyWnd=1

;µØÍ¼×ø±ê
[ScenePos]
Left=2
Top=19
Width=130
Height=14
Font=14
HAlign=1
Color=0,255,0
DummyWnd=1

;»­µØÍ¼µÄ·¶Î§
[MapRect]
Left=3
Top=17
Width=150
Height=124

;×îĞ¡»¯°´Å¥
[MinSizeBtn]
Left=129
Top=3
;Width=22
;Height=14
Up=0
Down=1
CheckBox=1
;Over=2
;OverFrame=2
Trans=0
Image=\Spr\UI4\Ğ¡µØÍ¼\¹Ø±Õ¼ü.spr
Tip=$Èn / HiÖn
DisableFrame=1

;ÇĞ»»¸÷ÖÖµØÍ¼µÄ°´Å¥
[SwitchBtn]
Left=136
Top=127
;Width=12
;Height=12
Up=1
Down=1
;Over=2
;OverFrame=2
Trans=0
Image=\Spr\UI4\Ğ¡µØÍ¼\Ëõ·Å.spr
Tip=$Phãng

;ÇĞ»»ÊÀ½çµØÍ¼µÄ°´Å¥
[WorldMapBtn]
Left=120
Top=129
;Width=14
;Height=10
Up=0
Down=1
Over=1
OverFrame=1
Trans=0
Image=\Spr\UI4\Ğ¡µØÍ¼\ÊÀ½çµØÍ¼¼ü.spr
Tip=$ThÕ giíi

[BtnFlag]
Left=105
Top=127
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\Ğ¡Æì×Ó°´Å¥.spr
Tip=$Hång kú
FlagImage=\Spr\Ui4\Ğ¡µØÍ¼\Ğ¡Æì×Ó.spr

[BtnQuery]
Left=89
Top=127
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\Ğ¡µØÍ¼\ÎÊºÅ.spr
Tip=$T×m



