[Main]
; Original Phong Than VNG tooltip geometry.
ImgWidth=12
ImgHeight=9
Indent=6
Font=14
ImgType=0
Frame=0
TitleBgColor=41,44,41
PropBgColor=53,58,70
DescBgColor=53,58,70
BackgroundAlpha=5
BKImageIndet=5
RectColor=130,100,32
SmallBKImageLeft=50
SmallBKImageTop=74
BoderColor=80,100,48
SpriteColor=120,224,120
