[Main]
Left=0
Top=116
Moveable=1
StartPos=250,116
Trans=1
Image=\spr\Ui4\合成\合成栏.spr

[CloseBtn]
Left=126
Top=4
;Width=20
;Height=13
Up=0
Down=1
Over=1
OverFrame=2
Image=\spr\Ui4\按钮\关闭键.spr

[CombineBtn]
Left=57
Top=289
;Left=57
;Top=180
;Top=260
;Width=32
;Height=32
Up=0
Down=1
Over=2
OverFrame=2
Image=\spr\Ui4\合成\镶嵌.spr

[Item1]
Left=59
Top=48
Width=32
Height=32

[Item2]
Left=93
Top=63
Width=32
Height=32

[Item3]
Left=108
Top=97
Width=32
Height=32

[Item4]
Left=93
Top=131
Width=32
Height=32

[Item5]
Left=59
Top=146
Width=32
Height=32

[Item6]
Left=25
Top=131
Width=32
Height=32

[Item7]
Left=10
Top=97
Width=32
Height=32

[Item8]
Left=25
Top=63
Width=32
Height=32

[Item9]
Left=59
Top=96
Width=32
Height=32


[TxtMoneyCost]
Left=7
Top=200
Width=136
Height=15
Font=14
HAlign=1
Color=255,217,78


[TxtInfo]
Left=7
Top=223
Width=136
Height=30
Font=14
Color=214,214,214
MultiLine=1

[EffectBegin]
Left=10
Top=48
Image=\spr\Ui4\合成\合成特效前.spr
DummyWnd=1

[EffectWaiting]
Left=10
Top=48
LoopCount=2
Image=\spr\Ui4\合成\合成特效中.spr
DummyWnd=1

[EffectEnd]
Left=10
Top=48
Image=\spr\Ui4\合成\合成特效后.spr
DummyWnd=1
