-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Nguoi Hai Thuoc (tpl 776, 1624/3686): task 1043 Ha Do Huyen Canh (8 Linh Thach tpl 946-949 visited in order,
-- each releases a Long Ma tpl 942-945), the brother (tpl 950 at 227/216) ends it; task 97 hexagram Ton (Thuc
-- Duoc Thu tpl 879). The Linh Thach and the brother use this script too (dispatch by template).
Include("\\script\\phongthan\\tienma\\tm_lib.lua")

function main(npc)
	local tpl = 0
	if npc and npc > 0 then tpl = GetNpcTemplateID(npc) end
	if tpl >= 946 and tpl <= 949 then
		ht_stone(npc)
	elseif tpl == 950 then
		ht_brother()
	else
		ht_main()
	end
end

function ht_main()
	local t = "<color=green>Ng­êi H¸i Thuèc<color>: "
	if GetTaskByte(PTTM_T_GUA, 3) == 2 and GetTaskByte(PTTM_T_GUA, 4) == 5 then
		if PTTM_SummonAlive(PTTM_K_THUCDUOC) > 0 then
			Talk(1, "", t .. "Thùc D­îc Thó ®ang ë ®©y! Gi¸o huÊn nã gióp ta.")
		else
			Say(t .. "Bän <color=red>Thùc D­îc Thó<color> ngµy nµo còng ®Õn ¨n trém th¶o d­îc cña ta. Ng­¬i gi¸o huÊn chóng gióp ta ®­îc kh«ng?", 2,
				"Gi¸o huÊn Thùc D­îc Thó/ht_beast", "KÕt thóc ®èi tho¹i/no")
		end
		return
	end
	local s = PTTM_Get(F_1043S)
	if s == 0 then
		Say(t .. "Ta cã mét ng­êi anh, th¸ng tr­íc lªn nói råi kh«ng râ tung tÝch. Nghe nãi Long M· trong <color=yellow>Linh Th¹ch<color> hãa ¶o ¶nh mª hoÆc ng­êi. Theo thø tù thu phôc <color=yellow>8 Long M·<color> míi ph¸ ®­îc ¶o c¶nh.", 2,
			"NhËn nhiÖm vô Hµ §å HuyÒn C¶nh/ht_take", "KÕt thóc ®èi tho¹i/no")
	elseif s == 1 then
		local p = PTTM_LT[PTTM_Get(F_1043C) + 1]
		Talk(1, "", t .. format("§· thu phôc %d/8 Long M·. Linh Th¹ch tiÕp theo ë kho¶ng (%d,%d).", PTTM_Get(F_1043C), floor(p[1] / 8), floor(p[2] / 16)))
	elseif s == 2 then
		Talk(1, "", t .. "¶o c¶nh ®· tan! Mau ®Õn (227,216) t×m huynh tr­ëng cña ta.")
	else
		Talk(1, "", t .. "§a t¹ ©n nh©n ®· cøu huynh tr­ëng cña ta.")
	end
end

function ht_take()
	if PTTM_Get(F_1043S) ~= 0 then return end
	if GetLevel() < 28 then
		Talk(1, "", "CÇn ®¹t cÊp 28.")
		return
	end
	PTTM_Set(F_1043S, 1)
	PTTM_Set(F_1043C, 0)
	PTTM_HdNote(0)
	Msg2Player("NhËn nhiÖm vô <color=yellow>Hµ §å HuyÒn C¶nh<color>: theo thø tù t×m 8 Linh Th¹ch, thu phôc Long M·.")
end

function ht_beast()
	if GetTaskByte(PTTM_T_GUA, 3) ~= 2 or GetTaskByte(PTTM_T_GUA, 4) ~= 5 then return end
	if PTTM_SummonAlive(PTTM_K_THUCDUOC) > 0 then return end
	if PTTM_Summon(879, 78, "Thùc D­îc Thó", PTTM_K_THUCDUOC, 300) > 0 then
		TaskNote(97, 11)
		Msg2Player("<color=red>Thùc D­îc Thó<color> xuÊt hiÖn!")
	end
end

function ht_stone(npc)
	local m, x, y = GetNpcPos(npc)
	local i = 1
	local idx = 0
	while PTTM_LT[i] do
		if abs(PTTM_LT[i][1] - x) <= 2 and abs(PTTM_LT[i][2] - y) <= 2 then idx = i end
		i = i + 1
	end
	if PTTM_Get(F_1043S) ~= 1 or idx == 0 then
		Talk(1, "", "<color=green>Linh Th¹ch<color>: Khèi ®¸ táa ra linh khÝ kú l¹.")
		return
	end
	local c = PTTM_Get(F_1043C)
	if PTTM_SummonAlive(PTTM_K_LONGMA) > 0 then
		Talk(1, "", "<color=green>Linh Th¹ch<color>: Long M· ®· ®­îc phãng thÝch, mau thu phôc nã!")
		return
	end
	if idx ~= c + 1 then
		Talk(1, "", format("<color=green>Linh Th¹ch<color>: Linh Th¹ch kh«ng ph¶n øng. H·y theo thø tù trªn Hµ §å, t×m Linh Th¹ch sè %d.", c + 1))
		return
	end
	Say("<color=green>Linh Th¹ch<color>: Bªn trong phong Ên mét con Long M·.", 2, "Phãng thÝch Long M·/ht_release", "KÕt thóc ®èi tho¹i/no")
end

function ht_release()
	if PTTM_Get(F_1043S) ~= 1 or PTTM_SummonAlive(PTTM_K_LONGMA) > 0 then return end
	local c = PTTM_Get(F_1043C)
	if PTTM_Summon(942 + mod(c, 4), 76, "Long M·", PTTM_K_LONGMA, 180) > 0 then
		Msg2Player("<color=red>Long M·<color> tho¸t khái Linh Th¹ch! Thu phôc nã.")
	end
end

function ht_brother()
	local s = PTTM_Get(F_1043S)
	local t = "<color=green>Huynh §Ö Ng­êi H¸i Thuèc<color>: "
	if s == 2 then
		Say(t .. "Ta bÞ ¶o ¶nh Long M· giam ë ®©y c¶ th¸ng trêi... §a t¹ ©n nh©n!", 2, "§­a tin cho Ng­êi H¸i Thuèc/ht_done", "KÕt thóc ®èi tho¹i/no")
	else
		Talk(1, "", t .. "Nói nµy ®Çy ¶o ¶nh, cÈn thËn kÎo l¹c ®­êng.")
	end
end

function ht_done()
	if PTTM_Get(F_1043S) ~= 2 then return end
	PTTM_Set(F_1043S, 3)
	TaskNote(1043, -1)
	PTTM_Reward(500000, 30000)
end
