-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Nu Oa Nuong Nuong (tpl 780, 1656/3769): task 1026 Ho Tien Hoan Ma (6 rounds a day; Tien opens the Ho Ma thap
-- tpl 791 -> 6 Phi Tho Ma tpl 810, Ma opens the Ho Tien thap tpl 790 -> 6 Hung Tien tpl 809) and step 3 of task
-- 96 (Thach Trung Hoa). The two towers use this script too.
Include("\\script\\phongthan\\tienma\\tm_lib.lua")

function main(npc)
	local tpl = 0
	if npc and npc > 0 then tpl = GetNpcTemplateID(npc) end
	if tpl == 790 or tpl == 791 then
		nw_tower(npc, tpl)
		return
	end
	local o = {}
	if PTTM_Get(F_96) == 3 then tinsert(o, "Hái tung tÝch Th¹ch Trung Háa/nw_96") end
	tinsert(o, "H« Tiªn Ho¸n Ma/nw_1026")
	tinsert(o, "KÕt thóc ®èi tho¹i/no")
	Say("<color=green>N÷ Oa N­¬ng N­¬ng<color>: §¸ ngò s¾c v¸ trêi, ta vÉn cßn gi÷ l¹i vµi viªn. Ng­¬i t×m ta cã viÖc g×?", getn(o), o)
end

function nw_96()
	if PTTM_Get(F_96) ~= 3 then return end
	PTTM_Set(F_96, 4)
	TaskNote(96, 3)
	Talk(1, "", "<color=green>N÷ Oa N­¬ng N­¬ng<color>: Th¹ch Trung Háa Èn trong ®¸ ngò s¾c, cÇm lÊy. Méc Trung Háa th× h·y hái <color=yellow>Thî §ång<color> ë BÊt Chu Thiªn Quan.")
end

function nw_1026()
	local s = PTTM_Get(F_1026S)
	local r = PTTM_Get(F_1026R)
	local t = "<color=green>N÷ Oa N­¬ng N­¬ng<color>: "
	if s == 0 then
		if r >= 6 then
			Talk(1, "", t .. "H«m nay ng­¬i ®· siªu ®é 6 vßng, ngµy mai h·y quay l¹i.")
			return
		end
		Say(t .. format("§¹o h÷u nghÞch ph¶n bÞ biÕn thµnh Hung Tiªn, Phi Thè Ma, bÞ trÊn trong th¸p nh­ng vÉn muèn tho¸t ra quËy ph¸. Gióp ta siªu ®é chóng (h«m nay %d/6 vßng).", r), 2,
			"NhËn nhiÖm vô H« Tiªn Ho¸n Ma/nw_take", "KÕt thóc ®èi tho¹i/no")
	elseif s == 1 then
		if PTTM_IsMa() then
			Talk(1, "", t .. "CÇm Táa Tiªn bµi ®Õn <color=yellow>H« Tiªn Th¸p<color> më phong Ên.")
		else
			Talk(1, "", t .. "CÇm TrÊn Ma ph­ín ®Õn <color=yellow>H« Ma Th¸p<color> më phong Ên.")
		end
	elseif s == 2 then
		Talk(1, "", t .. format("§· siªu ®é %d/6, cè lªn!", PTTM_Get(F_1026C)))
	else
		Say(t .. "Ng­¬i ®· siªu ®é thµnh c«ng!", 2, "NhËn th­ëng/nw_done", "KÕt thóc ®èi tho¹i/no")
	end
end

function nw_take()
	if PTTM_Get(F_1026S) ~= 0 or PTTM_Get(F_1026R) >= 6 then return end
	PTTM_Set(F_1026S, 1)
	PTTM_Set(F_1026C, 0)
	if PTTM_IsMa() then
		TaskNote(1026, 1)
		Msg2Player("NhËn ®­îc <color=yellow>Táa Tiªn bµi<color>. §Õn H« Tiªn Th¸p më phong Ên.")
	else
		TaskNote(1026, 0)
		Msg2Player("NhËn ®­îc <color=yellow>TrÊn Ma ph­ín<color>. §Õn H« Ma Th¸p më phong Ên.")
	end
end

function nw_tower(npc, tpl)
	local want = 791
	if PTTM_IsMa() then want = 790 end
	local s = PTTM_Get(F_1026S)
	if tpl ~= want or (s ~= 1 and s ~= 2) then
		Talk(1, "", "<color=green>Phong Ên Th¸p<color>: Phong Ên vÉn v÷ng ch¾c.")
		return
	end
	if s == 2 and PTTM_SummonAlive(PTTM_K_WAVE) > 0 then
		Talk(1, "", "<color=green>Phong Ên Th¸p<color>: Linh hån ®ang lôc tôc bay ra, h·y siªu ®é chóng!")
		return
	end
	Say("<color=green>Phong Ên Th¸p<color>: Phong Ên cã thÓ më ra.", 2, "Më phong Ên/nw_open", "KÕt thóc ®èi tho¹i/no")
end

function nw_open()
	local s = PTTM_Get(F_1026S)
	if s ~= 1 and s ~= 2 then return end
	if s == 2 and PTTM_SummonAlive(PTTM_K_WAVE) > 0 then return end
	local tpl, name = 810, "Phi Thè Ma"
	if PTTM_IsMa() then tpl, name = 809, "Hung Tiªn" end
	local m, x, y = GetWorldPos()
	local n = 6 - PTTM_Get(F_1026C)
	local i = 1
	while i <= n do
		PTTM_SummonAt(tpl, 76, name, PTTM_K_WAVE, 180, x - 6 + mod(i, 3) * 6, y + 3 + floor(i / 3) * 4)
		i = i + 1
	end
	PTTM_Set(F_1026S, 2)
	if PTTM_IsMa() then TaskNote(1026, 3) else TaskNote(1026, 2) end
	Msg2Player("Phong Ên ®· më, trong 3 phót <color=red>" .. name .. "<color> sÏ lôc tôc bay ra, h·y siªu ®é chóng!")
end

function nw_done()
	if PTTM_Get(F_1026S) ~= 3 then return end
	PTTM_Set(F_1026S, 0)
	PTTM_Set(F_1026C, 0)
	PTTM_Set(F_1026R, PTTM_Get(F_1026R) + 1)
	TaskNote(1026, -1)
	PTTM_Reward(GetLevel() * 2500, 10000)
end
