-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Bat Chu Son: Hoa Than (tpl 856), Thuy Than (tpl 857) and Thien Nien Dai Thach (tpl 876): main steps 20-27.
-- 20 take both powers -> 21 give them to the rock -> 22 Thach Quai (tpl 877, 249/226) -> 23 -> Hoa Than sends to
-- Thuy Than (24) -> Thuy Than reward (25) -> Hoa Than reward -> 27 (= phase 3 done, F11 Step_26). A Thach Quai
-- that escapes = failure (F11 Step_27, F_SUB +4, main stays 22) until a god grants the power again (21).
Include("\\script\\phongthan\\tienma\\tm_lib.lua")
PTTM_THACH = { 1992, 3624 }

function main(npc)
	local tpl = 0
	if npc and npc > 0 then tpl = GetNpcTemplateID(npc) end
	if tpl == 876 then
		dt_main()
	elseif tpl == 857 then
		th_main(2, "Thñy ThÇn")
	else
		th_main(1, "Háa ThÇn")
	end
end

-- Thach Quai gone while the player is at step 22: failure
function th_checkfail()
	if GetTask(PTTM_T_MAIN) == 22 and PTTM_Get(F_SUB) < 4 and PTTM_SummonAlive(PTTM_K_THACH) == 0 then
		PTTM_Set(F_SUB, PTTM_Get(F_SUB) + 4)
		PTTM_Note(27)
		Msg2Player("Th¹ch Qu¸i ®· trèn mÊt, nhiÖm vô thÊt b¹i! H·y t×m Thñy ThÇn vµ Háa ThÇn xin nhËp l¹i ph¸p lùc.")
	end
end

function th_main(b, name)
	local m = GetTask(PTTM_T_MAIN)
	local t = "<color=green>" .. name .. "<color>: "
	th_checkfail()
	local sub = PTTM_Get(F_SUB)
	if m == 20 then
		if PTTM_Bit(sub, b) == 1 then
			Talk(1, "", t .. "Ng­¬i ®· nhËn ph¸p lùc cña ta, h·y ®i t×m vÞ thÇn cßn l¹i.")
		else
			Say(t .. "Phong Ên cña Thiªn Niªn §¹i Th¹ch chØ cã ph¸p lùc cña Thñy Háa hîp nhÊt míi ph¸ ®­îc. NhËn lÊy ph¸p lùc cña ta.", 2,
				"NhËn ph¸p lùc/th_take" .. b, "KÕt thóc ®èi tho¹i/no")
		end
	elseif m == 22 and sub >= 4 then
		Say(t .. "Th¹ch Qu¸i ®· trèn tho¸t? Ta nhËp l¹i ph¸p lùc cho ng­¬i, lÇn nµy ®õng ®Ó nã ch¹y mÊt.", 2,
			"Xin nhËp l¹i ph¸p lùc/th_regrant", "KÕt thóc ®èi tho¹i/no")
	elseif m == 21 or m == 22 then
		Talk(1, "", t .. "Mau truyÒn ph¸p lùc cho <color=yellow>Thiªn Niªn §¹i Th¹ch<color> trªn Th¹ch ®µi phÝa ®«ng (249/226) råi chinh phôc Th¹ch Qu¸i.")
	elseif m == 23 then
		if b == 1 then
			Say(t .. "Lµm tèt l¾m! H·y ®i phôc mÖnh <color=yellow>Thñy ThÇn<color> tr­íc.", 2, "§i gÆp Thñy ThÇn/th_23", "KÕt thóc ®èi tho¹i/no")
		else
			Say(t .. "Ng­¬i ®· chinh phôc Th¹ch Qu¸i! §©y lµ phÇn th­ëng cña ta.", 2, "NhËn th­ëng/th_water", "KÕt thóc ®èi tho¹i/no")
		end
	elseif m == 24 then
		if b == 2 then
			Say(t .. "Ng­¬i ®· chinh phôc Th¹ch Qu¸i! §©y lµ phÇn th­ëng cña ta.", 2, "NhËn th­ëng/th_water", "KÕt thóc ®èi tho¹i/no")
		else
			Talk(1, "", t .. "H·y ®i phôc mÖnh <color=yellow>Thñy ThÇn<color> tr­íc.")
		end
	elseif m == 25 then
		if b == 1 then
			Say(t .. "Phong ThÇn b¶ng ®· bay vÒ phÝa <color=yellow>Ngôc Ph¸p S¬n<color>. §©y lµ phÇn th­ëng cña ta.", 2, "NhËn th­ëng/th_fire", "KÕt thóc ®èi tho¹i/no")
		else
			Talk(1, "", t .. "H·y ®i phôc mÖnh <color=yellow>Háa ThÇn<color>.")
		end
	elseif m >= 27 then
		Talk(1, "", t .. "Sau cÊp 55 h·y ®Õn <color=yellow>Ngôc Ph¸p S¬n<color> t×m Tu Hµnh S­ tiÕp tôc t×m hiÓu Phong ThÇn b¶ng.")
	else
		Talk(1, "", t .. "BÊt Chu S¬n lµ cét chèng trêi, kÎ phµm tôc chí lµm cµn.")
	end
end

function th_take(b)
	if GetTask(PTTM_T_MAIN) ~= 20 then return end
	local sub = PTTM_Get(F_SUB)
	if PTTM_Bit(sub, b) == 1 then return end
	sub = sub + b
	PTTM_Set(F_SUB, sub)
	if PTTM_Bit(sub, 1) == 1 and PTTM_Bit(sub, 2) == 1 then
		SetTask(PTTM_T_MAIN, 21)
		PTTM_Note(21)
		Msg2Player("§· nhËn ph¸p lùc cña Háa ThÇn vµ Thñy ThÇn! Mau truyÒn cho <color=yellow>Thiªn Niªn §¹i Th¹ch<color>.")
	else
		Msg2Player("NhËn ®­îc ph¸p lùc, h·y ®i t×m vÞ thÇn cßn l¹i.")
	end
end

function th_take1()
	th_take(1)
end

function th_take2()
	th_take(2)
end

function th_regrant()
	if GetTask(PTTM_T_MAIN) ~= 22 or PTTM_Get(F_SUB) < 4 then return end
	PTTM_Set(F_SUB, 3)
	SetTask(PTTM_T_MAIN, 21)
	PTTM_Note(21)
	Msg2Player("§· nhËp l¹i ph¸p lùc. TruyÒn cho Thiªn Niªn §¹i Th¹ch lÇn n÷a.")
end

function th_23()
	if GetTask(PTTM_T_MAIN) ~= 23 then return end
	SetTask(PTTM_T_MAIN, 24)
	PTTM_Note(24)
end

function th_water()
	local m = GetTask(PTTM_T_MAIN)
	if m ~= 23 and m ~= 24 then return end
	SetTask(PTTM_T_MAIN, 25)
	PTTM_Note(25)
	PTTM_TuLuyen(400000)
end

function th_fire()
	if GetTask(PTTM_T_MAIN) ~= 25 then return end
	SetTask(PTTM_T_MAIN, 27)
	PTTM_Note(26)
	PTTM_TuLuyen(400000)
	Earn(40000)
	Msg2Player("§· cã tin tøc Phong ThÇn b¶ng! Sau cÊp 55 ®Õn <color=yellow>Ngôc Ph¸p S¬n<color> t×m Tu Hµnh S­.")
end

function dt_main()
	local m = GetTask(PTTM_T_MAIN)
	local t = "<color=green>Thiªn Niªn §¹i Th¹ch<color>: "
	th_checkfail()
	if m == 21 then
		Say(t .. "T¶ng ®¸ ngµn n¨m rung lªn khi c¶m nhËn ph¸p lùc Thñy Háa trªn ng­êi ng­¬i.", 2, "TruyÒn ph¸p lùc/dt_give", "KÕt thóc ®èi tho¹i/no")
	elseif m == 22 and PTTM_Get(F_SUB) >= 4 then
		Talk(1, "", t .. "Ph¸p lùc ®· tiªu t¸n. H·y t×m Thñy ThÇn vµ Háa ThÇn xin nhËp l¹i ph¸p lùc.")
	elseif m == 22 then
		Talk(1, "", t .. "Th¹ch Qu¸i ®ang ë gÇn ®©y (249/226), mau chinh phôc nã!")
	else
		Talk(1, "", t .. "Mét t¶ng ®¸ khæng lå n»m trªn Th¹ch ®µi, phñ ®Çy rªu phong ngµn n¨m.")
	end
end

function dt_give()
	if GetTask(PTTM_T_MAIN) ~= 21 then return end
	if PTTM_SummonAt(877, 82, "Th¹ch Qu¸i", PTTM_K_THACH, 300, PTTM_THACH[1], PTTM_THACH[2]) <= 0 then
		Talk(1, "", "Th¹ch Qu¸i ch­a xuÊt hiÖn, h·y thö l¹i.")
		return
	end
	PTTM_Set(F_SUB, 3)
	SetTask(PTTM_T_MAIN, 22)
	PTTM_Note(22)
	Msg2Player("Thiªn Niªn §¹i Th¹ch ®· biÕn thµnh <color=red>Th¹ch Qu¸i<color>! Chinh phôc nã trong 5 phót.")
end
