-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Cuu Thien Huyen Nu (tpl 837, adopted placeholder 1996/3256): task 1027 Thien Kiep, once a day. Tien uses the
-- Vat to Tien kiep (tpl 838, 251/208) -> Nguyen Than 823..829, Ma the Vat to Ma kiep (tpl 839, 242/202) -> 830..836,
-- summoned one after the other. The totems use this script too.
Include("\\script\\phongthan\\tienma\\tm_lib.lua")

function main(npc)
	local tpl = 0
	if npc and npc > 0 then tpl = GetNpcTemplateID(npc) end
	if tpl == 838 or tpl == 839 then
		ct_totem(tpl)
		return
	end
	local s = PTTM_Get(F_1027S)
	local t = "<color=green>Cöu Thiªn HuyÒn N÷<color>: "
	if s == 0 then
		Say(t .. "§é kiÕp lµ kiÕp n¹n mµ ng­êi tu hµnh nµo còng ph¶i tr¶i qua. Ng­¬i ®· s½n sµng ®èi mÆt Thiªn KiÕp ch­a?", 2,
			"NhËn nhiÖm vô Thiªn KiÕp/ct_take", "KÕt thóc ®èi tho¹i/no")
	elseif s == 1 then
		if PTTM_IsMa() then
			Talk(1, "", t .. "§Õn gÇn <color=yellow>VËt Tæ Ma KiÕp<color> (242/202) gäi ra Ma Háa KiÕp N¹n.")
		else
			Talk(1, "", t .. "§Õn gÇn <color=yellow>VËt Tæ Tiªn KiÕp<color> (251/208) gäi ra Thiªn L«i KiÕp N¹n.")
		end
	elseif s == 2 then
		Talk(1, "", t .. format("Thiªn KiÕp ®ang diÔn ra, cßn %d XuÊt KhiÕu Nguyªn ThÇn.", 7 - PTTM_Get(F_1027C)))
	elseif s == 3 then
		Say(t .. "Ng­¬i ®· ®é kiÕp thµnh c«ng!", 2, "Phôc mÖnh/ct_done", "KÕt thóc ®èi tho¹i/no")
	else
		Talk(1, "", t .. "H«m nay ng­¬i ®· ®é kiÕp, ngµy mai h·y quay l¹i.")
	end
end

function ct_take()
	if PTTM_Get(F_1027S) ~= 0 then return end
	PTTM_Set(F_1027S, 1)
	PTTM_Set(F_1027C, 0)
	if PTTM_IsMa() then TaskNote(1027, 1) else TaskNote(1027, 0) end
	Msg2Player("NhËn ®­îc <color=yellow>Hi Hoµng Th¹ch<color>. §Õn VËt Tæ gäi ra kiÕp n¹n.")
end

function ct_totem(tpl)
	local want = 838
	if PTTM_IsMa() then want = 839 end
	local s = PTTM_Get(F_1027S)
	if tpl ~= want or (s ~= 1 and s ~= 2) then
		Talk(1, "", "<color=green>VËt Tæ<color>: VËt tæ cæ x­a kh¾c ®Çy phï v¨n.")
		return
	end
	if s == 2 and PTTM_SummonAlive(PTTM_K_NT) > 0 then
		Talk(1, "", "<color=green>VËt Tæ<color>: Nguyªn ThÇn ®ang ë gÇn ®©y!")
		return
	end
	Say("<color=green>VËt Tæ<color>: Hi Hoµng Th¹ch ph¸t s¸ng, kiÕp n¹n cã thÓ b¾t ®Çu.", 2, "Dïng Hi Hoµng Th¹ch/ct_call", "KÕt thóc ®èi tho¹i/no")
end

function ct_call()
	local s = PTTM_Get(F_1027S)
	if s ~= 1 and s ~= 2 then return end
	if s == 2 and PTTM_SummonAlive(PTTM_K_NT) > 0 then return end
	local base, st = 823, 2
	if PTTM_IsMa() then base, st = 830, 3 end
	local c = PTTM_Get(F_1027C)
	if PTTM_Summon(base + c, 76 + c, "XuÊt KhiÕu Nguyªn ThÇn", PTTM_K_NT, 300) > 0 then
		PTTM_Set(F_1027S, 2)
		TaskNote(1027, st, 7 - c)
		Msg2Player("Thiªn KiÕp b¾t ®Çu! LÇn l­ît tiªu diÖt 7 XuÊt KhiÕu Nguyªn ThÇn.")
	end
end

function ct_done()
	if PTTM_Get(F_1027S) ~= 3 then return end
	PTTM_Set(F_1027S, 4)
	TaskNote(1027, -1)
	PTTM_Reward(500000, 30000)
end
