-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Bach Hac Dao Truong (tpl 761, Tien camp) and Linh Nha Kiem Tien (tpl 771, Ma camp): task 89 Phong Thu Son Hon.
Include("\\script\\phongthan\\tienma\\tm_lib.lua")

function bh_name()
	local m, x, y = GetWorldPos()
	if x and x < 1800 then return "Linh Nha KiÕm Tiªn" end
	return "B¹ch H¹c §¹o Tr­ëng"
end

function main()
	local m, x, y = GetWorldPos()
	if x and x < 1800 then
		if PTTM_Tlt("linhnha", "Linh Nha KiÕm Tiªn") then return end
	else
		if PTTM_Tlt("bachhac", "B¹ch H¹c §¹o Tr­ëng") then return end
	end
	local q = PTTM_Get(F_89)
	local nm = "<color=green>" .. bh_name() .. "<color>: "
	if q == 0 then
		Say(nm .. "BÊt Chu Thiªn Quan bçng xuÊt hiÖn dÞ thó <color=yellow>Phong Thó S¬n Hån<color>, Tiªn Ma hîp søc vÉn ch­a trõ ®­îc. ChØ cã ph¸p b¶o <color=yellow>Táa Tinh Bµn<color> míi khèng chÕ ®­îc nã.", 2,
			"NhËn nhiÖm vô Phong Thó S¬n Hån/bh_take", "KÕt thóc ®èi tho¹i/no")
	elseif q == 1 then
		Talk(1, "", nm .. "Táa Tinh Bµn ®ang ë trªn ng­êi <color=red>Tr¹nh Nanh<color> (kho¶ng 232/218, phÝa nam §¾c Kû). H·y ®¸nh b¹i chóng.")
	elseif q == 2 then
		Say(nm .. "Ng­¬i ®· lÊy ®­îc Táa Tinh Bµn! Ta sÏ më ph¸p trËn ngay t¹i ®©y, dïng Táa Tinh Bµn ®¸nh b¹i <color=red>Phong Thó S¬n Hån<color>.", 2,
			"Giao Táa Tinh Bµn, më ph¸p trËn/bh_fight", "§Ó ta chuÈn bÞ/no")
	elseif q == 3 then
		if PTTM_SummonAlive(PTTM_K_BOSS) > 0 then
			Talk(1, "", nm .. "Phong Thó S¬n Hån ®· xuÊt hiÖn, mau ®¸nh b¹i nã!")
		else
			Say(nm .. "Phong Thó S¬n Hån ®· tho¸t khái ph¸p trËn. Më l¹i ph¸p trËn?", 2,
				"Më l¹i ph¸p trËn/bh_fight", "§Ó ta chuÈn bÞ/no")
		end
	elseif q == 4 then
		Say(nm .. "Ng­¬i ®· khèng chÕ ®­îc dÞ thó, c«ng lao kh«ng nhá!", 2, "Phôc mÖnh/bh_done", "KÕt thóc ®èi tho¹i/no")
	else
		Talk(1, "", nm .. "Nhê cã ng­¬i, Phong Thó S¬n Hån kh«ng cßn quÊy ph¸ n÷a.")
	end
end

function bh_take()
	if PTTM_Get(F_89) ~= 0 then return end
	if PTTM_TmLevel() < 11 then
		Talk(1, "", "CÊp Tiªn Ma cÇn ®¹t 11.")
		return
	end
	PTTM_Set(F_89, 1)
	TaskNote(89, 0)
	Msg2Player("NhËn nhiÖm vô <color=yellow>Phong Thó S¬n Hån<color>: ®¸nh b¹i Tr¹nh Nanh lÊy Táa Tinh Bµn.")
end

function bh_fight()
	local q = PTTM_Get(F_89)
	if q ~= 2 and q ~= 3 then return end
	if q == 3 and PTTM_SummonAlive(PTTM_K_BOSS) > 0 then return end
	local tpl = 750
	if PTTM_Phe() == 2 then tpl = 751 end
	local ni = PTTM_Summon(tpl, 76, "Phong Thó S¬n Hån", PTTM_K_BOSS, 300)
	if ni <= 0 then
		Talk(1, "", "Ph¸p trËn ch­a më ®­îc, h·y ®øng ë chç trèng råi thö l¹i.")
		return
	end
	if q == 2 then PTTM_Set(F_89, 3) end
	TaskNote(89, 2)
	Msg2Player("Ph¸p trËn ®· më! Dïng Táa Tinh Bµn ®¸nh b¹i <color=red>Phong Thó S¬n Hån<color> (5 phót).")
end

function bh_done()
	if PTTM_Get(F_89) ~= 4 then return end
	PTTM_Set(F_89, 5)
	TaskNote(89, -1)
	PTTM_Reward(500000, 50000)
end
