-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Objects of Bat Chu Thien Quan: the 12 Lien Hoa Than Dang (tpl 819; 6 Tien around Ho Su Tien, 6 Ma around Ho Su
-- Ma; main 9/11 and 16/18), Lien Toa (tpl 874, task 96) and the 16 flowers (tpl 792 Man Da La / 793 Man Chau Sa;
-- tasks 1023/1028 and 97). Lamps and flowers are found by their cell (tables below).
Include("\\script\\phongthan\\tienma\\tm_lib.lua")
PTTM_LAMPS = {}
PTTM_LAMPS[1] = { 1902, 3632 }
PTTM_LAMPS[2] = { 1932, 3620 }
PTTM_LAMPS[3] = { 1962, 3632 }
PTTM_LAMPS[4] = { 1962, 3680 }
PTTM_LAMPS[5] = { 1932, 3692 }
PTTM_LAMPS[6] = { 1902, 3680 }
PTTM_LAMPS[7] = { 1624, 3238 }
PTTM_LAMPS[8] = { 1652, 3226 }
PTTM_LAMPS[9] = { 1682, 3238 }
PTTM_LAMPS[10] = { 1682, 3286 }
PTTM_LAMPS[11] = { 1649, 3295 }
PTTM_LAMPS[12] = { 1622, 3286 }
PTTM_FLOWERS = {}
PTTM_FLOWERS[1] = { 1890, 3729, 792 }
PTTM_FLOWERS[2] = { 1888, 3727, 792 }
PTTM_FLOWERS[3] = { 1803, 3633, 792 }
PTTM_FLOWERS[4] = { 1797, 3643, 792 }
PTTM_FLOWERS[5] = { 1857, 3555, 792 }
PTTM_FLOWERS[6] = { 1864, 3565, 792 }
PTTM_FLOWERS[7] = { 1754, 3714, 792 }
PTTM_FLOWERS[8] = { 1754, 3719, 792 }
PTTM_FLOWERS[9] = { 1706, 3306, 793 }
PTTM_FLOWERS[10] = { 1707, 3291, 793 }
PTTM_FLOWERS[11] = { 1769, 3351, 793 }
PTTM_FLOWERS[12] = { 1752, 3360, 793 }
PTTM_FLOWERS[13] = { 1659, 3419, 793 }
PTTM_FLOWERS[14] = { 1657, 3427, 793 }
PTTM_FLOWERS[15] = { 1805, 3278, 793 }
PTTM_FLOWERS[16] = { 1796, 3275, 793 }

function obj_index(npc, tbl)
	if npc == nil or npc <= 0 then return 0 end
	local m, x, y = GetNpcPos(npc)
	local i = 1
	while tbl[i] do
		if abs(tbl[i][1] - x) <= 2 and abs(tbl[i][2] - y) <= 2 then return i end
		i = i + 1
	end
	return 0
end

function main(npc)
	local tpl = 0
	if npc and npc > 0 then tpl = GetNpcTemplateID(npc) end
	if tpl == 874 then
		lt_main()
	elseif tpl == 792 or tpl == 793 then
		fl_main(npc, tpl)
	else
		lamp_main(npc)
	end
end

function lamp_main(npc)
	local i = obj_index(npc, PTTM_LAMPS)
	local m = GetTask(PTTM_T_MAIN)
	local side = 1
	if i > 6 then side = 2 end
	local want = 0
	if side == 1 and (m == 9 or m == 11) then want = 1 end
	if side == 2 and (m == 16 or m == 18) then want = 1 end
	if i == 0 or want == 0 then
		Talk(1, "", "<color=green>Liªn Hoa ThÇn §¨ng<color>: Ngän ®Ìn hoa sen táa ¸nh s¸ng mê nh¹t.")
		return
	end
	local k = i
	if side == 2 then k = i - 6 end
	local b, j = 1, 1
	while j < k do
		b = b * 2
		j = j + 1
	end
	local mk = PTTM_Get(F_LAMP)
	if PTTM_Bit(mk, b) == 1 then
		Talk(1, "", "<color=green>Liªn Hoa ThÇn §¨ng<color>: Ngän ®Ìn nµy ®· ®­îc ng­¬i th¾p s¸ng.")
		return
	end
	mk = mk + b
	PTTM_Set(F_LAMP, mk)
	local c, bb = 0, 1
	while bb <= 32 do
		if PTTM_Bit(mk, bb) == 1 then c = c + 1 end
		bb = bb * 2
	end
	if c >= 6 then
		Msg2Player("C¶ 6 ngän <color=yellow>Liªn Hoa ThÇn §¨ng<color> ®· s¸ng! VÒ gÆp Liªn §¨ng Hé Sø gäi Liªn §¨ng Sø Gi¶.")
	else
		Msg2Player(format("Th¾p s¸ng Liªn Hoa ThÇn §¨ng %d/6.", c))
	end
end

-- Lien Toa: 96 (plant 1 -> 2, light 8 -> 9, talk 9 -> 10 = done)
function lt_main()
	local s = PTTM_Get(F_96)
	local t = "<color=green>Liªn Täa<color>: "
	if s == 1 then
		Say(t .. "Mét ®µi sen c¹n n­íc, cã thÓ trång h¹t Êu.", 2, "Trång h¹t Êu/lt_plant", "KÕt thóc ®èi tho¹i/no")
	elseif s == 8 then
		Say(t .. "Liªn ®¨ng trªn ®µi sen ®· t¾t tõ l©u.", 2, "Dïng Nh©n Gian Háa th¾p s¸ng/lt_light", "KÕt thóc ®èi tho¹i/no")
	elseif s == 9 then
		Say(t .. "Liªn ®¨ng bõng s¸ng, linh khÝ ng­ng tô thµnh mét giäng nãi: \"§a t¹ ng­êi ®· th¾p l¹i ta...\"", 2, "§èi tho¹i víi Liªn ®¨ng/lt_done", "KÕt thóc ®èi tho¹i/no")
	else
		Talk(1, "", t .. "§µi sen yªn tÜnh gi÷a BÊt Chu Thiªn Quan.")
	end
end

function lt_plant()
	if PTTM_Get(F_96) ~= 1 then return end
	PTTM_Set(F_96, 2)
	TaskNote(96, 1)
	Msg2Player("H¹t Êu ®· lín thµnh Liªn täa. VÒ phôc mÖnh <color=yellow>Liªn §¨ng Hé Sø<color>.")
end

function lt_light()
	if PTTM_Get(F_96) ~= 8 then return end
	PTTM_Set(F_96, 9)
	TaskNote(96, 8)
	Msg2Player("Liªn ®¨ng ®· ®­îc th¾p s¸ng! H·y ®èi tho¹i víi nã.")
end

function lt_done()
	if PTTM_Get(F_96) ~= 9 then return end
	PTTM_Set(F_96, 10)
	TaskNote(96, -1)
	PTTM_Reward(600000, 60000)
end

-- dialog callbacks fl_pick1 .. fl_pick16 (the engine calls option functions without arguments)
FL_K = 1
while FL_K <= 16 do
	local k = FL_K
	setglobal("fl_pick" .. k, function() fl_pick(%k) end)
	FL_K = FL_K + 1
end

-- flowers: 1023/1028 (8 of the own kind) and 97 Ly (Man Chau Sa) / Chan (Man Da La)
function fl_main(npc, tpl)
	local i = obj_index(npc, PTTM_FLOWERS)
	local fn = "M¹n §µ La Hoa"
	if tpl == 793 then fn = "M¹n Ch©u Sa Hoa" end
	local q = 0
	local s = PTTM_Get(F_1023S)
	if s == 1 and ((tpl == 792 and not PTTM_IsMa()) or (tpl == 793 and PTTM_IsMa())) then q = 1 end
	local g = 0
	if GetTaskByte(PTTM_T_GUA, 3) == 2 then
		local gg = GetTaskByte(PTTM_T_GUA, 4)
		if (gg == 3 and tpl == 793) or (gg == 4 and tpl == 792) then g = gg end
	end
	if i == 0 or (q == 0 and g == 0) then
		Talk(1, "", "<color=green>" .. fn .. "<color>: §ãa hoa ch­a në d­íi bãng c©y.")
		return
	end
	Say("<color=green>" .. fn .. "<color>: §ãa hoa ch­a në, cÇn Cam Lé míi tr­ëng thµnh.", 2, "T­íi Cam Lé vµ h¸i hoa/fl_pick" .. i, "KÕt thóc ®èi tho¹i/no")
end

function fl_pick(i)
	local p = PTTM_FLOWERS[i]
	if p == nil then return end
	local tpl = p[3]
	local b, j = 1, 1
	while j < i do
		b = b * 2
		j = j + 1
	end
	local mk = PTTM_Get(F_FLOWER)
	if PTTM_Bit(mk, b) == 1 then
		Talk(1, "", "§ãa hoa nµy ng­¬i võa h¸i råi, h·y t×m ®ãa kh¸c.")
		return
	end
	-- all flowers of this kind picked: start a new pass
	local first, last = 1, 8
	if tpl == 793 then first, last = 9, 16 end
	local c, k, bb = 0, 1, 1
	while k <= 16 do
		if k >= first and k <= last and PTTM_Bit(mk, bb) == 1 then c = c + 1 end
		bb = bb * 2
		k = k + 1
	end
	if c >= 7 then
		k, bb = 1, 1
		while k <= 16 do
			if k >= first and k <= last and PTTM_Bit(mk, bb) == 1 then mk = mk - bb end
			bb = bb * 2
			k = k + 1
		end
	end
	mk = mk + b
	PTTM_Set(F_FLOWER, mk)
	local fn = "M¹n §µ La Hoa"
	if tpl == 793 then fn = "M¹n Ch©u Sa Hoa" end
	local got = 0
	if PTTM_Get(F_1023S) == 1 and ((tpl == 792 and not PTTM_IsMa()) or (tpl == 793 and PTTM_IsMa())) then
		local n = PTTM_Cnt(F_1023C, 8)
		got = 1
		if n >= 8 then
			PTTM_Set(F_1023S, 2)
			Msg2Player("§· h¸i ®ñ 8 ®ãa " .. fn .. ", vÒ phôc mÖnh <color=yellow>Tu Hµnh S­<color>!")
		else
			Msg2Player(format("H¸i ®­îc %d/8 ®ãa ", n) .. fn .. ".")
		end
	end
	if GetTaskByte(PTTM_T_GUA, 3) == 2 then
		local gg = GetTaskByte(PTTM_T_GUA, 4)
		if (gg == 3 and tpl == 793) or (gg == 4 and tpl == 792) then
			PTTM_GuaStep(gg)
			got = 1
		end
	end
	if got == 0 then
		Talk(1, "", "Ng­¬i kh«ng cÇn h¸i hoa lóc nµy.")
	end
end
