-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Chuc Dung (tpl 781, 1668/3753): task 97 Bat Quai Luan Hoi (hexagram scrolls 6,1,447-454 with the VNG item
-- scripts \script\item\(gua juan)\*.lua, variables 1340/1341; 3 rounds a day) and task 1042 Van Canh Vien (Huyen Quang
-- Kinh 6,1,483, variable 1384, item script replaced by extra_tienma.py).
Include("\\script\\phongthan\\tienma\\tm_lib.lua")
CD_NEED = {}
CD_NEED[1] = 15
CD_NEED[2] = 5
CD_NEED[3] = 10
CD_NEED[4] = 10
CD_NEED[5] = 0
CD_NEED[6] = 30
CD_NEED[7] = 0
CD_NEED[8] = 0
CD_GUA = "|Cµn|§oµi|Ly|ChÊn|Tèn|Kh¶m|CÊn|Kh«n|"

function main()
	Say("<color=green>Chóc Dung<color>: ¢m d­¬ng sinh Th¸i cùc, Th¸i cùc sinh L­ìng nghi, L­ìng nghi sinh Tø t­îng, Tø t­îng sinh B¸t qu¸i... Ng­¬i muèn g×?", 3,
		"B¸t Qu¸i Lu©n Håi/cd_97", "V¹n C¶nh Viªn/cd_1042", "KÕt thóc ®èi tho¹i/no")
end

function cd_97()
	local st = GetTaskByte(PTTM_T_GUA, 3)
	local t = "<color=green>Chóc Dung<color>: "
	if st == 3 then
		Say(t .. "Ng­¬i ®· gi¶i ®­îc quÎ! Qu¶ lµ ng­êi cã duyªn.", 2, "NhËn th­ëng/cd_97done", "KÕt thóc ®èi tho¹i/no")
	elseif st == 2 then
		Talk(1, "", t .. "Ng­¬i ®ang gi¶i quÎ, xem sæ nhiÖm vô (F11) ®Ó biÕt c¸ch gi¶i.")
	elseif st == 1 then
		Say(t .. "H·y më <color=yellow>Qu¸i quyÓn<color> ta ®­a (nhÊp chuét ph¶i vµo nã). NÕu kh«ng më ®­îc, ta cã thÓ gi¶i quÎ gióp ng­¬i.", 2,
			"Nhê Chóc Dung më quÎ/cd_97open", "KÕt thóc ®èi tho¹i/no")
	else
		local r = PTTM_Get(F_97R)
		if r >= 3 then
			Talk(1, "", t .. "H«m nay ng­¬i ®· gi¶i 3 quÎ, ngµy mai h·y quay l¹i.")
			return
		end
		Say(t .. format("Ta cã 8 Qu¸i quyÓn, mçi quÎ mét kh¶o nghiÖm. H«m nay ng­¬i ®· gi¶i %d/3 quÎ. Rót mét quÎ chø?", r), 2,
			"Rót Qu¸i quyÓn/cd_97take", "KÕt thóc ®èi tho¹i/no")
	end
end

function cd_97take()
	local st = GetTaskByte(PTTM_T_GUA, 3)
	if st == 1 or st == 2 or st == 3 then return end
	if PTTM_Get(F_97R) >= 3 then return end
	if PTTM_FreeCells() < 1 then
		Talk(1, "", "Hµnh trang cÇn 1 « trèng.")
		return
	end
	local g = random(1, 8)
	AddNormalItem(6, 1, 446 + g, 0, 0, 0)
	SetTaskByte(PTTM_T_GUA, 3, 1)
	SetTaskByte(PTTM_T_GUA, 4, g)
	TaskNote(97, 0)
	Msg2Player("NhËn ®­îc Qu¸i quyÓn <color=yellow>" .. cd_name(g) .. "<color>. NhÊp chuét ph¶i ®Ó më qu¸i t­îng.")
end

function cd_name(g)
	local p, k, i = 1, 0, 1
	local s, e = 0, 0
	while i <= strlen(CD_GUA) do
		if strsub(CD_GUA, i, i) == "|" then
			k = k + 1
			if k == g then s = i + 1 end
			if k == g + 1 then e = i - 1 end
		end
		i = i + 1
	end
	return strsub(CD_GUA, s, e)
end

-- same effect as the VNG item script set_8gua() of the scroll (fallback when the scroll cannot be opened)
function cd_97open()
	if GetTaskByte(PTTM_T_GUA, 3) ~= 1 then return end
	local g = GetTaskByte(PTTM_T_GUA, 4)
	if g < 1 or g > 8 then g = 1 end
	if DelNormalItem(6, 1, 446 + g, 0) == 0 then DelNormalItem(6, 1, 454 + g, 0) end
	SetTaskByte(PTTM_T_GUA, 3, 2)
	SetTaskByte(PTTM_T_GUA, 4, g)
	SetTask(PTTM_T_GUAN, CD_NEED[g])
	if CD_NEED[g] > 0 then
		TaskNote(97, g + 1, 0)
	else
		TaskNote(97, g + 1)
	end
	Talk(1, "", "<color=green>Chóc Dung<color>: QuÎ <color=yellow>" .. cd_name(g) .. "<color> ®· më. Xem sæ nhiÖm vô (F11) ®Ó biÕt c¸ch gi¶i.")
end

function cd_97done()
	if GetTaskByte(PTTM_T_GUA, 3) ~= 3 then return end
	SetTaskByte(PTTM_T_GUA, 3, 0)
	PTTM_Set(F_97R, PTTM_Get(F_97R) + 1)
	TaskNote(97, -1)
	PTTM_Reward(GetLevel() * 3000, 10000)
end

-- 1042 Van Canh Vien
function cd_1042()
	local s = PTTM_Get(F_1042)
	local t = "<color=green>Chóc Dung<color>: "
	if s == 0 then
		Say(t .. "Háa ThÇn hoµi niÖm nh©n gian, muèn lµm mét tßa hoa viªn m« pháng c¶nh ®Ñp nh©n gian. CÇm <color=yellow>HuyÔn Quang KÝnh<color> nµy, t×m ®Õn n¬i gièng h×nh trªn kÝnh råi dïng kÝnh ë ®ã (7 n¬i).", 2,
			"NhËn nhiÖm vô V¹n C¶nh Viªn/cd_1042take", "KÕt thóc ®èi tho¹i/no")
	elseif s == 1 then
		local st = GetTaskByte(PTTM_T_WANJING, 1)
		if st >= 8 then
			Say(t .. "Ng­¬i ®· ghi l¹i ®ñ 7 c¶nh ®Ñp nh©n gian!", 2, "Phôc mÖnh/cd_1042done", "KÕt thóc ®èi tho¹i/no")
		elseif HaveNormalItem(6, 1, 483, 1) + HaveNormalItem(6, 1, 483, 0) <= 0 then
			Say(t .. "Ng­¬i lµm mÊt HuyÔn Quang KÝnh råi sao?", 2, "Xin l¹i HuyÔn Quang KÝnh/cd_1042again", "KÕt thóc ®èi tho¹i/no")
		else
			Talk(1, "", t .. format("§· ghi l¹i %d/7 c¶nh. Dïng HuyÔn Quang KÝnh ®Ó xem c¶nh tiÕp theo.", st - 1))
		end
	else
		Talk(1, "", t .. "V¹n C¶nh Viªn cña Háa ThÇn ®· thµnh, ®a t¹ ng­¬i.")
	end
end

function cd_1042take()
	if PTTM_Get(F_1042) ~= 0 then return end
	if GetLevel() < 23 then
		Talk(1, "", "CÇn ®¹t cÊp 23.")
		return
	end
	if PTTM_FreeCells() < 1 then
		Talk(1, "", "Hµnh trang cÇn 1 « trèng.")
		return
	end
	SetTask(PTTM_T_WANJING, 0)
	SetTaskByte(PTTM_T_WANJING, 1, 1)
	SetTaskByte(PTTM_T_WANJING, 2, random(1, 18))
	AddNormalItem(6, 1, 483, 1, 0, 0)
	PTTM_Set(F_1042, 1)
	TaskNote(1042, 0, 0)
	Msg2Player("NhËn ®­îc <color=yellow>HuyÔn Quang KÝnh<color>. NhÊp chuét ph¶i ®Ó xem c¶nh cÇn t×m.")
end

function cd_1042again()
	if PTTM_Get(F_1042) ~= 1 then return end
	if HaveNormalItem(6, 1, 483, 1) + HaveNormalItem(6, 1, 483, 0) > 0 then return end
	AddNormalItem(6, 1, 483, 1, 0, 0)
end

function cd_1042done()
	if PTTM_Get(F_1042) ~= 1 or GetTaskByte(PTTM_T_WANJING, 1) < 8 then return end
	if DelNormalItem(6, 1, 483, 1) == 0 then DelNormalItem(6, 1, 483, 0) end
	PTTM_Set(F_1042, 2)
	TaskNote(1042, -1)
	PTTM_Reward(800000, 50000)
end
