-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Tiep Dan Dao Nhan (tpl 767): Tay Ky, Trieu Ca and both camps of Bat Chu Thien Quan. Entry to Tien Ma gioi,
-- faction choice, start of the main chain 86/87/88 (Tien Ma weapon), way back to the cities.
Include("\\script\\phongthan\\tienma\\tm_lib.lua")

function main()
	if PTTM_Tlt("tiepdan", "TiÕp DÉn §¹o Nh©n") then return end
	local w = GetWorldPos()
	if w == PTTM_MAP then
		if GetTask(PTTM_T_MAIN) == 0 then
			Say("<color=green>TiÕp DÉn §¹o Nh©n<color>: BÊt Chu Thiªn Quan lµ cöa ngâ Tiªn Ma giíi. Phe cña ng­¬i: <color=yellow>" .. PTTM_PheName() .. "<color>. Ng­¬i cÇn g×?", 5,
				"NhËn nhiÖm vô chñ tuyÕn Tiªn Ma/tm_main_start", "H­íng dÉn Tiªn Ma giíi/tm_help", "VÒ T©y Kú/tm_go_tk", "VÒ TriÒu Ca/tm_go_tc", "KÕt thóc ®èi tho¹i/no")
		else
			Say("<color=green>TiÕp DÉn §¹o Nh©n<color>: BÊt Chu Thiªn Quan lµ cöa ngâ Tiªn Ma giíi. Phe cña ng­¬i: <color=yellow>" .. PTTM_PheName() .. "<color>. Ng­¬i cÇn g×?", 4,
				"H­íng dÉn Tiªn Ma giíi/tm_help", "VÒ T©y Kú/tm_go_tk", "VÒ TriÒu Ca/tm_go_tc", "KÕt thóc ®èi tho¹i/no")
		end
		return
	end
	if GetTask(PTTM_T_MAIN) == 0 then
		Say("<color=green>TiÕp DÉn §¹o Nh©n<color>: Phong ThÇn b¶ng l¹c xuèng nh©n gian, Tiªn Ma l­ìng giíi tranh ®o¹t kh«ng ngõng. Anh hïng tõ cÊp <color=yellow>" .. PTTM_ENTRY_LV .. "<color> cã thÓ theo ta ®Õn <color=yellow>BÊt Chu Thiªn Quan<color>.", 4,
			"§Õn BÊt Chu Thiªn Quan/tm_go", "NhËn nhiÖm vô chñ tuyÕn Tiªn Ma/tm_main_start", "H­íng dÉn Tiªn Ma giíi/tm_help", "KÕt thóc ®èi tho¹i/no")
	else
		Say("<color=green>TiÕp DÉn §¹o Nh©n<color>: Phong ThÇn b¶ng l¹c xuèng nh©n gian, Tiªn Ma l­ìng giíi tranh ®o¹t kh«ng ngõng. Anh hïng tõ cÊp <color=yellow>" .. PTTM_ENTRY_LV .. "<color> cã thÓ theo ta ®Õn <color=yellow>BÊt Chu Thiªn Quan<color>.", 3,
			"§Õn BÊt Chu Thiªn Quan/tm_go", "H­íng dÉn Tiªn Ma giíi/tm_help", "KÕt thóc ®èi tho¹i/no")
	end
end

function tm_help()
	Talk(4, "",
		"<color=green>TiÕp DÉn §¹o Nh©n<color>: ë BÊt Chu Thiªn Quan, <color=yellow>Tu Hµnh S­<color> dÉn d¾t nhiÖm vô chñ tuyÕn, <color=yellow>HuyÒn §« §¹i Ph¸p S­<color> (gÇn Linh Xµ thô) nhê diÖt Phi Thè vµ ¦u Trïng.",
		"<color=yellow>B¹ch H¹c §¹o Tr­ëng<color> (phe Tiªn) vµ <color=yellow>Linh Nha KiÕm Tiªn<color> (phe Ma) giao nhiÖm vô Phong Thó S¬n Hån; <color=yellow>Méc Tra<color> giao nhiÖm vô ngµy Nam Minh Ly Háa (9 vßng).",
		"PhÝa t©y nam cã <color=yellow>Chóc Dung<color> (B¸t Qu¸i, V¹n C¶nh Viªn), <color=yellow>N÷ Oa N­¬ng N­¬ng<color> (H« Tiªn Ho¸n Ma), <color=yellow>Ng­êi H¸i Thuèc<color> (Hµ §å); phÝa b¾c cã <color=yellow>Cöu Thiªn HuyÒn N÷<color> (Thiªn KiÕp); <color=yellow>§¹i Phu<color> ë hai doanh tr¹i giao Tr­ Lung Th¶o.",
		"CÊp Tiªn Ma ®­îc tÝnh b»ng cÊp nh©n vËt. NhiÖm vô chñ tuyÕn Tiªn Ma cÇn cÊp <color=yellow>" .. PTTM_MAIN_LV .. "<color>, nhËn t¹i ta. Hoµn thµnh Liªn Hoa ThÇn §¨ng, Tu Hµnh S­ sÏ ®­a ng­¬i ®Õn <color=yellow>BÊt Chu S¬n<color>.")
end

function tm_go()
	if GetLevel() < PTTM_ENTRY_LV then
		Talk(1, "", "<color=green>TiÕp DÉn §¹o Nh©n<color>: Tiªn Ma giíi hiÓm ¸c, ®¹t cÊp <color=yellow>" .. PTTM_ENTRY_LV .. "<color> råi h·y ®Õn.")
		return
	end
	if PTTM_Phe() == 0 then
		Say("<color=green>TiÕp DÉn §¹o Nh©n<color>: LÇn ®Çu ®Õn Tiªn Ma giíi, ng­¬i ph¶i chän phe. Phe Tiªn ®ãng ë phÝa ®«ng nam, phe Ma ë phÝa t©y b¾c BÊt Chu Thiªn Quan.", 3,
			"Gia nhËp Tiªn giíi/tm_phe_tien", "Gia nhËp Ma giíi/tm_phe_ma", "§Ó ta suy nghÜ/no")
		return
	end
	PTTM_GoCamp()
end

function tm_phe_tien()
	if PTTM_Phe() == 0 then SetTask(PTTM_T_PHE, 1) end
	Msg2Player("Ng­¬i ®· gia nhËp <color=yellow>Tiªn giíi<color>.")
	tm_go()
end

function tm_phe_ma()
	if PTTM_Phe() == 0 then SetTask(PTTM_T_PHE, 2) end
	Msg2Player("Ng­¬i ®· gia nhËp <color=yellow>Ma giíi<color>.")
	tm_go()
end

function tm_go_tk()
	NewWorld(PTTM_POS_TK[1], PTTM_POS_TK[2], PTTM_POS_TK[3])
	if SetFightState then SetFightState(0) end
end

function tm_go_tc()
	NewWorld(PTTM_POS_TC[1], PTTM_POS_TC[2], PTTM_POS_TC[3])
	if SetFightState then SetFightState(0) end
end

function tm_main_start()
	if GetTask(PTTM_T_MAIN) ~= 0 then return end
	if GetLevel() < PTTM_MAIN_LV then
		Talk(1, "", "<color=green>TiÕp DÉn §¹o Nh©n<color>: NhiÖm vô chñ tuyÕn Tiªn Ma cÇn ®¹t cÊp <color=yellow>" .. PTTM_MAIN_LV .. "<color>.")
		return
	end
	if PTTM_FreeCells() < 1 then
		Talk(1, "", "<color=green>TiÕp DÉn §¹o Nh©n<color>: Hµnh trang cÇn Ýt nhÊt 1 « trèng ®Ó nhËn vò khÝ Tiªn Ma giíi.")
		return
	end
	if GetPlayerType() == 0 then
		Say("<color=green>TiÕp DÉn §¹o Nh©n<color>: Tõ lóc Phong ThÇn b¶ng l¹c xuèng nh©n gian, vËn mÖnh cña ng­¬i b¾t ®Çu thay ®æi. H·y chän vò khÝ Tiªn Ma giíi:", 3,
			"Th­¬ng Khung (vò khÝ ng¾n)/tm_weapon_short", "§o¹n Nh¹c (vò khÝ dµi)/tm_weapon_long", "§Ó ta suy nghÜ/no")
		return
	end
	tm_give_weapon(0)
end

function tm_weapon_short()
	tm_give_weapon(0)
end

function tm_weapon_long()
	tm_give_weapon(1)
end

function tm_give_weapon(k)
	if GetTask(PTTM_T_MAIN) ~= 0 or GetLevel() < PTTM_MAIN_LV then return end
	local pt = GetPlayerType()
	local id = 84 + k
	if pt == 1 then id = 86 elseif pt == 2 then id = 87 end
	if AddNormalItemBind then
		AddNormalItemBind(0, 0, id, 1, 0, 0, 0)
	else
		AddNormalItem(0, 0, id, 1, 0, 0)
	end
	SetTask(PTTM_T_MAIN, 1)
	PTTM_Note(0)
	Msg2Player("NhËn ®­îc mét vò khÝ Tiªn Ma giíi. H·y ®Õn <color=yellow>BÊt Chu Thiªn Quan<color> t×m <color=yellow>Tu Hµnh S­<color>.")
	Talk(1, "", "<color=green>TiÕp DÉn §¹o Nh©n<color>: CÇm lÊy vò khÝ nµy. Khi cÊp Tiªn Ma ®¹t <color=yellow>15<color>, h·y ®Õn BÊt Chu Thiªn Quan t×m <color=yellow>Tu Hµnh S­<color> nhËn nhiÖm vô míi.")
end
