-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Huyen Do Dai Phap Su (tpl 779) beside Linh Xa thu: task 1024 Uu Trung Phu The, then 1025 Phi Tho Cot.
Include("\\script\\phongthan\\tienma\\tm_lib.lua")

function main()
	local q1 = PTTM_Get(F_1024)
	local q2 = PTTM_Get(F_1025)
	if q1 == 0 then
		Say("<color=green>HuyÒn §« §¹i Ph¸p S­<color>: Phi Thè th­êng quÇn tô ë BÊt Chu Thiªn Quan, gÇn ®©y l¹i léng hµnh ph¸ ho¹i c©y cèi. Ng­¬i gãp søc tiªu diÖt chóng chø?", 2,
			"NhËn nhiÖm vô ¦u Trïng Phô ThÓ/hd_take1024", "KÕt thóc ®èi tho¹i/no")
	elseif q1 == 1 then
		Talk(1, "", "<color=green>HuyÒn §« §¹i Ph¸p S­<color>: H·y ®¸nh b¹i <color=red>Phi Thè<color> (phÝa t©y nam Linh Xµ thô) ®Ó ®iÒu tra nguyªn nh©n.")
	elseif q1 == 2 then
		Talk(1, "", format("<color=green>HuyÒn §« §¹i Ph¸p S­<color>: Cßn ph¶i tiªu diÖt <color=red>%d<color> ¦u Trïng (phÝa nam Linh Xµ thô).", 20 - PTTM_Get(F_CNT1)))
	elseif q1 == 3 then
		Say("<color=green>HuyÒn §« §¹i Ph¸p S­<color>: Th× ra Phi Thè bÞ ¦u Trïng phô thÓ! Ng­¬i lµm rÊt tèt.", 2,
			"Phôc mÖnh/hd_done1024", "KÕt thóc ®èi tho¹i/no")
	elseif q2 == 0 then
		Say("<color=green>HuyÒn §« §¹i Ph¸p S­<color>: Phi Thè bÞ ¦u Trïng khèng chÕ, cÇn nghiªn cøu c¸ch trõ chóng. H·y b¾t cho ta <color=yellow>20<color> con Phi Thè.", 2,
			"NhËn nhiÖm vô Phi Thè Cèt/hd_take1025", "KÕt thóc ®èi tho¹i/no")
	elseif q2 == 1 then
		Talk(1, "", format("<color=green>HuyÒn §« §¹i Ph¸p S­<color>: §· b¾t %d/20 Phi Thè, cè lªn!", PTTM_Get(F_CNT2)))
	elseif q2 == 2 then
		Say("<color=green>HuyÒn §« §¹i Ph¸p S­<color>: §ñ 20 Phi Thè råi, ta cã thÓ nghiªn cøu c¸ch trÞ chóng.", 2,
			"Phôc mÖnh/hd_done1025", "KÕt thóc ®èi tho¹i/no")
	else
		Talk(1, "", "<color=green>HuyÒn §« §¹i Ph¸p S­<color>: §a t¹ ng­¬i ®· gióp BÊt Chu Thiªn Quan yªn æn.")
	end
end

function hd_take1024()
	if PTTM_Get(F_1024) ~= 0 then return end
	if PTTM_TmLevel() < 6 then
		Talk(1, "", "CÊp Tiªn Ma cÇn ®¹t 6.")
		return
	end
	PTTM_Set(F_1024, 1)
	TaskNote(1024, 0)
	Msg2Player("NhËn nhiÖm vô <color=yellow>¦u Trïng Phô ThÓ<color>: ®¸nh b¹i Phi Thè.")
end

function hd_done1024()
	if PTTM_Get(F_1024) ~= 3 then return end
	PTTM_Set(F_1024, 4)
	TaskNote(1024, -1)
	PTTM_Reward(200000, 20000)
end

function hd_take1025()
	if PTTM_Get(F_1024) ~= 4 or PTTM_Get(F_1025) ~= 0 then return end
	if PTTM_TmLevel() < 9 then
		Talk(1, "", "CÊp Tiªn Ma cÇn ®¹t 9.")
		return
	end
	PTTM_Set(F_1025, 1)
	PTTM_Set(F_CNT2, 0)
	TaskNote(1025, 0)
	Msg2Player("NhËn nhiÖm vô <color=yellow>Phi Thè Cèt<color>: ®¸nh b¹i (b¾t) 20 Phi Thè.")
end

function hd_done1025()
	if PTTM_Get(F_1025) ~= 2 then return end
	PTTM_Set(F_1025, 3)
	TaskNote(1025, -1)
	PTTM_Reward(300000, 30000)
end
