-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Linh Xa thu (tpl 775) at 222/225: main chain step 3 -> 5 (the hostile Linh Xa, tpl 806, appears beside the
-- player; killing it gives the snake scale, step 6). Can be called again if the snake vanished.
Include("\\script\\phongthan\\tienma\\tm_lib.lua")

function main()
	local m = GetTask(PTTM_T_MAIN)
	if m == 4 then
		Say("<color=green>Linh Xµ thô<color>: C©y cæ thô táa ra linh khÝ cña r¾n. Dïng DiÖp Tö Tiªu ch¨ng?", 2,
			"Thæi DiÖp Tö Tiªu/lx_call", "KÕt thóc ®èi tho¹i/no")
	elseif m == 5 then
		if PTTM_SummonAlive(PTTM_K_SNAKE) > 0 then
			Talk(1, "", "<color=green>Linh Xµ thô<color>: Linh Xµ ®ang ë gÇn ®©y, h·y mau chinh phôc nã!")
		else
			Say("<color=green>Linh Xµ thô<color>: Linh Xµ khÝ ®· tiªu t¸n. Thæi l¹i DiÖp Tö Tiªu?", 2,
				"Thæi DiÖp Tö Tiªu/lx_call", "KÕt thóc ®èi tho¹i/no")
		end
	else
		Talk(1, "", "<color=green>Linh Xµ thô<color>: Mét c©y cæ thô, rÔ c©y quÊn ®Çy v¶y r¾n.")
	end
end

function lx_call()
	local m = GetTask(PTTM_T_MAIN)
	if m ~= 4 and m ~= 5 then return end
	if m == 5 and PTTM_SummonAlive(PTTM_K_SNAKE) > 0 then return end
	local ni = PTTM_Summon(806, 75, "Linh Xµ", PTTM_K_SNAKE, 300)
	if ni <= 0 then
		Talk(1, "", "Linh Xµ ch­a xuÊt hiÖn, h·y thö l¹i ë chç trèng gÇn c©y.")
		return
	end
	if m == 4 then
		SetTask(PTTM_T_MAIN, 5)
	end
	PTTM_Note(5)
	Msg2Player("Linh Xµ ®· lé ra b¶n tÝnh hung tµn, ph¶i chinh phôc ®­îc nã míi nhËn ®­îc V¶y r¾n!")
end
