-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Other NPCs of Bat Chu Thien Quan (dispatch by template): Dai Phu (766, task 92 Tru Lung Thao, both camps),
-- tran phap Ho Phap (813 Luc Giap Phuoc Hon, 814 Ngu Hanh Thien Nguc), the NPCs of the task 92 talk lists
-- (Xich Tinh Tu 764, Tao Bao 759, Thu Kho 768, Tieu Thang 760, Thanh Hu 762, Cao Giac 774, Ma Le Tho 773,
-- O Van 769, Di Dau 770, Kim Quang 772), Tho Dong (777, task 96 step 4) and Kim Ha Dong Tu (763 here, task 96 step 6).
Include("\\script\\phongthan\\tienma\\tm_lib.lua")

function main(npc)
	local tpl = 0
	if npc and npc > 0 then tpl = GetNpcTemplateID(npc) end
	if tpl == 766 then
		dp_main()
	elseif tpl == 813 or tpl == 814 then
		dp_tran(tpl)
	elseif tpl == 777 then
		ms_thodong()
	elseif tpl == 763 then
		ms_kimha()
	elseif tpl == 764 then
		ms_say("xichtinhtu", "XÝch Tinh Tö", "BÊt Chu Thiªn Quan lµ n¬i Tiªn Ma giao tranh. §Ö tö XiÓn gi¸o ph¶i gi÷ v÷ng ®¹o t©m.")
	elseif tpl == 759 then
		ms_say("taobao", "Tµo B¶o", "Ta vµ Tiªu Th¨ng du ngo¹n tø h¶i, kh«ng ngê l¹i gÆp Phong ThÇn ®¹i kiÕp.")
	elseif tpl == 768 then
		ms_say("thukho", "Thñ Khè", "Kho cña doanh tr¹i do ta tr«ng coi, ®å ®¹c cña c¸c vÞ cø yªn t©m.")
	elseif tpl == 760 then
		ms_say("tieuthang", "Tiªu Th¨ng", "L¹c B¶o Kim TiÒn cña ta chuyªn thu ph¸p b¶o cña kÎ ®Þch.")
	elseif tpl == 762 then
		ms_say("thanhhu", "Thanh H­ §¹o Tr­ëng", "Thanh tÞnh v« vi, tu t©m d­ìng tÝnh míi lµ chÝnh ®¹o.")
	elseif tpl == 774 then
		ms_say("caogiac", "Cao Gi¸c", "Ta cã ThuËn Phong NhÜ, chuyÖn g× ë BÊt Chu Thiªn Quan còng kh«ng qua ®­îc tai ta.")
	elseif tpl == 773 then
		ms_say("molietho", "Ma LÔ Thä", "Tø §¹i Thiªn V­¬ng huynh ®Ö ta trÊn gi÷ doanh Ma, kÎ nµo d¸m x©m ph¹m!")
	elseif tpl == 769 then
		ms_say("ovan", "¤ V©n KiÕm Tiªn", "§Ö tö TiÖt gi¸o kh«ng sî bÊt kú ai.")
	elseif tpl == 770 then
		ms_say("cauthu", "Di §Çu KiÕm Tiªn", "S­ t«n Th«ng Thiªn Gi¸o Chñ ®· an bµi, chóng ta chØ cÇn tu©n lÖnh.")
	elseif tpl == 772 then
		ms_say("kimquang", "Kim Quang KiÕm Tiªn", "Kim quang chiÕu räi, yªu tµ khã lßng Èn nÊp.")
	else
		Talk(1, "", "...")
	end
end

function ms_say(key, name, line)
	if PTTM_Tlt(key, name) then return end
	Talk(1, "", "<color=green>" .. name .. "<color>: " .. line)
end

function ms_thodong()
	local t = "<color=green>Thî §ång<color>: "
	if PTTM_Get(F_96) == 4 then
		Say(t .. "Méc Trung Háa? Ta dïng gç ngµn n¨m rÌn ®ång, trong lß vÉn cßn mét ngän.", 2, "Xin Méc Trung Háa/ms_96", "KÕt thóc ®èi tho¹i/no")
		return
	end
	Talk(1, "", t .. "Lß rÌn cña ta ch­a bao giê t¾t löa.")
end

function ms_96()
	if PTTM_Get(F_96) ~= 4 then return end
	PTTM_Set(F_96, 5)
	TaskNote(96, 4)
	Msg2Player("NhËn ®­îc <color=yellow>Méc Trung Háa<color>. VÒ gÆp Liªn §¨ng Hé Sø hái Tam Muéi Háa.")
end

function ms_kimha()
	local t = "<color=green>Kim Hµ §ång Tö<color>: "
	if PTTM_Get(F_96) == 6 then
		Say(t .. "S­ phô sai ta mang <color=yellow>Nh©n Gian Háa<color> tõ Ngäc H­ Cung ®Õn cho Liªn §¨ng Hé Sø. Ng­¬i ®Õn ®óng lóc l¾m.", 2, "NhËn Nh©n Gian Háa/ms_kimha96", "KÕt thóc ®èi tho¹i/no")
		return
	end
	Talk(1, "", t .. "Ta tõ Ngäc H­ Cung ®Õn, phông mÖnh s­ phô ®i kh¾p n¬i.")
end

function ms_kimha96()
	if PTTM_Get(F_96) ~= 6 then return end
	PTTM_Set(F_96, 7)
	TaskNote(96, 6)
	Msg2Player("§· cã ®ñ Ngò Háa! VÒ gÆp <color=yellow>Liªn §¨ng Hé Sø<color> hîp thµnh Nh©n Gian Háa.")
end

-- 92 Tru Lung Thao (state: 1 talk, 2 catch Trung Hon, 3 tran phap, 4 report, 9 done)
function dp_main()
	local s = PTTM_Get(F_92S)
	local t = "<color=green>§¹i Phu<color>: "
	if s == 0 then
		Say(t .. "¦u Trïng trªn ng­êi Phi Thè ®­îc Tr¹nh Nanh hç trî, kh«ng thÓ diÖt trõ. ChØ cã thÓ dïng Tiªn Háa ®Ó luyÖn hãa. Ng­¬i gióp ta chuÈn bÞ <color=yellow>Tr­ Lung Th¶o<color> chø?", 2,
			"NhËn nhiÖm vô Tr­ Lung Th¶o/dp_take", "KÕt thóc ®èi tho¹i/no")
	elseif s == 1 then
		if PTTM_IsMa() then
			Talk(1, "", t .. "H·y lÇn l­ît nhê Cao Gi¸c, TiÕp DÉn §¹o Nh©n, Thñ Khè, Tu Hµnh S­, Ma LÔ Thä, Linh Nha KiÕm Tiªn, ¤ V©n KiÕm Tiªn, Di §Çu KiÕm Tiªn, Kim Quang KiÕm Tiªn chó nhËp ph¸p lùc.")
		else
			Talk(1, "", t .. "H·y lÇn l­ît nhê XÝch Tinh Tö, Tµo B¶o, Thñ Khè, Tu Hµnh S­, Tiªu Th¨ng, Méc Tra, TiÕp DÉn §¹o Nh©n, B¹ch H¹c §¹o Tr­ëng, Thanh H­ §¹o Tr­ëng chó nhËp ph¸p lùc.")
		end
	elseif s == 2 then
		Talk(1, "", t .. format("§· b¾t %d/5 Trïng Hån. Tiªu diÖt Tr¹nh Nanh sÏ cã x¸c suÊt b¾t ®­îc.", PTTM_Get(F_92C)))
	elseif s == 3 then
		if PTTM_IsMa() then
			Talk(1, "", t .. "Vµo <color=yellow>Ngò Hµnh Thiªn Ngôc trËn<color> (242/201) dïng Tr­ Lung Th¶o.")
		else
			Talk(1, "", t .. "§Õn <color=yellow>Lôc Gi¸p Ph­îc Hån trËn<color> (215/237) dïng Tr­ Lung Th¶o.")
		end
	elseif s == 4 then
		Say(t .. "Trïng Hån ®· bÞ luyÖn hãa, Phi Thè sÏ ®­îc gi¶i tho¸t!", 2, "Tr¶ nhiÖm vô/dp_done", "KÕt thóc ®èi tho¹i/no")
	else
		Talk(1, "", t .. "§a t¹ ng­¬i ®· gióp ta nghiªn cøu Trïng Hån.")
	end
end

function dp_take()
	if PTTM_Get(F_92S) ~= 0 then return end
	if GetLevel() < 18 then
		Talk(1, "", "CÇn ®¹t cÊp 18.")
		return
	end
	PTTM_Set(F_92S, 1)
	PTTM_Set(F_92M, 0)
	PTTM_Set(F_92C, 0)
	if PTTM_IsMa() then TaskNote(92, 4) else TaskNote(92, 0) end
	Msg2Player("NhËn nhiÖm vô <color=yellow>Tr­ Lung Th¶o<color>: nhê 9 ng­êi chó nhËp ph¸p lùc.")
end

function dp_tran(tpl)
	local want = 813
	if PTTM_IsMa() then want = 814 end
	local t = "<color=green>Hé Ph¸p<color>: "
	if tpl ~= want or PTTM_Get(F_92S) ~= 3 then
		Talk(1, "", t .. "TrËn ph¸p nµy ®Ó trÊn ¸p Trïng Hån, kh«ng phËn sù miÔn vµo.")
		return
	end
	Say(t .. "Ng­¬i mang theo Tr­ Lung Th¶o vµ Trïng Hån sao? H·y dïng trong trËn.", 2, "Dïng Tr­ Lung Th¶o/dp_use", "KÕt thóc ®èi tho¹i/no")
end

function dp_use()
	if PTTM_Get(F_92S) ~= 3 then return end
	PTTM_Set(F_92S, 4)
	TaskNote(92, 3)
	Msg2Player("Trïng Hån ®· bÞ luyÖn hãa! VÒ t×m <color=yellow>§¹i Phu<color> tr¶ nhiÖm vô.")
end

function dp_done()
	if PTTM_Get(F_92S) ~= 4 then return end
	PTTM_Set(F_92S, 9)
	TaskNote(92, -1)
	PTTM_Reward(600000, 40000)
end
