-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Bat Chu Son NPCs (B, dispatch by template): Son Than Hong Bac (860, adopted placeholder, task 1036), Duong Nham
-- (847, task 1037 Tien), Kinh Thien Thap (928 x3) + hoa than Dai Uy Thien Long (922, dialog summon) + Thien Nhac Ho
-- Phap Truong Lao (1112) of task 1037, Kim Tra (862, task 1040 Tien) / Duong Sam (861, task 1041 Ma), Thiet Quan Dao
-- Nhan (840) / Ban Minh Ton Gia (848) of task 1031, Thien Toan Tu (845 here, task 1030).
Include("\\script\\phongthan\\tienma\\tm_lib.lua")

function main(npc)
	local tpl = 0
	if npc and npc > 0 then tpl = GetNpcTemplateID(npc) end
	if tpl == 860 then
		b2_1036()
	elseif tpl == 847 then
		if PTTM_IsMa() then
			Talk(1, "", "<color=green>D­¬ng NhËm<color>: Ng­êi phe Ma h·y hái <color=yellow>Hång L­ §¬n Kh¸ch<color>.")
		else
			PTTM_B1037("D­¬ng NhËm")
		end
	elseif tpl == 928 then
		b2_tower()
	elseif tpl == 922 then
		b2_hoathan(npc)
	elseif tpl == 1112 then
		b2_elder()
	elseif tpl == 862 then
		b2_1040(nil, "Kim Tra")
	elseif tpl == 861 then
		b2_1040(1, "D­¬ng S©m")
	elseif tpl == 840 then
		b2_teacher(1, "ThiÕt Qu¸n §¹o Nh©n")
	elseif tpl == 848 then
		b2_teacher(2, "BÇn Minh T«n Gi¶")
	elseif tpl == 845 then
		b2_1030()
	else
		Talk(1, "", "...")
	end
end

function Timeout(npc)
	DelNpc(npc)
end

-- 1036 Thien Hanh Thuan Nghich (1 hunt 40, 2 report, 3 wait level 43, 4 ready to brew, 5 Si Nha, 6 report, 7 done)
function b2_1036()
	local s = PTTM_Get(F_1036S)
	local t = "<color=green>S¬n ThÇn Hång B¸c<color>: "
	if s == 0 then
		Say(t .. "Muèn luyÖn thÇn ®¬n cÇn linh khÝ cña <color=red>Phong Thó S¬n Hån<color> phe ®Þch. CÇm <color=yellow>VÞ TÕ L­<color>, ®¸nh b¹i 40 Phong Thó S¬n Hån bªn ®èi ®Þch trªn BÊt Chu S¬n.", 2,
			"NhËn nhiÖm vô Thiªn Hµnh ThuËn NghÞch/b2_1036take", "KÕt thóc ®èi tho¹i/no")
	elseif s == 1 then
		Talk(1, "", t .. format("§· thu %d/40 linh khÝ Phong Thó S¬n Hån.", PTTM_Get(F_1036C)))
	elseif s == 2 then
		Say(t .. "Háa hÇu ®· ®Õn!", 2, "Phôc mÖnh/b2_1036r1", "KÕt thóc ®èi tho¹i/no")
	elseif s == 3 then
		if GetLevel() < 43 then
			Talk(1, "", t .. "Sau cÊp 43 h·y quay l¹i t×m ta.")
		else
			Say(t .. "B©y giê cã thÓ luyÖn <color=yellow>Hoµng Lé §¬n<color>. Mçi l­ît sÏ cã <color=red>SÝ Nha<color> ®Õn trém thuèc, ®¸nh b¹i 5 con lµ thµnh c«ng.", 2,
				"NhËn VÞ TÕ L­ vµ Hoµng Lé §¬n/b2_1036p2", "KÕt thóc ®èi tho¹i/no")
		end
	elseif s == 4 or s == 5 then
		if s == 5 and PTTM_SummonAlive(PTTM_K_SINHA) > 0 then
			Talk(1, "", t .. "SÝ Nha ®ang trém thuèc, mau ®¸nh b¹i chóng!")
		else
			Say(t .. "Lß luyÖn ®¬n ®· s½n sµng.", 2, "B¾t ®Çu luyÖn ®¬n/b2_1036brew", "KÕt thóc ®èi tho¹i/no")
		end
	elseif s == 6 then
		Say(t .. "Thµnh c«ng mü m·n! Më VÞ TÕ L­ nhËn ®¬n d­îc ®i.", 2, "NhËn ®¬n d­îc/b2_1036r2", "KÕt thóc ®èi tho¹i/no")
	else
		Talk(1, "", t .. "BÊt Chu S¬n cã ng­¬i gióp søc, linh khÝ dåi dµo h¬n tr­íc.")
	end
end

function b2_1036take()
	if PTTM_Get(F_1036S) ~= 0 then return end
	if GetLevel() < 42 then
		Talk(1, "", "CÇn ®¹t cÊp 42.")
		return
	end
	PTTM_Set(F_1036S, 1)
	PTTM_Set(F_1036C, 0)
	TaskNote(1036, 1, 0)
end

function b2_1036r1()
	if PTTM_Get(F_1036S) ~= 2 then return end
	PTTM_Set(F_1036S, 3)
	TaskNote(1036, 5)
	PTTM_TuLuyen(500000)
end

function b2_1036p2()
	if PTTM_Get(F_1036S) ~= 3 or GetLevel() < 43 then return end
	PTTM_Set(F_1036S, 4)
	PTTM_Set(F_1036C, 0)
	TaskNote(1036, 6)
end

function b2_1036brew()
	local s = PTTM_Get(F_1036S)
	if s ~= 4 and s ~= 5 then return end
	if s == 5 and PTTM_SummonAlive(PTTM_K_SINHA) > 0 then return end
	local m, x, y = GetWorldPos()
	local n = 5 - PTTM_Get(F_1036C)
	local i = 1
	while i <= n do
		PTTM_SummonAt(921, 80, "SÝ Nha", PTTM_K_SINHA, 600, x - 6 + mod(i, 3) * 6, y + 3 + floor(i / 3) * 4)
		i = i + 1
	end
	PTTM_Set(F_1036S, 5)
	TaskNote(1036, 7, PTTM_Get(F_1036C))
	Msg2Player("<color=red>SÝ Nha<color> kÐo ®Õn trém thuèc! §¸nh b¹i chóng.")
end

function b2_1036r2()
	if PTTM_Get(F_1036S) ~= 6 then return end
	PTTM_Set(F_1036S, 7)
	TaskNote(1036, -1)
	PTTM_TuLuyen(600000)
end

-- 1037 Bach Xuyen Huy Tu: towers / hoa than / elder (giver dialog is PTTM_B1037 in tm_lib2? no: here + bcs1)
function b2_tower()
	local s = PTTM_Get(F_1037)
	if s ~= 1 and s ~= 2 then
		Talk(1, "", "<color=green>K×nh Thiªn Th¸p<color>: Tßa th¸p trÊn ¸p ®Þa khÝ BÊt Chu S¬n.")
		return
	end
	if PTTM_SummonAlive(PTTM_K_HOATHAN) > 0 then
		Talk(1, "", "<color=green>K×nh Thiªn Th¸p<color>: Hãa th©n cña §¹i Uy Thiªn Long ®ang ë gÇn ®©y, mau t×m!")
		return
	end
	Say("<color=green>K×nh Thiªn Th¸p<color>: Tßa th¸p cã thÓ khëi ®éng.", 2, "Khèng chÕ th¸p/b2_towerOn", "KÕt thóc ®èi tho¹i/no")
end

function b2_towerOn()
	local s = PTTM_Get(F_1037)
	if s ~= 1 and s ~= 2 then return end
	if PTTM_SummonAlive(PTTM_K_HOATHAN) > 0 then return end
	local m, x, y = GetWorldPos()
	local ni = PTTM_SummonAt(922, 80, "Hãa Th©n §¹i Uy Thiªn Long", PTTM_K_HOATHAN, 60, x + 6, y + 6)
	if ni <= 0 then return end
	SetNpcScript(ni, "\\script\\phongthan\\tienma\\npc_bcs2.lua")
	PTTM_Set(F_1037, 2)
	TaskNote(1037, 1)
	Msg2Player("§· khèng chÕ th¸p! Trong 1 phót t×m <color=yellow>hãa th©n cña §¹i Uy Thiªn Long<color>.")
end

function b2_hoathan(npc)
	if npc == nil or GetNpcParam(npc, 0) ~= GetPlayerID() or PTTM_Get(F_1037) ~= 2 then
		Talk(1, "", "<color=green>Hãa Th©n §¹i Uy Thiªn Long<color>: ...")
		return
	end
	PTTM_Set(F_1037, 3)
	TaskNote(1037, 2)
	SetNpcTimeout(npc, 18)
	Talk(1, "", "<color=green>Hãa Th©n §¹i Uy Thiªn Long<color>: Ph¸p lùc cña ta ®· håi phôc phÇn nµo. BÝ mËt BÊt Chu S¬n chØ ng­êi Thiªn Nh¹c biÕt. <color=yellow>Thiªn Nh¹c Hé Ph¸p Tr­ëng L·o<color> ë trªn ®µi cao phÝa b¾c.")
end

function b2_elder()
	local t = "<color=green>Thiªn Nh¹c Hé Ph¸p Tr­ëng L·o<color>: "
	if PTTM_Get(F_1037) ~= 3 then
		Talk(1, "", t .. "Thiªn Nh¹c canh gi÷ BÊt Chu S¬n tõ thêi th­îng cæ.")
		return
	end
	PTTM_Set(F_1037, 4)
	TaskNote(1037, 3, PTTM_Name1037())
	Talk(1, "", t .. "Ph¸p trËn Canh Quý Lôc Kú Phong th«ng ®Õn Ngôc Ph¸p S¬n ®ang gÆp nguy. VÒ b¸o víi " .. PTTM_Name1037() .. ".")
end

-- 1040 (Tien, Kim Tra) / 1041 (Ma, Duong Sam): 4 rounds a day (1 Huyet Yeu, 2 Ly Tran Tran, 3 ao anh, 5 report)
function b2_1040(ma, name)
	local t = "<color=green>" .. name .. "<color>: "
	if (ma and not PTTM_IsMa()) or (not ma and PTTM_IsMa()) then
		Talk(1, "", t .. "Hån ph¸ch cña ta bÞ yªu ma c­íp mÊt... Nh­ng ng­¬i kh«ng ph¶i ng­êi phe ta.")
		return
	end
	local id = PTTM_Q1040()
	local s = PTTM_Get(F_1040S)
	local r = PTTM_Get(F_1040R)
	if s == 0 then
		if r >= 4 then
			Talk(1, "", t .. "H«m nay ng­¬i ®· gióp ta 4 lÇn, ngµy mai h·y quay l¹i.")
			return
		end
		Say(t .. format("Ta th¸m thÝnh BÊt Chu S¬n, bÞ yªu ma c­íp mÊt mét hån mét ph¸ch. §¸nh <color=red>HuyÕt Yªu<color> hót hån cã lÏ sÏ ph¸t hiÖn ra ®iÒu g×. (H«m nay %d/4)", r), 2,
			"NhËn nhiÖm vô/b2_1040take", "KÕt thóc ®èi tho¹i/no")
	elseif s == 1 then
		Talk(1, "", t .. "H·y ®¸nh b¹i <color=red>HuyÕt Yªu<color> (phÝa ®«ng nam) ®Ó hót hån.")
	elseif s == 2 then
		Say(t .. "Ng­¬i lÊy ®­îc <color=yellow>Ly TrÇn TrËn<color>! Dïng nã sÏ vµo ®­îc ¶o ¶nh c¶nh, n¬i giam hån ph¸ch cña ta.", 2,
			"Dïng Ly TrÇn TrËn vµo ¶o ¶nh c¶nh/b2_1040enter", "KÕt thóc ®èi tho¹i/no")
	elseif s == 3 then
		if PTTM_SummonAlive(PTTM_K_AOANH) > 0 then
			Talk(1, "", t .. "H·y tiªu diÖt ¶o ¶nh ®Ó gi¶i cøu hån ph¸ch cña ta!")
		else
			PTTM_Set(F_1040S, 2)
			TaskNote(id, 6)
			Talk(1, "", t .. "Ng­¬i ®· rêi ¶o ¶nh c¶nh... Dïng l¹i Ly TrÇn TrËn ®Ó vµo lÇn n÷a.")
		end
	else
		Say(t .. "Hån Ph¸ch Tinh! Hån ph¸ch cña ta ®· trë vÒ!", 2, "Phôc mÖnh/b2_1040done", "KÕt thóc ®èi tho¹i/no")
	end
end

function b2_1040take()
	if PTTM_Get(F_1040S) ~= 0 or PTTM_Get(F_1040R) >= 4 then return end
	PTTM_Set(F_1040S, 1)
	TaskNote(PTTM_Q1040(), 1)
end

function b2_1040enter()
	if PTTM_Get(F_1040S) ~= 2 then return end
	local k = random(0, 3)
	local name = "¶o ¶nh Hçn §én"
	if k == 1 then name = "¶o ¶nh Cïng Kú" elseif k == 2 then name = "¶o ¶nh Thao ThiÕt" elseif k == 3 then name = "¶o ¶nh §µo Ngét" end
	if PTTM_Summon(980 + k, 80, name, PTTM_K_AOANH, 180) <= 0 then return end
	PTTM_Set(F_1040S, 3)
	TaskNote(PTTM_Q1040(), 3, name)
	Msg2Player("§· vµo ¶o ¶nh c¶nh! Tiªu diÖt <color=red>" .. name .. "<color> ®Ó gi¶i cøu hån ph¸ch.")
end

function b2_1040done()
	if PTTM_Get(F_1040S) ~= 5 then return end
	PTTM_Set(F_1040S, 0)
	PTTM_Set(F_1040R, PTTM_Get(F_1040R) + 1)
	TaskNote(PTTM_Q1040(), -1)
	PTTM_Reward(GetLevel() * 3000, 10000)
end

-- 1031 teachers: Thiet Quan (state 1 -> 2), Ban Minh (2 -> 3)
function b2_teacher(k, name)
	local t = "<color=green>" .. name .. "<color>: "
	if PTTM_Get(F_1031S) == k then
		PTTM_Set(F_1031S, k + 1)
		if k == 1 then
			TaskNote(1031, 1)
			Talk(1, "", t .. "Tu ®¹o dÜ phi th¨ng, c¨n khÝ lµ gèc. §i gÆp <color=yellow>BÇn Minh T«n Gi¶<color> nghe gi¶ng tiÕp.")
		else
			local third = "Nam Minh Tö"
			if PTTM_IsMa() then third = "Ly CÊu T«n Gi¶" end
			TaskNote(1031, 2, third)
			Talk(1, "", t .. "Duyªn ph¸p tïy t©m. §i gÆp <color=yellow>" .. third .. "<color> nghe gi¶ng tiÕp.")
		end
		return
	end
	Talk(1, "", t .. "§¹o ph¸p tù nhiªn.")
end

-- 1030 Linh Quang Sa Hien (F_1030S 1 = collecting, mask in F_1030M; 2 = done)
function b2_1030()
	local s = PTTM_Get(F_1030S)
	local t = "<color=green>Thiªn To¸n Tö<color>: "
	if s == 0 then
		Say(t .. "Muèn më Linh Quang cho Ph¸p khÝ, ph¶i qua kh¶o nghiÖm cña ta: thu thËp <color=yellow>Nh©n Hån Ch©u, §Þa Hån Ch©u, Thiªn Hån Ch©u<color> b»ng c¸ch tiªu diÖt Nanh, Phong Yªu, Sãi.", 2,
			"NhËn nhiÖm vô Linh Quang S¹ HiÖn/b2_1030take", "KÕt thóc ®èi tho¹i/no")
	elseif s == 1 then
		if PTTM_Get(F_1030M) >= 7 then
			Say(t .. "§ñ ba viªn Hån Ch©u råi!", 2, "Tr¶ nhiÖm vô/b2_1030done", "KÕt thóc ®èi tho¹i/no")
		else
			Talk(1, "", t .. "H·y tiªu diÖt Nanh (BÊt Chu Thiªn Quan), Phong Yªu vµ Sãi (BÊt Chu S¬n) ®Ó thu thËp Hån Ch©u.")
		end
	else
		Talk(1, "", t .. "Ng­¬i ®· cã t­ c¸ch më Linh Quang cho Ph¸p khÝ.")
	end
end

function b2_1030take()
	if PTTM_Get(F_1030S) ~= 0 then return end
	PTTM_Set(F_1030S, 1)
	PTTM_Set(F_1030M, 0)
	TaskNote(1030, 0)
end

function b2_1030done()
	if PTTM_Get(F_1030S) ~= 1 or PTTM_Get(F_1030M) < 7 then return end
	PTTM_Set(F_1030S, 2)
	TaskNote(1030, -1)
	PTTM_Reward(400000, 30000)
end
