-- Phong Than 2026-10-03 (tienma/tienma23): Tien Ma gioi phase 1-3. Generated by scratchpad\tienma\mk_tienma.py; edit the generator, not this file.
-- Shared library of the Tien Ma scripts (Bat Chu Thien Quan = runtime map 1073, Bat Chu Son = 1074).
-- Included by every NPC / monster script of script\phongthan\tienma\ and by the PAK death stubs of extra_tienma.py.
-- Tien Ma level: the engine compat GetPlayerExtLevel() returns the character level (ScriptFuns.cpp
-- LuaGetPlayerExtLevelCompat), AddOwnExtendExp() adds normal experience; this file follows that rule.
Include("\\script\\phongthan\\lib\\vng_tasknote.lua")
-- load the taskinfo texts now (top level of the script load), not lazily deep inside a kill handler
if PTTaskNote_Load then PTTaskNote_Load() end

PTTM_MAP = 1073
PTTM_MAP2 = 1074
PTTM_MAP3 = 1075
PTTM_ENTRY_LV = 75          -- teleport to Bat Chu Thien Quan (monsters there are level 70-74)
PTTM_MAIN_LV = 85           -- main chain 86/87/88 (end level of the 3-faction main chain 27-29)
-- task variables. The assigned range 2220-2279 is mostly used by VNG scripts (pet system "Phi Thang"
-- 2224-2241/2246-2251/2260-2262/2264-2277/2279, gift boxes 2220/2221/2273): only 2222 2223 2242 2245 2252 2254
-- 2256 2258 2259 2263 2278 are free. 2222 (main chain) and 2252 (faction) are plain values (read by tienma45);
-- the others hold several decimal fields (PTTM_Get / PTTM_Set with a field descriptor {var, digit, width, daily}).
PTTM_T_MAIN = 2222          -- main chain: 0 none, 1 step0 ... 7 step7, 8-19 Lien Hoa Than Dang, 14 phase 2 end,
                            -- 20-25 Bat Chu Son, 27 = phase 3 done (hand-over to tienma45: step 28 starts at 27)
PTTM_T_DAILY = 2245         -- Nam Minh Ly Hoa: day(6 digits)*100 + rounds*10 + state(0 idle,1 hunt,2 report)
PTTM_T_PHE = 2252           -- 1 Tien gioi, 2 Ma gioi
PTTM_P10 = {}
PTTM_P10[1] = 1
PTTM_P10[2] = 10
PTTM_P10[3] = 100
PTTM_P10[4] = 1000
PTTM_P10[5] = 10000
PTTM_P10[6] = 100000
PTTM_P10[7] = 1000000
PTTM_P10[8] = 10000000
PTTM_P10[9] = 100000000
PTTM_P10[10] = 1000000000
-- 2223: d0 1024 | d1-2 96 | d3 1042 | d4 1043 state | d5 1043 count | d6 1037 | d7 1030 state | d8 1030 mask
F_1024 = { 2223, 0, 1 }
F_96 = { 2223, 1, 2 }
F_1042 = { 2223, 3, 1 }
F_1043S = { 2223, 4, 1 }
F_1043C = { 2223, 5, 1 }
F_1037 = { 2223, 6, 1 }
F_1030S = { 2223, 7, 1 }
F_1030M = { 2223, 8, 1 }
-- 2258: d0 1025 | d1-2 lamp mask | d3 main sub (1 Hoa than, 2 Thuy than, 4 failed) | d4 1031 state | d5 1031 count
--       d6 1032 state | d7-8 1032 count
F_1025 = { 2258, 0, 1 }
F_LAMP = { 2258, 1, 2 }
F_SUB = { 2258, 3, 1 }
F_1031S = { 2258, 4, 1 }
F_1031C = { 2258, 5, 1 }
F_1032S = { 2258, 6, 1 }
F_1032C = { 2258, 7, 2 }
-- 2242: d0 89 | d1 92 state | d2-4 92 talk mask | d5 92 count | d6 1036 state | d7-8 1036 count
F_89 = { 2242, 0, 1 }
F_92S = { 2242, 1, 1 }
F_92M = { 2242, 2, 3 }
F_92C = { 2242, 5, 1 }
F_1036S = { 2242, 6, 1 }
F_1036C = { 2242, 7, 2 }
-- 2254: d0-1 Uu Trung count (1024) | d4-8 flower mask (16 flowers)
F_CNT1 = { 2254, 0, 2 }
F_FLOWER = { 2254, 4, 5 }
-- 2256: d0-1 Phi Tho count (1025) | daily: d2 1040 rounds | d3 1040 state | d4 1023 state | d5 1023 count
F_CNT2 = { 2256, 0, 2 }
F_1040R = { 2256, 2, 1, 1 }
F_1040S = { 2256, 3, 1, 1 }
F_1023S = { 2256, 4, 1, 1 }
F_1023C = { 2256, 5, 1, 1 }
-- 2259: d0-4 npc index of the player's last summon
F_SUMMON = { 2259, 0, 5 }
-- 2263 (daily): d0 97 rounds | d1 1026 rounds | d2 1026 state | d3 1026 count | d4 1027 state | d5 1027 count
--               d6 99/100 rounds | d7 99/100 state | d8 99/100 count
F_97R = { 2263, 0, 1, 1 }
F_1026R = { 2263, 1, 1, 1 }
F_1026S = { 2263, 2, 1, 1 }
F_1026C = { 2263, 3, 1, 1 }
F_1027S = { 2263, 4, 1, 1 }
F_1027C = { 2263, 5, 1, 1 }
F_99R = { 2263, 6, 1, 1 }
F_99S = { 2263, 7, 1, 1 }
F_99C = { 2263, 8, 1, 1 }
-- 2278: d0-3 day stamp (MMDD) of the daily fields | d4 103 state | d5 103 count | d6 1033/1034 state | d7-8 count
F_DAY = { 2278, 0, 4 }
F_103S = { 2278, 4, 1, 1 }
F_103C = { 2278, 5, 1, 1 }
F_1033S = { 2278, 6, 1, 1 }
F_1033C = { 2278, 7, 2, 1 }
-- VNG variables of the hexagram item scripts (\script\item\(gua juan)\*.lua, task 97): 1340 byte3 state (1 scroll given,
-- 2 solving, 3 solved), byte4 hexagram 1-8; 1341 remaining count. V¹n C¶nh Viªn item (task 1042): 1384.
PTTM_T_GUA = 1340
PTTM_T_GUAN = 1341
PTTM_T_WANJING = 1384

PTTM_MOB_SCRIPT = "\\script\\phongthan\\tienma\\mob_kill.lua"
PTTM_K_PACK = 7701          -- GetNpcParam(npc, 1) of the quest monster packs (ext\tienma.lua)
PTTM_K_BOSS = 7702          -- Phong Thu Son Hon of task 89
PTTM_K_SNAKE = 7703         -- Linh Xa of the main chain
PTTM_K_SUGIA = 7704         -- Lien Dang Su Gia (main 10 / 17)
PTTM_K_THACH = 7705         -- Thach Quai (main 22)
PTTM_K_NT = 7706            -- Xuat Khieu Nguyen Than (1027)
PTTM_K_WAVE = 7707          -- Hung Tien / Phi Tho Ma of the towers (1026)
PTTM_K_LONGMA = 7708        -- Long Ma (1043)
PTTM_K_THUCDUOC = 7709      -- Thuc Duoc Thu (97, hexagram Ton)
PTTM_K_KNSON = 7710         -- Ma Kham Nguyen (Son) (97, hexagram Can)
PTTM_K_TY = 7711            -- Thien Yet (103)
PTTM_K_TYP = 7712           -- Thien Yet phan than (103)
PTTM_K_SINHA = 7713         -- Si Nha (1036)
PTTM_K_AOANH = 7715         -- ao anh of task 1040/1041
PTTM_K_HOATHAN = 7716       -- hoa than Dai Uy Thien Long (1037, dialog summon)
-- templates (Npcs.txt data row): 739 Phi Tho, 808 Uu Trung, 740/741 Tranh/Nanh, 744/745 Ly Chau (Ma/Tien),
-- 750/751 Phong Thu Son Hon (Tien/Ma), 806 Linh Xa, 821 Lien Dang Su Gia, 877 Thach Quai, 743/783 Kham Nguyen,
-- 746 Soi, 885 Soi chua, 748/749 Phong Yeu (Tien/Ma), 747 Huyet Yeu, 927 La Hau, 921 Si Nha, 1059/1060 Thien Yet
PTTM_DAILY_MAX = 9
PTTM_POS_TIEN = { 1984, 3800 }
PTTM_POS_MA = { 1622, 3221 }
PTTM_POS_TK = { 1020, 1476, 3060 }
PTTM_POS_TC = { 1021, 1776, 3047 }

function no()
end

-- decimal field of a task variable; f = { var, first digit, width, daily }
function PTTM_Get(f)
	if f[4] then PTTM_DayCheck() end
	return mod(floor(GetTask(f[1]) / PTTM_P10[f[2] + 1]), PTTM_P10[f[3] + 1])
end

function PTTM_Set(f, v)
	if f[4] then PTTM_DayCheck() end
	local o = GetTask(f[1])
	local cur = mod(floor(o / PTTM_P10[f[2] + 1]), PTTM_P10[f[3] + 1])
	SetTask(f[1], o + (v - cur) * PTTM_P10[f[2] + 1])
end

-- daily fields: a new day clears 2263, the daily digits of 2256 and 2278 (d4-d8), and stamps 2278
function PTTM_DayCheck()
	local d = PTTM_Day4()
	if mod(GetTask(2278), 10000) ~= d then
		SetTask(2263, 0)
		SetTask(2278, d)
		SetTask(2256, mod(GetTask(2256), 100))
	end
end

function PTTM_Bit(v, b)
	return mod(floor(v / b), 2)
end

function PTTM_TmLevel()
	if GetPlayerExtLevel then
		local v = GetPlayerExtLevel()
		if v and v > 0 then return v end
	end
	return GetLevel()
end

function PTTM_NoteId()
	local pt = GetPlayerType()
	if pt == nil or pt < 0 or pt > 2 then pt = 0 end
	return 86 + pt
end

function PTTM_Note(step)
	TaskNote(PTTM_NoteId(), step)
end

function PTTM_Phe()
	return GetTask(PTTM_T_PHE)
end

function PTTM_IsMa()
	if GetTask(PTTM_T_PHE) == 2 then return 1 end
	return nil
end

function PTTM_PheName()
	if PTTM_Phe() == 2 then return "Ma giíi" end
	if PTTM_Phe() == 1 then return "Tiªn giíi" end
	return "ch­a chän phe"
end

function PTTM_Today6()
	local d = 0
	if date then
		d = tonumber(date("%Y%m%d"))
	elseif GetLocalDate then
		local s = GetLocalDate("%Y%m%d")
		if s then d = tonumber(s) end
	end
	if d == nil or d <= 0 then d = floor(SystemTime() / 86400) end
	return mod(d, 1000000)
end

function PTTM_Day4()
	local d = mod(PTTM_Today6(), 10000)
	if d <= 0 then d = 1 end
	return d
end

function PTTM_Reward(exp, cash)
	if exp and exp > 0 then AddOwnExp(exp) end
	if cash and cash > 0 then Earn(cash) end
	Msg2Player(format("NhËn ®­îc <color=yellow>%d<color> kinh nghiÖm vµ <color=yellow>%d<color> l­îng.", exp or 0, cash or 0))
end

-- Tien Ma training points (= normal experience on this server)
function PTTM_TuLuyen(n)
	local got = 0
	if AddOwnExtendExp then got = AddOwnExtendExp(n) end
	if got == nil or got <= 0 then AddOwnExp(n) end
	Msg2Player(format("NhËn ®­îc <color=yellow>%d<color> ®iÓm tu luyÖn Tiªn Ma giíi.", n))
end

function PTTM_FreeCells()
	if CalcFreeItemCellCount then
		local n = CalcFreeItemCellCount()
		if n then return n end
	end
	return 99
end

function PTTM_GoCamp()
	local p = PTTM_POS_TIEN
	if PTTM_Phe() == 2 then p = PTTM_POS_MA end
	NewWorld(PTTM_MAP, p[1], p[2])
	if SetFightState then SetFightState(1) end
end

-- quest summon at a cell of the player's map (1073/1074): owner = player id, timeout = secs
function PTTM_SummonAt(tpl, lv, name, kind, secs, x, y)
	local m = GetWorldPos()
	if m ~= PTTM_MAP and m ~= PTTM_MAP2 then return 0 end
	local sw = SubWorldID2Idx(m)
	if sw == nil or sw < 0 then return 0 end
	local ni = AddNpc(tpl, lv, sw, x * 32, y * 32, 1)
	if ni == nil or ni <= 0 then ni = AddNpc(tpl, lv, sw, (x + 2) * 32, y * 32, 1) end
	if ni == nil or ni <= 0 then ni = AddNpc(tpl, lv, sw, x * 32, (y + 2) * 32, 1) end
	if ni == nil or ni <= 0 then return 0 end
	SetNpcName(ni, name)
	SetNpcScript(ni, PTTM_MOB_SCRIPT)
	SetNpcParam(ni, 0, GetPlayerID())
	SetNpcParam(ni, 1, kind)
	SetNpcTimeout(ni, secs * 18)
	PTTM_Set(F_SUMMON, ni)
	return ni
end

-- beside the player
function PTTM_Summon(tpl, lv, name, kind, secs)
	local m, x, y = GetWorldPos()
	return PTTM_SummonAt(tpl, lv, name, kind, secs, x + 3, y + 3)
end

function PTTM_SummonAlive(kind)
	local ni = PTTM_Get(F_SUMMON)
	if ni > 0 and GetNpcParam(ni, 1) == kind and GetNpcParam(ni, 0) == GetPlayerID() then return ni end
	return 0
end

-- task 92 Tru Lung Thao: one-shot talk of a listed NPC (key) while the player is in the talk stage.
-- Returns 1 when the dialog was used for it (the caller then stops).
PTTM_TLT_TIEN = "|xichtinhtu|taobao|thukho|tuhanhsu|tieuthang|moctra|tiepdan|bachhac|thanhhu|"
PTTM_TLT_MA = "|caogiac|tiepdan|thukho|tuhanhsu|molietho|linhnha|ovan|cauthu|kimquang|"
function PTTM_Tlt(key, name)
	if PTTM_Get(F_92S) ~= 1 then return nil end
	local lst = PTTM_TLT_TIEN
	if PTTM_IsMa() then lst = PTTM_TLT_MA end
	local p = strfind(lst, "|" .. key .. "|", 1, 1)
	if p == nil then return nil end
	-- index 1..9 = number of "|" before p
	local k, i = 0, 1
	while i <= p do
		if strsub(lst, i, i) == "|" then k = k + 1 end
		i = i + 1
	end
	local b = PTTM_P10[1]
	i = 1
	while i < k do
		b = b * 2
		i = i + 1
	end
	local m = PTTM_Get(F_92M)
	if PTTM_Bit(m, b) == 1 then return nil end
	m = m + b
	PTTM_Set(F_92M, m)
	local c, j = 0, 1
	while j <= 256 do
		if PTTM_Bit(m, j) == 1 then c = c + 1 end
		j = j * 2
	end
	Talk(1, "", "<color=green>" .. name .. "<color>: §­îc, ta chó nhËp ph¸p lùc vµo <color=yellow>Tr­ Lung Th¶o<color> cho ng­¬i. (" .. c .. "/9)")
	if c >= 9 then
		PTTM_Set(F_92S, 2)
		PTTM_Set(F_92C, 0)
		TaskNote(92, 1, 5)
		Msg2Player("Tr­ Lung Th¶o ®· ®ñ ph¸p lùc! H·y b¾t 5 <color=red>Trïng Hån<color> (diÖt Tr¹nh Nanh cã x¸c suÊt xuÊt hiÖn).")
	end
	return 1
end

-- task 97: hexagram solved
function PTTM_GuaDone()
	SetTaskByte(PTTM_T_GUA, 3, 3)
	TaskNote(97, 1)
	Msg2Player("Gi¶i quÎ thµnh c«ng! VÒ gÆp <color=yellow>Chóc Dung<color>.")
end

-- task 97: one more item / kill for the counting hexagrams (1 Can, 2 Doai, 3 Ly, 4 Chan, 6 Kham)
function PTTM_GuaStep(g)
	local need = 15
	if g == 2 then need = 5 elseif g == 3 or g == 4 then need = 10 elseif g == 6 then need = 30 end
	local rem = GetTask(PTTM_T_GUAN) - 1
	if rem > need then rem = need - 1 end
	if rem <= 0 then
		SetTask(PTTM_T_GUAN, 0)
		PTTM_GuaDone()
		return
	end
	SetTask(PTTM_T_GUAN, rem)
	TaskNote(97, g + 1, need - rem)
end

function PTTM_Gua(tpl, kind)
	if GetTaskByte(PTTM_T_GUA, 3) ~= 2 then return end
	local g = GetTaskByte(PTTM_T_GUA, 4)
	if g == 1 and tpl == 739 then
		if random(1, 100) <= 50 then PTTM_GuaStep(1) end
	elseif g == 2 and (tpl == 740 or tpl == 741) then
		PTTM_GuaStep(2)
	elseif g == 6 and tpl == 739 then
		PTTM_GuaStep(6)
	elseif g == 7 and tpl == 878 and kind == PTTM_K_KNSON then
		PTTM_GuaDone()
	elseif g == 7 and (tpl == 783 or tpl == 743) then
		if PTTM_SummonAlive(PTTM_K_KNSON) == 0 and random(1, 100) <= 25 then
			if PTTM_Summon(878, 80, "Ma Kh©m Nguyªn (S¬n)", PTTM_K_KNSON, 300) > 0 then
				TaskNote(97, 10)
				Msg2Player("§Çu lÜnh <color=red>Ma Kh©m Nguyªn (S¬n)<color> ®· xuÊt hiÖn!")
			end
		end
	elseif g == 8 and (tpl == 783 or tpl == 743) then
		if random(1, 100) <= 10 then
			Msg2Player("§· tiªu diÖt <color=red>Ma Kh©m Nguyªn (§Þa)<color>!")
			PTTM_GuaDone()
		end
	elseif g == 5 and tpl == 879 and kind == PTTM_K_THUCDUOC then
		PTTM_GuaDone()
	end
end

-- kill credit for the current PlayerIndex: phase 1 quests
function PTTM_KillOne(tpl, kind)
	if tpl == 739 then
		if PTTM_Get(F_1024) == 1 then
			PTTM_Set(F_1024, 2)
			PTTM_Set(F_CNT1, 0)
			TaskNote(1024, 1, 20)
			Msg2Player("Phi Thè bÞ <color=red>¦u Trïng<color> phô thÓ! H·y tiªu diÖt 20 ¦u Trïng.")
		end
		if PTTM_Get(F_1025) == 1 then
			local c = PTTM_Get(F_CNT2) + 1
			PTTM_Set(F_CNT2, c)
			if c >= 20 then
				PTTM_Set(F_1025, 2)
				TaskNote(1025, 2)
				Msg2Player("§· b¾t ®ñ 20 Phi Thè, vÒ phôc mÖnh HuyÒn §« §¹i Ph¸p S­!")
			else
				TaskNote(1025, 1, c)
			end
		end
	elseif tpl == 808 then
		if PTTM_Get(F_1024) == 2 then
			local c = PTTM_Get(F_CNT1) + 1
			PTTM_Set(F_CNT1, c)
			if c >= 20 then
				PTTM_Set(F_1024, 3)
				TaskNote(1024, 2)
				Msg2Player("§· t×m ra nguyªn nh©n, vÒ b¸o cho HuyÒn §« §¹i Ph¸p S­!")
			else
				TaskNote(1024, 1, 20 - c)
			end
		end
	elseif tpl == 740 or tpl == 741 then
		if PTTM_Get(F_89) == 1 then
			PTTM_Set(F_89, 2)
			TaskNote(89, 1)
			Msg2Player("§¸nh b¹i Tr¹nh Nanh, nhËn ®­îc ph¸p b¶o <color=yellow>Táa Tinh Bµn<color>!")
		end
	elseif (tpl == 750 or tpl == 751) and kind == PTTM_K_BOSS then
		if PTTM_Get(F_89) == 3 then
			PTTM_Set(F_89, 4)
			TaskNote(89, 3)
			Msg2Player("§· khèng chÕ ®­îc Phong Thó S¬n Hån, vÒ giao nhiÖm vô!")
		end
	elseif tpl == 806 and kind == PTTM_K_SNAKE then
		if GetTask(PTTM_T_MAIN) == 5 then
			SetTask(PTTM_T_MAIN, 6)
			PTTM_Note(6)
			Msg2Player("Chinh phôc thµnh c«ng Linh Xµ, nhËn ®­îc <color=yellow>V¶y r¾n<color>! Mang vÒ cøu §¾c Kû.")
		end
	elseif tpl == 744 or tpl == 745 then
		local v = GetTask(PTTM_T_DAILY)
		if floor(v / 100) == PTTM_Today6() and mod(v, 10) == 1 then
			SetTask(PTTM_T_DAILY, v + 1)
			TaskNote(PTTM_DailyId(), 1)
			Msg2Player("NhËn ®­îc <color=yellow>Ly Háa néi ®¬n<color>, vÒ giao nhiÖm vô!")
		end
	end
end

-- all quests, called one after the other (flat: keeps the Lua stack shallow in the kill handler)
function PTTM_KillAll(tpl, kind)
	PTTM_KillOne(tpl, kind)
	PTTM_Gua(tpl, kind)
	PTTM_KillP2(tpl, kind)
	PTTM_KillP3(tpl, kind)
end

function PTTM_DailyId()
	if PTTM_Phe() == 2 then return 94 end
	return 93
end

-- killer and the team members on the same map get the credit
function PTTM_OnKill(npc)
	local tpl = GetNpcTemplateID(npc)
	local kind = GetNpcParam(npc, 1)
	local me = PlayerIndex
	local n = 0
	if GetTeamSize then n = GetTeamSize() end
	if n and n > 1 then
		local w = GetWorldPos()
		local i = 1
		while i <= n do
			local p = GetTeamMember(i)
			if p and p > 0 then
				PlayerIndex = p
				if GetWorldPos() == w then PTTM_KillAll(tpl, kind) end
			end
			i = i + 1
		end
		PlayerIndex = me
	else
		PTTM_KillAll(tpl, kind)
	end
end
Include("\\script\\phongthan\\tienma\\tm_lib2.lua")
