#ifndef KMAGICATTRIBH
#define KMAGICATTRIBH

#define INVALID_ATTRIB -1

// Numeric attribute IDs are part of the Phong Than data contract.  Keep this
// enum and the string table in KMagicDesc.cpp generated from the same registry.
enum MAGIC_ATTRIB
{
#define MAGIC_ATTRIB_ENTRY(id, symbol, key) symbol = id,
#include "KMagicAttribRegistry.inc"
#undef MAGIC_ATTRIB_ENTRY

	// Exclusive upper bound. The 358 source rows contain one duplicate key,
	// therefore the Phong Than numeric contract contains IDs 0..356.
	magic_normal_end = 357,

	// Exact compatibility aliases for names used by the inherited engine.
	magic_skill_attackradius = magic_skill_reserve1,
	magic_skill_eventskilllevel = magic_skill_reserve2,
	magic_skill_showevent = magic_skill_reserve3,
	magic_skill_appendskill = magic_skill_reserve4,
	magic_missle_missrate = magic_missle_reserve1,
	magic_missle_hitcount = magic_missle_reserve2,
	magic_vitality_v = magic_constitution_v,
	magic_energy_v = magic_intellect_v,
	magic_damage2addmana_p = magic_damagetomana_p,
	magic_lifemax_yan_v = magic_lifemax_v,
	magic_lifemax_yan_p = magic_lifemax_p,
	magic_manamax_yan_v = magic_manamax_v,
	magic_manamax_yan_p = magic_manamax_p,
	magic_fastwalkrun_yan_p = magic_fastwalkrun_p,
	magic_fasthitrecover_yan_v = magic_fasthitrecover_v,
	magic_attackspeed_yan_v = magic_attackspeed_v,
	magic_castspeed_yan_v = magic_castspeed_v,
	magic_earthres_yan_p = magic_earthres_p,
	magic_lightingres_yan_p = magic_lightingres_p,
	magic_fireres_yan_p = magic_fireres_p,
	magic_physicsres_yan_p = magic_physicsres_p,
	magic_coldres_yan_p = magic_coldres_p,
	magic_poisonres_yan_p = magic_poisonres_p,
	magic_allres_yan_p = magic_allres_p,
	magic_expenhance_p = magic_getmoreexp_p,
	magic_expenhance_s = magic_getmoreskillexp_p,

	// Removed Vo Lam attributes remain source-compatible while the remaining
	// inherited systems are ported. They are deliberately outside the VNG ID
	// range, so they cannot overwrite a real Phong Than handler.
	magic_legacy_begin = 1000,
	magic_married = magic_legacy_begin,
	magic_dec_percasttime,
	magic_require_translife,
	magic_require_fortune_value,
	magic_item_reserve2,
	magic_item_purple,
	magic_add_damage_p,
	magic_not_add_pkvalue_p,
	magic_add_boss_damage,
	magic_seriesdamage_p,
	magic_randmove,
	magic_fatallystrikeres_p,
	magic_dynamicmagicshield_v,
	magic_staticmagicshield_p,
	magic_ignoreskill_p,
	magic_poisondamagereturn_v,
	magic_poisondamagereturn_p,
	magic_returnskill_p,
	magic_skill_mintimepercastonhorse_v,
	magic_poison2decmana_p,
	magic_hide,
	magic_autodeathskill,
	magic_clearnegativestate,
	magic_returnres_p,
	magic_autoattackskill,
	magic_dec_percasttimehorse,
	magic_normal_reserve4,
	magic_lifereplenish_p,
	magic_frozen_action,
	magic_normal_reserve5,
	magic_sorbdamage_p,
	magic_autorescueskill,
	magic_autoreplyskill,
	magic_anti_hitrecover,
	magic_magicdamage_p,
	magic_anti_earthres_p,
	magic_anti_fireres_p,
	magic_anti_lightingres_p,
	magic_anti_physicsres_p,
	magic_anti_coldres_p,
	magic_anti_poisontimereduce_p,
	magic_do_hurt_p,
	magic_me2wooddamage_p,
	magic_skill_desc,
	magic_skill_collideevent,
	magic_skill_vanishedevent,
	magic_skill_startevent,
	magic_skill_flyevent,
	magic_skill_dohurt,
	magic_skill_bymissle,
	magic_candetonate1,
	magic_candetonate2,
	magic_candetonate3,
	magic_anti_fireres_yan_p,
	magic_anti_maxres_p,
	magic_anti_do_stun_p,
	magic_anti_stuntimereduce_p,
	magic_anti_earthres_yan_p,
	magic_anti_coldres_yan_p,
	magic_anti_do_hurt_p,
	magic_anti_allres_yan_p,
	magic_pk_punish_weaken,
	magic_block_rate,
	magic_enhancehit_rate,
	magic_sorbdamage_yan_p,
	magic_pk_punish_enhance,
	magic_me2earthdamage_p,
	magic_skill_enhance,
	magic_anti_physicsres_yan_p,
	magic_five_elements_enhance_v,
	magic_five_elements_resist_v,
	magic_anti_lightingres_yan_p,
	magic_metal2medamage_p,
	magic_reduceskillcd3,
	magic_clearallcd,
	magic_anti_enhancehit_rate,
	magic_me2metaldamage_p,
	magic_normal_reserve6,
	magic_normal_reserve7,
	magic_wood2medamage_p,
	magic_me2waterdamage_p,
	magic_water2medamage_p,
	magic_me2firedamage_p,
	magic_fire2medamage_p,
	magic_do_stun_p,
	magic_earth2medamage_p,
	magic_normal_reserve8,
	magic_enhancehiteffect_rate,
	magic_meleedamagereturnmana_p,
	magic_rangedamagereturnmana_p,
	magic_reduceskillcd1,
	magic_reduceskillcd2,
	magic_anti_sorbdamage_yan_p,
	magic_anti_block_rate,
	magic_addblockrate,
	magic_walkrunshadow,
	magic_returnskill2enemy,
	magic_manatoskill_enhance,
	magic_melee_returnres_p,
	magic_range_returnres_p,
	magic_addskilldamage1,
	magic_addskilldamage2,
	magic_addskilldamage3,
	magic_addskilldamage4,
	magic_addskilldamage5,
	magic_addskilldamage6,
	magic_addskilldamage7,
	magic_addskilldamage8,
	magic_addskilldamage9,
	magic_missle_exp_begin,
	magic_missle_range,
	magic_missle_dmginterval,
	magic_missle_zspeed,
	magic_missle_ablility,
	magic_missle_param,
	magic_missle_wait,
	magic_missle_fly,
	magic_missle_collide,
	magic_missle_vanish,
	magic_missle_exp_rev1,
	magic_missle_exp_rev2,
	magic_missle_exp_rev3,
	magic_missle_exp_rev4,
	magic_missle_exp_rev5,
	magic_missle_exp_end,
	magic_ignorenegativestate_p,
	magic_legacy_storage_end
};

// Historical spelling retained for translation units that still include it.
#define normal_reserve4 magic_normal_reserve4

extern const char MAGIC_ATTRIB_STRING[magic_normal_end + 1][100];

#endif
