[CmdletBinding()]
param(
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$VcBin = 'D:\VisualStudio6\VisualStudio6portable-langman.congdongcviet\Microsoft Visual Studio\VC98\Bin',
    [string]$VsCommonBin = 'D:\VisualStudio6\VisualStudio6portable-langman.congdongcviet\Microsoft Visual Studio\COMMON\MSDev98\Bin'
)

$ErrorActionPreference = 'Stop'
$libRoot = Join-Path $ProjectRoot 'ThirdParty\WindowsSDK\GDIPlus\Lib\x86'
$vendorLib = Join-Path $libRoot 'GdiPlus.WinSdk.lib'
$buildLib = Join-Path $libRoot 'GdiPlus.lib'
$manifestPath = Join-Path $libRoot 'GdiPlus.import.json'
$dumpbin = Join-Path $VcBin 'DUMPBIN.EXE'

foreach ($path in $vendorLib, $dumpbin) {
    if (-not (Test-Path -LiteralPath $path)) { throw "Thieu: $path" }
}
$env:PATH = "$VsCommonBin;$VcBin;$($env:PATH)"

# The official x86 SDK import objects expose decorated VC6 linker symbols but
# explicitly use Name type=undecorate, so Windows is asked for GdipXxx rather
# than the non-existent GdipXxx@N export. A DEF regenerated by VC6 LIB.EXE
# cannot preserve both sides of that mapping and must not be used here.
$requiredImports = [ordered]@{
    '_GdiplusStartup@12' = 'GdiplusStartup'
    '_GdiplusShutdown@4' = 'GdiplusShutdown'
    '_GdipGetImageEncodersSize@8' = 'GdipGetImageEncodersSize'
    '_GdipGetImageEncoders@12' = 'GdipGetImageEncoders'
    '_GdipSaveImageToFile@16' = 'GdipSaveImageToFile'
    '_GdipLoadImageFromStream@8' = 'GdipLoadImageFromStream'
    '_GdipAlloc@4' = 'GdipAlloc'
    '_GdipFree@4' = 'GdipFree'
    '_GdipDisposeImage@4' = 'GdipDisposeImage'
    '_GdipCloneImage@8' = 'GdipCloneImage'
}

$dump = (& $dumpbin /nologo /all $vendorLib 2>&1) -join "`n"
if ($LASTEXITCODE -ne 0) { throw 'DUMPBIN khong doc duoc GdiPlus.WinSdk.lib.' }
foreach ($entry in $requiredImports.GetEnumerator()) {
    $symbol = [regex]::Escape($entry.Key)
    $importName = [regex]::Escape($entry.Value)
    $pattern = "(?s)Symbol name\s*:\s*$symbol.{0,240}?Name type\s*:\s*undecorate.{0,240}?Name\s*:\s*$importName(?:\r?\n|$)"
    if ($dump -notmatch $pattern) {
        throw "Import ABI khong hop le: $($entry.Key) -> $($entry.Value)"
    }
}

Copy-Item -LiteralPath $vendorLib -Destination $buildLib -Force
$manifest = [ordered]@{
    Schema = 3
    Source = 'Microsoft.Windows.SDK.CPP.x86'
    PackageVersion = '10.0.22000.194'
    SourceLibrary = 'GdiPlus.WinSdk.lib'
    SourceSha256 = (Get-FileHash -LiteralPath $vendorLib -Algorithm SHA256).Hash
    BuildLibrary = 'GdiPlus.lib'
    BuildSha256 = (Get-FileHash -LiteralPath $buildLib -Algorithm SHA256).Hash
    Machine = 'I386'
    LinkerSymbolConvention = 'stdcall-decorated'
    DllImportNameType = 'undecorate'
    ValidatedImportCount = $requiredImports.Count
    ValidationTool = $dumpbin
}
[IO.File]::WriteAllText(
    $manifestPath,
    ($manifest | ConvertTo-Json),
    (New-Object Text.UTF8Encoding($false))
)

[pscustomobject]@{
    ValidatedImportCount = $requiredImports.Count
    Library = $buildLib
    Sha256 = $manifest.BuildSha256
}
