-- Phong Than 2026-10-05 (agent thanky): Than Ky (skills 1986-2000) + Vien Thuoc Tinh. Generated by
-- scratchpad\thanky\gen.py, do not edit by hand. Lua 4, ASCII (TCVN3 as escapes).
-- World-boss loot (dofile'd at call time by script\phongthan\boss\wb_lib.lua PTWB_GiveLoot, servertimer state).
-- Killer gets Manh Than Ky of a skill of his profession (stack) and maybe a Tui Thuoc Tinh. No top-level dofile.
PTTK_BOSS_MANH = { [40] = 3, [60] = 5, [80] = 8, [100] = 12 }
PTTK_BOSS_BAG = { [40] = 30, [60] = 40, [80] = 50, [100] = 60 }   -- % Tui Thuoc Tinh 6854
PTTK_BOSS_BAG2 = { [40] = 0, [60] = 0, [80] = 10, [100] = 25 }    -- % Tui Thuoc Tinh (Trung) 6982
PTTK_BOSS_SK = { [0] = { 8352 }, [1] = { 8354, 8355, 8356, 8357 }, [2] = { 8353 } }
PTTK_BOSS_NAME = { [8352] = "Huy\213t Nguy\214t Tr\182m", [8353] = "Huy\210n \182nh T\181n Hoa", [8354] = "Ph\203t N\233 H\225a Li\170n", [8355] = "L\171i H\225a To\181n Phong", [8356] = "Truy H\229n T\184n Hoa", [8357] = "V\185n Ki\213m Quy T\171ng" }

function PTTK_BossLoot(t, pi)
	PlayerIndex = pi
	local prof = GetProfession()
	local l = PTTK_BOSS_SK[prof]
	if l == nil then l = PTTK_BOSS_SK[random(0, 2)] end
	local mk = l[random(1, getn(l))]
	local n = PTTK_BOSS_MANH[t] or 3
	local got = 0
	local k = 1
	while k <= n do
		local r = AddNormalItemPile(6, 1, mk, 1, 0, 0)
		if r and r > 0 then got = got + 1 end
		k = k + 1
	end
	local bag = 0
	if random(1, 100) <= (PTTK_BOSS_BAG[t] or 0) then
		if AddNormalItem(6, 1, 6854, 1, 0, 0) > 0 then bag = bag + 1 end
	end
	if random(1, 100) <= (PTTK_BOSS_BAG2[t] or 0) then
		if AddNormalItem(6, 1, 6982, 1, 0, 0) > 0 then bag = bag + 1 end
	end
	if got + bag > 0 then
		Msg2Player("Boss r\172i " .. got .. " M\182nh Th\199n K\252 " .. PTTK_BOSS_NAME[mk] .. " (\174\241 30 m\182nh trong m\233t ch\229ng th\215 nh\202p ph\182i \174\211 gh\208p s\184ch)")
		if bag > 0 then Msg2Player("Boss r\172i th\170m " .. bag .. " T\243i Thu\233c T\221nh.") end
	end
	return got + bag
end
