-- Phong Than 2026-10-05 (agent thanky): Than Ky (skills 1986-2000) + Vien Thuoc Tinh. Generated by
-- scratchpad\thanky\gen.py, do not edit by hand. Lua 4, ASCII (TCVN3 as escapes).
-- Manh Than Ky 6/1/8352..8357 (ptfix magicscript column 15 points here). Logic: tk_lib.lua PTTK_UseManh.
Include("\\script\\phongthan\\thanky\\tk_lib.lua")

function main(nItemIdx)
	return PTTK_UseManh(nItemIdx)
end
