-- Phong Than 2026-10-02 (agent bikip): profession secret books ("bi kip"), shared logic.
-- Generated by scratchpad\bikip\gen_bikip.py, do not edit by hand.
--  * VNG skill books are item genre 7 (settings\item\001\skillbook.txt). The rebuilt engine never runs
--    a script for genre 7 (KItemList::ExecuteScript) and KBuySell cannot generate them, so they could be
--    neither bought nor used. Each book now also exists as a magicscript item 6/1/(62000+skill) with
--    its own script \script\phongthan\item\bikip_<skill>.lua (right click = learn the skill).
--  * Vo su Tay Ky / Trieu Ca: "Dong sach" (VNG: bind Khong Thu pages + crystals into a book, may fail),
--    profession book shops, and conversion of old genre-7 books into bi kip.
-- Lua 4: no local function, no true/false. File stays ASCII (TCVN3 escapes).

PTBK_KEY_BASE = 62000
PTBK_BOOK = {}      -- [skill] = { profession (-1 = any), required level, name, genre-7 detail }
PTBK_RECIPE = {}    -- [skill] = { page detail (8/x/2), pages, material (3/x), materials, success, out of }
PTBK_CONS = {}      -- [page] = { { genre, detail, particular, count, name }, ... } failure gifts (VNG)
PTBK_CRAFT = {}     -- [profession] = menu order of craftable books
PTBK_PAGE = {}
PTBK_MAT = {}
PTBK_PROF = { [0] = "Gi\184p S\220", [1] = "\167\185o S\220", [2] = "D\222 Nh\169n" }
if PTBK_SHOP_SALE == nil then PTBK_SHOP_SALE = {} end

PTBK_BOOK[3] = { 1, 4, "Ch\173\235ng T\169m L\171i", 0 }
PTBK_BOOK[4] = { 1, 6, "L\173u Tinh Th\185ch", 1 }
PTBK_BOOK[5] = { 1, 8, "B\168ng Tuy\213t \167\185n", 2 }
PTBK_BOOK[6] = { 1, 10, "T\221ch L\222ch H\225a", 3 }
PTBK_BOOK[7] = { 1, 14, "Tinh Th\171ng L\171i H\214", 4 }
PTBK_BOOK[8] = { 1, 18, "Thi\170n Phong \167\222a Nh\203n", 5 }
PTBK_BOOK[9] = { 1, 22, "B\168ng C\172 Tuy\213t C\232t", 6 }
PTBK_BOOK[10] = { 1, 26, "Phong L\169m H\225a S\172n", 7 }
PTBK_BOOK[11] = { 1, 30, "H\185n \167\222a L\171i", 8 }
PTBK_BOOK[12] = { 1, 34, "Tinh Th\171ng Th\230 H\214", 9 }
PTBK_BOOK[13] = { 1, 38, "Thi\213t M\183 B\168ng Qua", 10 }
PTBK_BOOK[14] = { 1, 42, "Tinh Th\171ng H\225a H\214", 11 }
PTBK_BOOK[15] = { 1, 46, "Phong V\169n L\171i \167\233ng", 12 }
PTBK_BOOK[16] = { 1, 50, "Ng\242 Nh\185c Tri\210u T\171ng", 13 }
PTBK_BOOK[17] = { 1, 54, "Tinh Th\171ng B\168ng H\214", 14 }
PTBK_BOOK[18] = { 1, 58, "Th\203p Ph\173\172ng Li\214t H\225a", 15 }
PTBK_BOOK[19] = { 1, 62, "L\171i Phong Gi\184p", 16 }
PTBK_BOOK[20] = { 1, 66, "Thi\170n B\168ng \167\222a Li\214t", 17 }
PTBK_BOOK[21] = { 1, 70, "B\168ng Phong B\185o", 18 }
PTBK_BOOK[22] = { 1, 74, "Ch\243c Dung Ch\169n Kh\221", 19 }
PTBK_BOOK[23] = { 1, 78, "L\171i \167\233ng C\246u Thi\170n", 20 }
PTBK_BOOK[24] = { 1, 82, "Huy\210n N\247 B\230 Thi\170n", 21 }
PTBK_BOOK[25] = { 1, 86, "B\168ng Phong V\185n L\253", 22 }
PTBK_BOOK[26] = { 1, 90, "Tam Mu\233i Ch\169n H\225a", 23 }
PTBK_BOOK[27] = { 0, 6, "T\213 Huy\213t Tr\182m", 24 }
PTBK_BOOK[28] = { 0, 12, "L\168ng Ba Vi B\233", 25 }
PTBK_BOOK[29] = { 0, 18, "Khai S\172n Tr\182m", 26 }
PTBK_BOOK[30] = { 0, 24, "H\229i Phong Tr\182m", 27 }
PTBK_BOOK[31] = { 0, 30, "\167i\214n Quang Tr\182m", 28 }
PTBK_BOOK[32] = { 0, 36, "Ho\181nh Kh\171ng Tr\182m", 29 }
PTBK_BOOK[33] = { 0, 42, "Tinh Th\171ng \167o\182n \167ao", 30 }
PTBK_BOOK[34] = { 0, 42, "Tinh Th\171ng Tr\173\234ng \167ao", 31 }
PTBK_BOOK[35] = { 0, 48, "Tam \167\199u L\244c Th\241", 32 }
PTBK_BOOK[36] = { 0, 54, "Huy\210n B\168ng Tr\182m", 33 }
PTBK_BOOK[37] = { 0, 60, "H\225a Quang Tr\182m", 34 }
PTBK_BOOK[38] = { 0, 66, "Li\170n Ho\181n Tr\182m", 35 }
PTBK_BOOK[39] = { 0, 72, "L\185c \167\222a Tr\182m", 36 }
PTBK_BOOK[40] = { 0, 78, "Thu\199n D\173\172ng H\233 Th\211", 37 }
PTBK_BOOK[41] = { 0, 84, "Thi\170n Qu\169n Tr\182m", 38 }
PTBK_BOOK[42] = { 0, 90, "Khuynh Th\181nh Nh\202t K\221ch", 39 }
PTBK_BOOK[43] = { 2, 10, "Kim Cang Ch\243", 40 }
PTBK_BOOK[44] = { 2, 20, "Th\171i Th\169n Ch\243", 41 }
PTBK_BOOK[45] = { 2, 30, "B\230 T\169m Ch\243", 42 }
PTBK_BOOK[46] = { 2, 40, "C\173\234ng C\171ng Ch\243", 43 }
PTBK_BOOK[47] = { 2, 50, "Ph\184 Gi\184p Ch\243", 44 }
PTBK_BOOK[48] = { 2, 60, "B\229 \167\210 Ch\243", 45 }
PTBK_BOOK[49] = { 2, 70, "Tr\182m T\169m Ch\243", 46 }
PTBK_BOOK[50] = { 2, 80, "T\203t Phong Ch\243", 47 }
PTBK_BOOK[51] = { 2, 90, "V\185n C\232t To\181n Kh\171", 48 }
PTBK_BOOK[62] = { -1, 1, "B\181n C\230 Khai Thi\170n", 58 }
PTBK_BOOK[128] = { -1, 1, "Ban M\171n L\233ng Ph\241", 59 }
PTBK_BOOK[450] = { 2, 5, "L\249c S\220 T\213", 49 }
PTBK_BOOK[451] = { 2, 15, "Tr\173\234ng Cung T\213", 50 }
PTBK_BOOK[452] = { 2, 25, "Thi\170n V\242 T\213", 51 }
PTBK_BOOK[453] = { 2, 35, "Li\170n N\231 T\213", 52 }
PTBK_BOOK[454] = { 2, 45, "H\225a L\171i T\213", 53 }
PTBK_BOOK[455] = { 2, 55, "To\184i C\232t T\213", 54 }
PTBK_BOOK[456] = { 2, 65, "L\173u Tinh T\213", 55 }
PTBK_BOOK[457] = { 2, 75, "Truy H\229n T\213", 56 }
PTBK_BOOK[458] = { 2, 85, "Phong Quy\211n T\181n V\169n", 57 }

PTBK_RECIPE[12] = { 139, 1, 77, 1, 3, 10 }
PTBK_RECIPE[13] = { 139, 1, 77, 1, 5, 10 }
PTBK_RECIPE[14] = { 139, 2, 77, 1, 2, 10 }
PTBK_RECIPE[15] = { 139, 2, 77, 1, 3, 10 }
PTBK_RECIPE[16] = { 139, 2, 77, 1, 15, 100 }
PTBK_RECIPE[17] = { 140, 1, 28, 1, 3, 10 }
PTBK_RECIPE[18] = { 140, 1, 28, 1, 15, 100 }
PTBK_RECIPE[19] = { 140, 2, 28, 1, 2, 10 }
PTBK_RECIPE[20] = { 140, 2, 28, 1, 3, 10 }
PTBK_RECIPE[21] = { 140, 2, 28, 1, 3, 10 }
PTBK_RECIPE[22] = { 141, 1, 79, 1, 2, 10 }
PTBK_RECIPE[23] = { 141, 1, 79, 1, 15, 100 }
PTBK_RECIPE[24] = { 141, 2, 79, 1, 2, 10 }
PTBK_RECIPE[25] = { 141, 2, 79, 1, 15, 100 }
PTBK_RECIPE[26] = { 142, 1, 79, 3, 1, 10 }
PTBK_RECIPE[32] = { 139, 1, 77, 1, 2, 10 }
PTBK_RECIPE[33] = { 139, 2, 77, 1, 3, 10 }
PTBK_RECIPE[34] = { 139, 2, 77, 1, 3, 10 }
PTBK_RECIPE[35] = { 139, 2, 77, 1, 5, 100 }
PTBK_RECIPE[36] = { 140, 1, 28, 1, 3, 10 }
PTBK_RECIPE[37] = { 140, 1, 28, 1, 2, 10 }
PTBK_RECIPE[38] = { 140, 2, 28, 1, 15, 100 }
PTBK_RECIPE[39] = { 140, 2, 28, 1, 15, 100 }
PTBK_RECIPE[40] = { 141, 1, 79, 1, 15, 100 }
PTBK_RECIPE[41] = { 141, 2, 79, 1, 15, 100 }
PTBK_RECIPE[42] = { 142, 1, 79, 3, 1, 10 }
PTBK_RECIPE[46] = { 139, 2, 77, 1, 3, 10 }
PTBK_RECIPE[47] = { 140, 1, 28, 1, 2, 10 }
PTBK_RECIPE[48] = { 140, 2, 28, 1, 3, 10 }
PTBK_RECIPE[49] = { 140, 2, 28, 1, 2, 10 }
PTBK_RECIPE[50] = { 141, 2, 79, 1, 2, 10 }
PTBK_RECIPE[51] = { 142, 1, 79, 3, 1, 10 }
PTBK_RECIPE[62] = { 139, 1, 0, 0, 1, 1 }
PTBK_RECIPE[128] = { 139, 1, 0, 0, 1, 1 }
PTBK_RECIPE[453] = { 139, 1, 77, 1, 5, 100 }
PTBK_RECIPE[454] = { 139, 2, 77, 1, 15, 100 }
PTBK_RECIPE[455] = { 140, 1, 28, 1, 3, 10 }
PTBK_RECIPE[456] = { 140, 2, 28, 1, 15, 100 }
PTBK_RECIPE[457] = { 141, 1, 79, 1, 15, 100 }
PTBK_RECIPE[458] = { 142, 1, 79, 3, 1, 10 }

PTBK_CONS[139] = { { 5, 0, 0, 1, "H\229i Th\181nh Ph\239" }, { 6, 1, 12, 1, "Th\168m" }, { 3, 62, 0, 1, "Th\230 Linh Ph\239" } }
PTBK_CONS[140] = { { 8, 57, 2, 3, "Tuy\213t Qu\184i Ph\239" }, { 8, 104, 2, 3, "H\225a Di\214n Ph\239" }, { 8, 85, 2, 3, "Ki\213m Nh\169n Ph\239" }, { 3, 63, 0, 1, "Th\241y Linh Ph\239" } }
PTBK_CONS[141] = { { 8, 35, 2, 1, "Di Ngo\185i Ph\239" }, { 8, 48, 2, 1, "Ph\243c H\233 Ph\239" }, { 3, 64, 0, 1, "H\225a Linh Ph\239" } }
PTBK_CONS[142] = { { 8, 159, 2, 1, "Di Ngo\185i Ph\239 (Si\170u C\202p)" }, { 3, 65, 0, 1, "Phong Linh Ph\239" } }

PTBK_CRAFT[0] = { 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 62, 128 }
PTBK_CRAFT[1] = { 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 62, 128 }
PTBK_CRAFT[2] = { 46, 47, 48, 49, 50, 51, 453, 454, 455, 456, 457, 458, 62, 128 }

PTBK_PAGE[139] = "B\185ch Kh\171ng Th\173"
PTBK_PAGE[140] = "Lam Kh\171ng Th\173"
PTBK_PAGE[141] = "H\229ng Kh\171ng Th\173"
PTBK_PAGE[142] = "Ho\181ng Kh\171ng Th\173"

PTBK_MAT[28] = "H\229ng Th\241y Tinh"
PTBK_MAT[77] = "M\182nh H\229ng Th\241y Tinh"
PTBK_MAT[79] = "H\229ng B\182o Th\185ch"

function no_ptbk()
end

function PTBK_Show(msg)
	Msg2Player(msg)
	Say(msg, 1, "\167\227ng/no_ptbk")
end

function PTBK_Log(tag)
	if openfile == nil or date == nil then return end
	local fh = openfile("admin_bridge\\token.log", "a")
	if fh then
		write(fh, date("%Y-%m-%d %H:%M:%S") .. "\tbikip\t" .. tag .. "\n")
		closefile(fh)
	end
end

function PTBK_ProfName(p)
	if p == nil or p < 0 then return "m\228i ph\184i" end
	return PTBK_PROF[p] or ""
end

-- learn the skill of a book; the item is removed only when the skill really was learned
function PTBK_UseBook(nItemIdx, sk)
	local b = PTBK_BOOK[sk]
	if b == nil then
		PTBK_Show("Kh\171ng nh\203n ra b\221 k\221p n\181y.")
		return 0
	end
	PTBK_Log("use skill=" .. sk .. " prof=" .. GetProfession() .. " lv=" .. GetLevel() .. " have=" .. (HaveMagic(sk) or -9))
	if b[1] >= 0 and GetProfession() ~= b[1] then
		PTBK_Show("B\221 k\221p " .. b[3] .. " ch\216 d\181nh cho ph\184i " .. PTBK_ProfName(b[1]) .. ".")
		return 0
	end
	if GetLevel() < b[2] then
		PTBK_Show("C\199n \174\185t c\202p " .. b[2] .. " m\237i l\220nh h\233i \174\173\238c " .. b[3] .. ".")
		return 0
	end
	local lv = HaveMagic(sk)
	if lv ~= nil and lv > 0 then
		PTBK_Show("Ng\173\172i \174\183 l\220nh h\233i " .. b[3] .. " (c\202p " .. lv .. "), b\221 k\221p v\201n c\223n. Mu\232n m\185nh h\172n h\183y d\239ng \174i\211m k\252 n\168ng v\181 luy\214n t\203p.")
		return 0
	end
	if lv ~= nil and lv == 0 then SetSkillLevel(sk, 1) end
	AddMagic(sk, 1)
	local nl = GetMagicLevel(sk)
	if nl == nil or nl <= 0 then
		PTBK_Show("L\220nh h\233i th\202t b\185i, b\221 k\221p v\201n c\223n.")
		return 0
	end
	RemoveItem(nItemIdx, 1, 0)
	PTBK_Log("learned skill=" .. sk .. " level=" .. nl)
	PTBK_Show("\167\183 l\220nh h\233i " .. b[3] .. " (c\202p 1). D\239ng \174i\211m k\252 n\168ng \174\211 n\169ng c\202p.")
	return 0
end

-- VNG genre-7 book (skillbook.txt): the particular is the skill id
function PTBK_UseSkillBook7(nItemIdx)
	local sk = GetItemPartByID(nItemIdx)
	if sk == nil or PTBK_BOOK[sk] == nil then
		PTBK_Show("Kh\171ng nh\203n ra b\221 k\221p n\181y.")
		return 0
	end
	return PTBK_UseBook(nItemIdx, sk)
end

-- ---------------------------------------------------------------- Vo su: shops
function PTBK_ShopMenu()
	local p = GetProfession()
	local s = PTBK_SHOP_SALE[p]
	if s == nil or s <= 0 then
		Talk(1, "no_ptbk", "Ta ch\216 b\184n b\221 k\221p cho Gi\184p S\220, \167\185o S\220 v\181 D\222 Nh\169n.")
		return
	end
	CloseDialog()
	Sale(s)
end

-- ---------------------------------------------------------------- Vo su: "dong sach" (VNG crafting)
function PTBK_CraftMenu()
	local p = GetProfession()
	local l = PTBK_CRAFT[p]
	if l == nil then
		Talk(1, "no_ptbk", "H\228c t\203p ph\182i ki\170n nh\201n m\237i \174\173\238c, sau n\181y l\185i \174\213n nh\208.")
		return
	end
	local opts = {}
	local i = 1
	while l[i] do
		opts[i] = PTBK_BOOK[l[i]][3] .. "/PTBK_CraftPick"
		i = i + 1
	end
	opts[i] = "Th\171i, \174\211 sau/no_ptbk"
	Say("Mang Kh\171ng Th\173 v\181 th\241y tinh \174\213n \174\169y, ta s\207 gi\243p ng\173\172i \174\227ng th\181nh b\221 k\221p. Ph\208p n\181y kh\171ng ch\190c th\181nh c\171ng, n\213u h\225ng ng\173\172i s\207 nh\203n v\203t ph\200m kh\184c. Mu\232n \174\227ng b\221 k\221p n\181o?", getn(opts), opts)
end

function PTBK_RecipeText(sk)
	local r = PTBK_RECIPE[sk]
	local s = r[2] .. " " .. PTBK_PAGE[r[1]]
	if r[4] > 0 then s = s .. ", " .. r[4] .. " " .. PTBK_MAT[r[3]] end
	return s
end

function PTBK_CraftPick(sel)
	local l = PTBK_CRAFT[GetProfession()]
	if l == nil or sel == nil then return end
	local sk = l[sel + 1]
	if sk == nil or PTBK_RECIPE[sk] == nil then return end
	local r = PTBK_RECIPE[sk]
	local pct = floor(r[5] * 100 / r[6])
	Say("\167\227ng b\221 k\221p " .. PTBK_BOOK[sk][3] .. " c\199n " .. PTBK_RecipeText(sk) .. ". T\216 l\214 th\181nh c\171ng: " .. r[5] .. "/" .. r[6] .. ". Nguy\170n li\214u ph\182i n\187m trong h\181nh trang. \167\227ng s\184ch ngay?", 2,
		"\167\227ng s\184ch" .. "/PTBK_C" .. sk, "Th\171i, \174\211 sau/no_ptbk")
end

function PTBK_Give(g, d, p, n)
	local k = 0
	local i = 1
	while i <= n do
		if AddNormalItem(g, d, p, 1, 0, 0) > 0 then k = k + 1 end
		i = i + 1
	end
	return k
end

-- stackgem 2026-10-03: crystals / gems (3/x, stack 100) and Khong Thu (8/139..142, stack 100) stack, so a
-- refund of items taken from a stack must join the stack again (AddNormalItemPile); one item per cell could
-- need more free cells than the 3 checked before the craft.
function PTBK_AddPile(g, d, p, lv)
	if AddNormalItemPile ~= nil then return AddNormalItemPile(g, d, p, lv, 0, 0) end
	return AddNormalItem(g, d, p, lv, 0, 0)
end

function PTBK_RefundPages(page, n)
	local i = 1
	while i <= n do
		PTBK_AddPile(8, page, 2, 0)
		i = i + 1
	end
end

function PTBK_RefundMats(mat, n)
	local i = 1
	while i <= n do
		PTBK_AddPile(3, mat, 0, 1)
		i = i + 1
	end
end

-- Takes the materials (bag only, counted), then the pages (counted), then rolls the VNG rate.
-- Everything taken is given back when something is short. 3 free cells are required first, so the
-- book or the failure gift (up to 3 items) always fits.
function PTBK_CraftDo(sk)
	local r = PTBK_RECIPE[sk]
	local b = PTBK_BOOK[sk]
	if r == nil or b == nil then return end
	CloseDialog()
	if b[1] >= 0 and GetProfession() ~= b[1] then
		Talk(1, "no_ptbk", "B\221 k\221p " .. b[3] .. " ch\216 d\181nh cho ph\184i " .. PTBK_ProfName(b[1]) .. ".")
		return
	end
	if CalcFreeItemCellCount(1, 1) < 3 then
		Talk(1, "no_ptbk", "H\181nh trang c\199n \221t nh\202t 3 \171 tr\232ng, h\183y s\190p x\213p l\185i r\229i quay l\185i.")
		return
	end
	if HaveNormalItem(8, r[1], 2, -1) < r[2] or (r[4] > 0 and HaveNormalItem(3, r[3], 0, -1) < r[4]) then
		Talk(1, "no_ptbk", "\167\227ng b\221 k\221p " .. b[3] .. " c\199n " .. PTBK_RecipeText(sk) .. ".")
		return
	end
	local got = 0
	while got < r[4] do
		if DelNormalItem(3, r[3], 0, -1) > 0 then got = got + 1 else break end
	end
	if got < r[4] then
		PTBK_RefundMats(r[3], got)
		Talk(1, "no_ptbk", "Th\241y tinh, b\182o th\185ch ph\182i \174\211 trong h\181nh trang (kh\171ng t\221nh r\173\172ng ch\248a \174\229).")
		return
	end
	local pg = 0
	while pg < r[2] do
		local idx = FindAValidIBItem(8, r[1], 2, 0)
		if idx ~= nil and idx > 0 and CostIBItem(idx) == 1 then pg = pg + 1 else break end
	end
	if pg < r[2] then
		PTBK_RefundPages(r[1], pg)
		PTBK_RefundMats(r[3], got)
		Talk(1, "no_ptbk", "Kh\171ng l\202y \174\241 Kh\171ng Th\173, nguy\170n li\214u \174\183 \174\173\238c tr\182 l\185i.")
		return
	end
	if random(1, r[6]) <= r[5] then
		if AddNormalItem(6, 1, PTBK_KEY_BASE + sk, 1, 0, 0) > 0 then
			PTBK_Log("craft ok skill=" .. sk)
			Msg2Player("Vui qu\184! B\221 k\221p " .. b[3] .. " \174\183 xu\202t hi\214n. Nh\202p chu\233t ph\182i v\181o b\221 k\221p \174\211 l\220nh h\233i.")
			Talk(1, "no_ptbk", "Vui qu\184! B\221 k\221p " .. b[3] .. " \174\183 xu\202t hi\214n. Nh\202p chu\233t ph\182i v\181o b\221 k\221p \174\211 l\220nh h\233i.")
			return
		end
		PTBK_RefundPages(r[1], pg)
		PTBK_RefundMats(r[3], got)
		Talk(1, "no_ptbk", "H\181nh trang c\199n \221t nh\202t 3 \171 tr\232ng, h\183y s\190p x\213p l\185i r\229i quay l\185i.")
		return
	end
	local c = PTBK_CONS[r[1]]
	local e = c[random(1, getn(c))]
	PTBK_Give(e[1], e[2], e[3], e[4])
	PTBK_Log("craft fail skill=" .. sk)
	Msg2Player("Su\253t n\247a t\200u h\225a nh\203p ma, \174\227ng s\184ch kh\171ng th\181nh. Nh\203n \174\173\238c " .. e[4] .. " " .. e[5] .. ".")
	Talk(1, "no_ptbk", "Su\253t n\247a t\200u h\225a nh\203p ma, \174\227ng s\184ch kh\171ng th\181nh. Nh\203n \174\173\238c " .. e[4] .. " " .. e[5] .. ".")
end

-- ---------------------------------------------------------------- old genre-7 books -> bi kip
function PTBK_ConvertOld()
	local n = 0
	local left = 0
	local guard = 0
	local sk, b = next(PTBK_BOOK, nil)
	while sk do
		while guard < 200 and HaveNormalItem(7, b[4], sk, -1) > 0 do
			guard = guard + 1
			if DelNormalItem(7, b[4], sk, -1) > 0 then
				if AddNormalItem(6, 1, PTBK_KEY_BASE + sk, 1, 0, 0) > 0 then
					n = n + 1
				else
					AddNormalItem(7, b[4], sk, 1, 0, 0)
					left = left + 1
					break
				end
			else
				left = left + 1
				break
			end
		end
		sk, b = next(PTBK_BOOK, sk)
	end
	PTBK_Log("convert n=" .. n .. " left=" .. left)
	if n == 0 and left == 0 then
		Talk(1, "no_ptbk", "Trong h\181nh trang kh\171ng c\227 s\184ch k\252 n\168ng c\242 n\181o.")
	elseif left > 0 then
		Talk(1, "no_ptbk", "\167\183 \174\230i " .. n .. " s\184ch k\252 n\168ng c\242 th\181nh b\221 k\221p. S\184ch c\223n l\185i n\187m ngo\181i h\181nh trang ho\198c h\181nh trang \174\183 \174\199y.")
	else
		Talk(1, "no_ptbk", "\167\183 \174\230i " .. n .. " s\184ch k\252 n\168ng c\242 th\181nh b\221 k\221p. Nh\202p chu\233t ph\182i v\181o b\221 k\221p \174\211 l\220nh h\233i.")
	end
end

function PTBK_C12() PTBK_CraftDo(12) end
function PTBK_C13() PTBK_CraftDo(13) end
function PTBK_C14() PTBK_CraftDo(14) end
function PTBK_C15() PTBK_CraftDo(15) end
function PTBK_C16() PTBK_CraftDo(16) end
function PTBK_C17() PTBK_CraftDo(17) end
function PTBK_C18() PTBK_CraftDo(18) end
function PTBK_C19() PTBK_CraftDo(19) end
function PTBK_C20() PTBK_CraftDo(20) end
function PTBK_C21() PTBK_CraftDo(21) end
function PTBK_C22() PTBK_CraftDo(22) end
function PTBK_C23() PTBK_CraftDo(23) end
function PTBK_C24() PTBK_CraftDo(24) end
function PTBK_C25() PTBK_CraftDo(25) end
function PTBK_C26() PTBK_CraftDo(26) end
function PTBK_C32() PTBK_CraftDo(32) end
function PTBK_C33() PTBK_CraftDo(33) end
function PTBK_C34() PTBK_CraftDo(34) end
function PTBK_C35() PTBK_CraftDo(35) end
function PTBK_C36() PTBK_CraftDo(36) end
function PTBK_C37() PTBK_CraftDo(37) end
function PTBK_C38() PTBK_CraftDo(38) end
function PTBK_C39() PTBK_CraftDo(39) end
function PTBK_C40() PTBK_CraftDo(40) end
function PTBK_C41() PTBK_CraftDo(41) end
function PTBK_C42() PTBK_CraftDo(42) end
function PTBK_C46() PTBK_CraftDo(46) end
function PTBK_C47() PTBK_CraftDo(47) end
function PTBK_C48() PTBK_CraftDo(48) end
function PTBK_C49() PTBK_CraftDo(49) end
function PTBK_C50() PTBK_CraftDo(50) end
function PTBK_C51() PTBK_CraftDo(51) end
function PTBK_C62() PTBK_CraftDo(62) end
function PTBK_C128() PTBK_CraftDo(128) end
function PTBK_C453() PTBK_CraftDo(453) end
function PTBK_C454() PTBK_CraftDo(454) end
function PTBK_C455() PTBK_CraftDo(455) end
function PTBK_C456() PTBK_CraftDo(456) end
function PTBK_C457() PTBK_CraftDo(457) end
function PTBK_C458() PTBK_CraftDo(458) end
