AddCommand("LButton", "", "Mouse_Action()")
AddCommand("RButton", "", "Mouse_Force1(0)")
AddCommand("Shift+LButton", "", "Mouse_Force0()")
AddCommand("Shift+RButton", "", "Mouse_Force1(1)")
AddCommand("Ctrl+LButton", "", "Mouse_Say()")
AddCommand("Ctrl+RButton", "", "Mouse_Menu()")
AddCommand("Alt+LButton","","Mouse_Action()")
AddCommand("Alt+RButton", "", "Mouse_Emote_Menu()")
AddCommand("Esc", "", "Open([[system]])")
AddCommand("Tab", "", "Open([[map]])")
AddCommand("Enter", "", "Focus([[commandline]])")
AddCommand("Del", "", "ClearMessage()")
AddCommand("F1", "", "Open([[help]])")
AddCommand("", "Help", "Open([[help]])")
AddCommand("", "Gióp ®ì", "Open([[help]])")
AddCommand("", "bz", "Open([[help]])")
AddCommand("", "", "Open([[options]])")
AddCommand("F10", "", "Open([[tongmanager]])")
AddCommand("F3", "", "Open([[status]])")
AddCommand("F4", "", "Open([[items]])")
AddCommand("F5", "", "Open([[skills]])")
AddCommand("F6", "", "Open([[friend]])")
AddCommand("F11", "", "Open([[tasknote]])")
AddCommand("Alt+A", "", "Switch([[leftautoai]])")
AddCommand("Alt+S", "", "Switch([[rightautoai]])")
AddCommand("Shift+1", "", "Switch([[aumletskill1]])")
AddCommand("Shift+2", "", "Switch([[aumletskill2]])")
AddCommand("Alt+D", "", "Switch([[rightlocalautoai]])")
AddCommand("F8", "", "Switch([[showplayerlife]])")
AddCommand("F9", "", "Switch([[pk]])")
AddCommand("F7", "", "Switch([[showplayername]])")
AddCommand("Alt+B", "", "Switch([[hidewindow]])")
AddCommand("PrintScreen", "", "PrintScreen()")
AddCommand("P", "", "PrintScreen()")
AddCommand("G", "", "Open([[team]])")
AddCommand("F2", "", "Open([[ibshop]])")
AddCommand("", "team", "Open([[team]])")
AddCommand("", "Tæ", "Open([[team]])")
AddCommand("", "dw", "Open([[team]])")
AddCommand("Q", "", "ShortcutSkill(0)")
AddCommand("W", "", "ShortcutSkill(1)")
AddCommand("E", "", "ShortcutSkill(2)")
AddCommand("A", "", "ShortcutSkill(3)")
AddCommand("S", "", "ShortcutSkill(4)")
AddCommand("D", "", "ShortcutSkill(5)")
AddCommand("Z", "", "ShortcutSkill(6)")
AddCommand("X", "", "ShortcutSkill(7)")
AddCommand("C", "", "ShortcutSkill(8)")
AddCommand("F", "", "UseSkill(215)")
AddCommand("Ctrl+H", "", "HideUI()")
AddCommand("1", "", "ShortcutUseItem(0)")
AddCommand("2", "", "ShortcutUseItem(1)")
AddCommand("3", "", "ShortcutUseItem(2)")
AddCommand("4", "", "ShortcutUseItem(3)")
AddCommand("5", "", "ShortcutUseItem(4)")
AddCommand("6", "", "ShortcutUseItem(5)")
AddCommand("7", "", "ShortcutUseItem(6)")
AddCommand("8", "", "ShortcutUseItem(7)")
AddCommand("9", "", "ShortcutUseItem(8)")
AddCommand("0", "", "ShortcutUseItem(9)")
AddCommand("R", "", "Switch([[horse]])")
AddCommand("V", "", "Switch([[sit]])")
AddCommand("T", "", "Switch([[trade]])")
AddCommand("O", "", "Switch([[trade]])")
--AddCommand("Alt+0", "", "SayPhrase(0)")
--AddCommand("Alt+1", "", "SayPhrase(1)")
--AddCommand("Alt+2", "", "SayPhrase(2)")
--AddCommand("Alt+3", "", "SayPhrase(3)")
--AddCommand("Alt+4", "", "SayPhrase(4)")
--AddCommand("Alt+5", "", "SayPhrase(5)")
--AddCommand("Alt+6", "", "SayPhrase(6)")
--AddCommand("Alt+7", "", "SayPhrase(7)")
--AddCommand("Alt+8", "", "SayPhrase(8)")
--AddCommand("Alt+9", "", "SayPhrase(9)")
AddCommand("Alt+0", "", "SetEmoteBalloon(0)")
AddCommand("Alt+1", "", "SetEmoteBalloon(1)")
AddCommand("Alt+2", "", "SetEmoteBalloon(2)")
AddCommand("Alt+3", "", "SetEmoteBalloon(3)")
AddCommand("Alt+4", "", "SetEmoteBalloon(4)")
AddCommand("Alt+5", "", "SetEmoteBalloon(5)")
AddCommand("Alt+6", "", "SetEmoteBalloon(6)")
AddCommand("Alt+7", "", "SetEmoteBalloon(7)")
AddCommand("Alt+8", "", "SetEmoteBalloon(8)")
AddCommand("Alt+9", "", "SetEmoteBalloon(9)")
--AddCommand("Alt+Q", "exit", "ExitGame()")
AddCommand("", "3d", "Set3D(1)")
AddCommand("", "2d", "Set3D(0)")
AddCommand("", "fullwindow", "SetFullWindow(1)")
AddCommand("", "window", "SetFullWindow(0)")
--AddCommand("NUM2", "", "MoveTo(0, 0)")
--ddCommand("NUM1", "", "MoveTo(8, 0)")
--ddCommand("NUM4", "", "MoveTo(16, 0)")
--AddCommand("NUM7", "", "MoveTo(24, 0)")
--AddCommand("NUM8", "", "MoveTo(32, 0)")
--AddCommand("NUM9", "", "MoveTo(40, 0)")
--AddCommand("NUM6", "", "MoveTo(48, 0)")
--AddCommand("NUM3", "", "MoveTo(56, 0)")
AddCommand("Left", "", "TurnTo(0)")
AddCommand("Right", "", "TurnTo(1)")
AddCommand("Insert", "", "SwitchPrivateMsgMode()")
AddCommand("`", "", "Open([[chatroom]])")
AddCommand("Alt+X", "", "AutoChangeWeapon()")
AddCommand("Alt+Q", "", "OneKeyGetOff()")
AddCommand("Alt+Z", "", "AutoBloodMana()")
AddCommand("I", "", "OpenAutoBloodMana()")
AddCommand("Alt+C", "", "OpenChatRoom()")
AddCommand("Ctrl+1", "", "ShortCutEquipment(0)")
AddCommand("Ctrl+2", "", "ShortCutEquipment(1)")
AddCommand("Ctrl+3", "", "ShortCutEquipment(2)")
AddCommand("Ctrl+4", "", "ShortCutEquipment(3)")
AddCommand("Ctrl+5", "", "ShortCutEquipment(4)")
AddCommand("Ctrl+6", "", "ShortCutEquipment(5)")
AddCommand("Ctrl+7", "", "ShortCutEquipment(6)")
AddCommand("Ctrl+8", "", "ShortCutEquipment(7)")
AddCommand("Ctrl+9", "", "ShortCutEquipment(8)")
AddCommand("Ctrl+0", "", "ShortCutEquipment(9)")
AddCommand("Alt+C", "", "OpenChatRoom()")
AddCommand("Alt+L", "", "Open([[emoteballoonshop]])")
AddCommand("Alt+W", "", "Switch([[previewstall]])")
AddCommand("Ctrl+D", "", "Switch([[itemcompare]])")
AddCommand("L", "", "Open([[liveSkill]])")
AddCommand("Alt+T", "", "SwitchBuffState()")
AddCommand("Alt+E", "", "HideAllPlayer()")

RegisterFunctionAlias("join", "JoinTeam")
RegisterFunctionAlias("gia nhËp", "JoinTeam")
RegisterFunctionAlias("jr", "JoinTeam")
RegisterFunctionAlias("+", "JoinTeam")
RegisterFunctionAlias("trade", "Trade")
RegisterFunctionAlias("Giao", "Trade")
RegisterFunctionAlias("jy", "Trade")
RegisterFunctionAlias("invite", "InviteTeam")
RegisterFunctionAlias("Mêi", "InviteTeam")
RegisterFunctionAlias("yq", "InviteTeam")
RegisterFunctionAlias("create", "CreateTeam")
RegisterFunctionAlias("Tæ ®éi", "CreateTeam")
RegisterFunctionAlias("zd", "CreateTeam")

-- SetPhrase(0, "H«m nay sao tù nhiªn tèt vËy? !:D")
-- SetPhrase(1, "Cã ai muèn ®i luyÖn cÊp chung víi t¹i h¹ kh«ng? (!hs)")
-- SetPhrase(2, "T«i ®i tr­íc ®©y! Cã g× nhí phone nhÐ!")
-- SetPhrase(3, "Cøu t«i víi ~ HELP! (!wg)")
-- SetPhrase(4, "Phï phï! MÖt qu¸! Ngåi nghØ chót th«i!")
-- SetPhrase(5, "û lín hiÕp nhá…!:L. §å mÊt nÕt…!:L")
-- SetPhrase(6, "Cè lªn…(!hh) Cè lªn…(!hh)")
-- SetPhrase(7, "Ta lµ ng­êi m¹nh nhÊt, cã ai muèn thö søc kh«ng? (!pk)")
-- SetPhrase(8, "Ph¸t tµi råi…hahaha~~~($)")
-- SetPhrase(9, "R­îu uèng h«m nay ta cø say, ­u phiÒn h·y g¸c l¹i ngµy mai (beer)")
AddCommand("B", "", "FSBook()")
