#ifndef PHONGTHAN_RELAY_PROTOCOL_H
#define PHONGTHAN_RELAY_PROTOCOL_H

#include "PhongThanProtocol.h"

// Native Phong Than service-routing contract. This is a new protocol, not a
// size-compatible representation of KRelayProtocol. Variable payloads follow
// their owning header and are always counted explicitly.
enum PHONGTHAN_RELAY_CONSTANT
{
	PHONGTHAN_RELAY_PROTOCOL_VERSION = 1,
	PHONGTHAN_RELAY_INSTANCE_NAME_SIZE = 32,
	PHONGTHAN_RELAY_ACCOUNT_NAME_SIZE = 32,
	PHONGTHAN_RELAY_ROLE_NAME_SIZE = 32,
	PHONGTHAN_RELAY_PROOF_SIZE = 64,
	PHONGTHAN_RELAY_ROUTE_KEY_MAX_SIZE = 64,
	PHONGTHAN_RELAY_CHAT_TEXT_MAX_SIZE = 512,
	PHONGTHAN_RELAY_DOMAIN_PAYLOAD_MAX_SIZE = 64 * 1024
};

enum PHONGTHAN_RELAY_MESSAGE_TYPE
{
	PHONGTHAN_MSG_RELAY_REGISTER = 0x6001,
	PHONGTHAN_MSG_RELAY_HEARTBEAT = 0x6002,
	PHONGTHAN_MSG_RELAY_SESSION_BIND = 0x6003,
	PHONGTHAN_MSG_RELAY_SESSION_UNBIND = 0x6004,
	PHONGTHAN_MSG_RELAY_MAP_BIND = 0x6005,
	PHONGTHAN_MSG_RELAY_MAP_UNBIND = 0x6006,
	PHONGTHAN_MSG_RELAY_ROUTE = 0x6010,
	PHONGTHAN_MSG_RELAY_ROUTE_RESULT = 0x6011,
	PHONGTHAN_MSG_RELAY_TRANSFER_PREPARE = 0x6020,
	PHONGTHAN_MSG_RELAY_TRANSFER_RESULT = 0x6021,
	PHONGTHAN_MSG_RELAY_TRANSFER_COMMIT = 0x6022,
	PHONGTHAN_MSG_RELAY_CHAT_PUBLISH = 0x6030,
	PHONGTHAN_MSG_RELAY_CHAT_DELIVER = 0x6031,
	PHONGTHAN_MSG_RELAY_CLAN_REQUEST = 0x6040,
	PHONGTHAN_MSG_RELAY_CLAN_EVENT = 0x6041,
	PHONGTHAN_MSG_RELAY_FRIEND_REQUEST = 0x6050,
	PHONGTHAN_MSG_RELAY_FRIEND_EVENT = 0x6051
};

enum PHONGTHAN_RELAY_SERVICE_ROLE
{
	PHONGTHAN_RELAY_SERVICE_INVALID = 0,
	PHONGTHAN_RELAY_SERVICE_COORDINATOR = 1,
	PHONGTHAN_RELAY_SERVICE_GATEWAY = 2,
	PHONGTHAN_RELAY_SERVICE_GAME = 3,
	PHONGTHAN_RELAY_SERVICE_CHARACTER = 4,
	PHONGTHAN_RELAY_SERVICE_CHAT = 5,
	PHONGTHAN_RELAY_SERVICE_CLAN = 6,
	PHONGTHAN_RELAY_SERVICE_SOCIAL = 7
};

enum PHONGTHAN_RELAY_CAPABILITY
{
	PHONGTHAN_RELAY_CAPABILITY_NONE = 0,
	PHONGTHAN_RELAY_CAPABILITY_SESSION = 0x0001,
	PHONGTHAN_RELAY_CAPABILITY_MAP = 0x0002,
	PHONGTHAN_RELAY_CAPABILITY_TRANSFER = 0x0004,
	PHONGTHAN_RELAY_CAPABILITY_CHAT = 0x0008,
	PHONGTHAN_RELAY_CAPABILITY_CLAN = 0x0010,
	PHONGTHAN_RELAY_CAPABILITY_FRIEND = 0x0020
};

enum PHONGTHAN_RELAY_ROUTE_KEY_TYPE
{
	PHONGTHAN_RELAY_ROUTE_DIRECT_SERVICE = 0,
	PHONGTHAN_RELAY_ROUTE_SESSION = 1,
	PHONGTHAN_RELAY_ROUTE_ACCOUNT = 2,
	PHONGTHAN_RELAY_ROUTE_ROLE = 3,
	PHONGTHAN_RELAY_ROUTE_MAP = 4,
	PHONGTHAN_RELAY_ROUTE_CLAN = 5
};

enum PHONGTHAN_RELAY_RESULT
{
	PHONGTHAN_RELAY_SUCCESS = 0,
	PHONGTHAN_RELAY_INVALID_PACKET = 1,
	PHONGTHAN_RELAY_UNSUPPORTED_VERSION = 2,
	PHONGTHAN_RELAY_UNAUTHORIZED = 3,
	PHONGTHAN_RELAY_DUPLICATE_SERVICE = 4,
	PHONGTHAN_RELAY_ROUTE_NOT_FOUND = 5,
	PHONGTHAN_RELAY_TARGET_UNAVAILABLE = 6,
	PHONGTHAN_RELAY_STATE_CONFLICT = 7,
	PHONGTHAN_RELAY_CAPACITY_EXCEEDED = 8
};

enum PHONGTHAN_RELAY_SESSION_END_REASON
{
	PHONGTHAN_RELAY_SESSION_END_UNKNOWN = 0,
	PHONGTHAN_RELAY_SESSION_END_DISCONNECTED = 1,
	PHONGTHAN_RELAY_SESSION_END_LOGOUT = 2,
	PHONGTHAN_RELAY_SESSION_END_TRANSFERRED = 3,
	PHONGTHAN_RELAY_SESSION_END_SERVER_SHUTDOWN = 4
};

enum PHONGTHAN_RELAY_ROUTE_FLAG
{
	PHONGTHAN_RELAY_ROUTE_FLAG_NONE = 0,
	PHONGTHAN_RELAY_ROUTE_FLAG_REQUIRE_RESULT = 1,
	PHONGTHAN_RELAY_ROUTE_FLAG_BROADCAST = 2
};

enum PHONGTHAN_CHAT_SCOPE
{
	PHONGTHAN_CHAT_SCOPE_PRIVATE = 1,
	PHONGTHAN_CHAT_SCOPE_NEARBY = 2,
	PHONGTHAN_CHAT_SCOPE_TEAM = 3,
	PHONGTHAN_CHAT_SCOPE_CLAN = 4,
	PHONGTHAN_CHAT_SCOPE_WORLD = 5,
	PHONGTHAN_CHAT_SCOPE_SYSTEM = 6
};

#pragma pack(push, 1)

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U16 ServiceRole;
	PHONGTHAN_U16 Reserved;
	PHONGTHAN_U32 ServiceId;
	PHONGTHAN_U32 Capabilities;
	PHONGTHAN_U32 AddressV4;
	PHONGTHAN_U16 ServicePort;
	PHONGTHAN_U16 PublicPort;
	PHONGTHAN_U8 InstanceName[PHONGTHAN_RELAY_INSTANCE_NAME_SIZE];
	PHONGTHAN_U8 CredentialProof[PHONGTHAN_RELAY_PROOF_SIZE];
} PHONGTHAN_RELAY_REGISTER_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U32 AssignedServiceId;
	PHONGTHAN_U32 ServerTime;
} PHONGTHAN_RELAY_REGISTER_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ServiceId;
	PHONGTHAN_U32 ServerTime;
	PHONGTHAN_U32 ActiveSessions;
	PHONGTHAN_U32 LoadPermille;
} PHONGTHAN_RELAY_HEARTBEAT;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ServiceId;
	PHONGTHAN_U8 SessionTicket[PHONGTHAN_SESSION_TICKET_SIZE];
	PHONGTHAN_U8 AccountName[PHONGTHAN_RELAY_ACCOUNT_NAME_SIZE];
	PHONGTHAN_U8 RoleName[PHONGTHAN_RELAY_ROLE_NAME_SIZE];
	PHONGTHAN_U32 MapId;
	PHONGTHAN_U32 ConnectionId;
} PHONGTHAN_RELAY_SESSION_BIND;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ServiceId;
	PHONGTHAN_U8 SessionTicket[PHONGTHAN_SESSION_TICKET_SIZE];
	PHONGTHAN_S32 Reason;
} PHONGTHAN_RELAY_SESSION_UNBIND;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ServiceId;
	PHONGTHAN_U32 MapId;
	PHONGTHAN_U32 WorldId;
	PHONGTHAN_U32 AddressV4;
	PHONGTHAN_U16 Port;
	PHONGTHAN_U16 Reserved;
} PHONGTHAN_RELAY_MAP_BIND;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RouteId;
	PHONGTHAN_U32 SourceServiceId;
	PHONGTHAN_U32 TargetServiceId;
	PHONGTHAN_U16 KeyType;
	PHONGTHAN_U16 RouteFlags;
	PHONGTHAN_U16 KeySize;
	PHONGTHAN_U16 Reserved;
	PHONGTHAN_U32 PayloadSize;
} PHONGTHAN_RELAY_ROUTE_HEADER;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RouteId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U32 TargetServiceId;
} PHONGTHAN_RELAY_ROUTE_RESULT;

// A canonical PHONGTHAN_CHARACTER_STATE_HEADER and its counted sections follow
// this header. The destination validates that state before accepting transfer.
typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 TransferId;
	PHONGTHAN_U32 SourceServiceId;
	PHONGTHAN_U32 TargetServiceId;
	PHONGTHAN_U32 DestinationMapId;
	PHONGTHAN_S32 DestinationX;
	PHONGTHAN_S32 DestinationY;
	PHONGTHAN_U8 SessionTicket[PHONGTHAN_SESSION_TICKET_SIZE];
	PHONGTHAN_U8 RoleName[PHONGTHAN_RELAY_ROLE_NAME_SIZE];
	PHONGTHAN_S32 ExtensionPoint;
	PHONGTHAN_S32 ChangedExtensionPoint;
	PHONGTHAN_U32 StateSize;
} PHONGTHAN_RELAY_TRANSFER_PREPARE_HEADER;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 TransferId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U32 TargetServiceId;
	PHONGTHAN_U32 AddressV4;
	PHONGTHAN_U16 Port;
	PHONGTHAN_U16 Reserved;
	PHONGTHAN_U8 SessionTicket[PHONGTHAN_SESSION_TICKET_SIZE];
} PHONGTHAN_RELAY_TRANSFER_RESULT;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 TransferId;
	PHONGTHAN_U32 SourceServiceId;
	PHONGTHAN_U32 TargetServiceId;
	PHONGTHAN_U8 SessionTicket[PHONGTHAN_SESSION_TICKET_SIZE];
	PHONGTHAN_U8 RoleName[PHONGTHAN_RELAY_ROLE_NAME_SIZE];
} PHONGTHAN_RELAY_TRANSFER_COMMIT;

// TargetName bytes and UTF-8 text bytes follow this header.
typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 MessageId;
	PHONGTHAN_U32 SourceServiceId;
	PHONGTHAN_U32 SourcePlayerId;
	PHONGTHAN_U16 Scope;
	PHONGTHAN_U16 ChatFlags;
	PHONGTHAN_U32 TargetId;
	PHONGTHAN_U16 TargetNameSize;
	PHONGTHAN_U16 TextSize;
	PHONGTHAN_U8 SourceRoleName[PHONGTHAN_RELAY_ROLE_NAME_SIZE];
} PHONGTHAN_RELAY_CHAT_HEADER;

// Operation-specific payload follows this header. It is versioned by the
// message type and Operation, never by a legacy union or runtime class layout.
typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U32 SourceServiceId;
	PHONGTHAN_U32 ClanId;
	PHONGTHAN_U32 PlayerId;
	PHONGTHAN_U16 Operation;
	PHONGTHAN_U16 PayloadSize;
	PHONGTHAN_U8 RoleName[PHONGTHAN_RELAY_ROLE_NAME_SIZE];
} PHONGTHAN_RELAY_CLAN_HEADER;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U32 SourceServiceId;
	PHONGTHAN_U32 PlayerId;
	PHONGTHAN_U16 Operation;
	PHONGTHAN_U16 PayloadSize;
	PHONGTHAN_U8 RoleName[PHONGTHAN_RELAY_ROLE_NAME_SIZE];
	PHONGTHAN_U8 TargetRoleName[PHONGTHAN_RELAY_ROLE_NAME_SIZE];
} PHONGTHAN_RELAY_FRIEND_HEADER;

#pragma pack(pop)

typedef char PHONGTHAN_RELAY_REGISTER_REQUEST_SIZE_MUST_BE_140[
	(sizeof(PHONGTHAN_RELAY_REGISTER_REQUEST) == 140) ? 1 : -1];
typedef char PHONGTHAN_RELAY_REGISTER_RESPONSE_SIZE_MUST_BE_36[
	(sizeof(PHONGTHAN_RELAY_REGISTER_RESPONSE) == 36) ? 1 : -1];
typedef char PHONGTHAN_RELAY_HEARTBEAT_SIZE_MUST_BE_36[
	(sizeof(PHONGTHAN_RELAY_HEARTBEAT) == 36) ? 1 : -1];
typedef char PHONGTHAN_RELAY_SESSION_BIND_SIZE_MUST_BE_112[
	(sizeof(PHONGTHAN_RELAY_SESSION_BIND) == 112) ? 1 : -1];
typedef char PHONGTHAN_RELAY_SESSION_UNBIND_SIZE_MUST_BE_44[
	(sizeof(PHONGTHAN_RELAY_SESSION_UNBIND) == 44) ? 1 : -1];
typedef char PHONGTHAN_RELAY_MAP_BIND_SIZE_MUST_BE_40[
	(sizeof(PHONGTHAN_RELAY_MAP_BIND) == 40) ? 1 : -1];
typedef char PHONGTHAN_RELAY_ROUTE_HEADER_SIZE_MUST_BE_44[
	(sizeof(PHONGTHAN_RELAY_ROUTE_HEADER) == 44) ? 1 : -1];
typedef char PHONGTHAN_RELAY_ROUTE_RESULT_SIZE_MUST_BE_32[
	(sizeof(PHONGTHAN_RELAY_ROUTE_RESULT) == 32) ? 1 : -1];
typedef char PHONGTHAN_RELAY_TRANSFER_PREPARE_HEADER_SIZE_MUST_BE_104[
	(sizeof(PHONGTHAN_RELAY_TRANSFER_PREPARE_HEADER) == 104) ? 1 : -1];
typedef char PHONGTHAN_RELAY_TRANSFER_RESULT_SIZE_MUST_BE_56[
	(sizeof(PHONGTHAN_RELAY_TRANSFER_RESULT) == 56) ? 1 : -1];
typedef char PHONGTHAN_RELAY_TRANSFER_COMMIT_SIZE_MUST_BE_80[
	(sizeof(PHONGTHAN_RELAY_TRANSFER_COMMIT) == 80) ? 1 : -1];
typedef char PHONGTHAN_RELAY_CHAT_HEADER_SIZE_MUST_BE_76[
	(sizeof(PHONGTHAN_RELAY_CHAT_HEADER) == 76) ? 1 : -1];
typedef char PHONGTHAN_RELAY_CLAN_HEADER_SIZE_MUST_BE_72[
	(sizeof(PHONGTHAN_RELAY_CLAN_HEADER) == 72) ? 1 : -1];
typedef char PHONGTHAN_RELAY_FRIEND_HEADER_SIZE_MUST_BE_100[
	(sizeof(PHONGTHAN_RELAY_FRIEND_HEADER) == 100) ? 1 : -1];

inline int PhongThanValidateRelayFixedPacket(
	const PHONGTHAN_WIRE_HEADER* pHeader, PHONGTHAN_U32 nAvailableSize,
	PHONGTHAN_U16 nMessageType, PHONGTHAN_U32 nExpectedSize)
{
	return PhongThanValidateWireHeader(pHeader, nAvailableSize) &&
		pHeader->MessageType == nMessageType &&
		pHeader->PacketSize == nExpectedSize &&
		nAvailableSize == nExpectedSize;
}

inline int PhongThanValidateRelayRoutePacket(
	const PHONGTHAN_RELAY_ROUTE_HEADER* pRoute,
	PHONGTHAN_U32 nAvailableSize)
{
	if (!pRoute ||
		!PhongThanValidateWireHeader(&pRoute->Header, nAvailableSize) ||
		pRoute->Header.MessageType != PHONGTHAN_MSG_RELAY_ROUTE ||
		pRoute->Header.PacketSize != nAvailableSize ||
		pRoute->KeyType > PHONGTHAN_RELAY_ROUTE_CLAN ||
		pRoute->KeySize > PHONGTHAN_RELAY_ROUTE_KEY_MAX_SIZE ||
		pRoute->PayloadSize > PHONGTHAN_RELAY_DOMAIN_PAYLOAD_MAX_SIZE)
	{
		return 0;
	}

	unsigned __int64 nExpected = sizeof(*pRoute);
	if (pRoute->KeyType != PHONGTHAN_RELAY_ROUTE_DIRECT_SERVICE &&
		pRoute->KeySize == 0)
		return 0;
	nExpected += pRoute->KeySize;
	nExpected += pRoute->PayloadSize;
	return nExpected == nAvailableSize;
}

inline int PhongThanValidateRelayTransferPacket(
	const PHONGTHAN_RELAY_TRANSFER_PREPARE_HEADER* pTransfer,
	PHONGTHAN_U32 nAvailableSize)
{
	if (!pTransfer ||
		!PhongThanValidateWireHeader(&pTransfer->Header, nAvailableSize) ||
		pTransfer->Header.MessageType != PHONGTHAN_MSG_RELAY_TRANSFER_PREPARE ||
		pTransfer->Header.PacketSize != nAvailableSize ||
		pTransfer->StateSize == 0 ||
		pTransfer->StateSize > PHONGTHAN_RELAY_DOMAIN_PAYLOAD_MAX_SIZE)
	{
		return 0;
	}
	return sizeof(*pTransfer) + pTransfer->StateSize == nAvailableSize;
}

inline int PhongThanValidateRelayChatPacket(
	const PHONGTHAN_RELAY_CHAT_HEADER* pChat,
	PHONGTHAN_U32 nAvailableSize)
{
	if (!pChat ||
		!PhongThanValidateWireHeader(&pChat->Header, nAvailableSize) ||
		(pChat->Header.MessageType != PHONGTHAN_MSG_RELAY_CHAT_PUBLISH &&
		 pChat->Header.MessageType != PHONGTHAN_MSG_RELAY_CHAT_DELIVER) ||
		pChat->Header.PacketSize != nAvailableSize ||
		pChat->Scope < PHONGTHAN_CHAT_SCOPE_PRIVATE ||
		pChat->Scope > PHONGTHAN_CHAT_SCOPE_SYSTEM ||
		pChat->TargetNameSize > PHONGTHAN_RELAY_ROLE_NAME_SIZE ||
		pChat->TextSize == 0 ||
		pChat->TextSize > PHONGTHAN_RELAY_CHAT_TEXT_MAX_SIZE)
	{
		return 0;
	}
	return sizeof(*pChat) + pChat->TargetNameSize + pChat->TextSize ==
		nAvailableSize;
}

#endif
