#ifndef PHONGTHAN_PROTOCOL_H
#define PHONGTHAN_PROTOCOL_H

// Phong Than owns this wire contract. It deliberately does not include any
// gameplay, UI, database or SwordOnline header. Every field crossing the
// network is represented by a fixed-size scalar.
typedef unsigned char  PHONGTHAN_U8;
typedef unsigned short PHONGTHAN_U16;
typedef unsigned int   PHONGTHAN_U32;
typedef signed int     PHONGTHAN_S32;

typedef char PHONGTHAN_U8_MUST_BE_1_BYTE[(sizeof(PHONGTHAN_U8) == 1) ? 1 : -1];
typedef char PHONGTHAN_U16_MUST_BE_2_BYTES[(sizeof(PHONGTHAN_U16) == 2) ? 1 : -1];
typedef char PHONGTHAN_U32_MUST_BE_4_BYTES[(sizeof(PHONGTHAN_U32) == 4) ? 1 : -1];
typedef char PHONGTHAN_S32_MUST_BE_4_BYTES[(sizeof(PHONGTHAN_S32) == 4) ? 1 : -1];

enum PHONGTHAN_WIRE_CONSTANT
{
	PHONGTHAN_WIRE_MAGIC = 0x4e485450, // bytes: P T H N
	PHONGTHAN_WIRE_VERSION = 1,
	PHONGTHAN_WIRE_MAX_PACKET_SIZE = 1024 * 1024,
	PHONGTHAN_EMBEDDED_ITEM_VERSION = 1,
	PHONGTHAN_SESSION_TICKET_SIZE = 16,
	PHONGTHAN_CLIENT_NAME_SIZE = 32,
	PHONGTHAN_WORLD_INSTANCE_NAME_SIZE = 32,
	PHONGTHAN_WORLD_MAP_LIMIT = 255,
	PHONGTHAN_CHARACTER_LIMIT = 3,
	PHONGTHAN_GENDER_COUNT = 2,
	PHONGTHAN_STARTER_SKILL_LIMIT = 64,
	PHONGTHAN_ITEM_PROPERTY_VALUE_COUNT = 40,
	PHONGTHAN_ITEM_ATTRIBUTE_COUNT = 20
};

enum PHONGTHAN_PROFESSION
{
	PHONGTHAN_PROFESSION_GIAP_SI = 0,
	PHONGTHAN_PROFESSION_DAO_SI = 1,
	PHONGTHAN_PROFESSION_DI_NHAN = 2,
	PHONGTHAN_PROFESSION_COUNT = 3,
	PHONGTHAN_PROFESSION_INVALID = -1
};

enum PHONGTHAN_MESSAGE_TYPE
{
	PHONGTHAN_MSG_INVALID = 0,

	PHONGTHAN_MSG_SESSION_HELLO = 0x0101,
	PHONGTHAN_MSG_SESSION_AUTHENTICATE = 0x0102,
	PHONGTHAN_MSG_SESSION_CHARACTER_LIST = 0x0103,
	PHONGTHAN_MSG_SESSION_SELECT_CHARACTER = 0x0104,
	PHONGTHAN_MSG_SESSION_ENTER_WORLD = 0x0105,
	PHONGTHAN_MSG_SESSION_CREATE_CHARACTER = 0x0106,
	PHONGTHAN_MSG_SESSION_DELETE_CHARACTER = 0x0107,

	PHONGTHAN_MSG_SERVICE_GATEWAY_HELLO = 0x1000,
	PHONGTHAN_MSG_SERVICE_ACCOUNT_AUTHENTICATE = 0x1001,
	PHONGTHAN_MSG_SERVICE_ACCOUNT_RELEASE = 0x1002,
	PHONGTHAN_MSG_SERVICE_ACCOUNT_ENTER_WORLD = 0x1003,
	PHONGTHAN_MSG_SERVICE_GATEWAY_HEARTBEAT = 0x1004,
	PHONGTHAN_MSG_SERVICE_CHARACTER_LIST = 0x1101,
	PHONGTHAN_MSG_SERVICE_CHARACTER_LOAD = 0x1102,
	PHONGTHAN_MSG_SERVICE_CHARACTER_CREATE = 0x1103,
	PHONGTHAN_MSG_SERVICE_CHARACTER_DELETE = 0x1104,
	PHONGTHAN_MSG_SERVICE_CHARACTER_SAVE = 0x1105,
	PHONGTHAN_MSG_SERVICE_CHARACTER_LOCK = 0x1106,
	PHONGTHAN_MSG_SERVICE_WORLD_HELLO = 0x1201,
	PHONGTHAN_MSG_SERVICE_WORLD_MAP_REGISTRY = 0x1202,
	PHONGTHAN_MSG_SERVICE_WORLD_SESSION = 0x1203,

	PHONGTHAN_MSG_WORLD_PLAYER_SNAPSHOT = 0x2001,
	PHONGTHAN_MSG_WORLD_NPC_SNAPSHOT = 0x2002,
	PHONGTHAN_MSG_WORLD_ENTITY_MOVE = 0x2003,
	PHONGTHAN_MSG_WORLD_ENTITY_REMOVE = 0x2004,
	PHONGTHAN_MSG_WORLD_ATTACH_CHARACTER = 0x2005,
	PHONGTHAN_MSG_WORLD_TRANSFER = 0x2006,
	PHONGTHAN_MSG_WORLD_NPC_UPDATE = 0x2007,
	PHONGTHAN_MSG_WORLD_MAP_SNAPSHOT = 0x2008,
	PHONGTHAN_MSG_WORLD_SELF_SNAPSHOT = 0x2009,
	PHONGTHAN_MSG_WORLD_SELF_VITALS = 0x200a,
	PHONGTHAN_MSG_WORLD_SYNC_COMPLETE = 0x200b,
	PHONGTHAN_MSG_WORLD_ENTITY_POSITION = 0x200c,
	PHONGTHAN_MSG_WORLD_ENTITY_STATUS = 0x200d,
	PHONGTHAN_MSG_WORLD_OBJECT_SNAPSHOT = 0x2010,
	PHONGTHAN_MSG_WORLD_OBJECT_STATE = 0x2011,
	PHONGTHAN_MSG_WORLD_OBJECT_DIRECTION = 0x2012,
	PHONGTHAN_MSG_WORLD_OBJECT_REMOVE = 0x2013,
	PHONGTHAN_MSG_WORLD_MOVE_REQUEST = 0x2101,
	PHONGTHAN_MSG_WORLD_ENTITY_REQUEST = 0x2102,
	PHONGTHAN_MSG_WORLD_ENTITY_NOT_FOUND = 0x2103,
	PHONGTHAN_MSG_WORLD_POSE_REQUEST = 0x2104,
	PHONGTHAN_MSG_WORLD_OBJECT_REQUEST = 0x2110,
	PHONGTHAN_MSG_WORLD_OBJECT_INTERACT = 0x2111,

	PHONGTHAN_MSG_INVENTORY_ITEM_SNAPSHOT = 0x3001,
	PHONGTHAN_MSG_INVENTORY_ITEM_REMOVE = 0x3002,
	PHONGTHAN_MSG_INVENTORY_ITEM_MOVE = 0x3003,
	PHONGTHAN_MSG_INVENTORY_ITEM_DURABILITY = 0x3004,
	PHONGTHAN_MSG_INVENTORY_ITEM_PROPERTIES = 0x3005,
	PHONGTHAN_MSG_INVENTORY_ITEM_AUTO_MOVE = 0x3006,
	PHONGTHAN_MSG_INVENTORY_USE_REQUEST = 0x3101,
	PHONGTHAN_MSG_INVENTORY_PICKUP_REQUEST = 0x3102,
	PHONGTHAN_MSG_INVENTORY_MOVE_REQUEST = 0x3103,
	PHONGTHAN_MSG_INVENTORY_DROP_REQUEST = 0x3104,
	PHONGTHAN_MSG_NPC_SHOP_SELL_REQUEST = 0x3105,
	PHONGTHAN_MSG_NPC_SHOP_BUY_REQUEST = 0x3106,
	PHONGTHAN_MSG_IBSHOP_OPEN_REQUEST = 0x3107,
	PHONGTHAN_MSG_IBSHOP_OPEN_RESPONSE = 0x3108,

	PHONGTHAN_MSG_GAMEPLAY_SKILL_CAST = 0x4001,
	PHONGTHAN_MSG_GAMEPLAY_STATE_EFFECT = 0x4002,
	PHONGTHAN_MSG_GAMEPLAY_SKILL_LIST = 0x4003,
	PHONGTHAN_MSG_GAMEPLAY_ATTRIBUTE_UPDATE = 0x4004,
	PHONGTHAN_MSG_GAMEPLAY_SKILL_LEVEL_UPDATE = 0x4005,
	PHONGTHAN_MSG_GAMEPLAY_STATE_CLEAR = 0x4006,
	PHONGTHAN_MSG_GAMEPLAY_EXPERIENCE = 0x4007,
	PHONGTHAN_MSG_GAMEPLAY_LEVEL = 0x4008,
	PHONGTHAN_MSG_WORLD_TITLE = 0x2014,
	PHONGTHAN_MSG_WORLD_MOUNT = 0x2015,
	PHONGTHAN_MSG_UI_PLAYER_EVENT = 0x5003,
	PHONGTHAN_MSG_GAMEPLAY_SKILL_REQUEST = 0x4101,
	PHONGTHAN_MSG_GAMEPLAY_ATTRIBUTE_REQUEST = 0x4102,
	PHONGTHAN_MSG_GAMEPLAY_SKILL_LEVEL_REQUEST = 0x4103,

	PHONGTHAN_MSG_UI_SCRIPT_ACTION = 0x5001,
	PHONGTHAN_MSG_UI_MESSAGE = 0x5002,
	PHONGTHAN_MSG_NPC_INTERACT_REQUEST = 0x5101,
	PHONGTHAN_MSG_UI_CHOICE_REQUEST = 0x5102
};

enum PHONGTHAN_WIRE_FLAG
{
	PHONGTHAN_WIRE_FLAG_NONE = 0,
	PHONGTHAN_WIRE_FLAG_REQUEST = 1,
	PHONGTHAN_WIRE_FLAG_RESPONSE = 2,
	PHONGTHAN_WIRE_FLAG_ERROR = 4
};

enum PHONGTHAN_AUTH_RESULT
{
	PHONGTHAN_AUTH_SUCCESS = 0,
	PHONGTHAN_AUTH_INVALID_CREDENTIALS = 1,
	PHONGTHAN_AUTH_ACCOUNT_IN_USE = 2,
	PHONGTHAN_AUTH_ACCOUNT_FROZEN = 3,
	PHONGTHAN_AUTH_SERVICE_UNAVAILABLE = 4,
	PHONGTHAN_AUTH_TIME_EXPIRED = 5,
	PHONGTHAN_AUTH_INCOMPATIBLE_VERSION = 6
};

enum PHONGTHAN_CHARACTER_LIST_RESULT
{
	PHONGTHAN_CHARACTER_LIST_SUCCESS = 0,
	PHONGTHAN_CHARACTER_LIST_SERVICE_UNAVAILABLE = 1
};

enum PHONGTHAN_CHARACTER_OPERATION_RESULT
{
	PHONGTHAN_CHARACTER_OPERATION_SUCCESS = 0,
	PHONGTHAN_CHARACTER_OPERATION_INVALID_NAME = 1,
	PHONGTHAN_CHARACTER_OPERATION_NAME_IN_USE = 2,
	PHONGTHAN_CHARACTER_OPERATION_INVALID_CREDENTIALS = 3,
	PHONGTHAN_CHARACTER_OPERATION_LIMIT_REACHED = 4,
	PHONGTHAN_CHARACTER_OPERATION_SERVICE_UNAVAILABLE = 5
};

enum PHONGTHAN_WORLD_TRANSFER_RESULT
{
	PHONGTHAN_WORLD_TRANSFER_SUCCESS = 0,
	PHONGTHAN_WORLD_TRANSFER_DESTINATION_UNAVAILABLE = 1,
	PHONGTHAN_WORLD_TRANSFER_REJECTED = 2,
	PHONGTHAN_WORLD_TRANSFER_INVALID_STATE = 3
};

enum PHONGTHAN_ACCOUNT_AUTH_PURPOSE
{
	PHONGTHAN_ACCOUNT_AUTH_LOGIN = 0,
	PHONGTHAN_ACCOUNT_AUTH_DELETE_CHARACTER = 1
};

enum PHONGTHAN_WORLD_SESSION_PHASE
{
	PHONGTHAN_WORLD_SESSION_ENTERED = 1,
	PHONGTHAN_WORLD_SESSION_LEAVING = 2,
	PHONGTHAN_WORLD_SESSION_TRANSFER_HOLD = 3,
	PHONGTHAN_WORLD_SESSION_TRANSFER_REBIND = 4,
	PHONGTHAN_WORLD_SESSION_TRANSFER_ABORT = 5
};

enum PHONGTHAN_WORLD_SESSION_REASON
{
	PHONGTHAN_WORLD_SESSION_REASON_NORMAL = 0,
	PHONGTHAN_WORLD_SESSION_REASON_TIMEOUT = 1,
	PHONGTHAN_WORLD_SESSION_REASON_DISCONNECTED = 2,
	PHONGTHAN_WORLD_SESSION_REASON_SERVER_SHUTDOWN = 3,
	PHONGTHAN_WORLD_SESSION_REASON_TRANSFER = 4
};

#pragma pack(push, 1)

typedef struct
{
	PHONGTHAN_U32 Magic;
	PHONGTHAN_U16 Version;
	PHONGTHAN_U16 HeaderSize;
	PHONGTHAN_U16 MessageType;
	PHONGTHAN_U16 Flags;
	PHONGTHAN_U32 PacketSize;
	PHONGTHAN_U32 Sequence;
} PHONGTHAN_WIRE_HEADER;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;

	PHONGTHAN_U32 ItemId;
	PHONGTHAN_U32 OwnerId;
	PHONGTHAN_S32 TradePrice;
	PHONGTHAN_S32 TemplateRow;
	PHONGTHAN_S32 DetailType;
	PHONGTHAN_S32 ParticularType;
	PHONGTHAN_S32 Luck;
	PHONGTHAN_U32 RandomSeed;
	PHONGTHAN_U16 GeneratorVersion;

	PHONGTHAN_U8 Genre;
	PHONGTHAN_U8 Series;
	PHONGTHAN_U8 Level;
	PHONGTHAN_U8 Container;
	PHONGTHAN_U8 SlotX;
	PHONGTHAN_U8 SlotY;
	PHONGTHAN_U8 IsNew;
	PHONGTHAN_U8 IsTemporary;
	PHONGTHAN_U8 LockSell;
	PHONGTHAN_U8 LockTrade;
	PHONGTHAN_U8 LockDrop;
	PHONGTHAN_U8 Reserved;

	PHONGTHAN_S32 StackCount;
	PHONGTHAN_S32 ExpireTime;
	PHONGTHAN_S32 Durability;
	PHONGTHAN_S32 LockState;
	PHONGTHAN_U32 LockUntil;
	PHONGTHAN_S32 Param;
	PHONGTHAN_S32 Fortune;

	PHONGTHAN_S32 BackIsSkill;
	PHONGTHAN_S32 BackIndex;
	PHONGTHAN_S32 BackContainer;
	PHONGTHAN_S32 BackX;
	PHONGTHAN_S32 BackY;

	// Authoritative persisted equipment metadata, independent of template rolls.
	// Exact PacketSize checks reject the previous shorter snapshot layout.
	// UpgradeLevel accepts legacy 0..15 and the tagged rule/level encoding
	// described in PhongThanUpgradeState.h; never expose the tagged integer as stars.
	PHONGTHAN_S32 UpgradeLevel;
	PHONGTHAN_S32 PhysicalValue;
	PHONGTHAN_S32 MagicValue;
	PHONGTHAN_S32 PropertyValues[PHONGTHAN_ITEM_PROPERTY_VALUE_COUNT];
} PHONGTHAN_ITEM_SNAPSHOT;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ItemId;
} PHONGTHAN_ITEM_REMOVE_MESSAGE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 FromContainer;
	PHONGTHAN_U8 FromX;
	PHONGTHAN_U8 FromY;
	PHONGTHAN_U8 ToContainer;
	PHONGTHAN_U8 ToX;
	PHONGTHAN_U8 ToY;
} PHONGTHAN_ITEM_MOVE_MESSAGE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ItemId;
	PHONGTHAN_U8 Container;
	PHONGTHAN_U8 SlotX;
	PHONGTHAN_U8 SlotY;
	PHONGTHAN_U8 Reserved;
} PHONGTHAN_ITEM_USE_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 WorldObjectId;
	PHONGTHAN_U8 DestinationContainer;
	PHONGTHAN_U8 DestinationX;
	PHONGTHAN_U8 DestinationY;
	PHONGTHAN_U8 Reserved;
} PHONGTHAN_ITEM_PICKUP_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 FromContainer;
	PHONGTHAN_U8 FromX;
	PHONGTHAN_U8 FromY;
	PHONGTHAN_U8 ToContainer;
	PHONGTHAN_U8 ToX;
	PHONGTHAN_U8 ToY;
	PHONGTHAN_U16 Reserved;
} PHONGTHAN_ITEM_MOVE_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ItemId;
} PHONGTHAN_ITEM_DROP_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ItemId;
	PHONGTHAN_U16 Count;
	PHONGTHAN_U16 Reserved;
} PHONGTHAN_NPC_SHOP_SELL_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_S32 ShopPage;
	PHONGTHAN_S32 ShopSlot;
	PHONGTHAN_U16 Count;
	PHONGTHAN_U16 Reserved;
} PHONGTHAN_NPC_SHOP_BUY_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_S32 ShopCount;
	PHONGTHAN_S32 ShopIds[10];
} PHONGTHAN_IBSHOP_OPEN_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 SessionTicket[PHONGTHAN_SESSION_TICKET_SIZE];
	PHONGTHAN_U8 ClientName[PHONGTHAN_CLIENT_NAME_SIZE];
} PHONGTHAN_SESSION_ENTER_WORLD_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 AccountName[32];
	PHONGTHAN_U8 PasswordProof[64];
} PHONGTHAN_SESSION_AUTHENTICATE_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U32 RemainingTime;
	PHONGTHAN_U8 AccountName[32];
} PHONGTHAN_SESSION_AUTHENTICATE_RESPONSE;

typedef struct
{
	PHONGTHAN_U8 Name[32];
	PHONGTHAN_U8 Gender;
	PHONGTHAN_U8 Profession;
	PHONGTHAN_U16 Level;
} PHONGTHAN_CHARACTER_SUMMARY;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U8 CharacterCount;
	PHONGTHAN_U8 RecommendedIndex;
	PHONGTHAN_U16 Reserved;
	PHONGTHAN_CHARACTER_SUMMARY Characters[PHONGTHAN_CHARACTER_LIMIT];
} PHONGTHAN_SESSION_CHARACTER_LIST_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 RoleName[32];
	PHONGTHAN_U8 Gender;
	PHONGTHAN_U8 Profession;
	PHONGTHAN_U16 NativePlaceId;
} PHONGTHAN_SESSION_CREATE_CHARACTER_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U8 RoleName[32];
} PHONGTHAN_SESSION_CREATE_CHARACTER_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 RoleName[32];
	PHONGTHAN_U8 PasswordProof[64];
} PHONGTHAN_SESSION_DELETE_CHARACTER_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U8 RoleName[32];
} PHONGTHAN_SESSION_DELETE_CHARACTER_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U8 Reconnect;
	PHONGTHAN_U8 Reserved[3];
	PHONGTHAN_U8 GatewayName[32];
	PHONGTHAN_U8 CredentialProof[64];
	PHONGTHAN_U8 AdapterAddress[6];
	PHONGTHAN_U8 ReservedTail[2];
} PHONGTHAN_SERVICE_GATEWAY_HELLO_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U32 GameServiceId;
	PHONGTHAN_U8 GatewayName[32];
} PHONGTHAN_SERVICE_GATEWAY_HELLO_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U8 Purpose;
	PHONGTHAN_U8 Reserved[3];
	PHONGTHAN_U8 AccountName[32];
	PHONGTHAN_U8 PasswordProof[64];
} PHONGTHAN_SERVICE_ACCOUNT_AUTHENTICATE_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U32 RemainingTime;
	PHONGTHAN_S32 ExtensionPoint;
	PHONGTHAN_U8 AccountName[32];
} PHONGTHAN_SERVICE_ACCOUNT_AUTHENTICATE_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 ExtensionPoint;
	PHONGTHAN_U8 AccountName[32];
} PHONGTHAN_SERVICE_ACCOUNT_RELEASE_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U8 AccountName[32];
} PHONGTHAN_SERVICE_ACCOUNT_RELEASE_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U8 AccountName[32];
} PHONGTHAN_SERVICE_ACCOUNT_ENTER_WORLD_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U8 AccountName[32];
} PHONGTHAN_SERVICE_ACCOUNT_ENTER_WORLD_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 Timestamp;
} PHONGTHAN_SERVICE_GATEWAY_HEARTBEAT;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U8 AccountName[32];
} PHONGTHAN_SERVICE_CHARACTER_LIST_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U8 CharacterCount;
	PHONGTHAN_U8 RecommendedIndex;
	PHONGTHAN_U16 Reserved;
	PHONGTHAN_U8 AccountName[32];
	PHONGTHAN_CHARACTER_SUMMARY Characters[PHONGTHAN_CHARACTER_LIMIT];
} PHONGTHAN_SERVICE_CHARACTER_LIST_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U8 AccountName[32];
	PHONGTHAN_U8 RoleName[32];
} PHONGTHAN_SERVICE_CHARACTER_DELETE_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U8 AccountName[32];
	PHONGTHAN_U8 RoleName[32];
} PHONGTHAN_SERVICE_CHARACTER_DELETE_RESPONSE;

typedef struct
{
	PHONGTHAN_S32 SkillId;
	PHONGTHAN_S32 SkillLevel;
	PHONGTHAN_S32 SkillValue;
} PHONGTHAN_STARTER_SKILL;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U8 AccountName[32];
	PHONGTHAN_U8 RoleName[32];
	PHONGTHAN_U8 Gender;
	PHONGTHAN_U8 Profession;
	PHONGTHAN_U16 NativePlaceId;
	PHONGTHAN_S32 SpawnMapId;
	PHONGTHAN_S32 SpawnX;
	PHONGTHAN_S32 SpawnY;
	PHONGTHAN_U16 FightLevel;
	PHONGTHAN_U16 SkillCount;
	PHONGTHAN_U32 FightExperience;
	PHONGTHAN_S32 Money;
	PHONGTHAN_S32 BankMoney;
	PHONGTHAN_S32 Power;
	PHONGTHAN_S32 Agility;
	PHONGTHAN_S32 Physique;
	PHONGTHAN_S32 Wisdom;
	PHONGTHAN_S32 Luck;
	PHONGTHAN_S32 MaxLife;
	PHONGTHAN_S32 MaxStamina;
	PHONGTHAN_S32 MaxMana;
	PHONGTHAN_S32 RemainingAttributePoints;
	PHONGTHAN_S32 RemainingSkillPoints;
	PHONGTHAN_U16 LeadershipLevel;
	PHONGTHAN_U16 Reserved;
	PHONGTHAN_U32 LeadershipExperience;
	PHONGTHAN_STARTER_SKILL Skills[PHONGTHAN_STARTER_SKILL_LIMIT];
} PHONGTHAN_SERVICE_CHARACTER_CREATE_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U8 AccountName[32];
	PHONGTHAN_U8 RoleName[32];
} PHONGTHAN_SERVICE_CHARACTER_CREATE_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U8 AccountName[32];
	PHONGTHAN_U8 RoleName[32];
} PHONGTHAN_SERVICE_CHARACTER_LOAD_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U32 StateSize;
} PHONGTHAN_SERVICE_CHARACTER_LOAD_RESPONSE_HEADER;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U8 LeaveWorld;
	PHONGTHAN_U8 Reserved[3];
	PHONGTHAN_U32 StateSize;
} PHONGTHAN_SERVICE_CHARACTER_SAVE_REQUEST_HEADER;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_S32 Result;
	PHONGTHAN_U8 RoleName[32];
} PHONGTHAN_SERVICE_CHARACTER_SAVE_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 RoleName[32];
	PHONGTHAN_U8 Lock;
	PHONGTHAN_U8 Reserved[3];
} PHONGTHAN_SERVICE_CHARACTER_LOCK_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
} PHONGTHAN_SERVICE_WORLD_HELLO_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 RequestId;
	PHONGTHAN_U32 ServiceId;
	PHONGTHAN_U32 PublicAddressV4;
	PHONGTHAN_U32 PrivateAddressV4;
	PHONGTHAN_U16 Port;
	PHONGTHAN_U16 Capacity;
	PHONGTHAN_U8 InstanceName[PHONGTHAN_WORLD_INSTANCE_NAME_SIZE];
} PHONGTHAN_SERVICE_WORLD_HELLO_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ServiceId;
	PHONGTHAN_U16 MapCount;
	PHONGTHAN_U16 Reserved;
} PHONGTHAN_SERVICE_WORLD_MAP_REGISTRY_HEADER;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 SessionTicket[PHONGTHAN_SESSION_TICKET_SIZE];
	PHONGTHAN_U32 TransferId;
	PHONGTHAN_S32 MapId;
	PHONGTHAN_S32 ExtensionPoint;
	PHONGTHAN_U8 Phase;
	PHONGTHAN_U8 Reason;
	PHONGTHAN_U8 ReleaseAccount;
	PHONGTHAN_U8 Reserved;
	PHONGTHAN_U8 AccountName[32];
	PHONGTHAN_U8 RoleName[32];
} PHONGTHAN_SERVICE_WORLD_SESSION_EVENT;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 SessionTicket[PHONGTHAN_SESSION_TICKET_SIZE];
	PHONGTHAN_S32 ExtensionPoint;
	PHONGTHAN_S32 ChangedExtensionPoint;
	PHONGTHAN_U32 StateSize;
} PHONGTHAN_WORLD_ATTACH_CHARACTER_HEADER;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 TransferId;
	PHONGTHAN_U8 SessionTicket[PHONGTHAN_SESSION_TICKET_SIZE];
	PHONGTHAN_U32 ServerAddressV4;
	PHONGTHAN_U16 ServerPort;
	PHONGTHAN_U16 Reserved;
	PHONGTHAN_S32 Result;
	PHONGTHAN_S32 DestinationMapId;
	PHONGTHAN_S32 DestinationX;
	PHONGTHAN_S32 DestinationY;
} PHONGTHAN_WORLD_TRANSFER_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 RoleName[32];
} PHONGTHAN_SESSION_SELECT_CHARACTER_REQUEST;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U8 SessionTicket[PHONGTHAN_SESSION_TICKET_SIZE];
	PHONGTHAN_U32 ServerAddressV4;
	PHONGTHAN_U16 ServerPort;
	PHONGTHAN_U8 Permit;
	PHONGTHAN_U8 Reserved;
	PHONGTHAN_U8 AccountName[32];
	PHONGTHAN_U8 RoleName[32];
} PHONGTHAN_SESSION_ENTER_WORLD_RESPONSE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ItemId;
	PHONGTHAN_S32 Durability;
} PHONGTHAN_ITEM_DURABILITY_MESSAGE;

typedef struct
{
	PHONGTHAN_S32 Type;
	PHONGTHAN_S32 Value[3];
} PHONGTHAN_ATTRIBUTE_WIRE;

typedef struct
{
	PHONGTHAN_WIRE_HEADER Header;
	PHONGTHAN_U32 ItemId;
	PHONGTHAN_S32 PropertyValues[PHONGTHAN_ITEM_PROPERTY_VALUE_COUNT];
	PHONGTHAN_ATTRIBUTE_WIRE Attributes[PHONGTHAN_ITEM_ATTRIBUTE_COUNT];
} PHONGTHAN_ITEM_PROPERTIES_MESSAGE;

#pragma pack(pop)

typedef char PHONGTHAN_HEADER_SIZE_MUST_BE_20[(sizeof(PHONGTHAN_WIRE_HEADER) == 20) ? 1 : -1];
typedef char PHONGTHAN_ITEM_USE_REQUEST_SIZE_MUST_BE_28[(sizeof(PHONGTHAN_ITEM_USE_REQUEST) == 28) ? 1 : -1];
typedef char PHONGTHAN_ITEM_PICKUP_REQUEST_SIZE_MUST_BE_28[(sizeof(PHONGTHAN_ITEM_PICKUP_REQUEST) == 28) ? 1 : -1];
typedef char PHONGTHAN_ITEM_MOVE_REQUEST_SIZE_MUST_BE_28[(sizeof(PHONGTHAN_ITEM_MOVE_REQUEST) == 28) ? 1 : -1];
typedef char PHONGTHAN_ITEM_DROP_REQUEST_SIZE_MUST_BE_24[(sizeof(PHONGTHAN_ITEM_DROP_REQUEST) == 24) ? 1 : -1];
typedef char PHONGTHAN_NPC_SHOP_SELL_REQUEST_SIZE_MUST_BE_28[(sizeof(PHONGTHAN_NPC_SHOP_SELL_REQUEST) == 28) ? 1 : -1];
typedef char PHONGTHAN_NPC_SHOP_BUY_REQUEST_SIZE_MUST_BE_32[(sizeof(PHONGTHAN_NPC_SHOP_BUY_REQUEST) == 32) ? 1 : -1];
typedef char PHONGTHAN_SESSION_ENTER_WORLD_REQUEST_SIZE_MUST_BE_68[(sizeof(PHONGTHAN_SESSION_ENTER_WORLD_REQUEST) == 68) ? 1 : -1];
typedef char PHONGTHAN_SESSION_AUTHENTICATE_REQUEST_SIZE_MUST_BE_116[(sizeof(PHONGTHAN_SESSION_AUTHENTICATE_REQUEST) == 116) ? 1 : -1];
typedef char PHONGTHAN_SESSION_AUTHENTICATE_RESPONSE_SIZE_MUST_BE_60[(sizeof(PHONGTHAN_SESSION_AUTHENTICATE_RESPONSE) == 60) ? 1 : -1];
typedef char PHONGTHAN_CHARACTER_SUMMARY_SIZE_MUST_BE_36[(sizeof(PHONGTHAN_CHARACTER_SUMMARY) == 36) ? 1 : -1];
typedef char PHONGTHAN_SESSION_CHARACTER_LIST_RESPONSE_SIZE_MUST_BE_136[(sizeof(PHONGTHAN_SESSION_CHARACTER_LIST_RESPONSE) == 136) ? 1 : -1];
typedef char PHONGTHAN_SESSION_CREATE_CHARACTER_REQUEST_SIZE_MUST_BE_56[(sizeof(PHONGTHAN_SESSION_CREATE_CHARACTER_REQUEST) == 56) ? 1 : -1];
typedef char PHONGTHAN_SESSION_CREATE_CHARACTER_RESPONSE_SIZE_MUST_BE_56[(sizeof(PHONGTHAN_SESSION_CREATE_CHARACTER_RESPONSE) == 56) ? 1 : -1];
typedef char PHONGTHAN_SESSION_DELETE_CHARACTER_REQUEST_SIZE_MUST_BE_116[(sizeof(PHONGTHAN_SESSION_DELETE_CHARACTER_REQUEST) == 116) ? 1 : -1];
typedef char PHONGTHAN_SESSION_DELETE_CHARACTER_RESPONSE_SIZE_MUST_BE_56[(sizeof(PHONGTHAN_SESSION_DELETE_CHARACTER_RESPONSE) == 56) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_GATEWAY_HELLO_REQUEST_SIZE_MUST_BE_132[(sizeof(PHONGTHAN_SERVICE_GATEWAY_HELLO_REQUEST) == 132) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_GATEWAY_HELLO_RESPONSE_SIZE_MUST_BE_64[(sizeof(PHONGTHAN_SERVICE_GATEWAY_HELLO_RESPONSE) == 64) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_ACCOUNT_AUTHENTICATE_REQUEST_SIZE_MUST_BE_124[(sizeof(PHONGTHAN_SERVICE_ACCOUNT_AUTHENTICATE_REQUEST) == 124) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_ACCOUNT_AUTHENTICATE_RESPONSE_SIZE_MUST_BE_68[(sizeof(PHONGTHAN_SERVICE_ACCOUNT_AUTHENTICATE_RESPONSE) == 68) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_ACCOUNT_RELEASE_REQUEST_SIZE_MUST_BE_60[(sizeof(PHONGTHAN_SERVICE_ACCOUNT_RELEASE_REQUEST) == 60) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_ACCOUNT_RELEASE_RESPONSE_SIZE_MUST_BE_60[(sizeof(PHONGTHAN_SERVICE_ACCOUNT_RELEASE_RESPONSE) == 60) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_ACCOUNT_ENTER_WORLD_REQUEST_SIZE_MUST_BE_56[(sizeof(PHONGTHAN_SERVICE_ACCOUNT_ENTER_WORLD_REQUEST) == 56) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_ACCOUNT_ENTER_WORLD_RESPONSE_SIZE_MUST_BE_60[(sizeof(PHONGTHAN_SERVICE_ACCOUNT_ENTER_WORLD_RESPONSE) == 60) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_GATEWAY_HEARTBEAT_SIZE_MUST_BE_24[(sizeof(PHONGTHAN_SERVICE_GATEWAY_HEARTBEAT) == 24) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_LIST_REQUEST_SIZE_MUST_BE_56[(sizeof(PHONGTHAN_SERVICE_CHARACTER_LIST_REQUEST) == 56) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_LIST_RESPONSE_SIZE_MUST_BE_172[(sizeof(PHONGTHAN_SERVICE_CHARACTER_LIST_RESPONSE) == 172) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_DELETE_REQUEST_SIZE_MUST_BE_88[(sizeof(PHONGTHAN_SERVICE_CHARACTER_DELETE_REQUEST) == 88) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_DELETE_RESPONSE_SIZE_MUST_BE_92[(sizeof(PHONGTHAN_SERVICE_CHARACTER_DELETE_RESPONSE) == 92) ? 1 : -1];
typedef char PHONGTHAN_STARTER_SKILL_SIZE_MUST_BE_12[(sizeof(PHONGTHAN_STARTER_SKILL) == 12) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_CREATE_REQUEST_SIZE_MUST_BE_936[(sizeof(PHONGTHAN_SERVICE_CHARACTER_CREATE_REQUEST) == 936) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_CREATE_RESPONSE_SIZE_MUST_BE_92[(sizeof(PHONGTHAN_SERVICE_CHARACTER_CREATE_RESPONSE) == 92) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_LOAD_REQUEST_SIZE_MUST_BE_88[(sizeof(PHONGTHAN_SERVICE_CHARACTER_LOAD_REQUEST) == 88) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_LOAD_RESPONSE_HEADER_SIZE_MUST_BE_32[(sizeof(PHONGTHAN_SERVICE_CHARACTER_LOAD_RESPONSE_HEADER) == 32) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_SAVE_REQUEST_HEADER_SIZE_MUST_BE_32[(sizeof(PHONGTHAN_SERVICE_CHARACTER_SAVE_REQUEST_HEADER) == 32) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_SAVE_RESPONSE_SIZE_MUST_BE_60[(sizeof(PHONGTHAN_SERVICE_CHARACTER_SAVE_RESPONSE) == 60) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_CHARACTER_LOCK_REQUEST_SIZE_MUST_BE_56[(sizeof(PHONGTHAN_SERVICE_CHARACTER_LOCK_REQUEST) == 56) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_WORLD_HELLO_REQUEST_SIZE_MUST_BE_24[(sizeof(PHONGTHAN_SERVICE_WORLD_HELLO_REQUEST) == 24) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_WORLD_HELLO_RESPONSE_SIZE_MUST_BE_72[(sizeof(PHONGTHAN_SERVICE_WORLD_HELLO_RESPONSE) == 72) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_WORLD_MAP_REGISTRY_HEADER_SIZE_MUST_BE_28[(sizeof(PHONGTHAN_SERVICE_WORLD_MAP_REGISTRY_HEADER) == 28) ? 1 : -1];
typedef char PHONGTHAN_SERVICE_WORLD_SESSION_EVENT_SIZE_MUST_BE_116[(sizeof(PHONGTHAN_SERVICE_WORLD_SESSION_EVENT) == 116) ? 1 : -1];
typedef char PHONGTHAN_WORLD_ATTACH_CHARACTER_HEADER_SIZE_MUST_BE_48[(sizeof(PHONGTHAN_WORLD_ATTACH_CHARACTER_HEADER) == 48) ? 1 : -1];
typedef char PHONGTHAN_WORLD_TRANSFER_RESPONSE_SIZE_MUST_BE_64[(sizeof(PHONGTHAN_WORLD_TRANSFER_RESPONSE) == 64) ? 1 : -1];
typedef char PHONGTHAN_SESSION_SELECT_CHARACTER_REQUEST_SIZE_MUST_BE_52[(sizeof(PHONGTHAN_SESSION_SELECT_CHARACTER_REQUEST) == 52) ? 1 : -1];
typedef char PHONGTHAN_SESSION_ENTER_WORLD_RESPONSE_SIZE_MUST_BE_108[(sizeof(PHONGTHAN_SESSION_ENTER_WORLD_RESPONSE) == 108) ? 1 : -1];

inline void PhongThanInitializeWireHeader(PHONGTHAN_WIRE_HEADER* pHeader,
	PHONGTHAN_U16 nMessageType, PHONGTHAN_U32 nPacketSize,
	PHONGTHAN_U16 nFlags, PHONGTHAN_U32 nSequence)
{
	if (!pHeader)
		return;
	pHeader->Magic = PHONGTHAN_WIRE_MAGIC;
	pHeader->Version = PHONGTHAN_WIRE_VERSION;
	pHeader->HeaderSize = (PHONGTHAN_U16)sizeof(PHONGTHAN_WIRE_HEADER);
	pHeader->MessageType = nMessageType;
	pHeader->Flags = nFlags;
	pHeader->PacketSize = nPacketSize;
	pHeader->Sequence = nSequence;
}

inline int PhongThanIsWirePacket(const void* pData, PHONGTHAN_U32 nAvailableSize)
{
	if (!pData || nAvailableSize < sizeof(PHONGTHAN_WIRE_HEADER))
		return 0;
	const PHONGTHAN_WIRE_HEADER* pHeader =
		(const PHONGTHAN_WIRE_HEADER*)pData;
	return pHeader->Magic == PHONGTHAN_WIRE_MAGIC;
}

inline int PhongThanValidateWireHeader(const PHONGTHAN_WIRE_HEADER* pHeader,
	PHONGTHAN_U32 nAvailableSize)
{
	if (!pHeader || pHeader->Magic != PHONGTHAN_WIRE_MAGIC ||
		pHeader->Version != PHONGTHAN_WIRE_VERSION ||
		pHeader->HeaderSize != sizeof(PHONGTHAN_WIRE_HEADER) ||
		pHeader->PacketSize < sizeof(PHONGTHAN_WIRE_HEADER) ||
		pHeader->PacketSize > PHONGTHAN_WIRE_MAX_PACKET_SIZE ||
		pHeader->PacketSize > nAvailableSize)
	{
		return 0;
	}
	return 1;
}

inline int PhongThanValidateItemSnapshot(const void* data, PHONGTHAN_U32 size)
{
	if (!data || size != sizeof(PHONGTHAN_ITEM_SNAPSHOT)) return 0;
	const PHONGTHAN_ITEM_SNAPSHOT* item = (const PHONGTHAN_ITEM_SNAPSHOT*)data;
	// Old untagged level 0..15 or tagged rule (bits 8..23) plus level.
	const PHONGTHAN_U32 upgrade=(PHONGTHAN_U32)item->UpgradeLevel;
	if(upgrade>15 && ((upgrade&0xff0000f0u)!=0x40000000u || !(upgrade&15u) || !((upgrade>>8)&65535u)))return 0;
	return PhongThanValidateWireHeader(&item->Header, size) &&
		item->Header.PacketSize == size &&
		item->Header.MessageType == PHONGTHAN_MSG_INVENTORY_ITEM_SNAPSHOT &&
		item->Header.Flags == PHONGTHAN_WIRE_FLAG_RESPONSE;
}

#endif
