[Water]
Depth=20.0
Size=64.0

[Sky]
;upTex=\spr\Ui3\聊天室\up.tga
;downTex=\spr\Ui3\聊天室\dn.tga
;leftTex=\spr\Ui3\聊天室\lf.tga
;rightTex=\spr\Ui3\聊天室\rt.tga
;frontTex=\spr\Ui3\聊天室\ft.tga
;backTex=\spr\Ui3\聊天室\bk.tga
upTex=\spr\Ui3\聊天室\up.jpg
downTex=\spr\Ui3\聊天室\dn.tga
leftTex=\spr\Ui3\聊天室\lf.jpg
rightTex=\spr\Ui3\聊天室\rt.jpg
frontTex=\spr\Ui3\聊天室\ft.jpg
backTex=\spr\Ui3\聊天室\bk.jpg

[Ground]
ModelFile=\spr\Ui3\聊天室\Island.x

[Flare]
SunHeight=10.0
SunSize=10.0
SunTex=\spr\Ui3\聊天室\sunflare.tga
