-- Phong Than 2026-10-02: ActionScript of the 4 tien and Thong Thien Giao Chu in Van Tien tran.
-- SetNpcScript (ActionScript) -> the engine calls LastDamage(npc) with PlayerIndex = kill owner
-- (KNpc::DoDeath, kind_normal); the template DeathScript (npcdeath\normal.lua) still runs as usual.
-- The bosses get SetNpcRevTime(24 h) and are removed by the engine when the mission closes.
-- 2026-10-04 (vtcc): the engine ignores the DropRateFile columns, so the VNG drop of the template is rolled
-- here (vt_drop.lua, generated by scratchpad\vtcc\gen_drop.py) into the killer's bag before the tran logic.
Include("\\script\\phongthan\\vantien\\vt_lib.lua")
Include("\\script\\phongthan\\vantien\\vt_drop.lua")

function LastDamage(npcIndex)
	local pi = PlayerIndex
	if PTVD_Drop then PTVD_Drop(npcIndex) end
	PlayerIndex = pi
	PTVT_BossDeath(npcIndex)
end

function Revive(npcIndex)
end

function DeathSelf(npcIndex)
end
