-- Phong Than 2026-10-04 (agent vtcc): VNG drops of the Van Tien tran tien, Thong Thien and Bao ruong.
-- Generated by scratchpad\vtcc\gen_drop.py from settings\phongthan\Npcs.txt (Treasure / DropRateFile pairs) and
-- the VNG \settings\item\droprate\*.ini; only entries that exist on server AND client are kept (drop_report.txt).
-- The engine does not read DropRateFile, so the ActionScripts vt_boss.lua / vt_chest.lua call PTVD_Drop(npc):
-- n rolls per table (n = Treasure for DropRateFile, Treasure1 for DropRateFile1), each roll random(1, RandRange)
-- against the cumulative RandRate; equipment / potion level weighted between MinItemLevel(Scale) and
-- MaxItemLevel(Scale). Items go into the killer's bag (AddNormalItemPile: stacks, nothing on the ground); the
-- special table (DropRateFile1) is given first, a full bag stops the rest. Genre-7 VNG skill books are given as
-- the project's usable bi kip 6/1/(62000 + skill) when that row exists. Do not edit: run the generator.
-- 0 = VNG (the tien roll their special table DropRateFile1 = jiuying.ini Treasure1 = 0 times: no bi kip).
-- n > 0 = non-VNG option: the tien roll that table n times (bi kip he phai, do luc 0/2/3-5, 0/9/3-5, Minh Uyen).
PTVD_FORCE1 = 1   -- 2026-10-04 user choice (not VNG): every tien rolls jiuying.ini once (bi kip, do luc)
PTVD_T = {}
PTVD_N = {}
PTVD_C = { {}, {}, {} }
PTVD_TTLV = {}

function PTVD_Tab(k, range)
	local t = {}
	t.range = range
	t.n = 0
	PTVD_T[k] = t
end

-- one entry: genre, detail, particular, rate, name; levels added by PTVD_Lv
function PTVD_Ent(k, g, d, p, r, nm)
	local t = PTVD_T[k]
	local e = {}
	e.g = g
	e.d = d
	e.p = p
	e.r = r
	e.nm = nm
	e.lv = {}
	e.lw = 0
	e.pri = 0
	if g == 0 and d ~= 4 and p <= 3 then e.pri = 1 end   -- plain white gear of the generic boss table: given last
	t.n = t.n + 1
	t[t.n] = e
end

function PTVD_Lv(k, lv, wt)
	local t = PTVD_T[k]
	local e = t[t.n]
	tinsert(e.lv, { lv, wt })
	e.lw = e.lw + wt
end

-- entry of table k (last added) belongs to bonus category cat (profession prof, -1 = any)
function PTVD_Cat(k, cat, prof)
	local t = PTVD_T[k]
	local e = t[t.n]
	e.prof = prof
	tinsert(PTVD_C[cat], e)
end

-- template: rolls of the main table, its key, rolls of the special table, its key
function PTVD_Npc(tpl, n0, k0, n1, k1)
	local o = {}
	o.n0 = n0
	o.k0 = k0
	o.n1 = n1
	o.k1 = k1
	PTVD_N[tpl] = o
end

-- npcdroprate-boss1.ini: RandRange 150000, kept rate sum 96090 (64.1% per roll)
PTVD_Tab(1, 150000)
PTVD_Ent(1, 0, 0, 0, 1000, "Vi\170m \167\213 ki\213m")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 0, 1, 1000, "Tr\185m Kim ph\241")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 0, 2, 2000, "Th\184i C\249c ki\213m")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 0, 3, 2000, "Di\214t Th\199n ph\241")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 2, 0, 2000, "Ho\181ng Kim Ch\202n \167\184n  Gi\184p")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 2, 1, 2000, "H\229ng Qu\169n \174\185o b\181o")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 2, 2, 2000, "Kh\184ng Long H\233 Gi\184p")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 5, 0, 2000, "Ch\202n \167\184n Chi\213n Ngoa")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 5, 1, 2000, "H\229ng Qu\169n l\253")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 5, 2, 2000, "Kh\184ng Long Ngoa")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 6, 0, 2000, "Ch\202n \167\184n  Y\170u \167\184i")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 6, 1, 2000, "H\229ng Qu\169n C\169n")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 6, 2, 2000, "Kh\184ng Long Y\170u \167\184i")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 7, 0, 2000, "Ch\202n \167\184n  Kh\171i")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 7, 1, 2000, "H\229ng Qu\169n qu\184n")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 7, 2, 2000, "Kh\184ng Long Tr\244")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 9, 0, 2000, "Ch\202n \167\184n phi phong")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 9, 1, 2000, "H\229ng Qu\169n l\214nh")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 0, 9, 2, 2000, "Kh\184ng Long k\213t")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Ent(1, 1, 1, 0, 30000, "Trung H\229ng \174\172n")
PTVD_Lv(1, 1, 20)
PTVD_Ent(1, 1, 4, 0, 30000, "Trung Ho\181n \174\172n")
PTVD_Lv(1, 1, 20)
PTVD_Ent(1, 0, 4, 0, 5, "Ng\242 Quang th\185ch")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Cat(1, 2, -1)
PTVD_Ent(1, 0, 4, 1, 5, "H\215nh Thi\170n \202n")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Cat(1, 2, -1)
PTVD_Ent(1, 0, 4, 2, 5, "C\181n Kh\171n X\221ch")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Cat(1, 2, -1)
PTVD_Ent(1, 0, 4, 3, 5, "H\231n Thi\170n L\168ng")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Cat(1, 2, -1)
PTVD_Ent(1, 0, 4, 4, 5, "B\215nh L\173u Ly")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Cat(1, 2, -1)
PTVD_Ent(1, 0, 4, 5, 5, "H\225a Long Ti\170u")
PTVD_Lv(1, 1, 20)
PTVD_Lv(1, 2, 19)
PTVD_Lv(1, 3, 18)
PTVD_Lv(1, 4, 17)
PTVD_Lv(1, 5, 16)
PTVD_Lv(1, 6, 14)
PTVD_Lv(1, 7, 13)
PTVD_Lv(1, 8, 12)
PTVD_Lv(1, 9, 11)
PTVD_Lv(1, 10, 10)
PTVD_Cat(1, 2, -1)
PTVD_Ent(1, 3, 41, 0, 30, "Lam b\182o th\185ch")
PTVD_Lv(1, 1, 1)
PTVD_Ent(1, 3, 79, 0, 30, "H\229ng b\182o th\185ch")
PTVD_Lv(1, 1, 1)
-- jiuying.ini: RandRange 1000000, kept rate sum 653000 (65.3% per roll)
PTVD_Tab(2, 1000000)
PTVD_Ent(2, 0, 0, 4, 2000, "Vi\170m \167\213 ki\213m")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Ent(2, 0, 0, 5, 2000, "Tr\185m Kim ph\241")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Ent(2, 0, 0, 6, 2000, "Th\184i C\249c ki\213m")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Ent(2, 0, 0, 7, 2000, "Di\214t Th\199n ph\241")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Ent(2, 0, 2, 3, 20000, "Ho\181ng Kim Ch\202n \167\184n Gi\184p")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 3, -1)
PTVD_Ent(2, 0, 2, 4, 20000, "H\229ng Qu\169n \174\185o b\181o")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 3, -1)
PTVD_Ent(2, 0, 2, 5, 20000, "Kh\184ng Long H\233 Gi\184p")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 3, -1)
PTVD_Ent(2, 0, 9, 3, 20000, "Ch\202n \167\184n phi phong")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 3, -1)
PTVD_Ent(2, 0, 9, 4, 20000, "H\229ng Qu\169n l\214nh")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 3, -1)
PTVD_Ent(2, 0, 9, 5, 20000, "Kh\184ng Long k\213t")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 3, -1)
PTVD_Ent(2, 0, 4, 0, 50000, "Ng\242 Quang th\185ch")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 2, -1)
PTVD_Ent(2, 0, 4, 1, 100000, "H\215nh Thi\170n \202n")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 2, -1)
PTVD_Ent(2, 0, 4, 2, 20000, "C\181n Kh\171n X\221ch")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 2, -1)
PTVD_Ent(2, 0, 4, 3, 20000, "H\231n Thi\170n L\168ng")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 2, -1)
PTVD_Ent(2, 0, 4, 4, 20000, "B\215nh L\173u Ly")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 2, -1)
PTVD_Ent(2, 0, 4, 5, 20000, "H\225a Long Ti\170u")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 2, -1)
PTVD_Ent(2, 6, 1, 62008, 20000, "<c=green>B\221 K\221p Thi\170n Phong \167\222a Nh\203n<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 1)
PTVD_Ent(2, 6, 1, 62009, 20000, "<c=green>B\221 K\221p B\168ng C\172 Tuy\213t C\232t<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 1)
PTVD_Ent(2, 6, 1, 62010, 20000, "<c=green>B\221 K\221p Phong L\169m H\225a S\172n<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 1)
PTVD_Ent(2, 6, 1, 62011, 20000, "<c=green>B\221 K\221p H\185n \167\222a L\171i<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 1)
PTVD_Ent(2, 6, 1, 62029, 20000, "<c=green>B\221 K\221p Khai S\172n Tr\182m<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 0)
PTVD_Ent(2, 6, 1, 62030, 20000, "<c=green>B\221 K\221p H\229i Phong Tr\182m<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 0)
PTVD_Ent(2, 6, 1, 62031, 20000, "<c=green>B\221 K\221p \167i\214n Quang Tr\182m<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 0)
PTVD_Ent(2, 6, 1, 62044, 20000, "<c=green>B\221 K\221p Th\171i Th\169n Ch\243<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 2)
PTVD_Ent(2, 6, 1, 62045, 20000, "<c=green>B\221 K\221p B\230 T\169m Ch\243<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 2)
PTVD_Ent(2, 6, 1, 62451, 20000, "<c=green>B\221 K\221p Tr\173\234ng Cung T\213<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 2)
PTVD_Ent(2, 6, 1, 62452, 20000, "<c=green>B\221 K\221p Thi\170n V\242 T\213<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 2)
PTVD_Ent(2, 0, 0, 8, 500, "Cu\232c chim c\202p 10")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Ent(2, 0, 0, 12, 500, "L\231 Ban ph\241 c\202p 10")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Ent(2, 6, 1, 62012, 5000, "<c=green>B\221 K\221p Tinh Th\171ng Th\230 H\214<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 1)
PTVD_Ent(2, 6, 1, 62013, 3000, "<c=green>B\221 K\221p Thi\213t M\183 B\168ng Qua<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 1)
PTVD_Ent(2, 6, 1, 62014, 1000, "<c=green>B\221 K\221p Tinh Th\171ng H\225a H\214<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 1)
PTVD_Ent(2, 6, 1, 62032, 5000, "<c=green>B\221 K\221p Ho\181nh Kh\171ng Tr\182m<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 0)
PTVD_Ent(2, 6, 1, 62033, 3000, "<c=green>B\221 K\221p Tinh Th\171ng \167o\182n \167ao<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 0)
PTVD_Ent(2, 6, 1, 62034, 1000, "<c=green>B\221 K\221p Tinh Th\171ng Tr\173\234ng \167ao<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 0)
PTVD_Ent(2, 6, 1, 62046, 5000, "<c=green>B\221 K\221p C\173\234ng C\171ng Ch\243<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 2)
PTVD_Ent(2, 6, 1, 62047, 2000, "<c=green>B\221 K\221p Ph\184 Gi\184p Ch\243<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 2)
PTVD_Ent(2, 6, 1, 62453, 5000, "<c=green>B\221 K\221p Li\170n N\231 T\213<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 2)
PTVD_Ent(2, 6, 1, 62454, 2000, "<c=green>B\221 K\221p H\225a L\171i T\213<c>")
PTVD_Lv(2, 1, 1)
PTVD_Cat(2, 1, 2)
PTVD_Ent(2, 0, 0, 316, 2000, "Long T\221ch Cung")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Ent(2, 0, 2, 311, 20000, "Minh Uy\170n C\184ch Gi\184p")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 3, -1)
PTVD_Ent(2, 0, 9, 311, 20000, "Minh Uy\170n Phi Phong")
PTVD_Lv(2, 1, 20)
PTVD_Lv(2, 2, 19)
PTVD_Lv(2, 3, 18)
PTVD_Lv(2, 4, 17)
PTVD_Lv(2, 5, 16)
PTVD_Lv(2, 6, 14)
PTVD_Lv(2, 7, 13)
PTVD_Lv(2, 8, 12)
PTVD_Lv(2, 9, 11)
PTVD_Lv(2, 10, 10)
PTVD_Cat(2, 3, -1)
-- tongtian5.ini: RandRange 1000000, kept rate sum 354800 (35.5% per roll)
PTVD_Tab(3, 1000000)
PTVD_Ent(3, 0, 0, 4, 4000, "Vi\170m \167\213 ki\213m")
PTVD_Lv(3, 10, 100)
PTVD_Ent(3, 0, 0, 5, 4000, "Tr\185m Kim ph\241")
PTVD_Lv(3, 10, 100)
PTVD_Ent(3, 0, 0, 6, 5000, "Th\184i C\249c ki\213m")
PTVD_Lv(3, 10, 100)
PTVD_Ent(3, 0, 0, 7, 5000, "Di\214t Th\199n ph\241")
PTVD_Lv(3, 10, 100)
PTVD_Ent(3, 6, 1, 890, 500, "\167\229 Ph\230: Th\202t B\182o Kim Li\170n*Gi\184p S\220")
PTVD_Lv(3, 1, 1)
PTVD_Ent(3, 6, 1, 891, 500, "\167\229 Ph\230: Th\202t B\182o Kim Li\170n*\167\185o S\220 ")
PTVD_Lv(3, 1, 1)
PTVD_Ent(3, 6, 1, 892, 500, "\167\229 Ph\230: Th\202t B\182o Kim Li\170n*D\222 Nh\169n ")
PTVD_Lv(3, 1, 1)
PTVD_Ent(3, 0, 4, 14, 20000, "D\169y Kh\230n Ti\170n")
PTVD_Lv(3, 10, 100)
PTVD_Cat(3, 2, -1)
PTVD_Ent(3, 0, 4, 15, 20000, "Ch\202n Thi\170n Cung")
PTVD_Lv(3, 10, 100)
PTVD_Cat(3, 2, -1)
PTVD_Ent(3, 0, 4, 16, 20000, "Kim B\184t Vu")
PTVD_Lv(3, 10, 100)
PTVD_Cat(3, 2, -1)
PTVD_Ent(3, 0, 4, 17, 20000, "Linh Lung Th\184p")
PTVD_Lv(3, 10, 100)
PTVD_Cat(3, 2, -1)
PTVD_Ent(3, 0, 4, 0, 20000, "Ng\242 Quang th\185ch")
PTVD_Lv(3, 10, 100)
PTVD_Cat(3, 2, -1)
PTVD_Ent(3, 0, 4, 1, 50000, "H\215nh Thi\170n \202n")
PTVD_Lv(3, 10, 100)
PTVD_Cat(3, 2, -1)
PTVD_Ent(3, 0, 4, 2, 20000, "C\181n Kh\171n X\221ch")
PTVD_Lv(3, 10, 100)
PTVD_Cat(3, 2, -1)
PTVD_Ent(3, 0, 4, 3, 20000, "H\231n Thi\170n L\168ng")
PTVD_Lv(3, 10, 100)
PTVD_Cat(3, 2, -1)
PTVD_Ent(3, 0, 4, 4, 20000, "B\215nh L\173u Ly")
PTVD_Lv(3, 10, 100)
PTVD_Cat(3, 2, -1)
PTVD_Ent(3, 0, 4, 5, 20000, "H\225a Long Ti\170u")
PTVD_Lv(3, 10, 100)
PTVD_Cat(3, 2, -1)
PTVD_Ent(3, 3, 41, 0, 100000, "Lam b\182o th\185ch")
PTVD_Lv(3, 1, 1)
PTVD_Ent(3, 0, 0, 316, 3500, "Long T\221ch Cung")
PTVD_Lv(3, 10, 100)
PTVD_Ent(3, 0, 0, 337, 1800, "C\181n Kh\171n Cung")
PTVD_Lv(3, 10, 100)
-- baoxiang5.ini: RandRange 1000000, kept rate sum 650400 (65.0% per roll)
PTVD_Tab(4, 1000000)
PTVD_Ent(4, 0, 0, 4, 80, "Vi\170m \167\213 ki\213m")
PTVD_Lv(4, 9, 100)
PTVD_Lv(4, 10, 1)
PTVD_Ent(4, 0, 0, 5, 80, "Tr\185m Kim ph\241")
PTVD_Lv(4, 9, 100)
PTVD_Lv(4, 10, 1)
PTVD_Ent(4, 0, 0, 6, 80, "Th\184i C\249c ki\213m")
PTVD_Lv(4, 9, 100)
PTVD_Lv(4, 10, 1)
PTVD_Ent(4, 0, 0, 7, 80, "Di\214t Th\199n ph\241")
PTVD_Lv(4, 9, 100)
PTVD_Lv(4, 10, 1)
PTVD_Ent(4, 3, 28, 0, 100000, "H\229ng th\241y tinh")
PTVD_Lv(4, 1, 1)
PTVD_Ent(4, 3, 80, 0, 100000, "Lam th\241y tinh")
PTVD_Lv(4, 1, 1)
PTVD_Ent(4, 3, 63, 0, 100000, "Th\241y linh ph\239")
PTVD_Lv(4, 1, 1)
PTVD_Ent(4, 3, 1173, 0, 350000, "Huy\212n Linh Nh\183n")
PTVD_Lv(4, 1, 1)
PTVD_Ent(4, 0, 0, 317, 80, "Long T\221ch Cung")
PTVD_Lv(4, 9, 100)
PTVD_Lv(4, 10, 1)
-- Thong Thien bonus (only when PTVD_FORCE1 > 0, user choice, not VNG): bi kip, phap bao, do luc pieces, level
PTVD_TTB = { 1, 1, 3 }
PTVD_TTLV[1908] = 7
PTVD_TTLV[1913] = 8
PTVD_TTLV[1918] = 9
PTVD_TTLV[1923] = 10
PTVD_Npc(1904, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1905, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1906, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1907, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1909, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1910, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1911, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1912, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1914, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1915, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1916, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1917, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1919, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1920, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1921, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1922, 18, 1, 0, 2)   -- tpl: npcdroprate-boss1.ini x18, jiuying.ini x0
PTVD_Npc(1908, 80, 1, 6, 3)   -- tpl: npcdroprate-boss1.ini x80, tongtian5.ini x6
PTVD_Npc(1913, 80, 1, 6, 3)   -- tpl: npcdroprate-boss1.ini x80, tongtian5.ini x6
PTVD_Npc(1918, 80, 1, 6, 3)   -- tpl: npcdroprate-boss1.ini x80, tongtian5.ini x6
PTVD_Npc(1923, 80, 1, 6, 3)   -- tpl: npcdroprate-boss1.ini x80, tongtian5.ini x6
PTVD_Npc(1929, 30, 1, 6, 4)   -- tpl: npcdroprate-boss1.ini x30, baoxiang5.ini x6

-- level of entry e (weighted)
function PTVD_PickLv(e)
	local n = getn(e.lv)
	if n <= 1 then return e.lv[1][1] end
	local r = random(1, e.lw)
	local i = 1
	while i <= n do
		r = r - e.lv[i][2]
		if r <= 0 then return e.lv[i][1] end
		i = i + 1
	end
	return e.lv[n][1]
end

-- n rolls of table k: picked entries appended to out
function PTVD_Roll(k, n, out)
	local t = PTVD_T[k]
	if not t or n <= 0 then return end
	local j = 1
	while j <= n do
		local r = random(1, t.range)
		local i = 1
		while i <= t.n do
			r = r - t[i].r
			if r <= 0 then
				tinsert(out, t[i])
				i = t.n
			end
			i = i + 1
		end
		j = j + 1
	end
end

-- weighted pick in bonus category cat (prof >= 0: only entries of that profession or any); nil if empty
function PTVD_PickCat(cat, prof)
	local c = PTVD_C[cat]
	local sum = 0
	local i = 1
	while c[i] do
		if prof < 0 or c[i].prof < 0 or c[i].prof == prof then sum = sum + c[i].r end
		i = i + 1
	end
	if sum <= 0 then return nil end
	local r = random(1, sum)
	i = 1
	while c[i] do
		if prof < 0 or c[i].prof < 0 or c[i].prof == prof then
			r = r - c[i].r
			if r <= 0 then return c[i] end
		end
		i = i + 1
	end
	return nil
end

-- guaranteed Thong Thien bonus (PTVD_FORCE1 > 0): PTVD_TTB[1] bi kip of the killer's profession, [2] phap bao,
-- [3] do luc pieces, at the tran level PTVD_TTLV (7 Tho .. 10 Phong, highest level of the entry otherwise)
function PTVD_Bonus(tpl, out)
	local lv = PTVD_TTLV[tpl]
	if not lv or PTVD_FORCE1 <= 0 then return end
	local prof = GetPlayerType()
	if not prof or prof < 0 or prof > 2 then prof = -1 end
	local cat = 1
	while cat <= 3 do
		local n = 0
		while n < PTVD_TTB[cat] do
			local e = PTVD_PickCat(cat, prof)
			if not e and cat == 1 then e = PTVD_PickCat(cat, -1) end
			if e then
				local b = {}
				b.g = e.g
				b.d = e.d
				b.p = e.p
				b.nm = e.nm
				b.pri = -1
				b.lv = { { lv, 1 } }
				b.lw = 1
				if not PTVD_HasLv(e, lv) then
					b.lv = e.lv
					b.lw = e.lw
				end
				tinsert(out, b)
			end
			n = n + 1
		end
		cat = cat + 1
	end
end

function PTVD_HasLv(e, lv)
	local i = 1
	while e.lv[i] do
		if e.lv[i][1] == lv then return 1 end
		i = i + 1
	end
	return nil
end

-- create one item in the current player's bag; 1 = given, 0 = no room (nothing is dropped on the ground)
function PTVD_GiveOne(e)
	local lv = PTVD_PickLv(e)
	local se = 0
	if e.g == 0 then se = random(0, 4) end
	local r = AddNormalItemPile(e.g, e.d, e.p, lv, se, 0)
	if r and r > 0 then return 1 end
	return 0
end

-- VNG drop of NPC ni for the current player (the killer); returns given, lost
function PTVD_Drop(ni)
	local o = PTVD_N[GetNpcTemplateID(ni)]
	if not o or not AddNormalItemPile then return 0, 0 end
	local list = {}
	local n1 = o.n1
	if n1 == 0 and PTVD_FORCE1 > 0 and o.k1 > 0 then n1 = PTVD_FORCE1 end
	PTVD_Bonus(GetNpcTemplateID(ni), list)
	PTVD_Roll(o.k1, n1, list)
	PTVD_Roll(o.k0, o.n0, list)
	local got = 0
	local lost = 0
	local names = ""
	local pass = -1
	while pass <= 1 do
		local i = 1
		while list[i] do
			if list[i].pri == pass then
				if lost == 0 and PTVD_GiveOne(list[i]) == 1 then
					got = got + 1
					if got <= 6 then names = names .. ", " .. list[i].nm end
				else
					lost = lost + 1
				end
			end
			i = i + 1
		end
		pass = pass + 1
	end
	if got > 0 then
		local s = "V\203t ph\200m r\172i (b\182ng VNG): nh\203n " .. got .. " m\227n: " .. strsub(names, 3)
		if got > 6 then s = s .. "..." end
		Msg2Player(s .. ".")
	end
	if lost > 0 then Msg2Player("H\181nh trang \174\199y: " .. lost .. " v\203t ph\200m r\172i kh\171ng nh\203n \174\173\238c. H\183y d\228n b\237t h\181nh trang.") end
	return got, lost
end
