-- Van Tien tran data (generated by scratchpad vantien\impl\build.py, 2026-10-02).
-- Cells are map coordinates (pixel / 32). Every cell was checked against the Huyen map Region_S:
-- obstacle 0, entry / tien / mobs in the main walkable area, Thong Thien + chests inside the
-- isolated 'Than Bi Tran Diem' area that the VNG traps teleport to.
PTVT_DATA_VERSION = 20261002
PTVT_MAPS = {1079, 1080, 1081, 1082}
PTVT_NAME = {"Th\230", "Th\241y", "H\225a", "Phong"}
PTVT_MINLV = {30, 51, 71, 91}
PTVT_GV0 = 400            -- GlobalValue 400..419 (VNG Van Tien chest slots, unused elsewhere): 5 per tran
PTVT_T_PROGRESS = 2000    -- task: bit n = tran n cleared once (unlocks tran n+1)
PTVT_T_DAY = 2001         -- task: date of the daily counter (YYYYMMDD)
PTVT_T_DAILY = 2002       -- task: rewarded clears today, decimal digit n = tran n
PTVT_T_SESSION = 2003     -- task: session key of the tran last entered
PTVT_T_ELIG = 2004        -- task: session key whose chests this player may open
PTVT_T_INMAP = 2005       -- task: map id while inside (cleanup by the minute tick)
PTVT_DAILY_CAP = 2        -- rewarded clears per tran per day
PTVT_PREP_DEMAND = 20     -- seconds of preparation when a player opens the tran
PTVT_PREP_SCHED = 300     -- seconds of preparation for the scheduled opening
PTVT_FIGHT = 1800         -- seconds of fighting (VNG: 30 minutes)
PTVT_NOREVIVE = 1555200   -- revive frames for bosses / chests (24 h): they stay dead
PTVT_TIMER_END = 1        -- mission timer id = PTVT_TIMER_END + n   (task02..05.lua, VNG off)
PTVT_TIMER_START = 5      -- mission timer id = PTVT_TIMER_START + n (task06..09.lua, VNG start)
PTVT_MAX_PLAYER = 1200
PTVT_SCHED = {"02:00", "10:00", "13:00", "18:00", "21:00", "23:00"}  -- VNG systemtimetask hours
PTVT_SCHED_OFFSET = {0, 5, 10, 15}                                    -- Tho :00, Thuy :05, Hoa :10, Phong :15
PTVT_TOWN = {1020, 1580, 3030}                                        -- Tay Ky, next to Bao Thuong
PTVT_TH = {1020, 50464, 96896, 202}                                   -- Thien Hung: map, mpsX, mpsY, template (passerby054, human immortal look)
PTVT_TH_NAME = "Thi\170n H\239ng"
PTVT_TH_SCRIPT = "\\script\\phongthan\\vantien\\vt_thienhung.lua"
PTVT_TPL_DOCTOR = 766                                                 -- VNG yisheng (Dai phu in the tran)
PTVT_DOCTOR_NAME = "\167\185i phu V\185n Ti\170n"
PTVT_DOCTOR_SCRIPT = "\\script\\phongthan\\vantien\\vt_daiphu.lua"
PTVT_BOSS_SCRIPT = "\\script\\phongthan\\vantien\\vt_boss.lua"
PTVT_CHEST_SCRIPT = "\\script\\phongthan\\vantien\\vt_chest.lua"
PTVT_MOB_SCRIPT = "\\script\\phongthan\\vantien\\vt_mob.lua"     -- 2026-10-02 vantien2: mob LastDamage -> daily quest credit
PTVT_TPL_CHEST = 1929                                                 -- baoxiang (huan)
PTVT_CHEST_NAME = "B\182o r\173\172ng Th\171ng Thi\170n"
PTVT_BOSS_NAME = {"\164 V\169n Ti\170n", "C\199u Th\241 Ti\170n", "Linh Nha Ti\170n", "Kim Quang Ti\170n", "Th\171ng Thi\170n Gi\184o Ch\241"}
PTVT_TOKEN_NAME = {"Thanh long l\214nh", "Chu t\173\237c l\214nh", "Huy\210n v\226 l\214nh", "B\185ch h\230 l\214nh"}
PTVT_TOKEN = {66, 67, 68, 69}                                         -- material (3, d): dropped by the 4 tien, opens the VNG traps
-- rewards (solo balance): exp = factor * player level
PTVT_CHEST_EXP = {300, 400, 500, 600}
PTVT_CHEST_MONEY = {3000, 6000, 10000, 15000}
PTVT_TT_EXP = {600, 800, 1000, 1200}
PTVT_TT_MONEY = {10000, 20000, 30000, 50000}
PTVT_ELEMENT = {110, 112, 113, 111}                                   -- Dia Tam / Thuy Hon / Hoa Linh / Phong Le (orange gear material)
-- chest item roll (1..100): {upper bound, detail or 0 = element of the tran}
PTVT_CHEST_ROLL = {{45, 0}, {65, 77}, {85, 78}, {95, 136}}             -- element / Manh Hong thuy tinh / Manh Lam thuy tinh / Hoan Nguyen Thach
PTVT_ITEM_NAME = {[0] = "", [77] = "M\182nh H\229ng th\241y tinh", [78] = "M\182nh Lam th\241y tinh", [136] = "Ho\181n Nguy\170n Th\185ch", [110] = "\167\222a T\169m", [111] = "Phong L\214", [112] = "Th\241y H\229n", [113] = "H\225a Linh"}
PTVT_D = {}
PTVT_D[1] = {
	entry = {1325,3280}, tt = {1340,3217},
	doctors = {{1328,3283},{1333,3215},{1329,3372}},
	chests = {{1344,3217},{1336,3217},{1340,3222},{1340,3212}},
	tien = {{1443,3164},{1531,3267},{1464,3368},{1595,3335}},
	mobs = {{1449,3164,53},{1437,3164,54},{1443,3171,53},{1537,3267,53},{1525,3267,54},{1531,3274,53},{1470,3368,53},{1458,3368,54},{1464,3375,53},{1601,3335,53},{1589,3335,54},{1595,3342,53}},
	tpl_tien = {1904, 1905, 1906, 1907}, tpl_tt = 1908,
	lv_mob = 40, lv_tien = 45, lv_tt = 50, lv_chest = 40,
}
PTVT_D[2] = {
	entry = {1752,3567}, tt = {1516,3312},
	doctors = {{1755,3570},{1510,3311},{1556,3159}},
	chests = {{1519,3311},{1512,3312},{1514,3315},{1516,3307}},
	tien = {{1555,3509},{1520,3383},{1675,3359},{1691,3177}},
	mobs = {{1561,3509,55},{1549,3509,56},{1555,3516,55},{1526,3383,55},{1514,3383,56},{1520,3390,55},{1681,3359,55},{1669,3359,56},{1675,3366,55},{1697,3177,55},{1685,3177,56},{1691,3184,55}},
	tpl_tien = {1909, 1910, 1911, 1912}, tpl_tt = 1913,
	lv_mob = 60, lv_tien = 65, lv_tt = 70, lv_chest = 60,
}
PTVT_D[3] = {
	entry = {1647,3397}, tt = {1713,3187},
	doctors = {{1647,3398},{1705,3184}},
	chests = {{1717,3187},{1709,3187},{1713,3192},{1713,3182}},
	tien = {{1509,3225},{1510,3430},{1653,3219},{1724,3377}},
	mobs = {{1515,3225,57},{1503,3225,58},{1509,3232,57},{1516,3430,57},{1504,3430,58},{1510,3437,57},{1659,3219,57},{1647,3219,58},{1653,3226,57},{1730,3377,57},{1718,3376,58},{1724,3384,57}},
	tpl_tien = {1914, 1915, 1916, 1917}, tpl_tt = 1918,
	lv_mob = 80, lv_tien = 85, lv_tt = 90, lv_chest = 80,
}
PTVT_D[4] = {
	entry = {1671,3035}, tt = {1704,3022},
	doctors = {{1674,3038},{1696,3019},{1517,3421}},
	chests = {{1708,3022},{1700,3022},{1704,3027},{1704,3017}},
	tien = {{1548,3056},{1527,3144},{1731,3154},{1781,3265}},
	mobs = {{1554,3056,59},{1542,3056,60},{1548,3063,59},{1533,3144,59},{1521,3144,60},{1527,3151,59},{1737,3154,59},{1727,3156,60},{1731,3161,59},{1787,3265,59},{1775,3265,60},{1781,3272,59}},
	tpl_tien = {1919, 1920, 1921, 1922}, tpl_tt = 1923,
	lv_mob = 95, lv_tien = 100, lv_tt = 105, lv_chest = 100,
}
-- VNG trap scripts (script.pak) of the Huyen map traps: registered once by the minute tick
PTVT_TRAP_SCRIPTS = {"\\script\\trap\\\205\242\207\201\213\243\205\1931.lua", "\\script\\trap\\\205\242\207\201\213\243\205\1932.lua", "\\script\\trap\\\205\242\207\201\213\243\203\1741.lua", "\\script\\trap\\\205\242\207\201\213\243\203\1742.lua", "\\script\\trap\\\205\242\207\201\213\243\187\2401.lua", "\\script\\trap\\\205\242\207\201\213\243\187\2402.lua", "\\script\\trap\\\205\242\207\201\213\243\183\2311.lua", "\\script\\trap\\\205\242\207\201\213\243\183\2312.lua"}
