;-------------------------------------------
;·Ö×éºÃÓÑ´°¿Ú¶¨Òå

;[GroupFriendWnd]
;Left=56
;Top=58
;Width=150
;Height=232
;Value=350
;WndName=ºÃÓÑ·Ö×é½çÃæ
;Tip=$Giao diÖn nhãm h¶o h÷u

[FriendTree_Branch]
Left=0
Top=0
Width=138
Height=24
Trans=1
UseParentClipRect=1

[FriendTree_Branch_OpenButton]
Left=0
Top=6
Width=17
Height=17
Up=0
Down=1
Image=\spr\Ui4\Ö÷½çÃæ\ÉùÍûÃæ°å\Àà±ğ+-.spr
UseParentClipRect=1

[FriendTree_Branch_NameText]
Left=21
Top=6
Width=76
Height=19
Font=14
HAlign=0
Color=255,255,255
Text=$Ph©n nhãm h¶o h÷u
UseParentClipRect=1

[FriendTree_Branch_NameEdit]
Left=20
Top=6
Width=76
Height=14
Font=14
HAlign=0
Type=2
MaxLen=8
Color=216,252,160
BorderColor=0,0,0
UseParentClipRect=1

[FriendTree_Branch_Number]
Left=80
Top=6
Width=65
Height=19
Font=14
HAlign=0
Color=216,252,160
Text=$Sè h¶o h÷u
UseParentClipRect=1

[FriendTree_Item]
Left=0
Top=2
Width=222
Height=0
Trans=1
UseParentClipRect=1

[FriendTree_Item_NameText]
Left=10
Top=2
Width=85
Height=14
Font=14
HAlign=0
Color=255,255,255
UseParentClipRect=1

[FriendTree_Item_MemberList]
;ºÃÓÑÁĞ±íÏà¶ÔÕû¸öÁÄÌì½çÃæ
Left=-10
Top=0
Width=222
Height=0
ColumnCount=2           ;ÁĞÊı
ColumnWidth_0=200       ;ÁĞ¿í
ColumnWidth_1=25
ColumnFormat_0=1        ;Ã»ÁĞµÄ¸ñÊ½,0-2,¶ÔÆë·½Ê½ 
ColumnFormat_1=1
Font=14
Color=255,255,0
BorderColor=0,0,0
SelColor=255,255,0            ;µãÖĞÊ±µÄÑÕÉ«
SelBorderColor=0,255,0
SelItemBgColor=0,50,0      ;±³¾°ÑÕÉ« 
HighLight=1             ;Êó±êÔÚÉÏÃæÊ±ÊÇ·ñÓĞÑÕÉ«£¬0-1
HighLightColor=0,0,0
HighLightBorderColor=0,255,0
OfflineColor=0,135,133
InitLine=2		;¸Õ´ò¿ªÊ±£¬µÄĞĞÊı
NumLine=35,35		;ºÃÓÑ´°¿Ú£¬¸Ä±ä´óĞ¡Ê±£¬ÔÊĞíµÄĞĞÊıµÄ·¶Î§£¨°üÀ¨×éĞĞºÍºÃÓÑĞĞ£©
UseParentClipRect=1
