[Main]
Left=237
Top=150
Trans=0
Image=\spr\ui4\ÏµÍ³Ñ¡Ïî\ÀëÏßĞŞÁ¶½çÃæ.spr
GroupCount=3
CalculateWay=10

;combobox
[Group_0]
Left=51
Top=58
Width=117
Height=14
SelCount=2
SelText_0=$Kh«ng
SelInfo_0=$Sö dông <c=g>NhËt NguyÖt ®¬n<c> cã thÓ <c=g>an toµn<c> rêi m¹ng vÉn nhËn ®­îc <c=g>®iÓm kinh nghiÖm<c>.
SelText_1=$NhËt NguyÖt ®¬n
SelInfo_1=$ Rêi m¹ng, cø c¸ch <color=green>1 giê<color> sÏ ®­îc t¨ng ®iÓm kinh nghiÖm luyÖn c«ng 1 lÇn, sè ®iÓm b»ng: <color=green>§¼ng cÊp*giê*1200<color=green><color>, mçi ngµy nhËn ®­îc tèi ®a 4 giê tu luyÖn. §iÒu kiÖn nhËn ®­îc kinh nghiÖm lµ <color=green>lÇn ®¨ng nhËp sau NhËt NguyÖt ®¬n<color> vÉn cßn tån t¹i! Xin chó ı ®Ó ®¨ng nhËp tr­íc khi NN§ hÕt h¹n!

[Group_0_Btn]
Left=0
Top=0
Up=0
Down=1
Over=1
OverFrame=2
Image=\spr\ui4\ÏµÍ³Ñ¡Ïî\ÏÂÀ­Ìõ.spr

[Group_0_Edit]
Left=3
Top=0
Width=102
Height=14
Font=14
HAlign=0
;Color=255,217,78
Disable=1
Color=218,255,165
FocusBKColor=150,142,105
FocusBKColorAlpha=120

[Group_1]
Left=214
Top=58
Width=117
Height=14
SelCount=2
SelText_0=$Kh«ng
SelInfo_0=$ Rêi m¹ng sÏ kh«ng ¶nh h­ëng ®Õn viÖc ®µo kho¸ng. B¹n nªn sö dông <color=green>Lam D­¬ng §¬n<color> cã thÓ <color=green>an toµn<color> tiÕn hµnh ®µo kho¸ng, cã thÓ nhËn ®­îc <color=green>m¶nh Lam Thñy tinh hoÆc Lam Thñy tinh<color>.
SelText_1=$Lam D­¬ng §¬n
SelInfo_1=$  Rêi m¹ng, cø c¸ch <color=green>1 giê<color> sÏ luyÖn b¶o th¹ch 1 lÇn, thµnh qu¶ sÏ lµ <color=green>m¶nh Lam Thñy tinh hoÆc Lam Thñy tinh<color>, tèi ®a sÏ luyÖn ®­îc 4 giê. Mçi giê sÏ tiªu hao 1 <color=green>Lam D­¬ng §¬n (hµnh trang ph¶i cßn chç trèng)<color>.


[Group_1_Btn]
Left=0
Top=0
Up=0
Down=1
Over=1
OverFrame=2
Image=\spr\ui4\ÏµÍ³Ñ¡Ïî\ÏÂÀ­Ìõ.spr

[Group_1_Edit]
Left=3
Top=0
Width=102
Height=14
Font=14
HAlign=0
;Color=255,217,78
Disable=1
Color=218,255,165
FocusBKColor=150,142,105
FocusBKColorAlpha=120



[Group_2]
Left=50
Top=78
Width=117
Height=14
SelCount=2
SelText_0=$Kh«ng
SelInfo_0=$Sö dông <c=g>NhËt NguyÖt ®¬n<c> cã thÓ <c=g>an toµn<c> rêi m¹ng vÉn nhËn ®­îc <c=g>®iÓm kinh nghiÖm<c>.
SelText_1=$Th¸i Cùc §¬n
SelInfo_1=$ Sau khi rêi m¹ng, <c=g>cø c¸ch 1 giê<c> <c=g>kinh nghiÖm kü n¨ng chuét ph¶i<c> sÏ t¨ng 1 lÇn, tèi ®a cã thÓ tİch lòy 4 giê. Mçi giê sÏ khÊu trõ <c=g>1 Th¸i Cùc ®¬n (Xin x¸c ®Şnh kü n¨ng chuét ph¶i ch­a ®Õn cÊp 10)<c>!

[Group_2_Btn]
Left=0
Top=0
Up=0
Down=1
Over=1
OverFrame=2
Image=\spr\ui4\ÏµÍ³Ñ¡Ïî\ÏÂÀ­Ìõ.spr

[Group_2_Edit]
Left=3
Top=0
Width=102
Height=14
Font=14
HAlign=0
;Color=255,217,78
Disable=1
Color=218,255,165
FocusBKColor=150,142,105
FocusBKColorAlpha=120






[BtnConfirm]
Left=60
Top=197
Image=\Spr\Ui4\npc¶Ô»°Ìõ\È·¶¨.spr
Up=0
Down=1
Over=1
OverFrame=2


[BtnCancel]
Left=235
Top=197
Image=\Spr\Ui4\npc¶Ô»°Ìõ\È¡Ïû.spr
Up=0
Down=1
Over=1
OverFrame=2

[TxtInfo]
Left=27
Top=104
Width=294
Height=75
Font=14
Color=202,230,171
MultiLine=1

[ChkSaveSetting]
Left=28
Top=178
Image=\spr\ui4\ÏµÍ³Ñ¡Ïî\¼ÇÂ¼±¾´ÎÍË³ö·½Ê½.spr
Up=0
Down=1
CheckBox=1
CheckOver=1
