;树控件Item配置
[Item]
Left=2
Top=5
Width=243
Height=30
Trans=1
UseParentClipRect=1

[Item_Txt]
Left=3
Top=5
Width=71
Height=15
Text=text
Color=235,255,200
UseParentClipRect=1

[Item_Credit]
Left=78
Top=5
Width=162
Height=12
Tip=$Danh v鋘g
Part=1
Up=0
Down=0
UseParentClipRect=1
Image=\spr\Ui4\主界面\声望面板\黄色边框.spr
ImagePart1=\spr\Ui4\主界面\声望面板\红血条.spr
ImagePart2=\spr\Ui4\主界面\声望面板\绿血条.spr
ImageStar=\spr\Ui4\主界面\声望面板\+.spr

;声望条图片
[Item_Credit_Image]
Left=0
Top=0
Width=162
Height=10
Trans=0
Image=\spr\Ui4\主界面\声望面板\红血条.spr
PartType=0
UseParentClipRect=1

;声望条文字
[Item_Credit_Text]
Left=43
Top=-1
Width=63
Height=14
Font=14
HAlign=1
Color=255,255,255
UseParentClipRect=1

;-------------------------------------------
[ItemBranch]
Left=0
Top=0
Width=293
Height=30
Trans=1
UseParentClipRect=1

[ItemBranch_Img]
Left=2
Top=6
Width=17
Height=17
Up=0
Down=1
Image=\spr\Ui4\主界面\声望面板\类别+-.spr
UseParentClipRect=1

[ItemBranch_ImgBtn]
Left=20
Top=5
Width=253
Height=19
Tip=$Danh v鋘g
Part=1
;Image=\spr\Ui4\主界面\声望面板\类别.spr
UseParentClipRect=1
Up=0
Down=0

;声望条图片
[ItemBranch_ImgBtn_Image]
Left=0
Top=3
Width=156
Height=8
Trans=0
Image=\spr\Ui4\主界面\声望面板\类别.spr
PartType=0
UseParentClipRect=1


[ItemBranch_ImgBtn_Text]
Left=0
Top=2
Width=63
Height=14
Font=14
HAlign=0
Color=255,255,255
UseParentClipRect=1
