[MiniMap]
Left=442
Top=0
Width=350
Height=300
Image=
Moveable=1

[NameShadow]
Left=198
Top=0
Image=\spr\ui4\小地图\顶部.spr
Moveable=1
;右上

[SceneName]
Left=198
Top=3
Width=129
Height=14
Font=14
HAlign=1
TextShadow=1
Color=0,255,0
OverColor=0,255,255
SelColor=0,255,255
DummyWnd=1
;地图坐标

[TongMapInfo1]
Left=0
Top=0
Width=0
Height=0

[TongMapInfo2]
Left=0
Top=0
Width=0
Height=0

[ScenePos]
Left=200
Top=19
Width=130
Height=14
Font=14
HAlign=1
Color=0,255,0
DummyWnd=1

;画地图的范围

[MapRect]
Left=1
Top=20
Width=350
Height=281

;最小化按钮

[SwitchBtn]
Left=334
Top=284
Width=12
Height=12
Up=0
Down=0
;Over=2
;OverFrame=2
Trans=0
Image=\Spr\UI4\小地图\缩放.spr
Tip=$Thu nh?

;切换世界地图的按钮

[WorldMapBtn]
Left=317
Top=286
Width=14
Height=10
Up=0
Down=1
Over=1
OverFrame=1
Trans=0
Image=\Spr\UI4\小地图\世界地图键.spr
Tip=$Th?gi韎

[BtnFlag]
Left=303
Top=284
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\小地图\小旗子按钮.spr
Tip=$H錸g k?
FlagImage=\Spr\Ui4\小地图\小旗子.spr

[CaveMapBtn]
Left=0
Top=0
Width=0
Height=0
Image=
