[MiniMap]
Left=640
Top=0
Width=161
Height=142
Image=
Moveable=1
;上

[NameShadow]
Left=0
Top=0
Image=\spr\UI4\小地图\顶部.spr
Moveable=1

[SceneName]
Left=0
Top=3
Width=129
Height=14
Font=14
HAlign=1
TextShadow=1
Color=0,255,0
OverColor=0,255,255
SelColor=0,255,255
DummyWnd=1

;地图坐标

[TongMapInfo1]
Left=0
Top=0
Width=0
Height=0

[TongMapInfo2]
Left=0
Top=0
Width=0
Height=0

[ScenePos]
Left=2
Top=19
Width=130
Height=14
Font=14
HAlign=1
Color=0,255,0
DummyWnd=1

;画地图的范围

[MapRect]
Left=3
Top=17
Width=150
Height=124

;最小化按钮

[SwitchBtn]
Left=136
Top=127
;Width=12
;Height=12
Up=1
Down=1
;Over=2
;OverFrame=2
Trans=0
Image=\Spr\UI4\小地图\缩放.spr
Tip=$Ph鉵g

;切换世界地图的按钮

[WorldMapBtn]
Left=120
Top=129
;Width=14
;Height=10
Up=0
Down=1
Over=1
OverFrame=1
Trans=0
Image=\Spr\UI4\小地图\世界地图键.spr
Tip=$Th?gi韎

[BtnFlag]
Left=105
Top=127
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\小地图\小旗子按钮.spr
Tip=$H錸g k?
FlagImage=\Spr\Ui4\小地图\小旗子.spr

[CaveMapBtn]
Left=0
Top=0
Width=0
Height=0
Image=
