[Main]
Left=0
Top=0
Width=800
Height=600
Moveable=0
Trans=1
DummyWnd=1
Image=

[ToolsMiniBar]
Left=261
Top=557
Moveable=0
Trans=0
Image=\spr\Ui4\主界面\快捷物品&技能\快捷物品&技能.spr

[InputBack]
Left=0
Top=581
Width=255
Height=19
Trans=0
Image=\Spr\Ui4\主界面\聊天\聊天框.spr

[Item_0]
Left=264
Top=560
Width=32
Height=32
HaveBgColor=0

;物品1

[Item_1]
Left=299
Top=560
Width=32
Height=32

HaveBgColor=0

;物品2

[Item_2]
Left=334
Top=560
Width=32
Height=32
HaveBgColor=0

;物品3

[Item_3]
Left=369
Top=560
Width=32
Height=32
HaveBgColor=0

[Item_4]
Left=0
Top=0
Width=0
Height=0

[Item_5]
Left=0
Top=0
Width=0
Height=0

[Item_6]
Left=0
Top=0
Width=0
Height=0

[Item_7]
Left=0
Top=0
Width=0
Height=0

[Item_8]
Left=0
Top=0
Width=0
Height=0

[ImediaLeftSkill]
Left=407
Top=561
Width=32
Height=32
EnableClickEmpty=1
HaveBgColor=0
Image=\spr\Ui4\主界面\快捷物品&技能\左.spr
ImageLeft=0
ImageTop=22

[ImediaRightSkill]
Left=442
Top=561
Width=32
Height=32
EnableClickEmpty=1
HaveBgColor=0
Image=\spr\Ui4\主界面\快捷物品&技能\右.spr
ImageLeft=0
ImageTop=22

;物品0

[InputEdit]
Left=50
Top=583
Width=187
Height=13
FollowSize=1
FollowMove=0,1
Font=14
Type=2
MultiLine=0
MaxLen=80
Color=254,255,160
FocusBKColor=25,31,11
FocusBKColorAlpha=240
FocusNoCanBKColor=97,2,0
FocusNoCanBKColorAlpha=180

;表情选择按键

[Face]
Left=237
Top=582
Width=18
Height=18
Trans=0
Up=0
Down=1
Over=1
OverFrame=2
Image=\spr\UI4\主界面\聊天\表情.spr

[ChannelBtn]
Left=19
Top=583
Width=30
Height=15
Font=14
Color=0,255,0
HAlign=1
VAlign=1

[Options]
Left=0
Top=0
Width=0
Height=0
Image=

[Friend]
Left=0
Top=0
Width=0
Height=0
Image=

[Market]
Left=0
Top=0
Width=0
Height=0
Image=

[DateTime]
Left=0
Top=0
Width=0
Height=0
Image=

[Icoin]
Left=0
Top=0
Width=0
Height=0
Image=

[AutoPlay]
Left=0
Top=0
Width=0
Height=0
Image=

[Support]
Left=0
Top=0
Width=0
Height=0
Image=

[UnlockBtn]
Left=0
Top=0
Width=0
Height=0
Image=

[SendBtn]
Left=0
Top=0
Width=0
Height=0
Image=

[OpenChannelBtn]
Left=0
Top=0
Width=0
Height=0
Image=

[SwitchSizeBtn]
Left=0
Top=0
Width=0
Height=0
Image=
