[Main]
Left=40
Top=100
Image=\spr\UI4\登陆界面\服务器选择\选择服务器.spr
Moveable=0
StartPos=800,0
LoginBg=Login
CalculateWay=10

[List]
Left=498
Top=239
Width=200
Height=135
Font=14
Color=235,255,200
SelColor=169,252,4
HAlign=0
CustomItem=1
CustomItemWidth=167
EnableCustomItemHeight=1
CustomItemHeight=22
CustomItemTextLeft=15
CustomItemTextTop=3
;CustomItemImage=\spr\Ui4\登陆界面\服务器选择\serverlist.spr
NormalItemFrame=0
SelItemFrame=1
CalculateWay=7

[Scroll]
Left=0
Top=0
Width=0
Height=0
Type=1
Min=0
Max=9
PageSize=1
SlideBegin=5
SlideEnd=151

[Scroll_Btn]
Left=0
Top=0
Width=0
Height=0
Up=0
Down=0
Over=0
OverFrame=0
Image=
Trans=0

[Login]
Left=95
Top=387
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\登陆界面\服务器选择\进入游戏.spr
CalculateWay=9

[Cancel]
Left=500
Top=387
Up=0
Down=1
Over=1
OverFrame=2
Trans=0
Image=\Spr\Ui4\登陆界面\服务器选择\退出游戏.spr
CalculateWay=9
