;系统消息

[Main]
Left=600
Top=450
Width=196
Height=50
;系统消息发到屏幕聊天窗口的文字颜色
NormalMsgColor=255,0,0

;消息文字
[MsgText]
Left=0
Top=25
Width=196
Height=15
Color=0,255,0
Font=14

;系统，连接相关
[MsgIcon_1]
Left=172
Top=0
;Width=28
;Height=28
Image=\Spr\Ui4\系统消息图标\系统.spr
Frame=0

;玩家相关
[MsgIcon_2]
Left=172
Top=0
;Width=28
;Height=28
Image=\Spr\Ui4\系统消息图标\系统.spr
Frame=0

;组队相关
[MsgIcon_3]
Left=172
Top=0
;Width=28
;Height=28
Image=\Spr\Ui4\系统消息图标\系统.spr
Frame=0

;聊天好友相关
[MsgIcon_4]
Left=172
Top=0
;Width=28
;Height=28
Image=\Spr\Ui4\系统消息图标\系统.spr
Frame=0

;任务相关
[MsgIcon_5]
Left=172
Top=0
;Width=28
;Height=28
Image=\Spr\Ui4\系统消息图标\系统.spr
Frame=0

;帮派相关
[MsgIcon_6]
Left=172
Top=0
;Width=28
;Height=28
Image=\Spr\Ui4\系统消息图标\系统.spr
Frame=0

;交易相关
[MsgIcon_7]
Left=172
Top=0
;Width=28
;Height=28
Image=\Spr\Ui4\系统消息图标\系统.spr
Frame=0
