; Phong Than local 2026-09-28: popup for KUiMissionNote (AddMissionNote).
[Main]
Left=300
Top=160
Width=300
Height=180
Moveable=1

[Name]
Left=16
Top=12
Width=268
Height=18
Font=14
Color=255,253,122

[DestText]
Left=16
Top=38
Width=268
Height=110
Font=14
MaxMsgCount=16
MsgColor=218,255,165
MsgBorderColor=23,68,0

[CloseBtn]
Left=230
Top=152
Width=50
Height=18
Font=14
Color=255,255,255
OverColor=255,253,122
Text=Dong