-- sudocpp_lib.lua (2026-10-03, agent sudocpp). Lua 4.0, ASCII (TCVN3 as byte escapes). Generated by scratchpad\sudocpp\gen_lua.py.
-- Doc: docs\features\hoang-phi-ho-su-do-phong-than-20261003.md
-- The VNG master-apprentice API (GetMasterPRValue, CanMasterPR, DoMasterPR, UnMasterPREx, AddWeightMax, ...) is
-- added to the GameServer by the C++ patch S\sudocpp\apply_patch.py (PhongThanLuaMasterPR.h). Until that build is
-- deployed every entry below behaves exactly like before (gated by PTSC_Ready). pt_compat.lua stubs several VNG
-- names with 0/no-op functions, so readiness is probed with the new name MasterPRVersion only.
-- Solo ("virtual master", same rule as sudo_dongdi): a player outside any team counts as a valid pair; Hoang Phi Ho
-- himself acts as the master, so the master share of the graduation reward goes to the player.

PTSC_T_GRAD = 2410              -- task: 1 = solo Dao ly graduation done, 2 = solo simple graduation done (2410-2429 = sudocpp)
PTSC_SOLO_DAOLY_POINTS = 15     -- master share of the VNG Dao ly graduation (shengxian_end_M)
PTSC_SOLO_SIMPLE_POINTS = 5     -- VNG simple graduation (PM_wuming_end) gives 5 to each member
PTSC_WEIGHT_EXCHANGE = 1        -- Na Tra "Doi suc luc": 1 = open once the C++ is deployed, nil = keep closed

-- 1 when the C++ master-apprentice API is registered in this GameServer
function PTSC_Ready()
	if MasterPRVersion ~= nil then
		if MasterPRVersion() >= 1 then return 1 end
	end
	return 0
end

function PTSC_IsSolo()
	local n = GetTeamSize()
	if n == nil or n <= 1 then return 1 end
	return 0
end

-- team of exactly 2 with the master-apprentice relation (VNG path)
function PTSC_IsPair()
	if GetTeamSize() ~= 2 then return 0 end
	local n = 0
	if IsCaptain() == 0 then n = GetTeamMember(1) else n = GetTeamMember(2) end
	if n and n > 0 and IsMasterPRRelation(n) == 1 then return 1 end
	return 0
end

function PTSC_JudgeRelation()
	if PTSC_IsPair() == 1 then return 1 end
	return PTSC_IsSolo()
end
