-- Phong Than 2026-10-03 (agent vienco). Generated by scratchpad\vienco\mk_vienco.py; edit the generator, not this file.
-- Giang Son Y Cuu (VNG taskinfo 1053-1058, 1081; the 201 \script\instance\ scripts and OpenNpcCollectionDlg are
-- missing): one quest chain at Du Khanh (Trieu Ca). Every step spawns personal targets on the step map (NpcParam
-- 1 = PTGS_K, 2 = k*10+stage, 3 = owner id), kills are counted by gs_mob.lua (LastDamage), boss chains spawn the next
-- stage where the last one died. Targets disappear after 30 minutes (SetNpcTimeout -> Timeout -> DelNpc).
Include("\\script\\phongthan\\vienco\\gs_data.lua")
PTGS_K = 7742
PTGS_T_STEP = 2355            -- current step k (0 = chain not started)
PTGS_T_STATE = 2356           -- 0 not accepted, 1 in progress, 2 report to Du Khanh
PTGS_T_STAGE = 2357           -- current stage of the step
PTGS_T_CNT = 2358             -- kills in the current stage
PTGS_T_SPAWN = 2359           -- minute stamp of the last spawn (re-summon after 10 minutes)
PTGS_T_DONE = 2360            -- 1 = whole chain finished
PTGS_LIFE = 18 * 60 * 30

function PTGS_Owner()
	local id = GetPlayerID()
	if id == nil then return 0 end
	return mod(id, 1000000)
end

function PTGS_Stamp()
	return (tonumber(date("%j")) or 0) * 1440 + (tonumber(date("%H")) or 0) * 60 + (tonumber(date("%M")) or 0)
end

function PTGS_Note(k, back)
	local s = PTGS_S[k]
	if back == 1 then
		AddNote(mod(s[1], 36), 1, "Giang S\172n Y C\249u - " .. s[8] .. ": \174\183 xong, v\210 Tri\210u Ca g\198p D\173 Kh\184nh ph\244c m\214nh.", 0)
	else
		AddNote(mod(s[1], 36), 1, "Giang S\172n Y C\249u - " .. s[8] .. ": " .. PTGS_GO[k], 0)
	end
end

-- spawn the targets of stage st of step k; x, y = 0 -> the step cells
function PTGS_Spawn(k, st, x, y)
	local g = PTGS_G[k * 10 + st]
	if g == nil then return 0 end
	local s = PTGS_S[k]
	local sw = SubWorldID2Idx(s[5])
	if sw == nil or sw < 0 then return 0 end
	local p = PTGS_P[k]
	local n = 0
	local i = 1
	local own = PTGS_Owner()
	while i <= g[3] do
		local cx = p[1]
		local cy = p[2]
		if x > 0 then
			cx = x + mod(i, 3) - 1
			cy = y + floor(i / 3)
		elseif p[2 * i] then
			cx = p[2 * i - 1]
			cy = p[2 * i]
		end
		local ni = AddNpc(g[1], g[2], sw, cx * 32, cy * 32, 1)
		if ni and ni > 0 then
			SetNpcName(ni, g[4])
			SetNpcScript(ni, "\\script\\phongthan\\vienco\\gs_mob.lua")
			SetNpcParam(ni, 1, PTGS_K)
			SetNpcParam(ni, 2, k * 10 + st)
			SetNpcParam(ni, 3, own)
			SetNpcTimeout(ni, PTGS_LIFE)
			n = n + 1
		end
		i = i + 1
	end
	SetTask(PTGS_T_SPAWN, PTGS_Stamp())
	return n
end

function PTGS_Start(k)
	SetTask(PTGS_T_STATE, 1)
	SetTask(PTGS_T_STAGE, 1)
	SetTask(PTGS_T_CNT, 0)
	local n = PTGS_Spawn(k, 1, 0, 0)
	PTGS_Note(k, 0)
	Msg2Player(PTGS_GO[k])
	return n
end

-- a Giang Son target died; PlayerIndex = killer
function PTGS_OnKill(npc)
	local code = GetNpcParam(npc, 2)
	local k = floor(code / 10)
	local st = mod(code, 10)
	if GetTask(PTGS_T_STEP) ~= k or GetTask(PTGS_T_STATE) ~= 1 or GetTask(PTGS_T_STAGE) ~= st then return 0 end
	local g = PTGS_G[code]
	local c = GetTask(PTGS_T_CNT) + 1
	if c < g[3] then
		SetTask(PTGS_T_CNT, c)
		Msg2Player(format("Giang S\172n Y C\249u: \174\183 thu ph\244c %d/%d.", c, g[3]))
		return 1
	end
	if PTGS_G[code + 1] then
		local w, x, y = GetNpcPos(npc)
		SetTask(PTGS_T_STAGE, st + 1)
		SetTask(PTGS_T_CNT, 0)
		PTGS_Spawn(k, st + 1, x, y)
		TopMessage(PTGS_G[code + 1][4] .. " \174\183 xu\202t hi\214n!")
		return 2
	end
	SetTask(PTGS_T_STATE, 2)
	SetTask(PTGS_T_CNT, c)
	PTGS_Note(k, 1)
	TopMessage("Giang S\172n Y C\249u: ho\181n th\181nh, v\210 Tri\210u Ca g\198p D\173 Kh\184nh!")
	return 3
end

function PTGS_Reward(k)
	local s = PTGS_S[k]
	local exp = s[4] * s[4] * 40
	if PTGS_G[k * 10 + 2] then exp = exp * 2 end
	AddOwnExp(exp)
	Earn(s[4] * 300)
	Msg2Player(format("Nh\203n \174\173\238c %d kinh nghi\214m v\181 %d l\173\238ng.", exp, s[4] * 300))
	local it = PTGS_I[k]
	if it then
		local i = 1
		while it[i] do
			AddNormalItem(it[i], it[i + 1], it[i + 2], 0, 0, 0)
			i = i + 3
		end
		Msg2Player("D\173 Kh\184nh t\198ng th\170m v\203t ph\200m qu\253.")
	end
	return exp
end

function PTGS_No()
end
