-- Phong Than 2026-10-03 (agent vienco). Generated by scratchpad\vienco\mk_vienco.py; edit the generator, not this file.
-- Vien Co Chien Su (Phong Than Dai 1001): registration for the Thuong-Chu battlefield (VNG <b7e2><c9f1><cca8>\<c9f1><b1ae>2.lua),
-- reward of Vi Quoc Lap Cong (VNG <cee4><cdf5>.lua / <e6fb><cdf5>.lua renwu2), battlefield rank.
Include("\\script\\phongthan\\vienco\\vc_lib.lua")

function main()
	PTVC_Lazy()
	local t = "<color=green>Vi\212n C\230 Chi\213n S\248<color>: Th\173\172ng Chu tranh b\184, b\184 t\184nh l\199m than. " .. PTVC_StatusText()
	if PTVC_RewardReady() then
		Say(t, 5, "Nh\203n th\173\235ng 'V\222 Qu\232c L\203p C\171ng'/vc_reward", "V\181o chi\213n tr\173\234ng Th\173\172ng Chu/vc_enter", "\167\188ng c\202p chi\213n tr\173\234ng/vc_rank", "Gi\237i thi\214u chi\213n tr\173\234ng/vc_intro", "K\213t th\243c \174\232i tho\185i/no")
	else
		Say(t, 4, "V\181o chi\213n tr\173\234ng Th\173\172ng Chu/vc_enter", "\167\188ng c\202p chi\213n tr\173\234ng/vc_rank", "Gi\237i thi\214u chi\213n tr\173\234ng/vc_intro", "K\213t th\243c \174\232i tho\185i/no")
	end
end

function vc_intro()
	Talk(3, "",
		"<color=green>Vi\212n C\230 Chi\213n S\248<color>: Chi\213n tr\173\234ng Th\173\172ng Chu (Vi\212n C\230 chi\213n tr\173\234ng) m\235 m\231i gi\234, k\208o d\181i 45 ph\243t. C\202p 50 tr\235 l\170n, ph\221 v\181o 5 v\185n l\173\238ng (\174\188ng c\202p chi\213n tr\173\234ng 10 \174\173\238c mi\212n).",
		"Ch\228n <color=yellow>phe Th\173\172ng<color> ho\198c <color=yellow>phe Chu<color>. Qu\169n phe m\215nh l\181 \174\229ng minh, qu\169n phe kia l\181 k\206 \174\222ch: h\185 qu\169n \174\222ch, th\184m qu\169n, ph\184 v\203t t\230 v\181 \174o\185t so\184i k\250 mang v\210 cho ch\241 t\173\237ng \174\211 ghi \174i\211m cho phe.",
		"V\181o tr\203n, g\198p ch\241 t\173\237ng (V\168n Tr\228ng ho\198c Kh\173\172ng Th\173\238ng) nh\203n 'V\222 Qu\232c L\203p C\171ng' (m\231i ng\181y 1 l\199n). H\213t gi\234, phe nhi\210u \174i\211m h\172n th\190ng; ho\181n th\181nh nhi\214m v\244 th\215 v\210 \174\169y nh\203n kinh nghi\214m (phe th\190ng \174\173\238c nhi\210u h\172n), m\231i 2 l\199n nh\203n th\173\235ng t\168ng 1 \174\188ng c\202p chi\213n tr\173\234ng, l\170n \174\188ng c\202p 4 v\181 10 \174\173\238c ch\228n 1 m\227n trang b\222 b\233.")
end

function vc_rank()
	Talk(1, "", format("<color=green>Vi\212n C\230 Chi\213n S\248<color>: \167\188ng c\202p chi\213n tr\173\234ng c\241a ng\173\172i l\181 <color=yellow>%d<color>, t\230ng c\171ng tr\185ng <color=yellow>%d<color>. Nhi\214m v\244: ", GetTask(PTVC_T_RANK), GetTask(PTVC_T_TOTAL)) .. PTVC_MissionText(GetTask(PTVC_T_MISSION)))
end

function vc_reward()
	if not PTVC_RewardReady() then return end
	local r = PTVC_RankItemDue()
	if r then
		-- VNG reward_add: choose one set piece first (rank 3: 5 pieces, rank 9: Ngoa / Yeu Dai / Khoi)
		local a = 1
		local b = 5
		if r == 9 then
			a = 2
			b = 4
		end
		local t = { "<color=green>Vi\212n C\230 Chi\213n S\248<color>: Ng\173\172i th\203t v\202t v\182! L\199n n\181y \174\173\238c ch\228n 1 m\227n trang b\222:", b - a + 2 }
		local k = a
		while k <= b do
			t[k - a + 3] = PTVC_PieceName(r, k) .. "/vc_item" .. k
			k = k + 1
		end
		t[b - a + 4] = "\167\211 sau/no"
		call(Say, t)
		return
	end
	local e = PTVC_Reward()
	if e then
		Talk(1, "", "<color=green>Vi\212n C\230 Chi\213n S\248<color>: L\199n n\181y ng\173\172i l\203p nhi\210u c\171ng tr\185ng, h\183y nh\203n l\202y ph\199n th\173\235ng.")
	end
end

function vc_item(k)
	if not PTVC_RankItem(k) then
		Talk(1, "", "<color=green>Vi\212n C\230 Chi\213n S\248<color>: H\181nh trang c\241a ng\173\172i \174\183 \174\199y, h\183y d\228n b\237t r\229i quay l\185i nh\203n th\173\235ng.")
		return
	end
	Talk(1, "", "<color=green>Vi\212n C\230 Chi\213n S\248<color>: L\199n n\181y ng\173\172i l\203p nhi\210u c\171ng tr\185ng, h\183y nh\203n l\202y ph\199n th\173\235ng.")
end

function vc_item1() vc_item(1) end
function vc_item2() vc_item(2) end
function vc_item3() vc_item(3) end
function vc_item4() vc_item(4) end
function vc_item5() vc_item(5) end

function vc_enter()
	if not PTVC_Open() then
		Talk(1, "", "<color=green>Vi\212n C\230 Chi\213n S\248<color>: Chi\213n tr\173\234ng ch\173a m\235. M\231i gi\234 t\245 ph\243t 00 \174\213n ph\243t 45 c\227 m\233t tr\203n.")
		return
	end
	if GetLevel() < PTVC_MINLV then
		Talk(1, "", "<color=green>Vi\212n C\230 Chi\213n S\248<color>: Chi\213n tr\173\234ng hung hi\211m, \174\185t c\202p 50 r\229i h\183y \174\213n.")
		return
	end
	if GetPK() >= 88 then
		Talk(1, "", "<color=green>Vi\212n C\230 Chi\213n S\248<color>: K\206 s\184t kh\221 n\198ng n\210 kh\171ng \174\173\238c v\181o chi\213n tr\173\234ng.")
		return
	end
	if PTVC_MinLeft() < 5 then
		Talk(1, "", "<color=green>Vi\212n C\230 Chi\213n S\248<color>: Tr\203n n\181y s\190p k\213t th\243c, h\183y \174\238i tr\203n sau.")
		return
	end
	local s = GetTask(PTVC_T_SIDE)
	if s > 0 and GetTask(PTVC_T_ROUND) == PTVC_Round() then
		vc_go(s)
		return
	end
	Say("<color=green>Vi\212n C\230 Chi\213n S\248<color>: Ng\173\172i mu\232n gia nh\203p phe n\181o?", 3, "Qu\169n Th\173\172ng (V\168n Tr\228ng)/vc_shang", "Qu\169n Chu (Kh\173\172ng Th\173\238ng)/vc_zhou", "\167\211 ta suy ngh\220/no")
end

function vc_shang()
	vc_pay(1)
end

function vc_zhou()
	vc_pay(2)
end

function vc_pay(side)
	if not PTVC_Open() then return end
	if GetTask(PTVC_T_RANK) < 10 then
		if GetCash() < PTVC_FEE then
			Talk(1, "", "<color=green>Vi\212n C\230 Chi\213n S\248<color>: V\181o chi\213n tr\173\234ng ph\182i n\233p 5 v\185n l\173\238ng.")
			return
		end
		Pay(PTVC_FEE)
	end
	vc_go(side)
end

function vc_go(side)
	if not PTVC_Enter(side) then
		Talk(1, "", "<color=green>Vi\212n C\230 Chi\213n S\248<color>: Chi\213n tr\173\234ng \174\183 \174\241 ng\173\234i, h\183y \174\238i tr\203n sau.")
	end
end

function no()
end
