-- Phong Than 2026-10-03 (agent vienco). Generated by scratchpad\vienco\mk_vienco.py; edit the generator, not this file.
-- Generals of the battlefield camps: Van Trong (Thuong base, side 1) and Khuong Thuong (Chu base, side 2)
-- (VNG <d0c2><b9c5><d5bd><b3a1>\<cec5><d6d9>.lua / <bdaa><c9d0>.lua): Vi Quoc Lap Cong, flag delivery, battle status, sortie, leave.
-- PTVC_GEN_SIDE is set by the wrapper (vc_vantrong.lua / vc_khuongthuong.lua) before this file is included.
Include("\\script\\phongthan\\vienco\\vc_lib.lua")

function main()
	local g = PTVC_GEN_SIDE
	local head = "<color=green>" .. PTVC_GENNAME[g] .. "<color>: "
	if not PTVC_InRound() then
		Say(head .. "Chi\213n s\249 ch\173a b\190t \174\199u ho\198c ng\173\172i ch\173a b\184o danh. H\183y \174\213n Phong Th\199n \167\181i g\198p Vi\212n C\230 Chi\213n S\248.", 2, "V\210 Phong Th\199n \167\181i/vc_leave", "K\213t th\243c \174\232i tho\185i/no")
		return
	end
	if GetTask(PTVC_T_SIDE) ~= g then
		Talk(1, "", head .. "Ng\173\172i kh\171ng ph\182i ng\173\234i c\241a " .. PTVC_SIDENAME[g] .. ", mau r\234i kh\225i \174\169y!")
		return
	end
	if PTVC_DeliverFlag() then
		Talk(1, "", head .. "Ng\173\172i \174o\185t \174\173\238c so\184i k\250 \174\222ch, th\203t kh\171ng h\230 danh anh h\239ng! C\171ng tr\185ng +10, phe ta +5 \174i\211m.")
		return
	end
	Say(head .. PTVC_StatusText(), 6, "V\222 Qu\232c L\203p C\171ng/vc_mission", "Chi\213n tr\185ng/vc_status", "C\171ng tr\185ng/vc_score", "Xu\202t tr\203n/vc_sortie", "V\210 th\181nh d\173\236ng s\248c/vc_leave_ask", "K\213t th\243c \174\232i tho\185i/no")
end

function vc_mission()
	local g = PTVC_GEN_SIDE
	local head = "<color=green>" .. PTVC_GENNAME[g] .. "<color>: "
	local m = GetTask(PTVC_T_MISSION)
	if m == 0 then
		if not PTVC_CanAccept() then
			Talk(1, "", head .. "H\171m nay ng\173\172i \174\183 l\203p c\171ng \174\241 r\229i, ng\181y mai h\183y \174\213n.")
			return
		end
		Say(head .. "\167\185i tr\173\238ng phu v\222 qu\232c qu\170n th\169n! Ta c\227 l\214nh ti\212n trong tay, ng\173\172i d\184m nh\203n kh\171ng?", 2, "Nh\203n l\214nh/vc_accept", "\167\211 ta suy ngh\220/no")
		return
	end
	Talk(1, "", head .. PTVC_MissionText(m))
end

function vc_accept()
	if not PTVC_InRound() or not PTVC_CanAccept() then return end
	local m = PTVC_Accept()
	Talk(1, "", "<color=green>" .. PTVC_GENNAME[PTVC_GEN_SIDE] .. "<color>: " .. PTVC_MissionText(m) .. " Ta s\207 b\200m b\184o v\237i " .. PTVC_KINGNAME[PTVC_GEN_SIDE] .. " ban th\173\235ng.")
	Msg2Player("Kh\171ng \174\173\238c r\234i chi\213n tr\173\234ng tr\173\237c khi k\213t th\243c, n\213u kh\171ng nhi\214m v\244 c\227 th\211 th\202t b\185i.")
end

function vc_status()
	Talk(1, "", "<color=green>" .. PTVC_GENNAME[PTVC_GEN_SIDE] .. "<color>: " .. PTVC_StatusText())
end

function vc_score()
	Talk(1, "", format("<color=green>" .. PTVC_GENNAME[PTVC_GEN_SIDE] .. "<color>: C\171ng tr\185ng tr\203n n\181y c\241a ng\173\172i l\181 <color=red>%d<color>. Ch\216 c\199n d\242ng c\182m, s\207 c\227 ph\199n th\173\235ng x\248ng \174\184ng.", GetTask(PTVC_T_SCORE)))
end

function vc_sortie()
	if not PTVC_InRound() then return end
	local s = GetTask(PTVC_T_SIDE)
	SetPos(PTVC_FRONT_X[s] + random(-3, 3), PTVC_FRONT_Y[s] + random(-3, 3))
	PTVC_SetCamp(s)
	SetFightState(1)
	Msg2Player("Ng\173\172i \174\183 ra tr\203n \174\222a c\241a " .. PTVC_SIDENAME[s] .. ".")
end

function vc_leave_ask()
	Say("<color=green>" .. PTVC_GENNAME[PTVC_GEN_SIDE] .. "<color>: R\234i chi\213n tr\173\234ng b\169y gi\234? C\171ng tr\185ng v\201n \174\173\238c ghi, nh\173ng kh\171ng \235 l\185i t\237i khi chi\213n s\249 k\213t th\243c th\215 nhi\214m v\244 'V\222 Qu\232c L\203p C\171ng' ch\173a xong s\207 b\222 h\241y.", 2, "R\234i chi\213n tr\173\234ng/vc_leave", "\235 l\185i/no")
end

function vc_leave()
	if GetTask(PTVC_T_SIDE) > 0 then
		local m = GetTask(PTVC_T_MISSION)
		if m >= 1000 then SetTask(PTVC_T_MISSION, 0) end
		SetTask(PTVC_T_TOTAL, GetTask(PTVC_T_TOTAL) + GetTask(PTVC_T_SCORE))
		SetTask(PTVC_T_SCORE, 0)
		SetTask(PTVC_T_SIDE, 0)
	end
	PTVC_Restore(1)
end

function no()
end
