-- Phong Than 2026-10-03 (agent vienco). Generated by scratchpad\vienco\mk_vienco.py; edit the generator, not this file.
-- Region placeholders of map 1071 (Nguyen Soai, Tuong Linh, Tiep Dan; npc_restore\1071_00..04 left on disk) are
-- re-bound to this script by ext\vienco.lua: battle status, help, way back.
Include("\\script\\phongthan\\vienco\\vc_lib.lua")

function main()
	Say("<color=green>Qu\169n s\220<color>: " .. PTVC_StatusText() .. " Ch\241 t\173\237ng phe Th\173\172ng l\181 V\168n Tr\228ng (doanh tr\185i ph\221a t\169y), phe Chu l\181 Kh\173\172ng Th\173\238ng (doanh tr\185i ph\221a \174\171ng).", 3, "V\210 doanh tr\185i phe m\215nh/vc_base", "V\210 Phong Th\199n \167\181i/vc_home", "K\213t th\243c \174\232i tho\185i/no")
end

function vc_base()
	if not PTVC_InRound() then
		Talk(1, "", "<color=green>Qu\169n s\220<color>: Ng\173\172i ch\173a b\184o danh tr\203n n\181y.")
		return
	end
	local s = GetTask(PTVC_T_SIDE)
	SetPos(PTVC_BASE_X[s], PTVC_BASE_Y[s])
	SetFightState(0)
end

function vc_home()
	if GetTask(PTVC_T_SIDE) > 0 then
		local m = GetTask(PTVC_T_MISSION)
		if m >= 1000 then SetTask(PTVC_T_MISSION, 0) end
		SetTask(PTVC_T_TOTAL, GetTask(PTVC_T_TOTAL) + GetTask(PTVC_T_SCORE))
		SetTask(PTVC_T_SCORE, 0)
		SetTask(PTVC_T_SIDE, 0)
	end
	PTVC_Restore(1)
end

function no()
end
