-- Phong Than 2026-10-03 (agent vienco). Generated by scratchpad\vienco\mk_vienco.py; edit the generator, not this file.
-- Vien Co chien truong (VNG \script\<d0c2><b9c5><d5bd><b3a1>\<d4b6><b9c5><d5bd><b3a1>*.lua = Mission 5 "chien truong Thuong Chu", map 71 = runtime
-- 1071): VNG is PvP Thuong vs Chu. Here a solo-playable PvE version: both armies are NPCs (camp 1 Thuong, camp 2 Chu);
-- the player joins one side (current camp 1/2), the other army is hostile. Shared by the ext tick (servertimer state),
-- the NPC scripts and the army action script. Session state lives in GlobalValue 2340..2369 (shared by all states).
PTVC_MAP = 1071
PTVC_HOME_M = 1001
PTVC_HOME_X = 1510
PTVC_HOME_Y = 3289
PTVC_MINLV = 50
PTVC_FEE = 50000
PTVC_DAILY_MAX = 1            -- (vtcc 2026-10-04) VNG: one Vi Quoc Lap Cong result per day (task PTVC_T_DAY)
PTVC_K = 7740                 -- NpcParam 1 marker of our army NPCs
-- player task variables (range 2340..2369 of agent vienco; 2355.. belong to Giang Son)
PTVC_T_ROUND = 2340           -- round key the player joined
PTVC_T_SIDE = 2341            -- 1 Thuong, 2 Chu (0 = not in a round)
PTVC_T_SCORE = 2342           -- cong trang of the round
PTVC_T_TOTAL = 2343           -- cong trang total
PTVC_T_MISSION = 2344         -- Vi Quoc Lap Cong: 1000+n kill, 2000+n flags, 3000+n totems, 4000+n scouts, 5001 win, 1 done, 2 reward
PTVC_T_RANK = 2345            -- dang cap chien truong 0..10
PTVC_T_RANKCNT = 2346         -- rewards toward the next rank (2 per rank, VNG task 373)
PTVC_T_DAY = 2347             -- yyyymmdd of the last Vi Quoc Lap Cong result (VNG task 410)
PTVC_T_DAYCNT = 2348          -- accepted today
PTVC_T_FLAG = 2349            -- round key while carrying an enemy flag
-- global values
PTVC_GV_STATE = 2340          -- 0 closed, 2 battle
PTVC_GV_ROUND = 2341          -- current round key mmddHHMM
PTVC_GV_SCORE = 2341          -- score of side s = GlobalValue(PTVC_GV_SCORE + s): 2342 Thuong, 2343 Chu
PTVC_GV_LAST = 2344           -- last settled round key
PTVC_GV_WIN = 2345            -- winner of the last settled round (0 draw)
PTVC_GV_END = 2346            -- minute of day (h*60+m) when the current round ends
PTVC_GV_SLOT = 2349           -- participant slots 2350..2369 (player index)
PTVC_SLOTS = 20

PTVC_BASE_X = { 1430, 2349 }
PTVC_BASE_Y = { 3393, 3053 }
PTVC_FRONT_X = { 1477, 2331 }
PTVC_FRONT_Y = { 3219, 3244 }
PTVC_SIDENAME = { "phe Th\173\172ng", "phe Chu" }
PTVC_GENNAME = { "V\168n Tr\228ng", "Kh\173\172ng Th\173\238ng" }
PTVC_KINGNAME = { "Tr\244 V\173\172ng", "V\226 V\173\172ng" }

-- Vi Quoc Lap Cong odds by rank (VNG <bdaa><c9d0>.lua RootProb, 60 = 100%): kill p,min,max | flag | totem | scout ; rest = win
PTVC_PROB = {}
PTVC_PROB[1] = { 60, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 }
PTVC_PROB[2] = { 20, 1, 5, 20, 1, 1, 0, 0, 0, 0, 0, 0 }
PTVC_PROB[3] = { 24, 5, 15, 18, 1, 4, 0, 0, 0, 12, 1, 1 }
PTVC_PROB[4] = { 24, 10, 30, 12, 3, 6, 0, 0, 0, 18, 2, 2 }
PTVC_PROB[5] = { 18, 25, 50, 12, 5, 8, 6, 1, 1, 12, 3, 3 }
PTVC_PROB[6] = { 18, 30, 60, 12, 8, 10, 12, 1, 1, 12, 4, 4 }
PTVC_PROB[7] = { 30, 40, 70, 6, 8, 12, 6, 1, 1, 12, 5, 5 }
PTVC_PROB[8] = { 6, 40, 80, 30, 10, 15, 6, 1, 1, 12, 5, 5 }
PTVC_PROB[9] = { 6, 50, 90, 6, 10, 15, 6, 1, 1, 12, 5, 5 }
PTVC_PROB[10] = { 0, 0, 0, 0, 0, 0, 60, 1, 1, 0, 0, 0 }
PTVC_PROB[11] = { 30, 50, 100, 15, 10, 25, 6, 1, 1, 6, 10, 10 }

function PTVC_Today()
	return tonumber(date("%Y%m%d")) or 0
end

function PTVC_Round()
	return GetGlobalValue(PTVC_GV_ROUND)
end

function PTVC_Open()
	return GetGlobalValue(PTVC_GV_STATE) == 2
end

-- the current player is a participant of the running round
function PTVC_InRound()
	if not PTVC_Open() then return nil end
	if GetTask(PTVC_T_SIDE) <= 0 then return nil end
	if GetTask(PTVC_T_ROUND) ~= PTVC_Round() then return nil end
	return 1
end

function PTVC_Score(s)
	return GetGlobalValue(PTVC_GV_SCORE + s)
end

function PTVC_AddScore(s, n)
	if s == 1 or s == 2 then SetGlobalValue(PTVC_GV_SCORE + s, GetGlobalValue(PTVC_GV_SCORE + s) + n) end
end

function PTVC_MinLeft()
	local now = tonumber(date("%H")) * 60 + tonumber(date("%M"))
	local e = GetGlobalValue(PTVC_GV_END)
	local d = e - now
	if d < 0 then d = d + 1440 end
	return d
end

function PTVC_Note(text)
	AddNote(13, 1, "'V\222 Qu\232c L\203p C\171ng': " .. text, 0)
end

function PTVC_MissionText(m)
	if m > 1000 and m < 2000 then return format("L\199n n\181y ng\173\172i ph\182i ti\170u di\214t <color=yellow>%d<color> qu\169n \174\222ch.", m - 1000) end
	if m > 2000 and m < 3000 then return format("L\199n n\181y ng\173\172i ph\182i \174o\185t <color=yellow>%d<color> so\184i k\250 \174\222ch r\229i mang v\210 giao cho ch\241 t\173\237ng.", m - 2000) end
	if m > 3000 and m < 4000 then return format("L\199n n\181y ng\173\172i ph\182i ph\184 h\241y v\203t t\230 \174\222ch <color=yellow>%d<color> l\199n.", m - 3000) end
	if m > 4000 and m < 5000 then return format("L\199n n\181y ng\173\172i ph\182i ti\170u di\214t <color=yellow>%d<color> th\184m qu\169n \174\222ch.", m - 4000) end
	if m == 5001 then return "L\199n n\181y ng\173\172i ph\182i gi\243p phe m\215nh gi\181nh chi\213n th\190ng!" end
	if m == 1 then return "\167\183 ho\181n th\181nh 'V\222 Qu\232c L\203p C\171ng', \235 l\185i chi\213n tr\173\234ng ch\234 chi\213n s\249 k\213t th\243c \174\211 nh\203n th\173\235ng!" end
	if m == 2 then return "H\183y v\210 Phong Th\199n \167\181i g\198p Vi\212n C\230 Chi\213n S\248 nh\203n th\173\235ng." end
	return "Ch\173a nh\203n nhi\214m v\244."
end

-- count down one objective of type base (1000/2000/3000/4000)
function PTVC_MissionDec(base)
	local m = GetTask(PTVC_T_MISSION)
	if m <= base or m >= base + 1000 then return end
	m = m - 1
	if m == base then
		SetTask(PTVC_T_MISSION, 1)
		TopMessage("Ho\181n th\181nh 'V\222 Qu\232c L\203p C\171ng'!")
		Msg2Player("\167\183 ho\181n th\181nh 'V\222 Qu\232c L\203p C\171ng'. \235 l\185i chi\213n tr\173\234ng \174\213n khi chi\213n s\249 k\213t th\243c \174\211 \174\173\238c ghi c\171ng.")
		PTVC_Note(PTVC_MissionText(1))
	else
		SetTask(PTVC_T_MISSION, m)
		PTVC_Note(PTVC_MissionText(m))
	end
end

function PTVC_AddPersonal(n)
	SetTask(PTVC_T_SCORE, GetTask(PTVC_T_SCORE) + n)
end

-- army NPC killed by the current player (kind 1 soldier, 2 scout, 3 flag, 4 totem; side = army side)
function PTVC_OnKill(kind, side)
	if not PTVC_InRound() then return end
	local my = GetTask(PTVC_T_SIDE)
	if side == my then return end
	if kind == 1 then
		PTVC_AddPersonal(1)
		PTVC_AddScore(my, 1)
		PTVC_MissionDec(1000)
	elseif kind == 2 then
		PTVC_AddPersonal(3)
		PTVC_AddScore(my, 1)
		PTVC_MissionDec(4000)
		PTVC_MissionDec(1000)
	elseif kind == 3 then
		SetTask(PTVC_T_FLAG, PTVC_Round())
		Msg2Player("Ng\173\172i \174\183 \174o\185t \174\173\238c so\184i k\250 c\241a " .. PTVC_SIDENAME[side] .. "! Mau mang v\210 giao cho " .. PTVC_GENNAME[my] .. ".")
		TopMessage("\167o\185t \174\173\238c so\184i k\250 \174\222ch!")
	elseif kind == 4 then
		PTVC_AddPersonal(5)
		PTVC_AddScore(my, 3)
		PTVC_MissionDec(3000)
		Msg2Player("V\203t t\230 c\241a " .. PTVC_SIDENAME[side] .. " \174\183 b\222 ph\184 h\241y! C\171ng tr\185ng +5.")
	end
end

-- flag delivered to the own general
function PTVC_DeliverFlag()
	if GetTask(PTVC_T_FLAG) ~= PTVC_Round() or not PTVC_InRound() then return nil end
	SetTask(PTVC_T_FLAG, 0)
	PTVC_AddPersonal(10)
	PTVC_AddScore(GetTask(PTVC_T_SIDE), 5)
	PTVC_MissionDec(2000)
	return 1
end

-- free a slot / find our slot
function PTVC_SlotAdd()
	local i = 1
	local free = 0
	while i <= PTVC_SLOTS do
		local v = GetGlobalValue(PTVC_GV_SLOT + i)
		if v == PlayerIndex then return i end
		if free == 0 and (v <= 0 or GetPlayerID(v) == nil) then free = i end
		i = i + 1
	end
	if free > 0 then SetGlobalValue(PTVC_GV_SLOT + free, PlayerIndex) end
	return free
end

function PTVC_SetCamp(side)
	SetCurCamp(side)
	SetTempRevPos(PTVC_MAP, PTVC_BASE_X[side] * 32, PTVC_BASE_Y[side] * 32)
	SetPunish(0)
	SetLogoutRV(1)
end

-- leave the battlefield state (camp, punish, revive point); go = 1 also teleports to Phong Than Dai
function PTVC_Restore(go)
	SetCurCamp(GetCamp())
	SetFightState(0)
	SetPunish(1)
	SetLogoutRV(0)
	SetTask(PTVC_T_FLAG, 0)
	if go == 1 then NewWorld(PTVC_HOME_M, PTVC_HOME_X, PTVC_HOME_Y) end
end

-- enter the running round on side (fee already checked by the caller)
function PTVC_Enter(side)
	if PTVC_SlotAdd() <= 0 then return nil end
	if GetTask(PTVC_T_ROUND) ~= PTVC_Round() then
		SetTask(PTVC_T_ROUND, PTVC_Round())
		SetTask(PTVC_T_SCORE, 0)
		SetTask(PTVC_T_FLAG, 0)
	end
	SetTask(PTVC_T_SIDE, side)
	NewWorld(PTVC_MAP, PTVC_BASE_X[side], PTVC_BASE_Y[side])
	PTVC_SetCamp(side)
	SetFightState(0)
	Msg2Player("Ng\173\172i \174\183 gia nh\203p " .. PTVC_SIDENAME[side] .. ". G\198p " .. PTVC_GENNAME[side] .. " trong doanh tr\185i nh\203n 'V\222 Qu\232c L\203p C\171ng', r\229i xu\202t tr\203n.")
	return 1
end

-- result of an older round for a player who was not settled by the tick (offline / left)
function PTVC_Lazy()
	local s = GetTask(PTVC_T_SIDE)
	if s <= 0 then return end
	if PTVC_InRound() then return end
	local won = (GetTask(PTVC_T_ROUND) == GetGlobalValue(PTVC_GV_LAST) and GetGlobalValue(PTVC_GV_WIN) == s)
	PTVC_Result(won)
	SetTask(PTVC_T_TOTAL, GetTask(PTVC_T_TOTAL) + GetTask(PTVC_T_SCORE))
	SetTask(PTVC_T_SCORE, 0)
	SetTask(PTVC_T_SIDE, 0)
	PTVC_Restore(0)
end

-- 2026-10-04 (vtcc, "qua chuan VNG"): result of the Vi Quoc Lap Cong objective at the end of a round, as VNG
-- <<d4b6><b9c5><d5bd><b3a1>.lua> BonusTime: an objective counted down to its base becomes 1 (done); on the winning side 1 and the
-- "win" objective 5001 become 2; task 410 (here PTVC_T_DAY) = day of the result, so a new objective can only be
-- taken the next day (VNG <<cec5><d6d9>.lua> main: lastday ~= task 410). An unfinished objective is cancelled.
-- returns the new state (0, 1 or 2)
function PTVC_Result(won)
	local m = GetTask(PTVC_T_MISSION)
	local st = 0
	if m == 1 then st = 1 end
	if won and (m == 1 or m == 5001) then st = 2 end
	if st > 0 then
		SetTask(PTVC_T_MISSION, st)
		SetTask(PTVC_T_DAY, PTVC_Today())
		PTVC_Note(PTVC_MissionText(2))
	elseif m >= 1000 then
		SetTask(PTVC_T_MISSION, 0)
	end
	return st
end

-- accept a Vi Quoc Lap Cong objective (one per round; VNG: none on the day of the last result)
function PTVC_Accept()
	local r = GetTask(PTVC_T_RANK)
	if r > 10 then r = 10 end
	local p = PTVC_PROB[r + 1]
	local seed = random(1, 60)
	local m = 5001
	if seed <= p[1] then
		m = 1000 + random(p[2], p[3])
	elseif seed <= p[1] + p[4] then
		m = 2000 + random(p[5], p[6])
	elseif seed <= p[1] + p[4] + p[7] then
		m = 3000 + random(p[8], p[9])
	elseif seed <= p[1] + p[4] + p[7] + p[10] then
		m = 4000 + random(p[11], p[12])
	end
	SetTask(PTVC_T_MISSION, m)
	PTVC_Note(PTVC_MissionText(m))
	return m
end

function PTVC_CanAccept()
	if GetTask(PTVC_T_MISSION) ~= 0 then return nil end
	if GetTask(PTVC_T_DAY) == PTVC_Today() then return nil end
	return 1
end

-- a finished objective waits for its reward (state 1 = done, 2 = done and the side won) outside the round
function PTVC_RewardReady()
	local m = GetTask(PTVC_T_MISSION)
	if (m == 1 or m == 2) and not PTVC_InRound() then return m end
	return nil
end

-- the next reward raises the rank from 3 or 9: VNG reward_add (choice of one set piece) comes first
function PTVC_RankItemDue()
	local r = GetTask(PTVC_T_RANK)
	if (r == 3 or r == 9) and GetTask(PTVC_T_RANKCNT) == 1 then return r end
	return nil
end

-- VNG <<e6fb><cdf5>.lua> / <<cee4><cdf5>.lua> reward_normal: exp = level x (rank x 100 + state x 1000) x 2, rank 10:
-- level x (1000 + state x 1000) x 2; no money, no item (the old 3 van luong and 1/3 Lam bao thach were not VNG).
-- Rank: +1 every 2 rewards (task 373), none above 10, none at rank 4 below level 60.
function PTVC_Reward()
	local st = PTVC_RewardReady()
	if not st then return nil end
	SetTask(PTVC_T_MISSION, 0)
	local r = GetTask(PTVC_T_RANK)
	local lv = GetLevel()
	local exp = 0
	if r >= 10 then
		exp = lv * (1000 + st * 1000) * 2
	else
		exp = lv * (r * 100 + st * 1000) * 2
		if r == 4 and lv < 60 then
			Msg2Player("C\202p c\241a ng\173\172i ch\173a \174\213n 60, \174\188ng c\202p chi\213n tr\173\234ng ch\173a th\211 t\168ng th\170m.")
		elseif GetTask(PTVC_T_RANKCNT) == 1 then
			r = r + 1
			SetTask(PTVC_T_RANK, r)
			SetTask(PTVC_T_RANKCNT, 0)
			Msg2Player(format("\167\188ng c\202p chi\213n tr\173\234ng t\168ng l\170n %d.", r))
		else
			SetTask(PTVC_T_RANKCNT, 1)
		end
	end
	AddOwnExp(exp)
	Msg2Player(format("Nh\203n \174\173\238c %d kinh nghi\214m.", exp))
	PTVC_Note("\167\183 nh\203n th\173\235ng.")
	return exp
end

-- VNG reward_add set pieces: rank 3 -> one of 5 pieces of set 2 (level 5), rank 9 -> one of 3 pieces of set 3
-- (level 7); genre 0, detail = piece, particular = player type + 6 (VNG player_type + 5, player_type = type + 1)
PTVC_PIECE = { 2, 5, 6, 7, 9 }
PTVC_SETNAME = {}
PTVC_SETNAME[1] = { "V\242 Kh\243c ", "Tinh Cang ", "Khai Thi\170n ", "Ch\202n \167\184n " }
PTVC_SETNAME[2] = { "X\221ch T\239ng ", "Th\184i \202t ", "Th\171ng Thi\170n ", "H\229ng Qu\169n " }
PTVC_SETNAME[3] = { "B\184o Th\199n ", "Gi\184c Th\243 ", "Lam \167i\170u ", "Kh\184ng Long " }
PTVC_PARTNAME = {}
PTVC_PARTNAME[1] = { "Gi\184p", "Chi\213n Ngoa", "Y\170u \167\184i", "Kh\171i", "Phi Phong" }
PTVC_PARTNAME[2] = { "\167\185o B\181o", "L\253", "C\169n", "Qu\184n", "L\214nh" }
PTVC_PARTNAME[3] = { "H\233 Gi\184p", "Ngoa", "Y\170u \167\184i", "Tr\244", "K\213t" }

function PTVC_PieceName(r, k)
	local t = GetPlayerType()
	if not t or t < 0 or t > 2 then t = 0 end
	local idx = 2
	if r == 9 then idx = 3 end
	return PTVC_SETNAME[t + 1][idx] .. PTVC_PARTNAME[t + 1][k]
end

-- give piece k of the due rank item, then the normal reward; nil if the bag is full (nothing lost)
function PTVC_RankItem(k)
	local r = PTVC_RankItemDue()
	if not r or not PTVC_RewardReady() then return nil end
	if r == 9 and (k < 2 or k > 4) then return nil end
	if k < 1 or k > 5 then return nil end
	local t = GetPlayerType()
	if not t or t < 0 or t > 2 then return nil end
	local lvi = 5
	if r == 9 then lvi = 7 end
	local it = AddNormalItem(0, PTVC_PIECE[k], t + 6, lvi, 0, 0, 0)
	if not it or it <= 0 then return nil end
	AddGlobalCountNews("<color=green>" .. GetName() .. format("<color> \174\188ng c\202p chi\213n tr\173\234ng t\168ng %d, \174\173\238c ban th\173\235ng <color=green>", r + 1) .. PTVC_PieceName(r, k) .. "<color>.", 2)
	PTVC_Reward()
	return 1
end

function PTVC_StatusText()
	if not PTVC_Open() then
		return "Chi\213n tr\173\234ng Th\173\172ng Chu \174ang \174\227ng."
	end
	return format("Chi\213n c\244c: <color=pink>phe Th\173\172ng<color> %d \174i\211m, <color=brown>phe Chu<color> %d \174i\211m. C\223n %d ph\243t.", PTVC_Score(1), PTVC_Score(2), PTVC_MinLeft())
end

function PTVC_No()
end
