[ROLE]
iid=0
dbegindate=0000-00-00 00:00:00
denddate=0000-00-00 00:00:00
dlogintime=0000-00-00 00:00:00
ifinishgame=0
caccname=边城浪子
calias=边城浪子
cpartnercode=玉女
cusercode=边城浪子
bsex=1
ifiveprop=0
iteam=0
irevivalid=20
irevivalx=10
irevivaly=0
ileftprop=0
ileftfight=0
ileftlife=0
ipower=7
iagility=4
iouter=6
iinside=3
iluck=30
ifightexp=0
ifightlevel=1
ileadexp=0
ileadlevel=1
iliveexp=0
imaxinner=9
imaxlife=30
imaxstamina=1
imoney=0
isavemoney=0
isect=-1
ijoincount=0
ifirstsect=-1
isectrole=0
igroupcode=0
igrouprole=0
ihelmres=1
iarmorres=1
iweaponres=1
iweightmax=200

; Notes by Cooler
; All skills initial move to gameserver
[FSKILLS]
COUNT=18
S1=1
L1=1
S2=2
L2=1
S3=27
L3=1
S4=28
L4=1
S5=29
L5=1
S6=30
L6=1
S7=31
L7=1
S8=32
L8=1
S9=33
L9=1
S10=34
L10=1
S11=35
L11=1
S12=36
L12=1
S13=37
L13=1
S14=38
L14=1
S15=39
L15=1
S16=40
L16=1
S17=41
L17=1
S18=42
L18=1

[LSKILLS]
COUNT=0

[ITEMS]
COUNT=1

[ITEM1]
cusercode=iloveu
idetailtype=0
iequipclasscode=0
iequipcode=4
iequipversion=0
iid=1
ilevel=10
ilocal=2
iparam1=0
iparam2=0
iparam3=0
iparam4=0
iparam5=0
iparam6=0
iparticulartype=9
irandseed=4
iseries=5
ix=5
iy=0
BLISTS=0
ELISTS=0
RLISTS=0

[TASKS]
COUNT=0

[FRIENDS]
COUNT=0
