; by Cooler

; The following setting is for Blaze game server
[2]
Count=1
RevivalId00=7

[3]
Count=1
RevivalId00=13

[4]
Count=1
RevivalId00=19

[60]
Count=1
RevivalId00=211

[92]
Count=1
RevivalId00=223

[93]
Count=1
RevivalId00=224

[94]
Count=1
RevivalId00=225

[95]
Count=1
RevivalId00=226

[96]
Count=1
RevivalId00=227

[97]
Count=1
RevivalId00=221

[98]
Count=1
RevivalId00=222
